### ISSUE TITLE
Gradle Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by jvegaf** [TwidereProject/Twidere-Android#10]
When I try import the project on Android Studio have this error with Gradle:

Error:Configuration with name 'default' not found.

I'm doing something wrong ? how can fix this error ?

Thanks

**Comment by anazhd** [comment]
Hello, sorry for opening this issue again. I'm new to github cloning. I having the same issue like OP, i tried to run ```--recursive``` on new project and ```submodule update -iinit --recursive``` on the cloned project, but both still giving me the same error.

**Comment by gafanhotz** [comment]
Same with me.

**Comment by morinap** [comment]
Can you verify that all of the submodules have actually been cloned correctly? There should be 5 folders inside of the libraries folder - is there content inside each of them?
