### ISSUE TITLE
No menu button: Opening menu with a swipe and swiping tabs sometimes collides

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#100]
As the phone's menu button does not open the menu anymore and there's also no menu button in the GUI, the only way to open it is by swiping from the left border of the phone's display. Often enough it happens, that I accidentally swipe tabs when I really want to open up the menu. So there should be a menu button in the GUI and maybe also the phone's menu button (if the phone has one) should open the menu.

Twidere 0.3.0 dev 2015-03-29 / Android 4.3 / Samsung Galaxy S3

**Comment by mariotaku** [comment]
fixed in recent versions.

**Comment by hebu** [comment]
Menu button stopped working in 0.3.0 2015-04-27
