### ISSUE TITLE
“Open in browser” menu item sometimes opens Twitter page instead of Mastodon page

### ISSUE THREAD

**Issue by ThibG** [TwidereProject/Twidere-Android#1003]
## Expected behavior

Selecting the “Open in browser” menu item from a Mastodon user profile should open their public page in a browser.

## Actual behavior

In certain cases, the “Open in browser” menu item on a Mastodon user profile will open the Twitter page of someone with the same local username.

## Steps to reproduce

1. Get a “like”, “follow” or “share” notification from a remote Mastodon user
2. Expand the notification, so that a summary of the user's profile is displayed
3. Click on it, showing the user profile within Twidere
4. Select “Open in browser” from the menu

## Extra info

I share a notification tab between a Mastodon and a Twitter account.

Android version: 7.1.2

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

**Comment by Rudloff** [comment]
I have the same issue with my Friendica (GNU Social) account.

**Comment by mariotaku** [comment]
Fixed in b3926faa34809871625d124a1e24d4b5a56b1595.

**Comment by pschwede** [comment]
I still get this in 3.7.6
