### ISSUE TITLE
Login type labels are unclear

### ISSUE THREAD

**Issue by waldyrious** [TwidereProject/Twidere-Android#1005]
I just tried adding a second account, and after tapping on the Twitter entry on the list, it expanded to show two sub-entries: "User settings" and "Twidere". As a new user, I have no idea what these mean and which one I should pick. Is there a way to either make these labels clearer, or add help text (e.g. smaller, greyed out, as is shown in some of the settings entries) to allow new users to pick the right option?

- Android version: 6.0.1
- App version: 3.7.1
- Build variant: Google

**Comment by mariotaku** [comment]
Done. This will be improved in next version.

**Comment by waldyrious** [comment]
That's great to hear, thanks!
