### ISSUE TITLE
*job*/org.mariotaku.twidere/.service.JobTaskService wakelock keeps phone awake a lot

### ISSUE THREAD

**Issue by fhimpe** [TwidereProject/Twidere-Android#1009]
Since a few versions, the Twideren wakelock *job*/org.mariotaku.twidere/.service.JobTaskService  keeps awake my phone a lot according to BetterBatteryStats. Currently, after 7 hours of time on battery, this wakelock was active for more than 33 minutes, and this is by far the longest wakelock on my phone.I have auto refresh of my single Twitter account disabled in Twidere, so I have no idea why Twidere is keeping my phone awake while it's not active and my screen is switched off.

**Comment by mariotaku** [comment]
I believe this is the same issue to #935 . Let's move to that thread.
