### ISSUE TITLE
Add which account the Tweet's follower comes from

### ISSUE THREAD

**Issue by crkellen** [TwidereProject/Twidere-Android#1011]
I have a scenario where I have two accounts.
There are some cases where there is still an overlap in who I follow. There are some cases where I don't want to remove this overlap. I am perfectly fine with seeing the same tweet/retweet twice, but currently there is no way of knowing which account the tweet is associated with.

This causes an issue if I want to reply, like, or retweet. The current setup says that the first account that is logged in will come first, so I can partially get around this, but there is absolutely no distinction between a tweet that has no overlap (One of my accounts doesn't follow the tweeter).

An example:

Account Foo and Bar are my accounts. Foo and Bar have some overlapping accounts that they both follow.

Foo follows these accounts:
Ayy
Bee
See

Bar follows these accounts:
Dee
Bee
See

Account "Ayy" submits a tweet.
Account "Bee" submits a tweet.
I want to retweet the tweet from Bee to my Bar account.
My timeline now looks like this:

```
---
Bee:
This is a picture of my cat
(Media)
Reply, Retweet, Like
---
---
Bee:
This is a picture of my cat
(Media)
Reply, Retweet, Like
---
---
Ayy:
I like cats
Reply, Retweet, Like
---
```

There is no distinction in any of these tweets which account of mine it originates from. The only reason I know Ayy's tweet is from Foo is because Bar does not follow Ayy.
It is entirely up to guessing and checking to figure out which of the tweets from Bee corresponds to account Bar. This makes it difficult to like, retweet, or reply.

**Comment by mariotaku** [comment]
There should be a color strip at the right side of each tweet. This indicates which account this tweet belongs to. You can change account color in Drawer - Accounts list

**Comment by crkellen** [comment]
Oh my that is incredibly hard to see. I have a galaxy S8, which has the curved sides and a little side bar that is always present, it was almost always completely covered under the white side bar. Thanks! I suppose this could be closed then.
null
