### ISSUE TITLE
Database Duplicity Causing UI Inconsistencies & Possibly Slowdowns & Unnecessary Data Usage

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#1017]
I've noticed this behavior for a while, but I never connected the dots until just now. Tweets seem to be stored in multiple databases, as they have different Like/Retweet/Reply counts depending on which way you open them up. For example, while I'm typing a reply to one of my tweets, someone Likes the tweet I'm replying to. That gives that tweet 1 Reply & 1 Like once I send it. But when I view my Notifications tab, that tweet shows 0 Replies & 1 Like until I actually open the tweet from within the Notification area to refresh the counts.

It's possible that rearranging the databases so that tweets & their stats are stored per-account instead of per-tab, while having each tab just use references to each tweet could help alleviate #883 which still exists, as well as save on overall data consumption so that it doesn't have to load the same tweet more than once when it exists on multiple tabs. It should, at the very least, alleviate the UI issue I'm reporting here.

## Extra info

Android version: 4.4.2 & 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.7.2

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
We're working on full datastore reimplementation. All tweets will be stored in database instead of internal cache, which can improve tweet status inconsistency a lot. However, using per-tab statuses is very necessary since using references between tables will take more time than storing redundant data.
