### ISSUE TITLE
Icon for Navigation Drawer is missing

### ISSUE THREAD

**Issue by gregorydk** [TwidereProject/Twidere-Android#1019]
The icon for Navigation Drawer is missing (the hamburger menu icon), therefore there is no visual indicator that there is a Navigation Drawer.

https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior

**Comment by mariotaku** [comment]
This is configurable in `Settings` - `Others`.

Yes, navigation drawer is part of the design guideline, but we already have gestures and related guidance for opening drawer.
