### ISSUE TITLE
Fav status does not update when faved from a list tab

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#102]
When I open a tweet's detail view from a list tab, I can fav the tweet, but the fav button is not updated. Also, when going back to the tab view and even when going back again to the tweet detail view, the fav button remains grey. In the main timeline tab and also in the view of the user who wrote the tweet, the fav button is displayed correctly as yellow.

Twidere 0.3.0 dev 2015-03-29 / Android 4.3

**Comment by hebu** [comment]
This is still an issue.
Reproduce like this:
- Create a tab based on a list
- Open a tweet detail view from this tab
- Fav the tweet -> star remains grey
- Return back to the list tab -> Fav count remains as before, fav star is grey
- Open the tweet's detail view again -> Fav star still grey, fav count as before
- Search the same tweet in your home timeline -> fav star count and color are correct

It only happens in the detail view, faving a tweet from the list tab itself works.

Version: 0.3.0 dev 2015-09-20

**Comment by mariotaku** [comment]
Seems newest versions are working.
