### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it.

### ISSUE THREAD

**Issue by mattjma** [TwidereProject/Twidere-Android#1021]
File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by mariotaku** [comment]
You may need to apply patch file from `twidere/patches/remove_closed_source_dependencies.patch` to build from source.

**Comment by AsixJin** [comment]
Posting this in case someone sees this and doesn't know how to use a patch file like myself.

https://stackoverflow.com/questions/30401227/how-to-apply-a-patch-in-android-studio

**Comment by neopostmodern** [comment]
Could this be added to the README?

**Comment by nlowe** [comment]
Note that this patch doesn't seem to apply cleanly on develop anymore.
