### ISSUE TITLE
First time user, found some issues

### ISSUE THREAD

**Issue by martinszy** [TwidereProject/Twidere-Android#1030]
Hello, I just tested twidere and found the following issues. I know this is not a proper way to file them, but I expect most of these are already reported or just lack of experience.

1) In the unified timeline, I would like to be able to determine from which of the accounts the tweet was from. This could be shown in each tweet, or a timeline could be created for each account.
2) When liking or retweeting, I would like to be able to determine from which account I'm doing the action. This could be showin in the confirmation pop-up.
2.5) What is the point of having the account selector in the left drawer if favs and retweets happen for the account that is following and not the active one, plus all the tweets are displayed?
3) I think there should be a feedback form inside the app, most users with problems will not come to github.
4) I think there should be an easy way to copy a profile's URL, right now I have to open it in a browser and copy the address.
5) Even when I activate preview media, it was not showing it, but now it is. So I think there might be an issue when enabling that setting for a little while.

I'm using twidere 3.7.3 on android 7.

**Comment by mariotaku** [comment]
1. You can distinguish tweet from which account by setting account color.
You can set account color by long-tapping account in list in Drawer menu - Accounts.

2. Account color is also displayed when retweeting. I'll make an option to use single-account mode #841 

3. Yes. I'm planning to integrate this (although it will require a Github account too but sending feedback will be much more simpler)

4. Good idea. I'll provide this feature in future releases.

5. If Settings - Network - Bandwidth saving enabled, preview media will be hidden when in cellular network.
