### ISSUE TITLE
[Improvement] Right-align text block of own DM's

### ISSUE THREAD

**Issue by regularlabs** [TwidereProject/Twidere-Android#1033]
Would be nice if the text block of the own DM's would be right-aligned.
You see this behaviour in many chat apps too, like Skype.

**Comment by orithena** [comment]
Please don't. That would mess up the visual cue for the start of the line and makes re-reading your own longer DMs harder.

See also: any typography book. Here's an example (under the heading "Centered and right-justified text blocks"): http://webstyleguide.com/wsg3/8-typography/3-legibility.html

**Comment by regularlabs** [comment]
Sorry for the incorrect wording. I don't mean right-align the text itself, but the text block.
This is already done with short texts in Twidere. But when text wraps, the block is 100% width, and you don't see a difference in 'alignment'.
So solution would be to always have a little left margin on the own DMs and right margin on the ones from the other.

![](http://regl.io/i/tyyni.png)

**Comment by regularlabs** [comment]
Or even have the text blocks a fixed width regardless of amount of ext and have something like this:

![](http://regl.io/i/y7ipu.png)

**Comment by orithena** [comment]
Ooh, now I get your meaning! I do support that feature request, including the fixed width! (which would improve legibility by creating the visual cue to the start of the lines of your own DM storm ^^)

**Comment by mariotaku** [comment]
Now message bubble will take up to 85% of screen width.

**Comment by regularlabs** [comment]
Great, thanks :)

**Comment by regularlabs** [comment]
When will this be pushed to the beta version?
PS: I don't see any code changes concerning this...

**Comment by mariotaku** [comment]
@regularlabs It's changed in mariotaku/MessageBubbleView library, so you may not find it in Twidere's code.

**Comment by regularlabs** [comment]
Ok, great :)
So when do you think this will be pushed to the beta version of Twidere Android?
