### ISSUE TITLE
List of "statusnet" instances is incomplete 

### ISSUE THREAD

**Issue by deutrino** [TwidereProject/Twidere-Android#1035]
When attempting to add an account for a gnusocial node, I am presented with a very incomplete list of nodes. This should be a text entry box similar to picking a mastodon instance if at all possible.

(The node not listed is quitter.es but there are a lot of others missing as well. A list is not the best approach for this.)

**Comment by mariotaku** [comment]
It's not possible to login to a StatusNet instance just by typing its host address. StatusNet doesn't provide API to retrieve auth token like Mastodon. All instances requires me to register and apply for an OAuth key.

**Comment by deutrino** [comment]
Please add quitter.es.

**Comment by orithena** [comment]
@deutrino Please check #795 and maybe #496. @mariotaku can't keep track of all the gnusocial instances and needs the help of others to add more.
