### ISSUE TITLE
Mastodon's API doesn't have `/api/direct_messages.json`

### ISSUE THREAD

**Issue by takayamaki** [TwidereProject/Twidere-Android#1038]
Hi there, I'm administrator of imastodon.net that is one of mastodon instances.

Twidere are requesting `/api/direct_messages.json` 500～700 times per day.
However, mastodon's API doesn't have `/api/direct_messages.json` .

I guress that it is Twitter's API.

Could you fix this?

Thank you!

![image](https://user-images.githubusercontent.com/24884114/33702627-d203d672-db67-11e7-8847-dea8a5fd5da4.png)

**Comment by mariotaku** [comment]
Done! Twidere will not trying to fetch DM for Mastodon instances in future releases.
