### ISSUE TITLE
Old Twitter DMs are not loaded

### ISSUE THREAD

**Issue by kit-ty-kate** [TwidereProject/Twidere-Android#1039]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

Getting all the old DMs.

## Actual behavior

When using Twidere almost all my Twitter DMs, apart from the 2 or 3 last ones, are not listed.
It would be great to have, at least, a ```Load more``` button to get them.

## Steps to reproduce

1) Sign-in with a Twitter account which already has many DMs.
2) Go to the DM tab.

## Extra info

Android version: (version code here)

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tedko** [comment]
fixed in 4.1.1
