### ISSUE TITLE
Twitter DM messages not received

### ISSUE THREAD

**Issue by kit-ty-kate** [TwidereProject/Twidere-Android#1040]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

Getting every messages.

## Actual behavior

From time to time, Twidere does not receive some of the messages someone-else is sending me.
If I relaunch the application however, it apparently gets them all.

## Steps to reproduce

(random behaviour)

## Extra info

Android version: (version code here)

Network type:

- [x] Cellular
- [ ] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tedko** [comment]
I will close this one and mv all DM related bugs to #1252
