### ISSUE TITLE
Can't open Friendica post in browser

### ISSUE THREAD

**Issue by Rudloff** [TwidereProject/Twidere-Android#1041]
I use a Friendica (GNU Social) account in Twidere 3.7.3.

## Expected behavior
When I open a post and use *Open in browser*, it should open the post on my Friendica server.

## Actual behavior
It tries to open `https://mobile.twitter.com/[username]/status/[post_id]` which generally does not exist.

## Steps to reproduce
1. Add a Friendica account to Twidere.
1. Touch a post to see its details.
1. Choose *Open in browser* in the post's menu.

## Extra info

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
I don't have such an instance. Could you paste JSON object, or URL link of your status here? If you don't want to make it public you can also send me email.

**Comment by Rudloff** [comment]
Here is an example status: https://social.rudloff.pro/display/de03dfa0135a1eaf11c200a900103524
And its JSON object (from https://social.rudloff.pro/api/statusnet/conversation/335105.json?count=20):
```json

**Comment by annando** [comment]
@mariotaku If you need additional data in the post, please tell. Then I will enhance the output.

**Comment by mariotaku** [comment]
@annando A field with permalink to this status would be nice. It called `external_url` in GNUSocial FYI. You can name it whatever you want and tell me when it's ready.

**Comment by annando** [comment]
I would adopt GS. Since I do have zwo GS installations, I will check there and adopt the changes.

**Comment by annando** [comment]
PR is done.

**Comment by Rudloff** [comment]
I confirm it now works correctly. Thanks everyone!
