### ISSUE TITLE
Migrate to new direct messages API

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#1046]
Twitter offered their roadmap retiring old DM api and streaming API. We must prepare migration and make as many user upgraded as possible.

**Comment by Konzertheld** [comment]
This is now a bug as direct messages stopped working (error message appears that user or message could not be found, message does not appear in Twidere but was sent / incoming messages never appear in Twidere).

**Comment by rodrigogolive** [comment]
Same issue, DM messages on Twitter are not working anymore

**Comment by orithena** [comment]
Using the API Keys from https://gist.github.com/mariotaku/5465786, DMs do still work in Twidere.

**Comment by danialbehzadi** [comment]
Same error here

**Comment by Tedko** [comment]
Fixed since 4.0.4

**Comment by danialbehzadi** [comment]
Not fixed yet!

No Direct message is shown in 4.0.4

**Comment by Tedko** [comment]
Oh! @Tlaster

**Comment by Tedko** [comment]
@danialbehzadi fixed since 4.0.8
