### ISSUE TITLE
[Feature request] Return gesture

### ISSUE THREAD

**Issue by azumukupoe** [TwidereProject/Twidere-Android#1050]

**Comment by mariotaku** [comment]
Could you tell me more about this feature request?

**Comment by azumukupoe** [comment]
I want a swipe gesture you see on iOS apps.
Left edge swipe

**Comment by mariotaku** [comment]
It was used before, but removed later since it would be better to let system handle such gestures.

**Comment by azumukupoe** [comment]
okay

**Comment by mariotaku** [comment]
@azumukupoe You can take a look at #970 . This will be added similar to swipe gesture, but in other forms.
