### ISSUE TITLE
Auto refresh not working

### ISSUE THREAD

**Issue by azumukupoe** [TwidereProject/Twidere-Android#1051]
Interactions, Direct messages, Trends, and Saved searches doesn't get refreshed.

**Comment by AeliusSaionji** [comment]
I'll get notifications for messages, at least.

The option to update my feed every {time} isn't working in the background, and I don't want to turn on streaming.

**Comment by AeliusSaionji** [comment]
I'm on Oreo 8.1 Pixel 2 XL

**Comment by Tedko** [comment]
seems this is fixed already -

**Comment by AeliusSaionji** [comment]
It'd be nice if the autorefresh also pulled in the mastodon's local server feed.
