### ISSUE TITLE
Friendica account has more menu items when disabled

### ISSUE THREAD

**Issue by Rudloff** [TwidereProject/Twidere-Android#1052]
I'm using a Friendica (StatusNet) account.

## Expected behavior
The account has the same menu items every time.

## Actual behavior
When the account is disabled:
![screenshot_20171226-140825](https://user-images.githubusercontent.com/840125/34357344-a443c830-ea46-11e7-981f-5445dd6f6387.png)

When the account is enabled:
![screenshot_20171226-140819](https://user-images.githubusercontent.com/840125/34357348-ac7da854-ea46-11e7-8d4f-17520f7548a5.png)

## Steps to reproduce
1. Had a Friendica account.
1. Disable it in the Accounts menu.

## Extra info

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Yes it's intended. When timelines like "Notifications" and "Public timeline" not available in any tabs, they will appear.

**Comment by Rudloff** [comment]
Oh OK, fair enough.
