### ISSUE TITLE
Blinking status bar when scrolling down

### ISSUE THREAD

**Issue by azumukupoe** [TwidereProject/Twidere-Android#1053]
[video](https://drive.google.com/file/d/19fEFpgNVyoYo8C1tX0TGpV7Xly6dHYxB/view?usp=drivesdk)

**Comment by mariotaku** [comment]
It's a weird problem. Are you using dark theme with default background? Is this device running custom ROM?

**Comment by azumukupoe** [comment]
My device is running on default rom.

**Comment by azumukupoe** [comment]
problem spotted on other apss
