### ISSUE TITLE
Accept/Reject Pending Follow Requests

### ISSUE THREAD

**Issue by Webreaper** [TwidereProject/Twidere-Android#1054]
For users with protected twitter accounts, it's possible to see a list of pending follow requests, but it's not possible to do anything with them. Would be great if each item in the list had an 'Approve' and 'Deny' button, so you could manage pending follow requests right from within the app.

**Comment by mariotaku** [comment]
Currently it's possible with [this hack](https://gist.github.com/mariotaku/5465786)
