### ISSUE TITLE
Twidere crashes after updating to 0.3.0 (dev 2015-03-31) (vercode: 101)

### ISSUE THREAD

**Issue by aelmahmoudy** [TwidereProject/Twidere-Android#106]
When I updated Twidere from 0.3.0 (vercode: 99) to 0.3.0 (dev 2015-03-31) (vercode: 101), Twidere crashes, here's the logcat output at crash:
```
W/dalvikvm(31298): threadid=14: thread exiting with uncaught exception (group=0x41887ba8)
E/AndroidRuntime(31298): FATAL EXCEPTION: pool-2-thread-1
E/AndroidRuntime(31298): Process: org.mariotaku.twidere, PID: 31298
E/AndroidRuntime(31298): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(31298):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(31298):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(31298):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(31298):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(31298):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(31298):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(31298):        at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(31298): Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
E/AndroidRuntime(31298):        at org.mariotaku.twidere.activity.support.HomeActivity$UpdateUnreadCountTask.doInBackground(HomeActivity.java:963)
E/AndroidRuntime(31298):        at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(31298):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(31298):        ... 3 more
W/ActivityManager( 2383):   Force finishing activity org.mariotaku.twidere/.activity.support.HomeActivity
```

**Comment by mariotaku** [comment]
weird. I haven't find that in my code.

**Comment by aelmahmoudy** [comment]
Please note that I am using the F-Droid flavour

**Comment by JIghtuse** [comment]
I can confirm this crash. Fresh update from F-Droid. System: Android 5.1

**Comment by mariotaku** [comment]
Seems It's the same problem with #112. 
Maybe I should migrate all Void[] to Object[].

Oh I hate Java generic types.

**Comment by ChadGray** [comment]
> Unfortunately, Twidere has stopped
> Nexus 4: CM11 M12

I get this crash-message after updating app to a newer version on f-droid (Version 0.3.0-dev-fdroid - Added on 2015-04-08)

**Comment by maxauvy** [comment]
Same here. Please note that notifications for mentions... sometimes appear, but the app crashes when I try to open it.

Twidere 0.3.0-dev-fdroid 106
CyanogenMod 12 (Android 5.0.2)
LG G3 International (d855)

**Comment by jomo** [comment]
Had the same issue and tried clearing cache but it didn't help, so I cleared the app's storage (i.e. deleted all accounts & settings).
I was then able to start the app and access settings, but it crashed again upon sign in.
Also, the login was not stored (the app crashed before?) and I could launch the app again where I had to sign in again.

**Comment by mariotaku** [comment]
that will be fixed in next release soon.

**Comment by mariotaku** [comment]
here, fixed in bd0198a6237940c56063723f8ff221553b179dc0.

**Comment by maxauvy** [comment]
Yeah, it's now working as expected ! Thanks for the great work \o/

**Comment by jomo** [comment]
Just updated, works indeed. Thanks!

**Comment by JIghtuse** [comment]
Thanks! It works now. And I like a new look.

**Comment by mariotaku** [comment]
Good! now I'll close this issue.
