### ISSUE TITLE
Giphy search bar blocked by header.

### ISSUE THREAD

**Issue by AsixJin** [TwidereProject/Twidere-Android#1063]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Being able to select the edit text so I can search for gifs.

## Actual behavior
Can't select edit text to input search term.

## Steps to reproduce
1.Open App
2.Hiit compose FAB
3.Tap paperclip icon opening menu
4.Tap 'Add Gif'
5.Banner blocks search bar

## Extra info
Tried to fix this myself, but couldn't find it in the project.

Android version: (version code here)
Nougat

Network type:

- [X] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by johnnydement** [comment]
I confirm this issue in Oreo

**Comment by AsixJin** [comment]
Is this still being looked into or can someone point me in the right direction so I can fix it and put in a pull request? Just need the banner out of the way so I can use gifs.

**Comment by kunev** [comment]
Silly workaround until this gets fixed seems to be to just flip to landscape and then the search field is visible.

**Comment by Tedko** [comment]
Seems this issue is fixed already. Cant reproduce in 4.1.1 

Will close for now.

**Comment by Tedko** [comment]
@AsixJin @kunev @johnnydement  Just want to let you folks know twidere is back and actively maintained by community and supported by  maskbook.com / dimension.im team. We would love any feedback any input from Twidere community. Many thx
