### ISSUE TITLE
Feature requests - Sensitive content

### ISSUE THREAD

**Issue by RayLennox** [TwidereProject/Twidere-Android#1065]
Add option to enable "sensitive content" by default. Some accounts appear to be flagged as having sensitive content which don't actually have any.

Add option to open links in the browser by default instead of opening in Twidere.

**Comment by krc** [comment]
Especially useful for Mastodon where they tend to put just about everything under "read more"

**Comment by mariotaku** [comment]
Sensitive contents should be hidden by default. You can disable this option in Settings - Content & Safety.

Also in-app browser itself is a feature by Chrome actually, it can be disabled in Settings - Content & Safety.

**Comment by krc** [comment]
Should I open another issue for Mastodon "read more"? The sensitive content setting doesn't currently affect it... 
I have images, but I guess I can't attach them here
