### ISSUE TITLE
"Save To" crashes Twidere

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#1067]
## Expected behavior
When opening content like videos or gifs Twidere offers a function "Save to". I'd like Twidere to let me choose, where I want to save the content.

## Actual behavior
Choosing the option leads to a crash. Twidere restarts from the timeline.

## Steps to reproduce
Open tweet with video content. Choose "Save to".

## Extra info

Android version: 7.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tedko** [comment]
Just able to reproduce with Video 'Save to'

@diesocke  - Just let you know Twidere is back and will be maintained by community with the sponsor of www.dimension.im / www.maskbook.com 

Pls help us spread the words and if possible - submit bugs, fix issues. Thanks.
