### ISSUE TITLE
Can't send tweets

### ISSUE THREAD

**Issue by DaniUg** [TwidereProject/Twidere-Android#1068]
## Extra info: stopped working about the 19th of january. The rest of the features work fine. when I send the exact same tweets on the web app from my pc or from another clients there is no problem.
Each of the tweets that has "Grabado en" under the tweet could not be sent.
![screenshot_twidere](https://user-images.githubusercontent.com/35685853/35214586-f7e7d546-ff61-11e7-8590-8341609d1794.png)

Android version: 7.0

Network type:
- [ ] Wi-Fi

App version: 3.7.3  I'm on the beta or so google play says.

Build variant:
- [ ] Google

Micro-blogging service:
- [ ] Twitter

App settings:
Everything standard only changd the theme to dark.

**Comment by Tedko** [comment]
Hi @DaniUg - We cannot reproduce this problem on Lastest twidere. You can download and try latest twidere on Google Play and FDroid soon as well.
