### ISSUE TITLE
Name and avatar not displayed on first PMs

### ISSUE THREAD

**Issue by kit-ty-kate** [TwidereProject/Twidere-Android#1069]
## Expected behavior

Get the name/pseudo & avatar of the person I'm talking to.

## Actual behavior

Just get a default avatar and ```Messages``` as the name.

## Steps to reproduce

Send a private message to somebody you never messaged before.

## Extra info

Android version: 7.1.2

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by martinszy** [comment]
I experienced the same issue

**Comment by Tedko** [comment]
I can reproduce in 4.1.1

**Comment by Tedko** [comment]
will close this one and move to #1295 

@kit-ty-kate @martinszy Just let you know Twidere is back and maintained by community, supported by www.dimension.im / maskbook.com -- appreciate any feedback and help from twidere community. pls spread the words.
