### ISSUE TITLE
image/picture view ideas

### ISSUE THREAD

**Issue by oprudkyi** [TwidereProject/Twidere-Android#107]
Hi, 

just two small issues:
- image view (after clicking on thumbnail, i.e. popup) shows also tweet text at bottom (removable by second click on image). is this possible to not show tweet text at all (additional option) or don't show it at first, i.e. second click will show text 
- when image view active then rotate is very slow - seems main view also rotated with all tweets and this takes lot of time/cpu

**Comment by benediktg** [comment]
In my opinion this issue is solved because

* Twidere shows no tweet text at pictures
* rotating the view does not seem slow for me
