### ISSUE TITLE
GIF tweet is displayed empty, no media to load

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#1070]
## Expected behavior
Tweets with GIF are displayed as such.

## Actual behavior

Some (not all) Tweets with a GIF are displayed empty in Twidere (while being correctly displayed in the official Android App). No media link, no text, no "load media" button, it's simply displayed empty.

One example would be: https://twitter.com/DaphnesMonster/status/956466494686355456

## Steps to reproduce

View the above linked Tweet in Twidere (probably with media preview disabled).

## Extra info

Might be some data model changes by Twitter. (I noticed on another project that I now need to augment all requests with tweet_mode=extended to get all data I need, and extended_entities now contains less data than it used to).

Android version: 7.0

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.7.3

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
duplicate with #1233

**Comment by Tedko** [comment]
@orithena Just let you know that twidere will be maintained by community, supported by www.dimension.im . Your input will be super appreciated. Thx :)

Love to have more feedback. We will fix this bug soon.
