### ISSUE TITLE
Dualposting Twitter Quotes to Mastodon Causes 502 error

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#1073]
Mastodon shoots a 502 error when trying to post Twitter links to both Mastodon & Twitter at the same time. This infects the subsequent Mastodon draft created by this failure, causing it to generate the same 502 error.

It works fine when each account is done individually. So copy-pasting the draft text into a new compose window & sending just to Mastodon will work.

## Steps to Reproduce
1. Copy the url to the tweet you want to quote.
2. Open a new compose window & paste the link in there.
3. Select both a Mastodon & a Twitter account with which to post it.
4. Send it.

## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.7.3

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
I'm not able to reproduce. HTTP 502 is gateway timeout error, which means that problem may happened on server side.

**Comment by Yowlen** [comment]
I'm using mastodon.social if it helps. Since it's server-side, it could be specific to the instance.

It's unusual that it occurred within just that time period, though. Also, it didn't seem like a timeout error since the error happened immediately. It's more like it was rejected entirely.

Is it possible Twidere didn't send a valid closer with the dualpost but did when it was done by itself?

**Comment by mariotaku** [comment]
Gateway timeout error doesn't happen between Mastodon server and Twidere, it happens between Mastodon's load balancer (like CDNs) and real server behind.

**Comment by Yowlen** [comment]
Ok. I guess it was just a weird issue with an intermediary server. It works fine now. Sorry for the trouble.
