### ISSUE TITLE
[Bug?] Missing reply count

### ISSUE THREAD

**Issue by vinceau** [TwidereProject/Twidere-Android#1077]
## Expected behavior
I expect there to be a count of how many replies have been made to a particular tweet.

## Actual behavior
There is no reply count.

## Steps to reproduce
N/A

## Extra info
There appears to be [code referencing a reply count](https://github.com/TwidereProject/Twidere-Android/blob/master/twidere/src/main/kotlin/org/mariotaku/twidere/adapter/StatusDetailsAdapter.kt) but the reply count does not appear and there doesn't appear to be options in the settings to enable the reply count.

Android version: 5.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Reply count only available to official clients. Here's an workaround: https://gist.github.com/mariotaku/5465786

**Comment by vinceau** [comment]
@mariotaku The workaround was working fine for a few weeks however, the replies have since disappeared not too long ago. I've tried re-adding the API keys but that hasn't helped. Is this a known issue?

**Comment by orithena** [comment]
Since it's still working here (Twidere 3.7.3-google), I suspect it's one of the following points:

* Your custom keys have been reverted to standard Twidere keys. To make sure this isn't the case, remove Twidere from the list of allowed apps (somewhere in TwitterWeb -> settings -> apps, if I remember correctly)
* The tweet which you're looking at has been loaded when there haven't been replies yet. If you're using streaming, this would be the case for most (if not all) tweets.

Can you verify whether none of these points apply? (There's always a third point, intermittent server issues on Twitters side, but you can't verify these ^^)

**Comment by vinceau** [comment]
I'm also using Twidere 3.7.3-google and I just did the following:
* Uninstall Twidere from phone
* Remove all instances of Twidere from allowed apps on Twitter Web
* Reinstall Twidere, and re-sign in
* Re-enter the consumer key and consumer secret for Twitter for Android
* Save, close and re-launch Twidere

However, replies still aren't being shown. I've tried repeating the steps for the key and secret for Twitter for iPhone but I still can't get the reply count to show. The tweet I'm looking at does have replies I can guarantee it since when I click into the tweet there are replies at the bottom.
If it helps, I'm running Android 7.0 on a Galaxy S7.

**Comment by vinceau** [comment]
Okay I've just reinstalled the app again and it worked. Previously I was reinstalling the apk manually by side loading (still the Play store version) but this time I re-downloaded the apk directly from the Play store and replies are working again now. Not sure why it wouldn't work when re-installing the apk locally though.
