### ISSUE TITLE
Loading drafts crashes Twidere

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#108]
I have a saved tweet in the drafts and whenever I click on the icon to access drafts Twidere crashes.

I've raised a report through the Android crash report thing.

**Comment by mariotaku** [comment]
Will release a bug fix within day or two, sorry for inconvenience!

**Comment by yamatt** [comment]
The saved post ain't going anywhere ;)

**Comment by mariotaku** [comment]
@yamatt drafts are not lost, don't worry.

**Comment by mariotaku** [comment]
fixed in 9f2abf6cd92043c317ae02c240cd3f91d9cfa952 and released to play store.
