### ISSUE TITLE
@reply count not displaying

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#109]
When your @replies tab is refreshed from the home tab it no-longer displays the "to read" count next to the icon.

Unless I'm missing something.

**Comment by muava12** [comment]
And also in timeline

**Comment by mariotaku** [comment]
not finished yet. I'll finish that soon.

**Comment by yamatt** [comment]
Cool ;)

**Comment by mariotaku** [comment]
implemented in 6d76e18d8a39e7d159a5b6c4563537c14e2f1c27
