### ISSUE TITLE
Display Glitch

### ISSUE THREAD

**Issue by Ceda-EI** [TwidereProject/Twidere-Android#1101]
## Expected behavior
Display looks normal when swiping down from a photo/video.

## Actual behavior
Display Glitches after swiping down from a photo/video.

## Steps to reproduce
+ Click on a photo / video.
+ Swipe down to exit the media and go back to home of Twidere.

## Extra info
+ This issue does not occur when pressing back button (or atleast hasn't occurred to me)
+ Doesn't occur always. (~30% of time)
![screenshot_20180318-183915](https://user-images.githubusercontent.com/19731116/37567818-29b3210a-2af2-11e8-97b3-38ed5cd35187.png)
![screenshot_20180318-183918](https://user-images.githubusercontent.com/19731116/37567829-4eb0e53c-2af2-11e8-9aba-8283e7f2a9b9.png)

Android version: 7.1.1 (Lineago OS)

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Ceda-EI** [comment]
Issue does not appear anymore

**Comment by orithena** [comment]
Anecdotal: After looking at your screenshots, the FastHub App glitched: from each line of the issue text, the leftmost 20px turned blank, resulting in cut-off characters ^^
(Never had that before.)
