### ISSUE TITLE
Twidere not showing all replies.

### ISSUE THREAD

**Issue by nikkopt** [TwidereProject/Twidere-Android#1105]
I just noticed that twidere has problems showing replies. Sometimes it shows half a dozen, sometimes it shows several dozens, but never all (when a tweet has lots of them). I'm talking about replies to other peoples tweets. I don't know if it affects my own tweets as i rarely have replies.
I'm using the official keys and have changed 'content' -> 'load item limit'.

## Expected behavior
Twidere would keep showing more replies as i keep scrolling down.

## Actual behavior
Sometimes it shows 20 replies and it does allow me to refresh and shows me more (but never all). Sometimes it only shows 3 or 4, even if the tweet itself has hundreds of replies.

## Steps to reproduce
Just open a tweet with lots of replies and try to see if twedere keeps showing more as you keep scrolling down

## Extra info

Android version: 7.1.1

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by nikkopt** [comment]
By the way, i just noticed it does the same thing in the "Media" tab of someones main page. Example: says the user has more than 1000 media posts and only shows around 32. Everytime i scroll down i tries to refresh but nothing new appears.

**Comment by mariotaku** [comment]
Have you changed Twidere's custom keys? Only keys from https://gist.github.com/mariotaku/5465786 are available to these features.

**Comment by nikkopt** [comment]
Yes i'm using the "Twitter for android" keys. I'm able to do things i wasn't capable with twidere keys and when i tweet it shows "Twitter for android" below my name so i guess they are working correctly.
I made this video some days ago: https://youtu.be/jXph9o_rK7w
By the way, this doesn't happen to every tweet, some seem to work fine and keep showing more replies as i keep scrolling down.

**Comment by nikkopt** [comment]
Have you been able to reproduce the problem? Is there anything you need from me to help you?

**Comment by mariotaku** [comment]
Status page is being rewritten. I'll see if it occurs on new status page too.

**Comment by ferrysyahrinal** [comment]
why not fixed this?

**Comment by Tedko** [comment]
duplicate with #1231 
Hi -- with 4.0.8 we fixed the problem with new logins and we have some basic func of DM working.

For reply flow. we're working on a fix. ( #1231 )

For translate tweet function I will create a separate issue.
@nikkopt  
Just let you know now twidere is maintained by community and supported by Dimension.im -- we're looking for more community contributor as well. Pls spread the words. Thx
