### ISSUE TITLE
New Twitter API

### ISSUE THREAD

**Issue by faissaloo** [TwidereProject/Twidere-Android#1106]
How badly will Twidere be affected?

**Comment by mariotaku** [comment]
See #1016 , Twidere's basic features will remain, but streaming feature will be completely gone.

**Comment by Tedko** [comment]
Hi, I will close this issue for now. @faissaloo Just let you know that Twidere will be maintained by community, supported by dimension.im -- pls spread the word. We would like to invite more community members ;)

**Comment by Tedko** [comment]
@faissaloo And appreciate your interest - would love to have more help
