### ISSUE TITLE
How to connect Twidere with Friendica?

### ISSUE THREAD

**Issue by GambaJo** [TwidereProject/Twidere-Android#1109]
All tutorials are old and doesn't work.
Can somebody tell me, how to connect to Friendica via Twiedere?

**Comment by annando** [comment]
Use "StatusNet" as account type and use the "basic" auth type. No version suffix and the API URL format is "server.tld/api".

**Comment by GambaJo** [comment]
This are my settings:
![twidere_01](https://user-images.githubusercontent.com/1378907/38545680-e4062330-3caa-11e8-86d1-05db8475c2d7.jpg)

But I can't type in my username and password, because there are no fields for this. And when I cklick on "log in", I get a 401.
![twidere_02](https://user-images.githubusercontent.com/1378907/38545679-e3e9a78c-3caa-11e8-9a0c-14d0a288460c.jpg)

**Comment by mariotaku** [comment]
@GambaJo Seems you've selected "Empty" auth type.

**Comment by jedie** [comment]
What's about to add Friendica as account type?!?

**Comment by GambaJo** [comment]
@mariotaku Yes, now it works. But this last radio button is confusing.
