### ISSUE TITLE
How to insert Mastodons home timeline?

### ISSUE THREAD

**Issue by GambaJo** [TwidereProject/Twidere-Android#1115]
I'm using Twidere also for Mastodon. I can add a tab for the local timeline and the federated timeline. But I can't find the home timeline.

**Comment by orithena** [comment]
Settings -> Tabs -> Add ("+" symbol) -> Home -> tap on "active accounts", select your mastodon account -> Save.

**Comment by GambaJo** [comment]
A little bit quirky, but it works. Thx!

**Comment by GambaJo** [comment]
Sorry, don't know how to close this issue.
