### ISSUE TITLE
[Feature Request] Use port 5353 for custom DNS

### ISSUE THREAD

**Issue by Crystal-RainSlide** [TwidereProject/Twidere-Android#1121]
It's effect is similar to TCP to some extent, but not every DNS support port 5353. (Which should be metioned in app)

And, according to Acrylic DNS Proxy GUI, TCP is useless in some area.
https://github.com/miaomiaosoft/Acrylic-DNS-Proxy-GUI/tree/master

## Extra info

Micro-blogging service:

- [x] Twitter

**Comment by Crystal-RainSlide** [comment]
![From Kafan](https://user-images.githubusercontent.com/16851802/39659082-3405979c-5053-11e8-9e27-8143d0ffc143.jpg)
https://bbs.kafan.cn/forum.php?mod=viewthread&tid=2039048
Login needed.

**Comment by Crystal-RainSlide** [comment]
Thanks for informing, and maybe you can notify the users by examples like: e.g. 208.67.222.222#5353
And I'm wondering whether I can use multiple DNS by 8.8.8.8,8.8.4.4 or 8.8.8.8;8.8.4.4

**Comment by mariotaku** [comment]
Yes it's possible. Multiple DNS addresses are separated by `;`,`,` and ` `
