### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by BluesDeChocobo** [TwidereProject/Twidere-Android#1124]
Delete messages in bulk. I can't seem to delete DM's on my Note5. I assume that's a bug.

**Comment by bobcanthelpyou** [comment]
I can't delete private messages, too. Twidere v3.7.3 via F-Droid

**Comment by Tedko** [comment]
Feature request for del DMs

**Comment by Tedko** [comment]
double checked - seems delete single DM also not working (long press a DM- delete )

**Comment by Tedko** [comment]
Fixed
