### ISSUE TITLE
Incorrect domain of URL (twitter.com) for Mastodon post

### ISSUE THREAD

**Issue by senooken** [TwidereProject/Twidere-Android#1125]
When perform [Share] or [Copy link] or [Open in browser] to Mastodon post, domain of URL is twitter.com (NG).

## Expected behavior
Correct Mastodon server URL is copied or opened in browser.

## Actual behavior
Domain of Mastodon post's URL is twitter.com.

## Steps to reproduce
1. Subscribe Mastodon account (ex. senopen@mstdn.jp).
2. View Mastdon post in Twidere (ex. <https://mstdn.jp/@senopen/100039252603887616>)
3. Open post (ex. <https://mstdn.jp/@senopen/100039252603887616>)> Select [...] > Select [Open in browser].
4. URL is mobile twitter domain (ex. <https://mobile.twitter.com/senopen/status/100039252603887616>) -> NG

[Copy link] and [Share] has same issue.

## Extra info

Android version: 7.0

Network type:

- [x] Cellular
- [ ] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [x] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
Fixed already.

**Comment by Tedko** [comment]
Just let you know Twidere is back online and maintained by community, supported by https://dimension.im . Pls spread the word and let ppl know! We would like to bring as many community contributor as possible. Many thanks
@senooken
