### ISSUE TITLE
Can't delete messages on Pleroma (Masto-API)

### ISSUE THREAD

**Issue by imolein** [TwidereProject/Twidere-Android#1127]
I tried to delete a message on my Pleroma instance over Twidere, but get a 500 error back. The account is connected over the Mastodon API.
In the log files of my instance I can see that Twidere is sending a POST request (`POST /api/v1/statuses/2336245/favourite`) instead of a DELETE requests (`DELETE /api/v1/statuses/2336245`)

This was tested on different instances by different users, as you can read here (if you understand german) https://edolas.world/notice/2336902 which all have the same error.

Here is the part of the log file, after I press delete in Twidere: https://hastebin.wiuwiu.de/jiyejovunu.sql

## Expected behavior

Post get deleted.

## Actual behavior

Twidere send out the wrong request, which cause an internal server error.

## Steps to reproduce

* Create a message on a Pleroma instance
* Try to delete the message

## Extra info

Since I have no mastodon account, I don't know if that happens there too.

Android version: 8.1.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon
- [x] Pleroma (Mastodon API)

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Got it, fixed :)
