### ISSUE TITLE
No Updates?

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [TwidereProject/Twidere-Android#1138]
It's been 7 months since Twidere received an update on F-Droid (3.7.3). Have you ditched F-Droid?

**Comment by BakaTakasugi** [comment]
Hi Nada. Unfortunately we are currently busying with other stuff with our
lives and we may not be able to update Twidere anytime soon. New updates
will be released when they are ready.

**Comment by iknownothingaboutcomputers** [comment]
@BakaTakasugi Thanks for the reply. I'm relieved.

**Comment by ferrysyahrinal** [comment]
up

**Comment by Tedko** [comment]
@ferrysyahrinal @iknownothingaboutcomputers Thanks for your contributing. Just let you know that Twidere is back and will be maintain by community, supported by dimension.im - we will roll out an update very soon. Pls spread the word and we would like have more and more community members as well.
