### ISSUE TITLE
Queue/schedule actions

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#114]
I would like to be able to queue and schedule actions (tweets, favs, retweets, un/follows).
This would allow scheduling actions at a future date (fixed time, time offset, reoccurring?) and allow queueing actions while offline to be performed when the phone regains connectivity.

**Comment by mariotaku** [comment]
Save failed rts/favs to drafts is finished.
Schedule tweets (via buffer) is finished also.

Closing this issue for now, if you have more suggestions, feel free to make a new issue.
