### ISSUE TITLE
Web page

### ISSUE THREAD

**Issue by cmmata** [TwidereProject/Twidere-Android#1144]
Hello,

I have just seen the web page 🤣 I'm a web developer and a Twidere active user, and could help with the web if you want. What would you like, a "product presentation" page or more like a documentation one? Depending on the needs, it can be a Github pages web or something more like [ReadTheDocs](https://readthedocs.org/).

**Comment by mariotaku** [comment]
Thanks a lot! I received several design and they looked awesome. And I'll try those designs when I make next version ready (4.0)

**Comment by Tedko** [comment]
Hi @cmmata Thx for reaching out. Twidere now is maintained by community and supported by dimension.im - I will close this issue for now but we love to have a better website soon.
