### ISSUE TITLE
Receive 422 errors on certain image uploads to Mastodon

### ISSUE THREAD

**Issue by ehashman** [TwidereProject/Twidere-Android#1150]
## Expected behavior

When I upload an image captured on my phone camera, it succeeds.

## Actual behavior

Image upload immediately fails with "Error 422".

## Steps to reproduce

A photo that produces the error is attached. Attempt to upload it to a Mastodon instance with version 2.4.3. I don't know if the GitHub upload will work for reproducing since it strips EXIF data but I'll test it.

Before my Mastodon instance was upgraded to 2.4.3 I had no issues with photo uploads on Mastodon with Twidere.

![img_20180827_1703527 2](https://user-images.githubusercontent.com/4706131/44759168-6526df80-ab06-11e8-99c2-0788ee329809.jpg)

## Extra info

Android version: 6.0.1 (BlackBerry DTEK60)

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Xefir** [comment]
Mastodon 2.4.3 and after limit the image upload to 8mo and restrict the upload to image below 1280x1280 in size.
All image above this will result on a 422 result HTTP code.
