### ISSUE TITLE
New direct messages don't show up

### ISSUE THREAD

**Issue by novica** [TwidereProject/Twidere-Android#1159]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Show new direct messages.

## Actual behavior
Direct messages don't show up.

## Steps to reproduce
Assuming you know there is a new direct message, go to twidere -> direct messages -> pull down to refresh. 

## Extra info
Twidere version 3.7.3

Android version: (7.0)

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (3.7.3)

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by orithena** [comment]
Can confirm, even with official keys. To me, it looks like the old DM API has been killed somewhen during the last two days.

**Comment by MoonDragon-MD** [comment]
Same problem.
App version: 3.7.3

**Comment by YtvwlD** [comment]
I have the same problem. The weird thing is, I can still send DMs. I get an error message, but the DM is sent.

**Comment by kozross** [comment]
Same problem here, version 3.7.3 from FDroid.

**Comment by datenteiler** [comment]
Same problem here, version 3.7.3 from FDroid

**Comment by datenteiler** [comment]
Same problem here, version 3.7.3 from FDroid

**Comment by shabbychef** [comment]
Same problem on a Moto X4; Can send DMs, though it produces an error message. Cannot receive DMs.

**Comment by knut-hildebrandt** [comment]
Same here on Moto G5 S with Android 7.1.1. Problem is prevailing. Installed 3.7.3 from F-Droid.

**Comment by PlanetSmasher** [comment]
Problem still exists in both version 3.7.6 and 4.0.6

**Comment by Tedko** [comment]
@PlanetSmasher Try 4.0.8 ? Thx

**Comment by Tedko** [comment]
I will put all DM (API) related issues under #1253 and close this one for now.

For now @novica @orithena @knut-hildebrandt @shabbychef @datenteiler @denefi  @kozross @MoonDragon-MD @YtvwlD @jorol @orithena Can you try 4.0.8 *(on Google Play now, will updated on F-Droid soon as well).
