### ISSUE TITLE
Cancel profile picture will cause dislocation of icon

### ISSUE THREAD

**Issue by xi4oh4o** [TwidereProject/Twidere-Android#116]
like →
![screenshot_2015-04-11-12-03-04](https://cloud.githubusercontent.com/assets/141127/7100210/94c9127e-e045-11e4-84a7-14d8c4f1342e.png)
![screenshot_2015-04-11-12-03-042](https://cloud.githubusercontent.com/assets/141127/7100211/96d9ea8e-e045-11e4-8ec1-27510ab9b803.png)

**Comment by mariotaku** [comment]
Fixed, profile type icon will be also hidden when profile image is disabled in next release.
