### ISSUE TITLE
Can't send a DM

### ISSUE THREAD

**Issue by openbrian** [TwidereProject/Twidere-Android#1162]
I searched and found many DM issues, but not this one.

## Expected behavior

DM is sent

## Actual behavior

Flashed message, The user, tweet, or page does not exist.

## Steps to reproduce

Go to the users page.  Tap ellipsis in top right.  Tap Send DM.

## Extra info

User follows me and I follow them.

Android version: 8.0

Network type:

- [ ] Cellular
- [ x] Wi-Fi

App version: 3.7.3

Build variant:

- [ ] Google
- [x ] F-Droid

Micro-blogging service:

- [x ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by orithena** [comment]
This works on my end. Try using the official keys (remove account from Twidere, enter official keys as linked in your post, re-create account in Twidere). There has been a point where Twitter removed some DM support from the API for third-party apps... with one of these keys, Twidere looks like the official app on API level.

**Comment by openbrian** [comment]
I followed the instructions, confirmed the new key/secret.  But still this did not work.  I get the same result.

**Comment by openbrian** [comment]
Despite getting the flash message, the DM does go through.

**Comment by deuzeffe** [comment]
I've just switched from Twidere(*) keys to Twitter for Android official app. ones (as linked in your post). And it works fine: DM, even with pic., sent&received, notif. with answers&fav. 
Question: are your connected *in the same time* with the Twitter for Android official app. (from the Google Play store)?

(*) v. 3.7.3 from F-droid running on Android 6.0.1

**Comment by jeremymeyers** [comment]
This is happening for me as well on a brand new install. Can only assume support for the new DM API has yet to be implemented

**Comment by patricktokeeffe** [comment]
This seems like a dup of #1159 - DM is sent but also produces error, and no DMs are received. Close maybe?

**Comment by seth100** [comment]
I have the same issue and also I cannot see the messages I sent, just a "Message" element with nothing in the thread

**Comment by Tedko** [comment]
I will put all DM (API) related issues under #1252 and close this one for now.

For now -- @patricktokeeffe @seth100 @jeremymeyers @Javran @openbrian @orithena 
Can you try 4.0.8 *(on Google Play now, will updated on F-Droid soon as well).
