### ISSUE TITLE
Trending topics not updating

### ISSUE THREAD

**Issue by galabean** [TwidereProject/Twidere-Android#1163]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Expect to have the French TT updated.

## Actual behavior
French TT not updated since many days

## Steps to reproduce
Set France for TT

## Extra info
I Uninstalled, reinstalled, cleared data, cleared cache, logout login, still the same. 

Android version: (version code here)
8.0.0
Network type:

- [ x ] Cellular
- [ x] Wi-Fi

App version: (version code here)
3.7 3
Build variant:

- [ x  ] Google
- [ ] F-Droid

Micro-blogging service:

- [ x  ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ x  ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by radoeka** [comment]
I experience the same issue.
However, I think that this is because the related website (providing the trends) might the reason.
Look up your country https://trends24.in/ 
In my case the list matches exactly what I see in the trends tab in twidere....

**Comment by galabean** [comment]
Yes, I've got exactly the same list than this website.
I saw on Twitter that other 3rd Twitter apps have the same problem with the trending topics.

I think that the problem is the Twitter's API

**Comment by galabean** [comment]
Problem solved by Twitter on their API I guess
