### ISSUE TITLE
but this project is dead?

### ISSUE THREAD

**Issue by MoonDragon-MD** [TwidereProject/Twidere-Android#1164]
The programmer is not responding and does not release updates (even on google play or f-droid), I would like to know if he left this project forever or not?

**Comment by mariotaku** [comment]
Sorry for letting you all waiting. It's hard to believe but I work from 10 AM till 11 PM (sometimes even 2-3 AM), that why there's no any updates last year.
Since I found another job and will leave this mess soon, I hope I could still maintain Twidere in 2019.

TL;DR: I was busy as hell in 2018, I'll start to maintain Twidere in 2019 if I could.

**Comment by haverholm** [comment]
@mariotaku Good to hear you're reclaiming your waking hours to hopefully have some time over for Twidere down the line. As a longtime user, I was worrying that the app had been abandoned, but I'll hang on for updates.

**Comment by cmmata** [comment]
@mariotaku If your new job has a "normal" work schedule, you made a great change only for that. We work to live, not live to work. So congrats! I'm a daily user of Twidere, so I'm glad to see you want to dedicate more time on the project. And if you still haven't much time to it, you could always have some contributors lending a hand or two.

If you want, I could help triaging issues or with easy development, as at the moment I'm a beginner in Android development.

**Comment by mariotaku** [comment]
@cmmata That would be great! I'll mark some issues as 'help-wanted' once finished current refactoring.

**Comment by Tedko** [comment]
@cmmata @MoonDragon-MD @haverholm 
Just let everyone know we're back. Now twidere are maintained by community ;), supported by dimension.im - Any contribute and feedback are appreciated! Thx
