### ISSUE TITLE
Direct Messages , Interactions and Messages not working

### ISSUE THREAD

**Issue by JPRuehmann** [TwidereProject/Twidere-Android#1166]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

Same as other Clients.

## Actual behavior

Not working.

## Steps to reproduce

Try to send Direct Messages, Messages and so on.

## Extra info

Android version: 8.1.0 Patchlevel 5.Januar.2019

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.7.3

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by orithena** [comment]
This is due to Twitter changing its API for third-party apps. Until the maintainer comes back from real life and actually has time to check whether the new API allows such things at all, please use one of the official keys, available at https://gist.github.com/mariotaku/5465786

**Comment by rodrigoswz** [comment]
@orithena I can not use that official keys or any other, when I try to login no page is loaded. Any help, please?

**Comment by Marcelofs1** [comment]
I have updated the keys as my previous key **was** working for replies but **NOT** for DM. Now, with this new key, nor DM or replies are working. Is there a way to get the previous key ?

**Comment by Tedko** [comment]
Just let you know Twidere is back online and maintained by community, supported by https://dimension.im . Pls spread the word and let ppl know! We would like to bring as many community contributor as possible. Many thanks 

@Marcelofs1 @rodrigoswz @orithena @JPRuehmann 

In the next release we will fix the twitter DM issue first. Thx.

**Comment by Tedko** [comment]
@Marcelofs1 @rodrigoswz @orithena @JPRuehmann So far some of the DM func as fixed in 4.0.8. I will close this issue for now and fix other glitches in #1252
