### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by ravi0lii** [TwidereProject/Twidere-Android#1172]
## Expected behavior
I should be able to connect over the proxy and should be able to login and use the client.

## Actual behavior
When I enter the proxy settings (the settings are correct, I checked that) and click on "Log In", the circle appears and then disappears and nothing happens.

## Steps to reproduce
I just enter the http proxy settings and then the case above appears.

## Extra info

Android version: 9.0

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.7.3

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [X] Connected through proxy
- [ ] Media preview enabled

**Comment by Wszl** [comment]
me too,  i think it's a bug, please fix it, i want use user/passwd login my proxy.

**Comment by Wszl** [comment]
@Moquo  i fixed it, but can't pr , this is fixed code [https://github.com/Wszl/Twidere-Android](url), i'm not android dev, only Java dev, can only do that.

**Comment by Tedko** [comment]
@Wszl Thanks for your PR!

I will close this issue now since its fixed
