### ISSUE TITLE
Official keys half-working after a backup restore

### ISSUE THREAD

**Issue by Torvin** [TwidereProject/Twidere-Android#1176]
Apparently the 'official keys' don't work anymore (as per comments in https://gist.github.com/mariotaku/5465786). I have a new phone, so I had to restore the backup from my old phone instead of logging in normally. I also changed the token in `/data/system_ce/0/accounts_ce.db` to my old one. Now after the reboot it got into a strange state where some of the functionality is there: I can see polls and the tweet reply count. But some stuff is missing: no tweet translation, 'media' tab only shows several tweets. I tried clearing app's data without any luck. Any idea what's going on?

Android version: 8.1.0

Network type:
- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:
- [x] Google

Micro-blogging service:
- [x] Twitter

App settings:
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)

**Comment by Torvin** [comment]
Figured it out! There's another table in the same `accounts_ce.db` called `extra` which had one of the values set to
```
{"official_credentials":false}
```

After changing it to `true` and rebooting everything works as expected!

**Comment by defaultxr** [comment]
For anyone having the same issue, I wrote up detailed instructions on how to fix it [here](https://gist.github.com/mariotaku/5465786#gistcomment-2913483). Note you'll need a phone where you're already logged in with the official API keys/secrets to work.
