### ISSUE TITLE
Cutting text from reply windown causes app to crash

### ISSUE THREAD

**Issue by mutmedia** [TwidereProject/Twidere-Android#1178]
## Expected behavior
Cutting text should just remove text

## Actual behavior
Cutting text is crashing app

## Steps to reproduce
1. Click to reply someone's tweet
2. Write something
3. Select whatever you've writter
4. Cut
5. Notice the app crashing

## Extra info
related to #1155 but with english

Android version: 8.0.0

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: (version code here)

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by fanf** [comment]
When replies where still displaying, I had that problem sometimes, but not systematically, and I wasn't able to reproduce it.

**Comment by h00701350103** [comment]
I very reliably get this, and also when I select text and delete with backspace. *very* infuriating as I do it often by habit when composing long tweets. Have had it for a while (several months?)

F-Droid, Twitter, LineageOS 15.1, Android 8.1

**Comment by h00701350103** [comment]
Further testing:
1. Reply to tweet
2. Select and delete authors handle.
3. Can now select and cut/delete to your heart's content.


* If adding back authors handle to beginning of tweet, it once again crashes on select+delete. Adding any character(s) before their handle (so it's white and not grey) and it doesn't crash.

* Adding somebody else's handle to the beginning does not make it crash.


So it's specifically something about how it handles parsing of replies to the author when deleting text.

**Comment by Tedko** [comment]
Closed by https://github.com/TwidereProject/Twidere-Android/commit/925e041a4b23c6de41c6c8cb5fffbaf2d983d063
