### ISSUE TITLE
Latest F-droid version chokes on 2FA

### ISSUE THREAD

**Issue by akwala** [TwidereProject/Twidere-Android#118]
V. 0.3.0-dev-fdroid, 4/10/15

Sign in does not seem to handle two-factor auth. Username+password are accepted, I get a text with the 2FA code but don't get a prompt to enter it.

**Comment by mariotaku** [comment]
I'm not able to testing it since SMS support is not available in China. would be awesome if someone could provide a test account to me.

**Comment by akwala** [comment]
The error that pops up is:
"Error while signing in: Error 403"

You may be able to reproduce it with other 2FA verification options, if Twitter offers them.

**Comment by cygairko** [comment]
Exception for 2-factor auth:
https://gist.github.com/cygairko/a025989804d56f78cf32

**Comment by mariotaku** [comment]
implemented 2fa in b720abe8b24b202b4a3604d595335904fce4c3b3.
