### ISSUE TITLE
Viewing threads/answers stopped working at start of June

### ISSUE THREAD

**Issue by fanf** [TwidereProject/Twidere-Android#1181]
## Expected behavior

When viewing a tweet with answers (or part of a thread), view the answers. 

## Actual behavior

Only one tweet is displayed, the one you clicked on from the timeline.

This is *critical* and most likely a showstopper for most people. 

## Steps to reproduce

- be after 2019-06-01

Timeline => clik on a tweet with answers => only the clicked tweet is displayed.

## Extra info

Of course, this used to worked, and twitter changed something and it broke.
It stopped somewhere between 2019-06-01 and 2019-06-02 (certainly depending on some timezone). 

Also, I first tried to logout - wait - login again the account, believing it was some kind of threshold. People, don't do that: you won't be able to reconnect easely with official keys (see comments at the end of https://gist.github.com/mariotaku/5465786)

Android version: (version code here)
3.7.3

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by svil3** [comment]
Can confirm this "bug" too.
And can confirm it isn't the keys since all the other features that only work with official ones are still there.

**Comment by flipsa** [comment]
Same here.

**Comment by ashrafammar** [comment]
I was facing the same issue. I deleted the cache and login details and re-logged in. Used Android Consumer Key but I can see the replies cannot see who likes my tweets.
Does anyone know how to solve it? It seems developer  is not going to update it anymore

**Comment by fanf** [comment]
@ashrafammar the fact that you can't see mentions let me believe that the official keys where not taken in account (Twitter changed login process and you can't use official keys without editing android accounts DB, see gist link comments for "official keys").

It also seems to mean that now, Twitter behave differently for threads / comments with officials / non officials keys. What a mess.
others clients seems to be affected too: owly displays answers but not threads for ex.

And regarding twidere authors, je said that he could have some time for twidere this year contrary to last one. He still use Twitter, hopefully through twidere, so maybe he is also impacted and the pb is sufficiently disrupting that he wants to correct it asap.

**Comment by WPettersson** [comment]
I realise that logging out/in means official keys won't work (easily), so be careful if you try this, but has anyone tried reverting to the original Twidere API keys, and do those still load replies properly?

As a possibly-relevant sidenote, the account twitter.com/twidere has been suspended. I do think that was the official account for this project, no idea if the suspension is relevant.

**Comment by fanf** [comment]
Twidere twitter account is: https://twitter.com/@twidereproject (and his author: https://twitter.com/mariotaku)

**Comment by LukeDuckwalker** [comment]
Same issue for me.

**Comment by Torvin** [comment]
This endpoint now returns 404: `https://api.twitter.com/1.1/conversation/show.json`. That's why tweets no longer load with official keys. The only thing you can do now is switching to non-official keys until this is fixed in the Twidere's code

**Comment by Torvin** [comment]
I believe the official Twitter client is now sending this GET request:

`https://api.twitter.com/2/timeline/conversation/1137399187195121664.json?&earned=true&include_entities=true&include_cards=true&cards_platform=Android-12&include_carousels=true&ext=mediaRestrictions%2CaltText%2CmediaStats%2CmediaColor%2Cinfo360%2CcameraMoment%2Cmaster_playlist_only&include_media_features=true&include_blocking=true&include_blocked_by=true&tweet_mode=extended&include_reply_count=true&include_composer_source=true&simple_quoted_tweet=true&include_ext_media_availability=true&include_user_entities=true&include_profile_interstitial_type=true`

If the response format is the same, it should be a trivial fix

**Comment by fanf** [comment]
For information, threads and answers work with twidere default keys. But of
course, no retweet/like with them.

**Comment by ZaZo0o** [comment]
I confirm the issue with tje official Twitter for android keys.
And when I log in using the default twidere keys I can see the replies again, but not the notifications...

**Comment by jomo** [comment]
FYI: If you want to switch to Twidere keys as a workaround, you can simply add the account again (select Twitter → Twitter). Twidere will say you're already authorized, but switch API keys.

**Comment by Torvin** [comment]
Unfortunately, looks like the new response format from `/2/timeline/conversation/{{ID}}.json` is quite different, so it's not going to be an easy change. So instad I made a workaround that falls back to the 'non-official' API endpoint to read conversations. 

@mariotaku, please, if you have time, accept it!

**Comment by mariotaku** [comment]
Since there're some build errors to be fixed, I'll be publishing this version to Google Play on Friday night.
Current code base is too old, I'm starting to maintain current situation only and exploring new possibility, like to build a new one with 100% Kotlin,  or Flutter.

**Comment by mariotaku** [comment]
By the way thank you so much to contribute to Twidere! @Torvin

**Comment by ferrysyahrinal** [comment]
Viewing threads/answers stopped working at start of June?
no! I experienced it from 2018 !

**Comment by ashrafammar** [comment]
The app updated but still  facing the same issues

**Comment by WPettersson** [comment]
Will the new version be uploaded to f-droid as well?

**Comment by Torvin** [comment]
@WPettersson F-droid maintainers do that by themselves, you cannot control that. Usually it takes them some time.

**Comment by fanf** [comment]
I updated to version 3.7.3 and deleted my previous account, then try to connect with xauth+Twitter official keys.
It worked.
I get notification and private messages, but still no answers in conversation.
Did someone had it working? What did you do?

**Comment by Torvin** [comment]
> I updated to version 3.7.3 and deleted my previous account, then try to connect with xauth+Twitter 
It was fixed in 3.7.4. You need to wait for it to become available on Play Store / F-droid.

**Comment by fanf** [comment]
@torvin: oh thanks, I misunderstood in what version it was corrected.

**Comment by fanf** [comment]
OK, I installed 3.7.4 from the release page on github and I have access back to thread, thank you

**Comment by Torvin** [comment]
> OK, I installed 3.7.4 from the release page on github and I have access back to thread, thank you

@mariotaku should we close this bug? or do you want to look into using the new API endpoint?

**Comment by igalic** [comment]
i've tried doing the same thing, however, my accounts are protected with 2FA, and it doesn't work for me — neither sign in, nor password sign in:

after my login attempts i get an SMS with a temporary password, but again, no matter where i try to plug that in, it does log me in.
I only get a 401 Error again

**Comment by WPettersson** [comment]
@igalic What do you mean by "doing the same thing"? If you've left your account as-is, with the Twitter API keys, then it should still be logged in, and not require any new login.

If you you need to login, however, then I've heard of people not being able to log in with the official twitter API keys. If that's the case, I'd suggest opening a new issue, as it's a different issue.

**Comment by igalic** [comment]
@WPettersson i did the exact same procedure (with 3.7.4) that (mostly) worked for @fanf:  
> I updated to version 3.7.3 and deleted my previous account, then try to connect with xauth+Twitter official keys.
> It worked.
> I get notification and private messages, but still no answers in conversation.
> Did someone had it working? What did you do?

**Comment by Marcelofs1** [comment]
> > OK, I installed 3.7.4 from the release page on github and I have access back to thread, thank you
> 
> @mariotaku should we close this issue? or do you want to look into using the new API endpoint?

Hello. I am running version 3.7.5 and still facing the issue with DM and (sometimes) replies. I have uninstalled couple times but no lucky on fixing the issue

**Comment by hkramski** [comment]
I have GitHub version 3.7.4 fully working here after
- deinstalling existing 3.7.3 (otherwise the GitHub .apk did not install)
- installing 3.7.4 from GitHub
- setting Consumer key: 3nVuSoBZnx6U4vzUxf5w from https://gist.github.com/mariotaku/5465786
- setting "Authentifizierungstyp" to "xAuth" (in German, sorry)

**Comment by igalic** [comment]
@hkramski do your accounts have 2FA enabled?

**Comment by hkramski** [comment]
> @hkramski do your accounts have 2FA enabled?

No.

**Comment by ferrysyahrinal** [comment]
viewing thread/answer stuck when 20 replies, i using official api key

**Comment by Torvin** [comment]
> viewing thread/answer stuck when 20 replies, i using official api key

I don't think it is exactly 20. The exact number will vary from thread to thread, but you won't be able to see all the replies anymore. That's the current limitation.

**Comment by yaomtc** [comment]
This is also occurring for me with Mastodon. It is not a Twitter exclusive issue.

**Comment by Torvin** [comment]
> This is also occurring for me with Mastodon. It is not a Twitter exclusive issue.

I don't think it's related. Please open a separate issue with all the relevant information you can provide

**Comment by yaomtc** [comment]
I mean it's the exact same problem, just with a different network, but sure, why not. One sec.

**Comment by Tedko** [comment]
Hi - with 4.0.8 we fixed the problem with new logins and we have some basic func of DM working.

For reply flow. we're working on a fix. ( #1231 )

@Torvin @fanf 
Just let you know now twidere is maintained by community and supported by Dimension.im -- we're looking for more community contributor as well. Pls spread the words. Thx
