### ISSUE TITLE
Liking, retweeting, answering tweet stopped working around 8 June 2019

### ISSUE THREAD

**Issue by fanf** [TwidereProject/Twidere-Android#1182]
## Expected behavior

I can like, retweet, or answer tweet. 

## Actual behavior

I get an error message: "that tweet, that user or that page doesn't exist"

## Steps to reproduce

Try to like or retweet any tweet. 

## Extra info

This is likely a behavior change in Twitter, it obviously used to work. 
It may be linked with the fact that answers/thread are no more displayed since beginning of June (#1181). 
It may also be linked with the usage of official keys. 

Android version: (version code here)
LineageOS 15.1 (android 8.1.0)
Network type:

- [X] Cellular
- [X] Wi-Fi

App version: (version code here)
3.7.3 

Build variant:

- [X] Gogle
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by WPettersson** [comment]
For what it's worth, liking and retweeting are seemingly working fine on my end, using official keys / 3.7.3. Threads/replies are not displaying still.

**Comment by kowith337** [comment]
I have another problem with official Android API Key...
- Now I cannot make any new logins, no browser window popped up even I've put the correct consumer key and secret.
- It seems like ability to view reply flow was disabled or no longer available, normally it should load replies, except if specific tweet have too many of replies. (around 20 and up?)
  - This will force me to open in browser in order to see replies, however, they inject popup or overlay to download their official app
- Translate tweet function also no longer available.

**Comment by danvilar** [comment]
> I have another problem with official Android API Key...
> 
>     * Now I cannot make any new logins, no browser window popped up even I've put the correct consumer key and secret.
> 
>     * It seems like ability to view reply flow was disabled or no longer available, normally it should load replies, except if specific tweet have too many of replies. (around 20 and up?)
>       
>       * This will force me to open in browser in order to see replies, however, they inject popup or overlay to download their official app.
> 
>     * Translate tweet function also no longer available.
> 
> 
> I'm try to switch to another API key like Echofon, but this key doesn't provide direct message supports.

I can confirm all of this as well

**Comment by craigtp** [comment]
> For what it's worth, liking and retweeting are seemingly working fine on my end, using official keys / 3.7.3. Threads/replies are not displaying still.

This is exactly the behaviour I'm experiencing also.

**Comment by Tedko** [comment]
@fanf  - Hi with 4.0.8 Liking and RT/reply should working properly.

**Comment by Tedko** [comment]
Hi @kowith337 with 4.0.8 we fixed the problem with `new logins` and we have some basic func of DM working.

**Comment by Tedko** [comment]
Fixed.
