### ISSUE TITLE
New Twitter Login to close the app every time

### ISSUE THREAD

**Issue by manimaran96** [TwidereProject/Twidere-Android#1183]
When I try to login twitter account username and password are correct but suddenly close the app. I try again and again same think repeatedly close the app.
Then login in browser twitter asking to verify the mobile number due to lake of un used long period of time. 

## Expected behavior
Covey the actual error or response to user.

## Actual behavior
Close the app

## Steps to reproduce
Twitter account not active in few months(I think 3 or 6 month)
The Login with that account 
Now You can get the error

## Extra info
Twitter verify the user. If user not active in few months,.

Android version: (version code here)
7

Network type:
4G

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
Latest

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by 1-eric** [comment]
Same problem on my phone.

After upgrading my phone from Android-4 to Android-6 (Mokee custom ROM), I've installed Twidere and logged in on Twitter. Twidere crashed after Twitter confirmed the login was successful.

It works on my phone with Android-5 (also Mokee custom ROM).
Same process: Upgrade ROM from Android-4 to Android-5, then install Twidere, then login on Twitter and then everything works.

Both installations were done on a freshly installed ROM without Googgle Apps.

**Comment by Tedko** [comment]
cant reproduce since 4.1.1
