### ISSUE TITLE
Unable to use official keys

### ISSUE THREAD

**Issue by nikkopt** [TwidereProject/Twidere-Android#1190]
Am i the only one having problems trying to login with the official twitter keys? Tried both for android and for iphone. When i press "Sign in" nothing happens. But it works if i use the keys for twidere.

## Expected behavior
Using the official keys should allow to login to the account.

## Actual behavior
Nothing happens when the button "Sign in" is pressed. 

## Steps to reproduce
Chose "User settings" from the Twitter drop down, on login screen. Then click the icon next to the cog wheel and replace the keys there with the official ones from here: https://gist.github.com/mariotaku/5465786 . Click save and then the green "Sign in" button.

## Extra info

Android version: 8.1.0

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by ferrysyahrinal** [comment]
update twidere to newest version, and using xAuth method when u sign in

**Comment by nikkopt** [comment]
@ferrysyahrinal i was just about to post about that. This morning i read the conversation on https://gist.github.com/mariotaku/5465786 and found out about the xAuth temporary fix (although it doesn't seem to work with 2FA on). I wasn't aware that there was a newer version of the app either, only after reading notpushkin's post. Why aren't the newer versions on the play store?

**Comment by ferrysyahrinal** [comment]
https://github.com/TwidereProject/Twidere-Android/releases

**Comment by Tedko** [comment]
duplicate with #1232

**Comment by Tedko** [comment]
@ferrysyahrinal @nikkopt - Just let you that Twidere is back and now maintained by community
