### ISSUE TITLE
Can't open link from Verizon Messages since last beta update

### ISSUE THREAD

**Issue by bbernardini** [TwidereProject/Twidere-Android#1193]
## Expected behavior

Twitter link from Verizon Messages should open in Twidere when I click on it.

## Actual behavior

Messages tries to open the link, then returns back to the same screen.

## Extra info

Android version: (version code here)

9

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

3.7.7

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by stecorb** [comment]
Same issue here. Can't open twitter links from Discord and Boost (reddit client). It briefly shows the in-app-client and then returns back to the app it opened from.

I think the problem began with the last update. Regular Twidere client works fine though.

Android Version 9
App Version 3.7.7

**Comment by orithena** [comment]
Same issue here. Even clicking on twitter links inside of Twidere (e.g. in a mastodon tab) shows this behaviour now. Twidere asks me to select one of my Twitter accounts to open the link, but then returns to the previous screen.

**Comment by mariotaku** [comment]
Just found out it was a stupid mistake I made. Got it fixed!

**Comment by Tedko** [comment]
Fixed by https://github.com/TwidereProject/Twidere-Android/commit/29035090d10021a508eb94e45ef3704ca96c54ca
