### ISSUE TITLE
[Feature Request] Allow Tabs on bottom instead of top

### ISSUE THREAD

**Issue by WolfFhang** [TwidereProject/Twidere-Android#1197]
With some more recent and larger phones it's a bit more awkward to reach all the way up to tap on certain areas of the screen, especially when using only 1 hand. Since your thumb/fingers are usually already lower on the phone it's much easier to navigate things like the tabs in some apps when they're on the bottom of the screen 

(For Example: LINE has moved the Contacts/Chats/Settings tabs to the bottom of the screen several updates back and it's more pleasant and easy to navigate on a larger phone)

The ability to tap a tab to auto-scroll to the top is something I use fairly regularly, and even though I understand you can swipe between tabs it would be nice to use that tap function from the bottom of the screen.

It would be greatly appreciated if you could implement this (at least as an option) in Twidere

**Comment by Tlaster** [comment]
Done by 0d6f6c5dd1a546778636cb79b3fe84e405cd5357
