### ISSUE TITLE
Add Malayalam localization 

### ISSUE THREAD

**Issue by joicemjoseph** [TwidereProject/Twidere-Android#1198]
Please add configurations for Malayalam, an Indic family of language to translations.

**Comment by Tedko** [comment]
We have a page for that http://crowdin.net/project/twidere Thanks!

**Comment by Tedko** [comment]
@joicemjoseph https://crowdin.com/project/twidere/ms#

**Comment by Tedko** [comment]
Since we dont have knowledge of Malayalam etc. It would be great if you can help as

**Comment by joicemjoseph** [comment]
Sure!
