### ISSUE TITLE
Friendica federated timeline

### ISSUE THREAD

**Issue by Arrappathor** [TwidereProject/Twidere-Android#1199]
## Expected behavior
Show federated timeline for friendica accounts

## Actual behavior
! Network error: timeout 

## Steps to reproduce
Refresh federated timeline

## Extra info
Posting to friendica works as well as reading the personal friendica timeline.
This happens regularly since upgrade to 3.7.8, but did occaisonally (sic!) before.

Android version: (version code here)
3.7.8

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet (i guess)
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

Thank you for your great work!

**Comment by annando** [comment]
It is working here with my systems. So I guess it is really just a timeout. Only question is if you still need the secret code to reach that setting in Twidere to increase the timeout value.

**Comment by Arrappathor** [comment]
"Only question is if you still need the secret code to reach that setting in Twidere to increase the timeout value."
¿How do i do this?

**Comment by Arrappathor** [comment]
Thank you. (Sorry, i forgot.)

**Comment by annando** [comment]
See here: https://www.haukepauke.de/2014/04/use-friendica-twidere/ and search for "Here comes the funny part:"

**Comment by Arrappathor** [comment]
Thank you for your hint. 
Unfortunately setting a timeout-limit to 30 seconds doesn't solve the problem. 
Hm.

**Comment by Arrappathor** [comment]
Now it works again. 
I feel a little bit like a fool.
Can i maybe tune my friendica-server (Raspbian buster on RaspberryPi3) somehow?

**Comment by Arrappathor** [comment]
Limiting elements-to-load to 30 (value before: 100) seems to do the trick.
Thank you annando for your help!
Shall/can i close the issue?

**Comment by annando** [comment]
I guess you should do so. It is not a Twidere issue. It is some timeout issue. Although it would be great to have the timeout setting in the regular settings environment. And it would be better to be able to increase the timeout to 60 seconds.
