### ISSUE TITLE
Timeline showing one account only

### ISSUE THREAD

**Issue by eself** [TwidereProject/Twidere-Android#12]
I have two Twitter accounts set up in Twidere, both as "Show in timeline: ON", but only tweets belonging to the first one appear in the timeline. I tried switching the "Show in timeline" on and off in various combinations but the result seems to be the same regardless. The second account is passive only, e.g. has not tweeted yet, but I assume I should still be seeing tweets from its followed accounts in the main timeline, right? When I open the profile of the account and then tap "Following", I can see the followed accounts and read their tweets without any issue - but they would not appear in the main timeline (home icon). I even tried "Clear databases" and restart, still the same.

Is this a bug, or am I missing something?

Using Twidere 0.2.9.12.

Great app, by the way, love it - thanks!

**Comment by tomwor** [comment]
Multiple accounts are broken. Second account doesn't show in timeline, I'd like to confirm that.

**Comment by mariotaku** [comment]
Should work now.
