### ISSUE TITLE
Bug: no twitter chats shown

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [TwidereProject/Twidere-Android#1209]
I can't display my old twitter chats on twidere, please fix

**Comment by tradej** [comment]
Not sure if we're talking about the same thing, but all I get when I open the _Interactions_ tab in Twitter is _Network Error._ The main feed updates normally.

**Comment by TanyaEleventhGoddess** [comment]
I think it isn't the same issue, I'm talking about private chats, not tweets

Judging by the commits the programmers are on vacation, we have to wait probably

**Comment by tradej** [comment]
Never mind my comment then. Also, it seems to have resolved by itself. :man_shrugging:

**Comment by KopfKrieg** [comment]
I've got the same (a similar?) issue here since a few days. In the Interactions tab I get no new tweets, only the old ones from 6 days ago (and older) are shown.

**Comment by Silmathoron** [comment]
Are we talking about private messages here? I'm not sure what you mean by "chats"...
If so, I may have a similar problem: when dealing with conversations, Twidere correctly sends messages (they appear on the Twitter website but does not display existing conversations nor messages in newly created conversations. Furthermore, the successfully sent message is followed by  and reports an error reporting "This tweet, user, or message does not exist" (at least that's how I'd translate it to English).

Android 9 using Lineage and microg, Twidere 3.7.6.
I use blokada (might be related if some specific domains need to be authorized...) but api and twitter.com are whitelisted, so I suspect a genuine bug

**Comment by Tedko** [comment]
Duplicate with #1166 

Just let you know Twidere is back online and maintained by community, supported by https://dimension.im . Pls spread the word and let ppl know! We would like to bring as many community contributor as possible. Many thanks @Silmathoron @tradej @TanyaEleventhGoddess 

In the next release we will fix the twitter DM issue first. Thx.

**Comment by Tedko** [comment]
This bug is fixed by 4.0.8
