### ISSUE TITLE
Bug: Only previous threaded tweets are displayed when opening a mid-thread tweet

### ISSUE THREAD

**Issue by buggleston** [TwidereProject/Twidere-Android#1212]
## Expected behavior
When opening a mid-thread tweet, both previous and subsequent threaded tweets from the author should be displayed

## Actual behavior
When opening a threaded tweet, only previous tweets are displayed along with any non-author replies to the opened tweet

## Steps to reproduce
Open a mid-thread tweet

## Extra info

Android version: 9

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.7.8

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [X] Custom API **(xAuth)**
- [ ] Custom consumer key/secrets
- [X] [Official keys](https://gist.github.com/mariotaku/5465786) **(official Android keys)**
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by Tedko** [comment]
Hi @buggleston  with 4.0.8 we fixed the problem with new logins and we have some basic func of DM working.

For reply flow. we're working on a fix. ( #1231 )

For translate tweet function I will create a separate issue.

Just let you know now twidere is maintained by community and supported by Dimension.im -- we're looking for more community contributor as well. Pls spread the words. Thx
