### ISSUE TITLE
Webview downloads and runs nonfree javascript programs

### ISSUE THREAD

**Issue by ian-kelling** [TwidereProject/Twidere-Android#1214]
For example on the twitter login page. Please make it an option
to disable javascript from webview. Just search the code for
javascript and you see places it is enabled.

**Comment by mariotaku** [comment]
Are you sure login will work after javascript disabled? I'm afraid this may break functionality for some platforms.

**Comment by ian-kelling** [comment]
No, I don't know if it will work. Someone will need to test it out. If it does work, to mitigate twitter breaking things, you could have it be configurable.

**Comment by Tedko** [comment]
@ian-kelling Hi ian, we love to support this feature and make it possible to not 'runs nonfree javascript programs'. However currently we're having problem about twitter close APIs etc and will try to fix that part first. If you would like to test it out and do a PR we love to take a deep look and see if we can fully support this feature soon.

Also now Twidere will be maintained by community ;) we would like to have more input and contribute from community :)
