### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by thomastesla-acdc** [TwidereProject/Twidere-Android#1219]
Once I made the app somehow crash on my phone and then uninstalled it ever since then it crashes on any attempt to refresh anything be it feed, friends list or whatever. I reinstalled it countless times the crash error persists throughout reinstall cycles. What's wrong with this app? I tried different versions older and newer result is still the same. It never crashed before but once it did it crashes everytime now and nothing helps, of course I'm not gonna reset my entire device to check if the problem stays. Once I enabled automatic refresh and app went into infinite refresh-crashing cycle so it made things even worse. I can browse the feed down and go through comments etc but once I refresh - instant crash. 
App version: whatever, it doesn't matter it crashes on all versions
Phone: meizu m2 note
Android: 5

**Comment by Tedko** [comment]
Hi @thomastesla-acdc - would you mind try the the latest version on google play (not the beta).

**Comment by Tedko** [comment]
This problem should be fixed in 4.0.x +. Let me know if you still encounter this problem @thomastesla-acdc
