### ISSUE TITLE
目录Android/data/org.mariotaku.twidere/cache/json/下泄漏用户ID

### ISSUE THREAD

**Issue by hateusingusername** [TwidereProject/Twidere-Android#1224]
今天偶然浏览文件夹 Android/data/org.mariotaku.twidere/cache/json/，居然发现该文件夹下面有好多以user_id为部分命名的文件。
在 https://twitter.com/intent/user?user_id= 后面接上 user_id后，发现链接到自己的twitter主页。
比如说 https://twitter.com/intent/user?user_id=32740706
这个本身没有安全问题，会泄漏隐私。
但在中国，几乎所有的App都会强行要求storage permission，会定向到本Twitter用户。这就可能存在人身安全了。
 麻烦看一下。谢谢！
@mariotaku 
@chenshaoju

Android version: (version code here)
8.1
Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
version 3.7.6
Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
@Tlaster @mariotaku what do you think

**Comment by Tedko** [comment]
之后会进行重构
