### ISSUE TITLE
Only 10 replies to tweets are shown

### ISSUE THREAD

**Issue by happysmash27** [TwidereProject/Twidere-Android#1225]
## Expected behavior
When clicking on a tweet, all replies should show up. 
## Actual behavior
When clicking on a tweet with more than 10 replies, only 10 replies show up. 
## Steps to reproduce
View a tweet with more than 10 replies, such as https://twitter.com/TheBabylonBee/status/1192827006427238402. 
## Extra info
I think the number is 10, but this is with a sample of 1 as I only counted the number of replies for a single popular tweet. 
Android version: 9

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
3.7.6
Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tedko** [comment]
duplicate with #1231
