### ISSUE TITLE
4.0.2 - Error in fav and RT

### ISSUE THREAD

**Issue by koroki** [TwidereProject/Twidere-Android#1230]
When you try to do fav or RT, the following error apears:

Error 283: This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later.

Occurs after the 4.0.2 updated. I'm not 100% sure, but 4.0.0 didn't have this error. 

Android version: 9.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [x] Custom API
- [x] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tlaster** [comment]
Hi, it looks like twitter blocks your account or your custom key, can you try the official client or another consumer key?

**Comment by Prof9** [comment]
I have the same problem using official TweetDeck keys.

**Comment by nlowe** [comment]
Alternating between 226 and 283 for me. Is there a different set of keys we're supposed to use now?

**Comment by Prof9** [comment]
Retweeting works fine on 3.7.8 with the exact same keys, so I don't think that's the problem.

Aside from RTs not working, I'm also having the app crash and restart when I try to send a DM.

**Comment by Tlaster** [comment]
I'm able to reproduce this issue right now, thanks.
Working on it right now.

**Comment by Tlaster** [comment]
I just see this commit (https://github.com/TwidereProject/Twidere-Android/commit/5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c) and seems like twitter is warning @mariotaku about private key and API usage, after talking with @mariotaku I think we can do nothing to solve this issue.

**Comment by koroki** [comment]
> I just see this commit ([5052d1f](https://github.com/TwidereProject/Twidere-Android/commit/5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c)) and seems like twitter is warning @mariotaku about private key and API usage, after talking with @mariotaku I think we can do nothing to solve this issue.

I downgrade the version to 3.8 but I can not obtain the benefits of official API. Is it the reason?

**Comment by szescxz** [comment]
> Aside from RTs not working, I'm also having the app crash and restart when I try to send a DM.

[`LengthyOperationsService` requires `android.permission.FOREGROUND_SERVICE`](https://github.com/TwidereProject/Twidere-Android/blob/842f07a26edb217ce22197d4baa6a77a43aad116/twidere/src/main/kotlin/org/mariotaku/twidere/service/LengthyOperationsService.kt#L187).

**Comment by Tedko** [comment]
> > I just see this commit ([5052d1f](https://github.com/TwidereProject/Twidere-Android/commit/5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c)) and seems like twitter is warning @mariotaku about private key and API usage, after talking with @mariotaku I think we can do nothing to solve this issue.
> 
> I downgrade the version to 3.8 but I can not obtain the benefits of official API. Is it the reason?

Hi @koroki  - you should able to use Official API on v4.0.6

**Comment by mist** [comment]
I had the same problem and it seems to be working fine again after installing 4.0.6 from fdroid.

**Comment by Tedko** [comment]
Thanks. 4.0.7 will be up on fdroid soon as well. I will close this issue
for now.

**Comment by Tedko** [comment]
@mist Thx ;)
