### ISSUE TITLE
Only 10 replies to tweets/10 media are shown 

### ISSUE THREAD

**Issue by hualuoshuijia** [TwidereProject/Twidere-Android#1231]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
Might be related:

![Screen Shot 2020-04-09 at 22 21 56](https://user-images.githubusercontent.com/6687437/78905532-bb188300-7ab0-11ea-8553-08fdf30cebc0.png)

@Tlaster
