### ISSUE TITLE
Official API don't work

### ISSUE THREAD

**Issue by koroki** [TwidereProject/Twidere-Android#1232]
After the error that I had with the last beta, I downgraded my app to 3.8. For doing it, I should uninstall the previous one, losing my configuration, where I used the official API.
When I introduce the values again, it doesn't work again. Basically, I introduce the two key consumers in the proper place. Is there any other option that should be introduced?

## Expected behavior
Having DM, translation and all interactions.
## Actual behavior
I don't have it.
## Steps to reproduce
Introduce an account in a new fresh instalation.

## Extra info

Android version: (version code here)
9.0
Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [x] Custom API
- [x] Custom consumer key/secrets
- [x] [Official keys]
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by orithena** [comment]
I remember reading some issue about not being able to re-authenticate with Twitters official keys last year or so. Can't find the issue any more, though. (Although I did find the hint to try xAuth while having 2FA disabled on the account.)

**Comment by Tlaster** [comment]
Official key support is now back online you can try it with the newest version.
