### ISSUE TITLE
Image is unloaded when switching tabs

### ISSUE THREAD

**Issue by abcang** [TwidereProject/Twidere-Android#1235]
## Expected behavior
Images remain displayed even if tabs are switched.

## Actual behavior
Image is unloaded when switching tabs

## Steps to reproduce
Switch tabs. It also happens when you press a tab button or swipe. It also happens on homes and notifications, not just on lists.

![20200408_222449](https://user-images.githubusercontent.com/4199439/78789344-fbf89500-79e7-11ea-940b-ffd4c25cf450.gif)

## Extra info

Android version: 9

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.0.6 (May occur at 4.0 or higher)

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tlaster** [comment]
Fixed by a2cec21b18097aa6c48bbd02a73432e94b80ce5f
