### ISSUE TITLE
cannot connect anymore my account after removing and reinstalling twidere

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [TwidereProject/Twidere-Android#1236]
## Expected behavior

Be able to connect my account with 2FA enabled

## Actual behavior
i was able to connect my account then removed the application and since then i cannot connect it anymore, my account is 2FA enabled

## Steps to reproduce

- install application from fdroid
- click on connection
- nothing happen

## Extra info

Android version: (version code here)

7.1.2

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: (version code here)

503

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by polyzen** [comment]
I couldn't login using any of the auth types, with and without 2FA enabled.

**Comment by polyzen** [comment]
Was able to log in with 3.7.6, and then upgraded.

**Comment by Tlaster** [comment]
Seems like a build-in consumer key issue, which were fixed by b1b9fd6026735312b69b50266fe0e9d9d8fa7d67
It will be fixed in the next update.
Reopen if you still encounter the same issue after the new update.
