### ISSUE TITLE
Disable retweets in lists

### ISSUE THREAD

**Issue by virgilinojuca** [TwidereProject/Twidere-Android#1241]
It seems that if I disable retweets from a user, they only stop showing up in the Home tab, but not in List timeline tabs. Is there a way to hide them in List tabs? If not, could it be implemented?

**Comment by Tlaster** [comment]
Done by 478a7dd1aeb7403a2bc15fb7f2ff854eb7fa696d

**Comment by virgilinojuca** [comment]
Hello. It seems that, with the last update, there is now an option to disable all retweets in a list tab. That is useful, but I wonder if you could make the setting for a specific user have effect in list tabs. I'm talking about unchecking the "Enable retweets" option in the user profile page. If I uncheck it, there is no effect in list tabs, only in the Home tab.

**Comment by Tlaster** [comment]
I see, add a new timeline tab with accounts and each account can enable/disable retweets might be a good choice.
I will add this functionality in the future.

**Comment by virgilinojuca** [comment]
I don't know if I made myself understood yet. Sorry if that's the case. I don't use multiple accounts; I have only my personal Twitter account.

It's just that I follow some people whose retweets flood the timeline or are kind of spam, but I'm still interested in their own tweets, that they write themselves. So I want to filter only what these specific people retweet.

There is already the option to disable their retweets (going to their profile > 3 dot menu > unchecking "Enable retweets"), but it seems to have effect only in the "Home" tab. Their retweets still appear in the lists they are in. I wondered if they could stop appearing in list tabs. Or else, if there could be a filter option to hide only the retweets of some profile.

**Comment by Tlaster** [comment]
Oh, sorry, now I see, make a filter option for it might be a good way if you don't want to see some people's retweet but still want to see their tweets in the home tab.
There will be a filter option for it in the future.

**Comment by jasongrig** [comment]
still the fix does not exist
