### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by pubmania** [TwidereProject/Twidere-Android#1242]
I am unable to login to twitter using twidere and figured I will register the app using https://developer.twitter.com/ and get the consumer API keys from there. However, I am not entirely sure what am I to put in the field named **Call Back URLs**

![image](https://user-images.githubusercontent.com/1966557/79226350-274f0a00-7e56-11ea-84da-0537d786c8f1.png)

Please can anyone give some guidance on this?

I can get consumer API Keys without this callback URL if I do not select the checkbox "Sign-in with twitter" but they do not work and so I am assuming that in order to use the consumer keys for authentication I must select that checkbox in which case I do need to provide the callback URL.

![image](https://user-images.githubusercontent.com/1966557/79234018-87977900-7e61-11ea-8d2a-9889051bf501.png)

**Comment by Tedko** [comment]
We will have official key support back soon -

**Comment by pubmania** [comment]
Thats brilliant. Still if it is not breach of any frameworks will it be possible to provide the guidance on call back url please?

**Comment by Tlaster** [comment]
You can put any URL as you like when using OAuth.
And the official key support is now back online you can try it with the newest version.

**Comment by pubmania** [comment]
Thanks. It did work after I put www.twitter.com/authorize as call back URL. I can also confirm that official key support is now working. 👍
