### ISSUE TITLE
Don't know what to do to use Twidere

### ISSUE THREAD

**Issue by lalejand** [TwidereProject/Twidere-Android#1243]
## Expected behavior
Be able to configure and use a twitter account.

## Actual behavior
At launch, twidere asks for some configuration and I don't know what to do.

## Steps to reproduce
Just installed Twidere. At launch Twidere asks which account I want to configure (I suppose):
![image](https://user-images.githubusercontent.com/30934848/79238264-781f2c80-7e6f-11ea-9d7e-018a1596984b.png)
If I click on "paramètres utilisateur" or "twitter" I get the same screen (why then two options?):
![image](https://user-images.githubusercontent.com/30934848/79238524-c3d1d600-7e6f-11ea-92f8-fd453969d84d.png)
I enter my id/pswd of my twitter profile, but I get an error:
![image](https://user-images.githubusercontent.com/30934848/79238627-e82db280-7e6f-11ea-9063-514aaacc4796.png)
If I click on the HD icon on top of the screen I get a configuration page of which I don't understand what I have to do:
![image](https://user-images.githubusercontent.com/30934848/79238776-1612f700-7e70-11ea-9a20-54ec5aa32e8f.png)

I didn't find any user manual or documentation to know how to configure social networks profiles.

## Extra info

Android version: 9

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 4.0.6

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by polyzen** [comment]
Duplicate of #1236
