### ISSUE TITLE
Saving media to gallery doesn't actually save media

### ISSUE THREAD

**Issue by f3rcho4r** [TwidereProject/Twidere-Android#1244]
Expected behavior 
When watching media from twitter, if you click on 'Save to gallery' the media should be saved to a folder named Twidere.

Actual behavior
The application displays a message saying that the media has been saved but the media can't be found in the gallery. The only way to save media is chosing 'Save to' and manually selecting a folder for the media to be saved to.

Steps to reproduce
Open media from Twitter.
Click three dots menu. 
Chose 'Save to gallery'
Extra info

Android version: Android 9.0 (Pie)

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.0.6

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by f3rcho4r** [comment]
The issue seems to happen also for images. Will edit accordingly

**Comment by Tedko** [comment]
![Screen Shot 2020-04-17 at 17 42 27](https://user-images.githubusercontent.com/6687437/79557709-96866180-80d5-11ea-8e4c-b257dc217a3b.png)
