### ISSUE TITLE
Report tweet

### ISSUE THREAD

**Issue by rancidfrog** [TwidereProject/Twidere-Android#1247]
Support reporting tweets

**Comment by Tedko** [comment]
hi @rancidfrog - can you specify what's ' reporting tweets' ?

**Comment by f3rcho4r** [comment]
> hi @rancidfrog - can you specify what's ' reporting tweets' ?

In twitter you can report tweets for spam, harassment, ilegal content or any other violations of twitter's rules.

**Comment by Tedko** [comment]
@rancidfrog @f3rcho4r So far twitter has not provide any API for 3rd party Apps to do the reporting. It's not able to achieve purely from our side and I guess we can wait for new APIs or potential  webview hacks later. I will close this for now . Thx
