### ISSUE TITLE
Fanfou support bug

### ISSUE THREAD

**Issue by Tedko** [TwidereProject/Twidere-Android#1248]
Check before submitting issue -- Thank you!

![Screen Shot 2020-04-17 at 17 53 06](https://user-images.githubusercontent.com/6687437/79574519-dc9dee00-80f2-11ea-9c44-60b0f8b160f6.png)

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [x] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
Able to reproduce on my side

**Comment by Tedko** [comment]
![20200418-125912](https://user-images.githubusercontent.com/6687437/79628709-0d733700-8176-11ea-900a-4b2b99c0830b.gif)
<img width="591" alt="Screen Shot 2020-04-18 at 13 04 34" src="https://user-images.githubusercontent.com/6687437/79628711-119f5480-8176-11ea-9b14-b01a25245147.png">

Potential fix -

**Comment by Tlaster** [comment]
Fixed by 614754f9754f649d35672ac1589adf5be688004a
