### ISSUE TITLE
[4.0.7] No replies displayed under tweets

### ISSUE THREAD

**Issue by Draky50110** [TwidereProject/Twidere-Android#1249]
Hello.

Just tried new 4.0.7 (PlayStore) and it does not shows replies under a tweet.

Not sure if related to #1231 because not even 10 answers, it loads (cirle) ans hows nothing after minutes...

**Comment by f3rcho4r** [comment]
I had the same issue but fixed it by re-signing in using official keys, using x-auth and ticking the "Use same URL as oauth". Somehow that did the trick.

**Comment by MrReSc** [comment]
I'm facing the same issue.

**Comment by palfans** [comment]
Same here.

**Comment by Tedko** [comment]
I can reproduce this as well @Tlaster

**Comment by Tedko** [comment]
Also -
<img width="771" alt="Screen Shot 2020-04-18 at 13 25 30" src="https://user-images.githubusercontent.com/6687437/79628992-4b715a80-8178-11ea-8d8d-c861e9c776dd.png">

**Comment by Tedko** [comment]
> I had the same issue but fixed it by re-signing in using official keys, using x-auth and ticking the "Use same URL as oauth". Somehow that did the trick.

@f3rcho4r Thanks! Will take a look and try fix this asap
