### ISSUE TITLE
DM bugs

### ISSUE THREAD

**Issue by Tedko** [TwidereProject/Twidere-Android#1252]
Check before submitting issue -- Thank you!
![20200418-230618](https://user-images.githubusercontent.com/6687437/79645000-0d5b5180-81df-11ea-8c04-78b2f86cec9f.gif)

Also seems it's impossible to fetch twitter DM history?

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by alanpoulain** [comment]
I don't think https://github.com/TwidereProject/Twidere-Android/commit/4da4b3b52c204f5f780098ce8ffb9c09abd970b8 has fixed the fetching of DM history. Should be reopened IMHO.

**Comment by Tlaster** [comment]
Thanks @alanpoulain , are there duplicate DM after upgrading to 4.0.9?

**Comment by alanpoulain** [comment]
In my case (4.1.0), I cannot fetch the previous DM I sent or received, it's totally empty. In logcat, if it can help you, I have:
```
[org.mariotaku.twidere/org.mariotaku.twidere.activity.LinkHandlerActivity#0] disconnect: not connected (req=1)
```
Maybe it's just me having this issue? Thanks for your work anyway :slightly_smiling_face:

**Comment by Tlaster** [comment]
@alanpoulain Is the DM from 30 days ago? [DM API](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events) can only fetch DM within the last 30 days.

**Comment by alanpoulain** [comment]
Oh OK, I didn't know. Sorry for the noise.

**Comment by Tlaster** [comment]
It's ok, feel free to reopen if the issue still exists
