### ISSUE TITLE
How can I join DM Groups?

### ISSUE THREAD

**Issue by JPRuehmann** [TwidereProject/Twidere-Android#1253]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Able to find and enter Groups.
## Actual behavior
Can´t find Groups.
## Steps to reproduce
Don´t know.

## Extra info

Android version: (version code here)
9
Network type:

- [X] Cellular
- [X] Wi-Fi

App version: (version code here)
4.0.8
Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [X] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by f3rcho4r** [comment]
Firstly, what you submitted is NOT an issue. This section is to submit bug, issues. 
In the DM section, tap the plus button and select multiple users to create a group DM.

**Comment by JPRuehmann** [comment]
Sorry if I am at the Wrong Place.
My problem is not to create but to enter an sexistng group.
Thanks.

**Comment by JPRuehmann** [comment]
I am an invited and esisting member of the group.
And can enter it with Twitter, Tweetdeck or Twitter for Android.
But how can I do it with Twidere?
Thanks.

**Comment by f3rcho4r** [comment]
> I am an invited and existing member of the group.
> And can enter it with Twitter, Tweetdeck or Twitter for Android.
> But how can I do it with Twidere?
> Thanks.

No problem, friend. From what I can understand: you're in a group DM that doesn't show up in the DM section in Twidere. That could be an issue, but you should check opened issues to see if it has been reported or if what you're reporting is part of an already opened issue. 
In particular, I believe issue #1252 is about various DM errors, you could add your info to that one. As far as I know, the devs are aware of DMs not working entirely correctly and are working on fixing them. 
For the future, try to make your reports as complete as possible, giving all the info the form requires as a minimun and more if you can.

**Comment by JPRuehmann** [comment]
Hello
I´ve searched but had not find any.
I´ve entered all I could.
Thanks,

**Comment by Tedko** [comment]
I will close this one - duplicate with #1252 

@JPRuehmann For group DM, as far as I know - Tweetdeck is owned by Twitter, so far Twitter have not provide any APIs allow access of group DM, and no API based 3rd party twitter client able to do so. Maybe we can try do a webview hack later but not now.

**Comment by Tedko** [comment]
Also @f3rcho4r Thanks for the input. Pls spread the words of Twidere since we need more community contributors 👍

**Comment by f3rcho4r** [comment]
> Also @f3rcho4r Thanks for the input. Pls spread the words of Twidere since we need more community contributors 👍

Whatever I can help with!
