### ISSUE TITLE
Video controls covered by OS buttons

### ISSUE THREAD

**Issue by defaultxr** [TwidereProject/Twidere-Android#1261]
![Screenshot_20200421-035112](https://user-images.githubusercontent.com/601567/79846810-7e883980-8384-11ea-8b3c-31553819e1af.jpg)

## Expected behavior
The video player controls should appear above the OS buttons.
## Actual behavior
The OS back/home/apps buttons cover the video interface, making them impossible to use.
## Steps to reproduce
Open any video in twidere 4.0.8 on OnePlus 6 Android 9 OxygenOS 9.0.9.
## Extra info

Android version: OnePlus 6 Android 9 OxygenOS 9.0.9

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.0.8

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

Any

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by abcang** [comment]
This behavior also happened in my environment.

- Xperia XZ1 Compact
- Android 9
- Twidere 4.1.0 (did not happen in 4.0.9)

**Comment by clavelm** [comment]
Same on realme x2 pro running unofficial LineageOS 17.1
Since twidere version 4.1.0

**Comment by Tlaster** [comment]
3240665b7dac5a0cd33870f82e4e4685b86b9825 break this, but still a nice to have feature.
Revert it for now, will provide a better way
