### ISSUE TITLE
Remove streaming

### ISSUE THREAD

**Issue by Xefir** [TwidereProject/Twidere-Android#1266]
Twitter forbid the use of streaming, Mastodon Streaming API isn't implemented and isn't really reliable and I don't think other platform has this option.

So I think, why not remove all the code around streaming capabilities witch seems useless.
I just thinking on it, I just want your opinion on this.
Thank you :)

**Comment by Tlaster** [comment]
I can confirm that streaming is not working anymore with twitter. I think it's time to remove streaming.

**Comment by Tedko** [comment]
if Twitter  streaming is not usable anymore then lets rm that

**Comment by Tlaster** [comment]
I just notice that twitter replace streaming API with Account Activity API ([migration guide](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide)), which is premium/enterprise API, should we migrate to Account Activity API?

**Comment by Xefir** [comment]
Do we have a premium/enterprise API ? If yes, why not. If no, will you be able to afford the price of this API ?

**Comment by Tlaster** [comment]
No, we can remove streaming until someone willing to provide premium/enterprise key

**Comment by Tedko** [comment]
Enterprise API so far only allow up to 250 user etc. not really that useful ;(

**Comment by Xefir** [comment]
I think, if we implement the Account Activity API, maybe with the hack with the official keys, this will maybe works because normally, official keys isn't limited don't they ?

**Comment by Tlaster** [comment]
The official key support is not that stable, 5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c might happen again

**Comment by Tlaster** [comment]
I think we can disable it for serval versions and tell the user streaming is not working anymore since twitter removes the streaming API, then remove it completely.

**Comment by Tlaster** [comment]
Remove Streaming API since there is no replacement API which is useable for this.
Will write into the changelog
