### ISSUE TITLE
[Feature request] Translation

### ISSUE THREAD

**Issue by koroki** [TwidereProject/Twidere-Android#1269]
One of the most interesting features of twitter official API is translation. 
Since the official API is not working (or I couldn't enable properly), I'm requesting for this feature.

I suppose that there is the possibility to use google translate API or Bing API for it.

**Comment by tomac4t** [comment]
They are paid API, and using Google Cloud you must have a credit card:
https://cloud.google.com/translate/pricing
https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator-text-api/

**Comment by Xefir** [comment]
Yandex provide free API key and service without entering credit card with a limited number of character per mouth like so : 

> the volume of the text translated: 1,000,000 characters per day but not more than 10,000,000 per month.

That can be a solution if the functionality isn't too often used

**Comment by JLRomero12** [comment]
I would also love to have this feature :) the app is amazing so far, thank you for the good work!!

**Comment by iknownothingaboutcomputers** [comment]
> Yandex provide free API key and service without entering credit card with a limited number of character per mouth like so :
> 
> > the volume of the text translated: 1,000,000 characters per day but not more than 10,000,000 per month.
> 
> That can be a solution if the functionality isn't too often used
> 
> https://translate.yandex.com/developers/offer

Fedilab, an android app for Mastodon, uses Yandex for translating toots. It also scrubs sensitive info before sending the query to Yandex. Perhaps you should check https://github.com/stom79/Fedilab to learn more about how it does this.

**Comment by stom79** [comment]
> Fedilab, an android app for Mastodon, uses Yandex for translating toots. It also scrubs sensitive info before sending the query to Yandex. Perhaps you should check https://github.com/stom79/Fedilab to learn more about how it does this.

It works with a lib that I built. More at https://github.com/stom79/mytransl/blob/master/README.md

**Comment by Tlaster** [comment]
Translation support was done by 0fc88a40766aece8e17a314309de7b244d870961 using yandex translate API.
And you can config the API key in network->advance

**Comment by koroki** [comment]
Thanks!

**Comment by FlaminSarge** [comment]
For those only seeing this issue now, looks like Yandex shut down their free API:

> We no longer issue free keys for the Yandex.Translate API. For all existing free keys, there will be a limit of 50,000 symbols as of July 31st and these keys will stop working on August 15th.
