### ISSUE TITLE
Tweet thread not working anymore

### ISSUE THREAD

**Issue by clavelm** [TwidereProject/Twidere-Android#1272]
When (trying) to read a tweet thread, the next tweet of the thread is not displayed but answers to the specific tweet of the thread. 

## Expected behavior
When reading a tweet thread (a succession of tweets from a same author each one as a response to the previous one), each tweet of the thread is displayed one after another. 

## Actual behavior
The thread is not displayed but tweets from others that respond to the current tweet of the thread, sometimes the next tweet of the thread is mixed in the lot but not always. 

## Steps to reproduce
Since version 4.1.0

## Extra info

Android version: 10 (LineageOS 17.1)

Network type:

- [ x] Cellular
- [ x] Wi-Fi

App version: 4.1.0

Build variant:

- [ x] Google
- [ ] F-Droid

Micro-blogging service:

- [ x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tlaster** [comment]
Seem like b4612859b2f1d6678940e74952e21a4ea68d8b85 break this, tweet thread was fetched from a web page of twitter as replies and can show up to 10 replies, since twitter does not provide API for the tweet thread.
Will revert that change but maybe there's a better way.

**Comment by Symbian9** [comment]
> tweet thread was fetched from a web page of twitter as replies and can show up to 10 replies, since twitter does not provide API for the tweet thread.
> Will revert that change but maybe there's a better way.

What about fetch thread from Nitter web page: `https://nitter.net/<thread_URL>` instead of `https://twitter.com/<thread_ID>`?

**Comment by clavelm** [comment]
The problem is back in v4.1.3
