### ISSUE TITLE
Navigation bar obscures media controls on Galaxy Note 9

### ISSUE THREAD

**Issue by utopianfiat** [TwidereProject/Twidere-Android#1287]
## Expected behavior
Navigation bar is hidden when full screen media plays, or otherwise does not obscure media controls

## Actual behavior

Media controls are obscured

## Steps to reproduce

- Twidere 4.1.0
- Samsung Galaxy Note 9
- Open a tweet (or whatever) that contains embedded video
- Open the embedded video
- Attempt to unmute the video

## Extra info

![20200427_130133](https://user-images.githubusercontent.com/38402346/80399509-4d799e80-8887-11ea-9f81-2bbfe680e3be.jpg)

Android version: 10

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.1.0

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tlaster** [comment]
This was fixed by 79898cdccf0722ab570a72df68b4add8860338ca and the fixed version is 4.1.1
Can you try the version 4.1.1?

**Comment by utopianfiat** [comment]
Sure. FWIW I'm on F-droid where the latest seems to be 4.1.0. Looks like
I'll have to migrate to the Play Store channel version to upgrade.

**Comment by Tedko** [comment]
> Sure. FWIW I'm on F-droid where the latest seems to be 4.1.0. Looks like I'll have to migrate to the Play Store channel version to upgrade.
> […](#)

F Droid have their own version control so we have to wait for them to fetch the latest the 4.1.1.

**Comment by Tedko** [comment]
Will close this for now and lets wait for 4.1.1 on FDroid -
