### ISSUE TITLE
Thread following seems broken

### ISSUE THREAD

**Issue by Rhialto** [TwidereProject/Twidere-Android#1289]
## Expected behavior
Somebody retweets the beginning of a thread. Sometimes adding something like "Look at this great thread!". So I tap on the tweet, expecting to see that tweet again, and the next messages from the same author below it.
## Actual behavior
I see the first message from the thread, and below it I see replies from other people to the thread. Often they add remarks like "yes that was a good thread". Unfortunately, I don't see any message from the thread past the first one. 

In case it helps, here is a link to one first message where this happened to me: https://twitter.com/beca_carrillo/status/1254515538845409280  I'm not sure if I can generate a link to the re-tweet, so far I didn't manage. It was retweeted by https://twitter.com/Felienne on April 26 or so.
## Steps to reproduce
As above.
## Extra info
I think this started happening at the latest update.
Android version: (version code here)
Android 7.0
Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: (version code here)
Twidere 4.1.0
Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786) (unfortunately that link is dead, but I think I should mark this one anyway since I don't remember fiddling with that)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by DaleBCooper** [comment]
Can confirm this with version 4.1.0.
4.0.8 works as expected.

**Comment by Rhialto** [comment]
I had an update to 4.1.1. On this new version I can't reproduce the problem any more. (To be accurate, I didn't try to go back to the tweet I mentioned above, but I don't see the problem on others any more).

**Comment by Tlaster** [comment]
Seems like this is the same issue with #1272 , still investigating a better way to fetch all replies
