### ISSUE TITLE
Even if you delete a saved search, it comes up again in the search bar. (It remains undeleted.)

### ISSUE THREAD

**Issue by Tedko** [TwidereProject/Twidere-Android#1290]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by f3rcho4r** [comment]
Sorry but I haven't been able to reproduce this. All searches, wether I save them or not, if I delete them from recent searches or from the list of saved searches, they get deleted properly.

**Comment by Tedko** [comment]
Yes I can’t reproduce either. This is a feedback from user on google play

**Comment by Tedko** [comment]
cannot reproduce. will close now.
