### ISSUE TITLE
Github releases are marked as "pre-release"

### ISSUE THREAD

**Issue by mbanck** [TwidereProject/Twidere-Android#1297]
All the releases (at least all on the first page) on https://github.com/TwidereProject/Twidere-Android/releases are marked as "pre-release" even though the latest one (4.1.1 as of writing) is shipped via the play store.

That's a bit weird and might scare people away, so unless there is a good reason for it, it should be removed? Maybe that is just being copy-pasted from one release to the other and was never lifted?

**Comment by Tlaster** [comment]
The pre-release tag is set by Travis from [the config file](https://github.com/TwidereProject/Twidere-Android/blob/master/.travis.yml#L64).
Yes, it's time to remove the pre-release tag, I did not think about it before.
