### ISSUE TITLE
Sensitive content enabled - Feature request type:feature-request

### ISSUE THREAD

**Issue by RayLennox** [TwidereProject/Twidere-Android#1298]
Add option to enable "sensitive content" by default. Some accounts appear to be flagged as having sensitive content which don't actually have any. I think the old version had an option for this in settings. 

Add option to open links in the browser by default instead of opening in Twidere.

Thanks for bringing back this great app.

**Comment by Tlaster** [comment]
You can enable display sensitive contents by turn on the settings -> content -> Display sensitive contents at the bottom. And if you want to show media at the timeline, you can enable it by settings -> cards -> media preview.
You can open links using the browser by turn off the settings -> content -> in-app browser.
