### ISSUE TITLE
Feature request: Export Filters

### ISSUE THREAD

**Issue by Mokura** [TwidereProject/Twidere-Android#1299]
Since Twidere and Twitter's filtering mechanisms are different, would it be possible to create an option to create a list or csv of blocked usernames and/or their twitter usernames?  (@example)

**Comment by Tlaster** [comment]
You can export filters by Settings -> Other settings -> Import/Export settings. Which will create a zip file that contains a Json file called `filters.json`

**Comment by Mokura** [comment]
Wait, I never closed this issue?  Sorry about that!
