### ISSUE TITLE
Example signing file?

### ISSUE THREAD

**Issue by Javran** [TwidereProject/Twidere-Android#130]
Would you mind providing example files for signing?
I want to sign the release version but cannot figure out how to make it done automatically.
Would you mind sharing signing files like `signing.properties` etc. with an extra extension (e.g. `signing.properties.example`. (Be sure to remove sensitive information though)

**Comment by mariotaku** [comment]
here: https://gist.github.com/mariotaku/7a0c51955d14def2fa0e#file-signing-properties

**Comment by Javran** [comment]
Thanks! It's working nicely :)

**Comment by mariotaku** [comment]
maybe I should add a build instruction for developers.
