### ISSUE TITLE
Unable to like tweets 

### ISSUE THREAD

**Issue by WalterS** [TwidereProject/Twidere-Android#1300]
Whenever I try to like a tweet, I get the error "Network error: Empty data" and the tweet in question is saved as favourite in drafts. 

## Expected behavior
Being able to "like" tweets. 

## Actual behavior
Unable to "like" tweets

## Steps to reproduce
Tap on the heart icon of any tweet. 

## Extra info

Android version: 8.0

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 4.1.1

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Tedko** [comment]
duplicate with #1293 -
Pls move this discussion to #1293
