### ISSUE TITLE
Can't like tweets

### ISSUE THREAD

**Issue by abh-oss01** [TwidereProject/Twidere-Android#1304]
I cannot like the tweets, the app returns "Network error: Empty data" all the time.
Tried uninstalling and reinstalling, and loggging in, but same issue again.

https://www.imgur.com/a/zGqlwJx

**Comment by Tlaster** [comment]
Same issue as #1293 
As https://github.com/TwidereProject/Twidere-Android/issues/1293#issuecomment-625684789 said Twidere's key currently limited by twitter. A quick workaround is replacing Twidere's key with other consumer keys.
Close as duplicated
