### ISSUE TITLE
View Home timeline of certain account

### ISSUE THREAD

**Issue by roytam1** [TwidereProject/Twidere-Android#1305]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

I hope I can view Home timeline of certain account, just like currently available Public and/or federated timeline entry in left menu.

Android version: 8.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.1.1

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [x] Fanfou
- [x] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tlaster** [comment]
You can add it as a tab by Settings -> Tabs -> Add button at the top right -> User's tweets.

**Comment by roytam1** [comment]
> You can add it as a tab by Settings -> Tabs -> Add button at the top right -> User's tweets.

I think the user's tweets page is NOT the same as account's home timeline.

**Comment by Tlaster** [comment]
Oh, I misunderstood.
By default, home timeline will display your activated account's timeline from the Accounts page, you can disable/enable the account to hide/show home timeline, or you can add a home tab at Tabs setting with a specific user's home timeline.

**Comment by roytam1** [comment]
> you can add a home tab at Tabs setting with a specific user's home timeline.

OK understood, but can the domain name of account be shown in account selection popup?

**Comment by roytam1** [comment]
and I think it will be nice to be accessible from left menu.

**Comment by Tlaster** [comment]
> > you can add a home tab at Tabs setting with a specific user's home timeline.
> 
> OK understood, but can the domain name of account be shown in account selection popup?

Currently no, seems like we need a better way to display user type.
