### ISSUE TITLE
Show account domain name in left menu

### ISSUE THREAD

**Issue by roytam1** [TwidereProject/Twidere-Android#1306]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

I hope twidere can show account's domain name in left menu because I have several accounts that have same name and I can't distinguish them without account's domain name.

Android version: 8.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.1.1

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [x] Fanfou
- [x] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tlaster** [comment]
Done by f49b77bfce9dd18f703699ba230fce60edd9b9fa
If you have multiple accounts with different domains, the account type(twitter, mastodon, etc) will display at the drawer before your user name like `twitter@twidere`, otherwise will only display your user name like `@twidere`

**Comment by roytam1** [comment]
> the account type(twitter, mastodon, etc) will display at the drawer before your user name like `twitter@twidere`

does it work with multiple mastodon accounts (for example: roy@mstdn.jp and roy@mastodon.social)?

**Comment by Tlaster** [comment]
> > the account type(twitter, mastodon, etc) will display at the drawer before your user name like `twitter@twidere`
> 
> does it work with multiple mastodon accounts (for example: [roy@mstdn.jp](mailto:roy@mstdn.jp) and [roy@mastodon.social](mailto:roy@mastodon.social))?

No, I've opened a new issue about it #1307
