### ISSUE TITLE
Better way to display user domain

### ISSUE THREAD

**Issue by Tlaster** [TwidereProject/Twidere-Android#1307]
From #1305 and #1306 , it's necessary to display user domain in case of user have multiple accounts from different domains with the same name

**Comment by Tlaster** [comment]
Done by 9ae74b04f7db06c1dc8d899b9a15ba5a4030eb41

**Comment by roytam1** [comment]
can same mechanism be applied to statusnet as well?

**Comment by Tlaster** [comment]
Yes, but not implemented yet
