### ISSUE TITLE
Lack of network could queue tweets for sending when network returns [feature request]

### ISSUE THREAD

**Issue by pseudomonas** [TwidereProject/Twidere-Android#131]
If I attempt to tweet but there is no network connectivity, the tweet is saved as "draft" - could there be an option to automatically re-attempt to post the tweet when connectivity returns? There is similar behaviour to this in the K9 mail client (failed outgoing mail is saved in an outbox and automatically sent as soon as there is network)

**Comment by mariotaku** [comment]
dup to #114.
