### ISSUE TITLE
Arabic language is missing

### ISSUE THREAD

**Issue by BoFFire** [TwidereProject/Twidere-Android#1319]
## Expected behavior
It is expected that `values-ar/strings.xml` to be displayed when Android is in arabic.

## Actual behavior
Arabic is missing since 4.1.3

Network type:

- [ x] Cellular
- [ x] Wi-Fi

App version: 4.1.3

Build variant:

- [ ] Google
- [x ] F-Droid

Micro-blogging service:

- [ x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ x] Mastodon

**Comment by Tlaster** [comment]
There is a `values-ar-rSA` folder under `src\main\res-localized`, might needs to remove the region

**Comment by BoFFire** [comment]
Yes please use `values-ar`

**Comment by Tlaster** [comment]
Done by 9de195d26a635e63a6c7a3216dfc842fd9b99781

**Comment by BoFFire** [comment]
Thank you @Tlaster does this affect Crowdin translations synchronization with the repo ?

**Comment by Tlaster** [comment]
I didn't change the Crowdin's setting, and the synchronization is done manually.
Will find a better way to synchronize with Crowdin automatically.
