### ISSUE TITLE
Goal of fundings

### ISSUE THREAD

**Issue by Linkid** [TwidereProject/Twidere-Android#1323]
Hi!
I've just seen that a funding file appeared, without a PR to discuss about it. In Patreon, it is said that "100% of the money goes into maintainer and community members". So I was wondering how the money would be used?
Thanks :).

**Comment by Tlaster** [comment]
@Tedko for FYI

**Comment by Tedko** [comment]
@Linkid 

Hi for now the roughly number -

80-100$ /month so far for 2-3 months in-App purchase for google play. Google will take 30%. 

Haven’t received lots of donations yet. Around 20$ of btc received last month.

Most of these went to MARIO Lee, and dimension.im is sponsoring @Tlaster etc’s full time development on Twidere.

**Comment by Tedko** [comment]
@Linkid Hi I will close this issue for now. but feel free to re open for any question. Thank you for helping the community :)
