### ISSUE TITLE
Twidere crashes when opening a tweet

### ISSUE THREAD

**Issue by dhardy92** [TwidereProject/Twidere-Android#137]
device is nexus 7 2012 runing cyanogenmod 10.1.
This appear un the last version installed yesterday via google play store (0.3.0)

**Comment by g00dy22** [comment]
Also crashes on starting application.
Logcat:
E/AndroidRuntime( 1266): FATAL EXCEPTION: main
E/AndroidRuntime( 1266): Process: org.mariotaku.twidere, PID: 1266
E/AndroidRuntime( 1266): java.lang.StackOverflowError
E/AndroidRuntime( 1266):        at android.view.View.<init>(View.java:3512)
E/AndroidRuntime( 1266):        at android.widget.TextView.<init>(TextView.java:623)
E/AndroidRuntime( 1266):        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
E/AndroidRuntime( 1266):        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:40)
E/AndroidRuntime( 1266):        at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:99)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:782)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:810)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.onCreateView(ThemedLayoutInflaterFactory.java:68)
E/AndroidRuntime( 1266):        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 1266):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 1266):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(Native Method)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:277)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:77)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.getActionBarContext(ThemedLayoutInflaterFactory.java:175)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.initViewTint(ThemedLayoutInflaterFactory.java:121)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.initView(ThemedLayoutInflaterFactory.java:114)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.onCreateView(ThemedLayoutInflaterFactory.java:72)
E/AndroidRuntime( 1266):        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 1266):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 1266):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(Native Method)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:277)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
E/AndroidRuntime( 1266):        at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:77)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.getActionBarContext(ThemedLayoutInflaterFactory.java:175)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.initViewTint(ThemedLayoutInflaterFactory.java:121)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.initView(ThemedLayoutInflaterFactory.java:114)
E/AndroidRuntime( 1266):        at org.mariotaku.twidere.util.ThemedLayoutInflaterFactory.onCreateView(ThemedLayoutInflaterFactory.java:72)
E/AndroidRuntime( 1266):        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime( 1266):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 1266):        at androi
W/ActivityManager(  411):   Force finishing activity org.mariotaku.twidere/.activity.support.SignInActivity

**Comment by mariotaku** [comment]
should be fixed very soon.
