### ISSUE TITLE
Where are the preferences/options

### ISSUE THREAD

**Issue by fnordson** [TwidereProject/Twidere-Android#1370]
I know it may sound stupid and I didn't find any issue for this but I just can't find a way to manage preferences of this app. 
I only have the 4 symbols (home, bell, #, envelope). I tried changing orientation but...nothing. 

Android: 7.1.1
App: 4.1.4 (F-Droid)

**Comment by Archenoth** [comment]
Oh! You can swipe from the left edge of the screen to get to the sidebar, which has settings and a bunch of other things.

**Comment by fnordson** [comment]
Oh man...thank you.  
Somehow that never happened ;)
