### ISSUE TITLE
What are the Plans for the new Twitter API v2?

### ISSUE THREAD

**Issue by yoshimo** [TwidereProject/Twidere-Android#1382]
It seems we will get more access and features with the upcoming api version 2
https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html
Will Twidere be working on the preview release and be ready on "launch day" as well as give feedback to twitter to deliver the best possible experience for us users?

**Comment by Tedko** [comment]
hi there. actually we're working on a brand new twidere code base upgrade. so definitely we will have plans! i will leave more to @Tlaster

**Comment by Tedko** [comment]
thx @yoshimo

**Comment by Tlaster** [comment]
We're working on it! TwidereX will using the new Twitter API V2 from day 1 and will continually migrate the V1 API to V2 since there're still lots of API in V1
