### ISSUE TITLE
Follow-Up-Tweets on quoted Tweets are hard to access

### ISSUE THREAD

**Issue by yoshimo** [TwidereProject/Twidere-Android#1383]
## Expected behavior

If a person in my timeline quotes a tweet from a series of tweets i want to be able to quickly see the rest of the messages in that Thread.

## Actual behavior

All you can do is see the first level  ofreplies to the quoted tweet.

Android version:
9
App version: 
4.1.4

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

**Comment by ccoenen** [comment]
I think this is the same problem that we are discussing in #1357 - currently threads don't work properly.
