### ISSUE TITLE
Can't connect to Twitter anymore

### ISSUE THREAD

**Issue by Salamandar** [TwidereProject/Twidere-Android#1389]
I tried to connect with Twidere yesterday. It loads correct j'y the Auch page. My token number displays correctly.
Then... No thing : i'm back to selecting my account type (twitter/mastodon/...) 

What could be happening?

**Comment by Tedko** [comment]
@jk234ert

**Comment by Tedko** [comment]
@jk234ert try test again?

**Comment by jk234ert** [comment]
> I tried to connect with Twidere yesterday. It loads correct j'y the Auch page. My token number displays correctly.
> Then... No thing : i'm back to selecting my account type (twitter/mastodon/...)
> 
> What could be happening?

How about select the account and sign in again? Looks like something broken inside the app storage. Could you try clean the app data and re-launch Twidere again?

**Comment by Salamandar** [comment]
Hi, I tried some days ago and it works correctly now. I'm kinda guessing it was my Android ROM doing weird things because other apps had issues too that were resolved by changing ROM.
Sorry about the issue. closing.
