### ISSUE TITLE
Crashes when trying to share an image from Twidere

### ISSUE THREAD

**Issue by albatros69** [TwidereProject/Twidere-Android#1396]
When I try to share an image from the image viewer within Twidere, the app crashes. Sharing a message works however. I can also save the image locally and share the file afterward.
I tried to clear the media cache without success. If I can provide you with more insights (like detailed error message), don't hesitate to ask.

## Expected behavior
Hitting the "share" icon should present the "share" menu with the target choices

## Actual behavior
App crashes

## Steps to reproduce
Difficult to say... I just need to hit the "share" button inside the Twidere image viewer.

## Extra info

Android version: 11

Network type:

- [X] Cellular
- [ ] Wi-Fi

App version: 4.1.4

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Tedko** [comment]
@mtlaster

**Comment by albatros69** [comment]
Hello,
Just a quick update: I tried to reinstall Twidere but to no avail: the app still crashes when I share a picture.
I detected a weird behavior too: I'm unable to export the parameters. All seems to work properly: I can choose what I want to export but nothing happens after that (no error message, but no config file also). No crash though. I've no idea if it's related.
For what it's worth, I checked Twidere's authorization and I can access or save a file without a problem.

**Comment by alesevilla92** [comment]
It also happens to me, since I updated to Android 11.

I have a Xiaomi Mi 10. With Android 10 this didn't happen to me but now after updating it began to happen.

**Comment by fusenuk** [comment]
I thing this might be an Android 11 specific issue. I was using Twidere 4.1.4 on my Pixel XL with Android 10 and could share all media as normal, I then bought the new Pixel 4a 5G which runs Android 11 and the same Twidere version (4.1.4) now crashes when sharing any media.

**Comment by depewzhang** [comment]
Yes, I have the same issue, using Samsung S10+ Android 11.

**Comment by pongkiat** [comment]
I'm also facing this problem with Samsung S20FE Android 11

**Comment by Tlaster** [comment]
Fixed in 4.1.8
