### ISSUE TITLE
Position lost after exiting with "back"-button

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#14]
After exiting Twidere with the physical "back"-button it loses the position (jumps to newest) and discards older tweets, which can be quite annoying, when I have not read them yet.

**Comment by benediktg** [comment]
I can not reproduce this issue.

**Comment by Sohalt** [comment]
For me the issue still occurs from time to time. The cause pointed out by @gena01 seems very likely.
Not sure how to handle this. Further increasing the database limit might be an option. Alternatively the app could display a warning, when there are more tweets before the current position than can be saved.

**Comment by mariotaku** [comment]
Fixed - #406
