### ISSUE TITLE
latest update from F-Droid broke the app

### ISSUE THREAD

**Issue by ciphercharly** [TwidereProject/Twidere-Android#1403]
Latest update from F-Droid (03/12/2020) makes the app crash on launch. tried to uninstall and reinstall fresh, same behavior

Android version: 6.0.1

**Comment by x2k13** [comment]
Confirmed. Same behaviour on my end (Android 6.0).
Update installed, 4.1.5 - instacrash/force close on startup.

**Comment by poppypundit** [comment]
Please upgrade from github or wait for the update on Fdroid. The issue has been solved. Check closed issues for further details. 

https://github.com/TwidereProject/Twidere-Android/releases/tag/4.1.6

**Comment by ciphercharly** [comment]
right, sorry missed that
