### ISSUE TITLE
Twidere crashes on boot on v. 4.1.5

### ISSUE THREAD

**Issue by pappasadrian** [TwidereProject/Twidere-Android#1407]
## Expected behavior
Open twidere

## Actual behavior
Twidere crashes on app startup 

## Steps to reproduce
Upgrade / install version 4.1.5

## Extra info
When I upgraded Twidere to 4.1.5, it started crashing when I try to open it. I tried downgrading to the previous version without uninstalling and it still crashes. I tried uninstalling and reinstalling v. 4.1.5 and it still crashes. 
It got "fixed" by uninstalling and reinstalling v. 4.1.4

Android version: 7.0 on blackview bv8000pro

App version: 4.1.5

Build variant:
- F-Droid

Micro-blogging service:
I use it for Twitter but I think this is irrelevant 

App settings:
Nothing peculiar as far as I know

**Comment by Tedko** [comment]
#1406 
This is fixed by 4.1.6 . waiting f-droid to pull and update. thx for reporting 🙏
