### ISSUE TITLE
Favorite icon doesn't update when pressed on the tweet detail page. (Using latest version)

### ISSUE THREAD

**Issue by gena01** [TwidereProject/Twidere-Android#142]
If I click on a tweet i am taken to the "detail" page. If I press the favorite/star button then the tweet is added as a favorite, but the icon doesn't refresh until i click back and click on that tweet again.

**Comment by gena01** [comment]
Same issue, when trying to favorite a tweet that's part of a conversation stream.

**Comment by gena01** [comment]
Also if there's a network error the star doesn't reset back.

**Comment by mariotaku** [comment]
Seems fixed now, closing.
