### ISSUE TITLE
Keeps crashing at start

### ISSUE THREAD

**Issue by skaldk** [TwidereProject/Twidere-Android#1429]
I just tap the icon and boom, it crashes...

**Comment by ilakast** [comment]
Same here

**Comment by Silkspire** [comment]
Probably related to this:
https://www.msn.com/en-us/money/other/android-apps-are-crashing-for-some-but-google-is-working-on-a-fix/ar-BB1eRajb

Try updating WebView

**Comment by ilakast** [comment]
> Probably related to this:
> https://www.msn.com/en-us/money/other/android-apps-are-crashing-for-some-but-google-is-working-on-a-fix/ar-BB1eRajb
> 
> Try updating WebView

Upgrading "Android System WebView" in Play Store solved the problem. Thanks!
