### ISSUE TITLE
"Display name first" on cards doesn't work

### ISSUE THREAD

**Issue by modestman** [TwidereProject/Twidere-Android#145]
On cards user name is always first. Turn off option "Display name first" does not nickname first

**Comment by mariotaku** [comment]
@screenname will be displayed first when this option disabled, not nickname.

**Comment by modestman** [comment]
Yes, I mean @screenname, but it doesn't work. (Nexus 5, Android 5.0.1)

**Comment by andrew-t** [comment]
I'm using it on a Nexus 5 on Lollipop, and I find that the cards go "Graham Linehan @Glinner" regardless of the 'display name first' option — and that if I hit "reply", the tweet goes to "@Graham Linehan" which is very much not helpful.
