### ISSUE TITLE
"Users liked this" not working

### ISSUE THREAD

**Issue by Fricsion** [TwidereProject/Twidere-Android#1458]
## Expected behavior
Shows a list of users who liked a certain tweet.

## Actual behavior
No one shows up in the list

## Steps to reproduce
Tap any tweet on timeline -> tap Favorite counter 

## Extra info
Even if you pull down to refresh in "Users liked this" screen, nothing will load.

It works for (at least) Mastodon Toots. Twitter problem?

Android version: (version code here)
12

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
4.1.8

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by obar** [comment]
I can confirm, seeing the same issue

**Comment by Inrumpo** [comment]
I"m experiencing the same issue. I don't think Twidere is still in development though. They're focusing on the new X version.

**Comment by japhir** [comment]
On the new X version I don't see any equivalent button, so perhaps this could be filed there as well?
