### ISSUE TITLE
Gesture slide right to left opens empty space

### ISSUE THREAD

**Issue by modestman** [TwidereProject/Twidere-Android#146]
Slide from right screen edge to the left opens empty space.
Screenshot: https://www.dropbox.com/s/n8hfvu8nth8cbmw/Screenshot_2015-05-19-15-40-01.png
Video example: https://www.dropbox.com/s/95nlq6eruzxher0/19.05.15-15-29.mp4

**Comment by fphillips** [comment]
This is fixed. Tested with 0.3.0 dev-2015-09-20.
