### ISSUE TITLE
Logged out of Twitter account and can't log back in

### ISSUE THREAD

**Issue by HiddenLeveI** [TwidereProject/Twidere-Android#1476]
It was saying that nothing was authorized and that I had to log off and log back in. I logged off, now I put in my correct information, and it says "Incorrect API Settings" although it's not incorrect.

**Comment by jkelly99** [comment]
Same here

**Comment by RetroRevo** [comment]
api authentication issue, needs a new set of keys

**Comment by hanecak** [comment]
Seems like a duplicate of #1475 .

See https://github.com/TwidereProject/Twidere-Android/issues/1475#issuecomment-1381384755

**Comment by lalorazor** [comment]
same problem, the only solution I find is use Twidere-X

**Comment by fabioromeo** [comment]
What Twidere X does to login that Twidered does not? In twidere there's a setting to choose the API address, type of Auth and more, is this something we can change to fix the login?

**Comment by lalorazor** [comment]
> What Twidere X does to login that Twidered does not? In twidere there's a setting to choose the API address, type of Auth and more, is this something we can change to fix the login?

Twidere X login via authorization in twitter webpage, you need to login to your account in a browser and give permission to the app

**Comment by Tlaster** [comment]
> What Twidere X does to login that Twidered does not? In twidere there's a setting to choose the API address, type of Auth and more, is this something we can change to fix the login?

I've done a few testing, it seems that Twitter suspend most of the v1 API keys, the Twidere X uses the new v2 API Key and so far not been affected.
We will keep tracing this issue.

**Comment by HiddenLeveI** [comment]
Screw Elon. I never hated him but never cared for him. Now I despise him.

**Comment by Tlaster** [comment]
duplicate #1475
