### ISSUE TITLE
Reinstate Private Key Usage

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#1477]
In [this commit](https://github.com/TwidereProject/Twidere-Android/commit/5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c), I removed private API usage to comply Twitter's request.

Now that Twitter's being a d*ck by shut off almost all third party clients' access, maybe it can be enabled again.

**Comment by Tlaster** [comment]
Which is done [before](https://github.com/TwidereProject/Twidere-Android/commit/2407b9f193424511fe97f483692de85877814901).

**Comment by mariotaku** [comment]
Thank you and long live Twidere!
