### ISSUE TITLE
I don't know why I didn't think of this earlier, but the official Twitter API Keys work!

### ISSUE THREAD

**Issue by ghost** [TwidereProject/Twidere-Android#1480]
I don't know why I didn't think of this earlier, but the official Twitter API Keys work! 
Just put in the Twitter for Android API Key (https://gist.github.com/shobotch/5160017), change authentication to XAuth, put in your details and refresh. Worked on the first try for me, and you notification column will display likes for once!

_Originally posted by @jonas1015119 in https://github.com/TwidereProject/Twidere-Android/issues/1475#issuecomment-1399516017_
            

Not working for me. Says the account has been suspended the moment I click on login. (it hasn't).

**Comment by ghost** [comment]
Sorry, not sure how this happened. Please delete this.

**Comment by Yimellovzski** [comment]
it did not work in my phone, but luckily for me my account hasn't been suspended or locked. Better wait for a more stable and permanent solution!
