### ISSUE TITLE
Android M crash

### ISSUE THREAD

**Issue by mkody** [TwidereProject/Twidere-Android#150]
_They're coming..._

It's a fresh install, and Twidere crashed when the configurations steps shows up. I've heard that the offical Twitter App doesn't work too, so maybe it's hard to stay stable at the moment on Android M. 

Anyway, here's my logcat: https://gist.github.com/mkody/4b09adf88ca322b11893

Nexus 5, Android M (MPZ44Q)

**Comment by mariotaku** [comment]
Does newest version works?

**Comment by simon1573** [comment]
It does for me on my Nexus 6, Android M. Version 0.3.0-dev-115.

**Comment by mariotaku** [comment]
OK, I'll close this issue. If problem occurs, feel free to open another issue.
