### ISSUE TITLE
[Feature Request] Show same tweet from multiple accounts only once

### ISSUE THREAD

**Issue by zapat3ro** [TwidereProject/Twidere-Android#151]
I was wondering if it'd be possible to do this. For example, if I'm following The Guardian on two accounts, their tweets show up twice, once per account. Could it be possible to show it just once, and have the colour line (to identify which account it is from) be broken into pieces (in this case 2), with the colours chosen for each account?
Does that make sense?

**Comment by mariotaku** [comment]
Each tweet has its own state corresponding to account, like favorite, retweet. So currently it's not possible. Also merging tweets into one is very slow, which is inacceptable on mobile devices.
