### ISSUE TITLE
Can't write a DM from user's profile

### ISSUE THREAD

**Issue by mithrial** [TwidereProject/Twidere-Android#156]
How can I write a direct message (DM) to the user which profile I have currently open?

I see in the code ( https://github.com/TwidereProject/Twidere-Android/blob/ee57d0b5746d3aaf485d9bb3b20e574f36f8db21/twidere/src/main/res/menu/menu_user_profile.xml ) that the button is set to *not visible*. Is there a reason behind this? I couldn't find how to enable it and how to easily write a DM to the user–other than memorizing the name and typing it in the DM view.

**Comment by edent** [comment]
Press your phone's menu button - or the three dots in the top right. It should bring up a menu which has "Send DM" in it.

**Comment by mithrial** [comment]
No, it does not, there is no such button. 
I have the following options (translated from German):
Add to list, set color, enter nickname, add to filter, enable retweets, mute, block, report spam, mentions, open in account
![twidere-no-pm](https://cloud.githubusercontent.com/assets/581257/8285740/9a957bb8-1905-11e5-8850-ca9fa74dd666.png)

**Comment by edent** [comment]
Ah, in that case, the user is not following you - so you can't send them a DM.

Or does it also happen on accounts which *are* following you?

**Comment by mithrial** [comment]
This happens on all accounts. I can send DMs in the DM view, or via Tweetdeck or on Twitter directly.

**Comment by zhaidoudou123** [comment]
well, I cannot write DMs from user profile of whom follows me too.
It must be a bug and I am waiting for a fixed version.

**Comment by mariotaku** [comment]
confirmed & fixed in 2b6cdeae652ea092bd698fcbe7e6cf78ff047b4c
