### ISSUE TITLE
tweet links not opening in twidere

### ISSUE THREAD

**Issue by matejcik** [TwidereProject/Twidere-Android#157]
twidere registers for url intents for direct-link-to-tweet, but when I click a link to a tweet, and choose "open with twidere", the link opens in browser anyway.

instead, twidere should load the tweet by itself and show it with controls

**Comment by matejcik** [comment]
sorry, my bad, tweet links work (at least those i tried)
what doesn't work are links to twitter profiles

**Comment by oprudkyi** [comment]
yes, for me too 
https://github.com/TwidereProject/Twidere-Android/issues/95

**Comment by openbrian** [comment]
Doesn't work for me either.
