### ISSUE TITLE
Can't retweet from multiple accounts?

### ISSUE THREAD

**Issue by rwhillrunner** [TwidereProject/Twidere-Android#158]
It appears that I can't retweet a single tweet from multiple Twitter accounts. If I retweet from my business account, then attempt to retweet from my personal account, I'm only given the option to cancel the retweet from my business account.

**Comment by MStrohmeier** [comment]
You can do this by choosing "open from account", selecting the account you want to RT from, then retweeting it from there. This is because Twidere looks at accounts separately when actually viewing or interacting with tweets.

**Comment by rwhillrunner** [comment]
That's exactly what I expected but, when I tried that, I got the cancel retweet option instead.

**Comment by rwhillrunner** [comment]
Strange. It definitely did not work yesterday. I tried multiple times. I restarted my phone this morning and it worked just as I expected and you described. All seems as I would expect now.
