### ISSUE TITLE
Data usage / Image preload

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#159]
Most of the time I am using Twidere outside on the mobile network. Although I configured it, not to preload any profile images or preview images and also to only preload something when inside a WLAN, Twidere is consuming about 300MB of mobile data within 14 days. So, is the preload option really working like it should or am I misunderstanding the settings?

**Comment by benediktg** [comment]
I do not have this issue…
![screenshot_20160221-135801](https://cloud.githubusercontent.com/assets/14795615/13202679/3866a896-d8a3-11e5-8db7-73c1127d5f4b.png)
