### ISSUE TITLE
Preparing API calls and UI for longer DMs (Twitter feature change in July)

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#160]
Twitter gave a heads-up that they will allow DirectMessages up to 10k characters in length in July. This would mean some UI changes for sending a DM, as well as a minor API call modification when receiving DMs via REST.

https://twittercommunity.com/t/removing-the-140-character-limit-from-direct-messages/41348
> REST API
> DM read endpoints (GET direct_messages, GET direct_messages/sent and GET direct_messages/show)
> Send “full_text=true” as a query parameter to receive long DM text. If this parameter is not provided, you will get a truncated version of the DM. There will be no structural changes to the response returned by these endpoints.
> DM write endpoint (POST direct_messages/new)
> The “text” parameter will start accepting text longer than 140 characters. The new limit for DMs will be 10k characters.
> 
> Streaming API
> User Streams (GET user) and Site Streams (GET site) will automatically start receiving DMs that have text longer than 140 characters. Unlike the REST API, no additional parameter is needed. There will be no structural changes to the objects returned by these endpoints.

**Comment by orithena** [comment]
Bumping up this issue. Twidere currently receives and displays long DMs, but the "send" button in a DM conversation is silently useless if I try to send DMs longer than 140 characters.

**Comment by mariotaku** [comment]
I think this was done, closing.
