### ISSUE TITLE
cannot load tweets between the latest and some former

### ISSUE THREAD

**Issue by highlando** [TwidereProject/Twidere-Android#161]
1. say I did read some tweets some hours ago.

2. Now, when I start twidere and load my timeline, I get the latest 20 tweets. At the bottom of these 20 tweets I get the button "load more".

3. If I press  "load more", one more tweet appears but the reload button is gone. The latest 21 tweets are directly connected to tweets from some hours ago (cf. 1.). No chance to load the tweets in between.

UPDATE: I am no longer affected -- probably this was an issue of the twitter API

I am with Twidere 0.3.0, on Android 4.4.2, with a Galaxy Note 3. 
The reported behavior I have been observing since a few days - say 2015, June 5th. Before that everything was ok.

**Comment by iangreenleaf** [comment]
+1. Same behavior, also starting a few days ago. Android 4.4.4, Twidere 0.3.0, Moto X (first gen). Also happening to my friend's Moto X (second gen).

**Comment by gena01** [comment]
+1 "Load more" disappears.. need to either clear databases or fallback to older version.

**Comment by the100rabh** [comment]
+1 I too am facing the same issue on Nexus5 with Android 5.1

**Comment by jacroe** [comment]
:+1: MotoX (2nd gen) with Android 5.0 using Twidere (0.3.0, dev 2015-05-01)

**Comment by uvok** [comment]
Same problem here. When I downgrade to the previous f-droid version (0.3.0-dev-fdroid) from May 5, one account lets me only gets the first page of tweets (when there are already some older tweets, load more does nothing), my other account only loads 1 tweet if I click on "load more".

Clearing cache and databases does not solve the problem (it seems you can load all older tweets if you clear the database, but this is kind of inconvenient to do if you've been offline for some hours)

**Comment by morinap** [comment]
:+1: Twidere 0.3.0 (dev 2015-05-01), Moto X (2014) with Android 5.0

**Comment by homelinen** [comment]
I had this issue for the past few days but seems to have fixed itself. Had the same issue in Robird (to see if it was an api issue maybe). Android 5.1.1 (Google Play 0.3.0)

**Comment by jacroe** [comment]
Issue has resolved itself for me. Probably as @homelinen said, was a problem with the API?

**Comment by iangreenleaf** [comment]
Yes, Twitter engineering pretty regularly makes braindead technical decisions, so most likely they screwed something up in the API, and eventually noticed and fixed it. This issue can be closed.
