### ISSUE TITLE
0 Replies is always there when clicking on a tweet.

### ISSUE THREAD

**Issue by gena01** [TwidereProject/Twidere-Android#162]
It seems that 0 Replies is showing incorrect information as sometimes there's actually replies present, but the count is not updated?

**Comment by JanvierUK** [comment]
Clicking on the Retweets and Favourites number also doesn't show the correct information.

**Comment by hebu** [comment]
And also, very often the replies are not shown below the tweet, when there should be some.

**Comment by mariotaku** [comment]
Changed in recent versions.
