### ISSUE TITLE
Option to make faving two step or disable completely

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#168]
I often accidentally hit the star, thereby unintentionally favoring a tweet. It would be great to be able to activate a two step process whereby one has to confirm the fav after pressing the star. (Accidental RTs occur very rarely because you have to choose from the dropdown after pressing the RT symbol)
Alternatively I would be happy with an option to disable favs entirely since I never really use them.
Thanks and keep up the great work!

**Comment by mariotaku** [comment]
You can hide card actions in Settings - Cards.

**Comment by Sohalt** [comment]
Thanks, but that way the retweet button (which I use quite often) gets hidden too, so not exactly what I would want.

**Comment by fphillips** [comment]
@Sohalt Do you happen to be left-handed? Would swapping sides for the card actions help?

**Comment by Sohalt** [comment]
I'm right handed. What I really want is the possibility to selectively disable card actions
