### ISSUE TITLE
Wrong twitter handle when replying

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#169]
When replying to someone who embedded a tweet link in his/her tweet, Twidere is building the reply-handle wrong: The reply will be send to @displayname instead of @twitterhandle. This only happends, as I said, when a tweet link was embedded in the original tweet.

**Comment by edent** [comment]
Screenshot of the issue.

![broken reply](https://cloud.githubusercontent.com/assets/837136/8285491/9978346e-18fb-11e5-9766-173c1209114c.png)

**Comment by mariotaku** [comment]
fixed in recent versions.
