### ISSUE TITLE
DM not shown up when a new account is added

### ISSUE THREAD

**Issue by Javran** [TwidereProject/Twidere-Android#17]
After adding a new account into Twidere, I got notification about receiving new direct messages, the new DM counter on tab icon was also working, but no direct message is shown up, nor will pull-update help.

Can be reproduced by:
- Delete Twidere app data
- Add a new account (maybe with no DM), toggle some first-time settings.
- Add another account (this time with some DMs)

**Comment by benediktg** [comment]
Is this still an issue?
