### ISSUE TITLE
quote tweets' text truncated after original link

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#170]
设备：Google Nexus 4
系统：Android 5.1.1
Twidere版本：0.3.0(dev 2015-05-01) 
现象：若推文中附带的推文网址（如下所示）位于正文末尾以外的其他位置，将会出现截断现象。
样本：https://twitter.com/chenshaoju/status/609984187441872896
对应截图：
![screenshot_2015-06-14-15-23-10](https://cloud.githubusercontent.com/assets/515763/8149510/26121e08-12f8-11e5-9802-29fbe6ae0f8a.png)

**Comment by mariotaku** [comment]
![image](https://cloud.githubusercontent.com/assets/830358/8156234/dda455ba-137d-11e5-9a9f-340e2329a8bd.png)
this should work
