### ISSUE TITLE
Too many notifications on mention

### ISSUE THREAD

**Issue by jomo** [TwidereProject/Twidere-Android#171]
Whenever someone mentions me, I get notifications for a bunch of recent mentions, for multiple accounts:

![screenshot](https://i.imgur.com/UEr3ZZel.jpg)

I installed Twidere via F-Droid on CyanogenMod. This issue also isn't new, it has been happening for quite a while.

**Comment by tasmo** [comment]
Same for me. Can't stop getting notifications for old mentions.

**Comment by tasmo** [comment]
Still getting to much notifications. Tried to use the keys from original [Twitter for Android](https://gist.github.com/mariotaku/5465786#twitter-for-android) and still get notified after every refresh.
Is there any possibility to mark everything read?

**Comment by mariotaku** [comment]
Still can't reproduce on current version. I'll release a new version soon, please see whether it works.

**Comment by tasmo** [comment]
The more mysterious part is, I had to setup my accounts again in Twidere. After a some time (weeks) the problem disappears.

**Comment by ralesk** [comment]
For me it comes back right away, when I freshly install Twidere and add multiple accounts.  I then sync, get notified for hundreds of replies (and a few DMs that Twidere still gets told are unread, but they aren't — it's always the same two DM threads), and then those notifications will come back pretty much every automatic refresh I guess... Especially if no new replies come in.

**Comment by jomo** [comment]
Just updated and it's still happening, unfortunately: ![screenshot](https://i.imgur.com/lXKUMAq.png)

In this case I got *one* mention for the second account in the list.

It might be worth pointing out that I don't use Twitter via this app only, I also use the web app. So it's quite possible that I haven't read all these mentions in Twidere, but I have definitely read all of them except the most recent one.

**Comment by jomo** [comment]
Unfortunately, this is still (or again?) happening.
Old notifications from other accounts still pop up when a different account gets notifications. I've tried opening them to "mark them as read" for Twidere, but they still pop up.
