### ISSUE TITLE
Provide link to tweet in sharing text

### ISSUE THREAD

**Issue by dpoi1** [TwidereProject/Twidere-Android#176]
Can you provide a link to the tweet when shring it? Just append it to the body text or something...

This would make the app even more amazing :)

**Comment by mariotaku** [comment]
It already does when you click "share" icon in a tweet detail view.

**Comment by dpoi1** [comment]
Hm. I don't know the API for the share-feature. But in another twitter app, I can share as, say, SMS, and in the end of the body text, the link to the tweet is included. When sharing from twidere to SMS, there is no link included. So maybe the destination app does not use all shared information?
Which app would show you the link to the tweet when shared to it?

**Comment by mariotaku** [comment]
This should work now.
