### ISSUE TITLE
Crash when typing username or hashtag

### ISSUE THREAD

**Issue by Lertsenem** [TwidereProject/Twidere-Android#177]
My twidere (Fdroid, 0.3.0-dev-114 version) crashes every time I try to type a hashtag or a username. I type the # or @ char, on letter and then it freezes and crashes.

I would guess it's trying to load suggestions for the hashtag/username but something goes wrong.

**Comment by callmemagnus** [comment]
I can confirm that issue with that same version.

**Comment by Natureshadow** [comment]
Confirmed.

**Comment by mariotaku** [comment]
fixed in recent commits.

**Comment by callmemagnus** [comment]
Updated and issue is gone
