### ISSUE TITLE
Crash when adding a list tab

### ISSUE THREAD

**Issue by 0liUms** [TwidereProject/Twidere-Android#178]
Since I upgrade to the latest fdroid version ( 5min earlier it was working ) I can't add user's list tab : I type two lettres and ... it crash, without showing suggestions ( https://github.com/TwidereProject/Twidere-Android/issues/177 ? )

I use it on Android 5 on a Samsung galaxy s2 ( not very stable ... )

**Comment by borekb** [comment]
Same issue here, but only after changing phones. On the old one, I had a list tab added just fine.

**Comment by benediktg** [comment]
I think this issue is obsolete because there is no possibility to add a lists tab anymore. If I don't lie this functionality is now moved to the sidebar menu and I do not notice any crashes there right now (with latest snapshot release 160210).
