### ISSUE TITLE
Retweeting from multiple accounts that follow the same user

### ISSUE THREAD

**Issue by rwhillrunner** [TwidereProject/Twidere-Android#179]
I previously posted an issue with retweeting from multiple accounts but I wasn't able to recreate it. Now I have recreated it and I think I know what's going on.

If I'm following a user with more than one account and I retweet one of that user's tweets from one of my accounts, it shows that I retweeted it from both accounts and I can not retweet from the other account.

For example, there is a very knowledgeable individual within my field who I follow from both my personal and business accounts. He tweeted a link I found very interesting so I wanted to retweet it from both my personal and business accounts. When I retweeted from my personal account, it then showed that I retweeted from both accounts and I was unable to retweet from my business account.

**Comment by ThePreviousOne** [comment]
Im having a similar issue. could you post a logcat so I (or someone else) can look into this, please

**Comment by mariotaku** [comment]
Now it is possible to retweet with different accounts by long clicking retweet icon.
