### ISSUE TITLE
Crash when switching account to post tweet to

### ISSUE THREAD

**Issue by smalltock** [TwidereProject/Twidere-Android#180]
Device: T-Mobile Galaxy S5
Android Distro: CM12.1
App Version: 0.3.0-dev-114 from F-Droid

I have three accounts registered on the app.
I start to write a tweet.
I want to post it under another account.
I press the account icon, expecting a dialog that allows me to switch accounts.
Twidere crashes. `"Twidere" s'est arrête.`

**Comment by mariotaku** [comment]
dup to #177

**Comment by smalltock** [comment]
this isn't the same issue. I'm trying to change which account I'm posting from, not do a @mention
