### ISSUE TITLE
Crash when changing accounts in composing page

### ISSUE THREAD

**Issue by zhaidoudou123** [TwidereProject/Twidere-Android#181]
I have two accounts, and if I change accounts when composing a new tweet, twidere crashes.
By the way, when I select a tweeted picture and choose 'share', it crashes too.

**Comment by mariotaku** [comment]
dup to #177 #180 .

**Comment by smalltock** [comment]
@mariotaku #177 and #180 aren't the same issue

you closed mine as duplication of #177, but it isn't a dupe

**Comment by mariotaku** [comment]
@smalltock it's technically the same and fixed in 0.3.0-dev150626 and newer.
