### ISSUE TITLE
Crash on clicking the "attach picture" button for DMs 

### ISSUE THREAD

**Issue by pseudomonas** [TwidereProject/Twidere-Android#188]
Twidere crashes on clicking the "attach picture" button when creating a new DM in replying to a thread. Happens every time. Doesn't get as far as any "choose picture" dialog box.

0.3.0-dev-115 / F-Droid build / CM11

**Comment by deuxpi** [comment]
Error is roughly:

**Comment by deuxpi** [comment]
This is fixed by updating the dependency to PickNCrop:44b09cbc69 by the way.
