### ISSUE TITLE
Feature Request - Split tweet

### ISSUE THREAD

**Issue by ghost** [TwidereProject/Twidere-Android#190]
This is a bit silly

When writing longer tweets, the option already exists to use the twitlonger add-on, but another solution is to break the contents into multiple tweets. It'd be convenient for the app to do that automagically.

**Comment by Sohalt** [comment]
Yep. Would be greatly appreciated. A small bonus would be if you could select how they are split and enumerated. Ie (1/3) (2/3) (3/3) or with either … or cont. at the end of incomplete tweets

**Comment by daks** [comment]
+1

**Comment by orithena** [comment]
I've had the same idea. This would help users in languages that use a latin alphabet... like german.

To be really useful, this feature would require a "tweet sending queue" where each subsequent tweet waits for the predecessor to be successfully sent and then includes it's tweet-ID as answer reference. This pseudo code (syntax borrowed from jQuery) hopefully helps to understand what I mean:

    tweet(tweetchain[current]).onSuccess( function(successful_tweet) {
      tweet_answer(tweetchain[next], successful_tweet.tweetid);
    });

Then, the best (but most complex to code) option would be to change the "compose tweet" dialog in the following way:

  * Whenever a tweet exceeds the 140 character limit, it is split up in two input widgets, displayed one after another in a scrollable container.
  * Splitting occurs at certain points:
    * Preferably at a double line break (if existent)
    * Then at single line breaks
    * Then at "full stop, quote character, space"
    * Then at "full stop, space"
    * Then at "comma, space" 
    * Then at "space"
  * Each tweet in the chain is then optionally ended by " … [x/n]", where x is the current tweet number in the chain and n the total number of tweets in the chain and "…" is U+2026.
  * Each subsequent tweet in the chain is optionally started by "…" (U+2026)
  * This would reduce the maximum length of each tweet in the chain to 128 characters + the "helper characters" from this list, assuming that a chain can not have more than 99 tweets.

A really simple option would be to extend the "tweet sent" toast to include a button "Immediately answer to this tweet I just sent", opening a standard "answer to tweet" dialog (as seen in Firefox mobile when opening a link from another app). This would make the whole process outlined above manual... you'd have to write the first tweet, wait for the toast that says "tweet sent", tap on it, getting the "answer to tweet" dialog, writing the next tweet and so on... (current workflow for that: send first tweet, wait for it to be successfully sent, go to user tab, refresh it, wait for it to be refreshed, answer to own tweet, delete own twitter handle from the answer (see #257), write answer, repeat. This is really tedious when you're on a german mobile data contract that is throttled to GPRS speed...)

This feature would be really appreciated by my german followers; I was a bit surprised by the number of favs/RTs requesting such a feature: https://twitter.com/anathem/status/669998807648755712 :)

**Comment by Sohalt** [comment]
@orithena you basically summed it up perfectly. The current workflow is really tedious. Really would love this feature.

**Comment by mariotaku** [comment]
Nice, I'll consider adding this.

**Comment by orithena** [comment]
Thanks @mariotaku! \o/

Reading again, I found some edge cases to consider (in the complex option):

  * some people might like setting manual splitting points (could be considered done if users knew that they only need to enter a double linebreak)
  * sometimes, one might want to edit something in one of the first tweets of the chain. In this case, the whole chain would need to be joined and re-splitted again.
  * sometimes, one might want to send a tweet chain as answer with mention. Here, the @-mentions would need to be prepended to each tweet in the chain, further limiting the character limit per tweet.

**Comment by smalltock** [comment]
You could just highlight the different segments in alternating colors. Yellow and pink, for instance. The segments could have draggable endpoints for manual delineation.

**Comment by smalltock** [comment]
Didn't mean to close

**Comment by orithena** [comment]
With draggable endpoints, one would need to create/derive a new UI widget, I'm afraid. More complex/tedious to code.

I just dug through the twitter API docs and found some thoughts about rate limiting:
  * There does not seem to be a way to check in advance how many tweets can be sent in the next 15 minutes without getting back a rate limit error. GET application/rate_limit_status does not seem to cover POST statuses/update (https://dev.twitter.com/rest/reference/get/application/rate_limit_status)
  * There does not seem to be a fixed rate limit for POST statuses/update: https://dev.twitter.com/rest/public/rate-limits
  * All I can find is "2400 tweets per day, but sublimits exist" (https://support.twitter.com/articles/355430). This article can be seen as a hint that status updates are limited to 50 tweets per 30 minute sliding window. On the other hand, the rate limiting docs talk about 15 minute sliding windows, so we're down to 25 tweets in a burst (=immediately sending the next tweet when the server replies with "success").
  * Taking into account that the user needs some time to write a tweet chain (and therefore did not send a tweet in the last 15 minutes or so), I think it's safe to assume that tweet chains up to 25 tweets could be sent in a burst, while longer tweet chains should wait at least 45 seconds between each tweet request. Simple solution to that: limit tweet chains to 25 tweets. Sounds good enough :)
  * Taking the HTTP response headers "X-Rate-Limit-*" into account to throttle the tweeting rate might be a good idea, but my experience with them did not yield any usable result yet (might also be the fault of the library I'm using or me using that library wrong). -> https://dev.twitter.com/rest/public/rate-limiting

**Comment by solstafir7** [comment]
Is anyone working on this?

**Comment by smalltock** [comment]
As far as editing earlier parts of a post go, I have an idea.

Suppose we had a "split" toggle button, which would run the split algorithm and break up the message into 140-character parts.  To unsplit it, just toggle it off.  All the strings will be concatenated back into one big message.  Ideally, one wouldn't split the message until they're finished writing it and about to send.

Draggable endpoints aren't necessary.  @orithena had a good idea earlier, that users could simply ***know*** that double-line-breaks are the highest priority.

I would also add that as a lowest priority, we should also allow splitting the tweet between characters, if none of the other criteria are met.

I don't think @ mentions will be an issue, since in my experience, the only post whose character limit is affected by @ mentions is the first in the series.  Replies don't seem to be affected.

Here's where it gets tough.

- What to do with tweets that have attachments?  Should we just assume that it should be attached to the first or last tweet in the sequence?
- What about tweets that are being sent to multiple accounts, one on GNU Social or Mastodon, the other on Twitter?  The character limits are wildly different on all of these platforms.

**Comment by orithena** [comment]
@smalltock: My post stems from before Twitter changed its rules about counting @-mentions. You're right, it's not that much of an issue anymore.

Also, with multiposting to accounts with different character limits, your idea has got more merit. Probably it could be solved by some buttons named "preview split text for account X"?

**Comment by mariotaku** [comment]
Move to #51. We can make twitter-style thread feature.
