### ISSUE TITLE
Feature request: timeline scroll via volume buttons

### ISSUE THREAD

**Issue by chastell** [TwidereProject/Twidere-Android#192]
A few other Twitter clients (Plume, Tweet Lanes, Twicca) have the option to scroll the timeline using the volume buttons (volume up: scroll one tweet up, volume down: scroll one tweet down). It would be super cool to have this feature in Twidere – once you try it you get used to it _very much_. :)

**Comment by raumzeit77** [comment]
Also it would be great if you could bring back the quick-scrolling option from older versions. It takes al whole lot of scrolling to reach the top of the timeline when you follow a lot of people

**Comment by mariotaku** [comment]
added in 641a61cb659eabbaf607e45d76e7c034e0abfb98.
However I suggest you not enable this feature, cause I broke one of my phones' volume key before.

@raumzeit77 You can navigate to top quickly with double tap to a tab.

**Comment by chastell** [comment]
Thanks, much appreciated!
