### ISSUE TITLE
当一条推文同时附带图片和引用推文网址时，无法点击附带的图片。

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#200]
版本：
0.3.0 (dev 2015-07-06)

现象：
当一条推文中同时附带引用的推文网址，以及图片时，无法单击图片网址查看图片，会变成选择文字。

测试地址：
https://twitter.com/chenshaoju/status/634012674347536384

截图：
![screenshot_2015-08-20-14-55-24](https://cloud.githubusercontent.com/assets/515763/9377495/2456c5ea-474c-11e5-9520-52a3f98e7c8f.png)

**Comment by mariotaku** [comment]
fixed in 63eb236c54ea14d9b746996b39e9cb9f84977d75.
