### ISSUE TITLE
Switching off automatic bug report

### ISSUE THREAD

**Issue by pmaziere** [TwidereProject/Twidere-Android#201]
Thanks to Xprivacy, I became aware of a  twidere attempt to connect to some cloudant.com account.
By looking at your code, I discovered that it was supposed to be an automatic bug report (commit d247f1921ed1081c3d7cb91974c1160866d12d6e).
I did look into the preferences, but obviously not well enough to find how to disable these automatic bug reports.

Could you point out the relevant place in the preferences in order to disable this "feature" ?

If no such switch exists, could you implement it ? 
Such an automatic bug report without any user approval should be considered as a privacy issue.

Thanks

**Comment by mariotaku** [comment]
added in f2fe2c7a5dad8f58f1a51d5c8f3679372b993020.

**Comment by pmaziere** [comment]
thanks !
