### ISSUE TITLE
Cannot remove user from list

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#202]
Can add people to lists but cannot remove them, as far as I can see.

**Comment by benediktg** [comment]
In my opinion this issue is not relevant anymore because I could successfully create a list, add a user (my own account), delete this user and delete the list right now. (with Twidere v3.1.3 from F-Droid).

**Comment by mariotaku** [comment]
I'm closing this issue because it should be fixed now.

**Comment by akorobov** [comment]
@mariotaku, I don't see a way to do this in 3.1.3.3 ui. How to remove user(s) from lists? Could you point to commit that implemented this? Thanks.

**Comment by mariotaku** [comment]
@akorobov https://github.com/TwidereProject/Twidere-Android/commit/c9e241d7d3a684cc08c477e868241534e253eccb Long click to open context menu

**Comment by yamatt** [comment]
@mariotaku can you please explain what to long click on?

**Comment by benediktg** [comment]
Navigate to the page where all the members of the list are enumerated:
Swipe from the left edge to the middle → "Lists" → tap on a list → go to the tab in the middle ("members") → long press on one member → then you can choose to delete the selected member.

**Comment by yamatt** [comment]
@benediktg got it! Thanks!

**Comment by borekb** [comment]
Is there a way to do this from a user screen? There's the "add to list" action but not the opposite one. 

Use case: I'm reading a list and one user is annoying in it. I tap his avatar and would expect to manage his presence in the list from there.

**Comment by borekb** [comment]
BTW long press does nothing in 3.2.4 when I follow your steps, @benediktg.

**Comment by yamatt** [comment]
Yes, I had noticed this too. It seems to be a regression. I'll open another ticket.
