### ISSUE TITLE
Emoji can be added to tweet via copy paste, can we have it on keyboard?

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#203]
![screenshot_2015-08-22-16-39-11](https://cloud.githubusercontent.com/assets/618054/9424687/108fe40e-48ed-11e5-978e-78e64f5a23b5.png)

I managed to copy+paste emoji from Hangout to Twidere, all that is missing in Twidere is the keyboard option.

**Comment by mkody** [comment]
Long-press the enter button to show emojis.

**Comment by yamatt** [comment]
@mkody no way! Did not know that. Thanks.
