### ISSUE TITLE
Feed sometimes jumps to top

### ISSUE THREAD

**Issue by Xiyng** [TwidereProject/Twidere-Android#204]
As the title says, the feed sometimes jumps to the top. Sometimes it happens when I rotate the screen, but not always. And sometimes it happens quite randomly, but I *think* it happens when I tilt the screen slightly in a certain manner. Needless to say, this is confusing and irritating, as it's not something I intend to do, and it makes me lose the position I was at.

**Comment by mariotaku** [comment]
This should work now.
