### ISSUE TITLE
Automatically "Load more" in between older and newer content

### ISSUE THREAD

**Issue by borekb** [TwidereProject/Twidere-Android#205]
UX suggestion: when I have a timeline (usually a list in my case) and I have read it a couple of hours ago and then refresh, there is like these two parts of the list:

    +-----------------+
    |                 |
    |                 |
    |   (new stuff)   |
    |                 |
    |                 |
    |                 |
    +-----------------+
    |    Load More    |
    +-----------------+
    |                 |
    |                 |
    |                 |
    |  (older stuff)  |
    |                 |
    |                 |
    |                 |
    +-----------------+

When I scroll down to the *Load more* button, I need to manually press it. If I miss it (during quick scrolling) I can be confused because from the new stuff I am suddenly in the older stuff, possibly missing some tweets in between.

It would be nice if the auto-loading worked automatically, like it does when there is no older stuff. Good enough workaround for me would be to completely refresh the timeline, i.e. remove the old stuff altogether and just start fresh but I don't think that's possible using the current UI, is it?

**Comment by pqrth** [comment]
Thanks @mariotaku for this wonderful app.

Now, I agree with @borekb that it'll be a better user experience if Twidere could automatically _Load more_. This will also solve #1104.
