### ISSUE TITLE
Application Crashing Switching to List Timeline Tabs

### ISSUE THREAD

**Issue by morinap** [TwidereProject/Twidere-Android#206]
After today's update, the application is crashing when trying to view my tabs containing list timelines. I tried removing all tabs and readding and that did not solve the issue.

**Twidere Version**: 0.3.0 (dev 2015-09-01)
**Android Version**: 5.1
**Device**: Moto X 2014 (Verizon XT0196)

**Comment by edent** [comment]
Also crashing on "Activities About Me" tab.

**Comment by morinap** [comment]
I received an update today (0.3.0 dev 2015-09-02) that appears to have fixed the issue.

**Comment by yamatt** [comment]
Just making note for others who may end up here it is still affecting the current release from the Play Store.

**Twidere Version**: 0.3.0 (dev 2015-10-24)
