### ISSUE TITLE
Direct Messages keep getting marked as unread

### ISSUE THREAD

**Issue by Don42** [TwidereProject/Twidere-Android#207]
Not sure what exactly is happening, but when I get a new direct message, the notification also often shows older messages as being unread. Even though I already read their whole conversation.

Using version 0.3.0 (dev 2015-09-01) on a Galaxy Nexus with Android 4.3,
but the problem existed a while.

**Comment by ralesk** [comment]
I'm getting the same but also for mentions.  A new mention comes in, I'll get notified about already read mentions for even another account.
