### ISSUE TITLE
Direct messages not shown since the 2015-06-29 release

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#208]
I can only ever see my own sent DMs, not any of the received ones, and after clearing database I can see nothing (until I send a DM again).

**Comment by ralesk** [comment]
Still an issue in 2015-09-03 release.

**Comment by GranPC** [comment]
Not seeing this issue in the latest release. What API tokens are you using?

**Comment by ralesk** [comment]
I created my own because otherwise I couldn't sign in after I reinstalled my phone a couple months ago.

**Comment by GranPC** [comment]
Hmm. Does it work if you borrow one of these? https://gist.github.com/mariotaku/5465786

**Comment by ralesk** [comment]
Oh. I had to change the access of my token to "read, write and access direct messages".  Sad thing: no error message was presented to me about this.

**Comment by ralesk** [comment]
Great, now I get network error all the time :(

**Comment by GranPC** [comment]
Can you try deleting your account and re-adding it?

**Comment by ralesk** [comment]
That's what i'm doing, not even the web login loads anymore.

**Comment by ralesk** [comment]
Really bad error reporting again:
 I use correct password = network error
 I use bad password = bad password error.

**Comment by ralesk** [comment]
Reinstalling Twidere fixed the network error. wtf...

**Comment by GranPC** [comment]
I guess you have to clear data when you change token permissions or something. The Twitter API is finicky.

**Comment by fphillips** [comment]
Sounds like this can be closed.

**Comment by ralesk** [comment]
Yes, sorry, forgot to.
