### ISSUE TITLE
Back-button stops working after using menu-button

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#211]
Version: 0.3.0 (dev 2015-09-03)

After opening the side menu using the phone's menu button, I cannot close the menu or exit the app with the phone's back button anymore. This does not happen, when I open the menu using the touch display (slide from left). Also, I still can use the back button to close for example, the tweet detail view or the options screen. It is exiting the menu or the app, what doesn't work anymore.

**Comment by mariotaku** [comment]
fixed in 6f3d7af4c082e647975aff4f89da75e26846bf86.

**Comment by JanvierUK** [comment]
I've updated but this bug is still occurring.

**Comment by hebu** [comment]
This bug is back in version dev 2015-10-19 :(
