### ISSUE TITLE
Image in commented retweet does not open

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#212]
When tapping the preview image of an commented retweet (aka. embedded tweet), the image does not open anymore.
When I open the detail view of the tweet (the comment), there is no preview image at all, just the pic.twitter.com link.
When I tap the pic.twitter.com link, the link does not open. It just gets selected and the text-selection header is shown (also looks a bit out of place).
When I tap the original tweet's link (the commented tweet), there is a preview image and I finally can tap it to see the full screen view.

**Comment by mariotaku** [comment]
This should be fixed in recent versions.

**Comment by fphillips** [comment]
All the above works. Tested with 0.3.0-dev-2015-09-20.
