### ISSUE TITLE
Error 401 with sending tweets, sending direct messages, favoriting or unfavoriting tweets

### ISSUE THREAD

**Issue by zfz** [TwidereProject/Twidere-Android#213]
Installed the new newest version(0.3.0) from Google Play on YQ601('坚果手机', Smartisan OS 1.5.3 based on Android 4.4.4, Kernel version 3.10.28-g68b87cd)。

Use my own twitter app key via oauth. Both updating new tweets and mention work fine. However, the following functions cannot work:
1) send tweets,
2) send direct messages,
3) favorite or unfavorite tweests,
4) show(and receive) direct messages

1), 2) and 3) return with a error 401.

Any help? Thanks.

**Comment by mariotaku** [comment]
I guess you forgot to set your application's permission to Read, Write and Direct Messages:
![image](https://cloud.githubusercontent.com/assets/830358/9979142/132d3aa2-5f8d-11e5-8681-0ba22d529913.png)
Then you need to sign in again.

**Comment by zfz** [comment]
@mariotaku Thanks. It solves my promblems.
