### ISSUE TITLE
How to open the settings?!?

### ISSUE THREAD

**Issue by reagle** [TwidereProject/Twidere-Android#215]
After the initial setup, I can't figure out how to open the settings. I have top tabs for: Home, Mentions, Trends, and Messages. There's a pen/tweet icon on the bottom. But I have no idea how to open the settings.

**Comment by mkody** [comment]
Slide from the left edge of your screen to the center. A drawer should appear with "Settings" and more in it.

![device-2015-09-18-190352 mp4](https://cloud.githubusercontent.com/assets/843787/9966062/c6eae61a-5e3a-11e5-81de-f90681deede1.gif)

**Comment by reagle** [comment]
Thanks, will try this. You might want to document this; I saw people complaining about it in the Play store too.

**Comment by mariotaku** [comment]
It's indeed a pain, I'm still figuring how to make content slide also work for this drawer.

**Comment by lucastx** [comment]
Just to say that I also didn't have the slight idea how to do this. Tried sliding many times to no avail (it has to be from the very very edge), struggled to find this page with google-fu.

**Comment by dequally** [comment]
Just started using the app, and it seems good. Though I have kinda the same problem, but I can't access it because it use the swipe to navigate around in app's and on phone, so edge swipe is equal to back. I would love if it was visible by default, but you could turn it if.
Sorry for opening again.

**Comment by mkody** [comment]
@dequally It shouldn't go back, but if it does for some reason you might need to hold your press for a second before starting to swipe to the right to prevent that.
I'd recommend to enable the drawer toggle if it's a pain to you.


![twidere-slide](https://user-images.githubusercontent.com/843787/107888577-844f9c80-6f0d-11eb-8b69-d846be036526.gif)

**Comment by dequally** [comment]
Thanks, sorry I did not see that.
Hope you are having a good day, and doing good in the pandemic.
