### ISSUE TITLE
API rate limit alert?

### ISSUE THREAD

**Issue by greendyj** [TwidereProject/Twidere-Android#216]
Currently when the API request is used up in any 15 minute window, there is no way to tell the difference between this and a network disconnection (without leaving twidere). 

It would be useful to see the API requests remaining in a window and an alert when reaching API limit. ps: It would be much better to fix the streaming extension.

**Comment by wynnsyt** [comment]
There is certainly a "rate limit exceeded" warning in Twidere already. The question is whether it's bugged out.

IMO the rate limit is hard to hit for general users and a count of remaining requests might add to the UI clutter (none of the big clients shows it AFAIK). However, I do agree that diverting people towarding streaming solves so many problems.
