### ISSUE TITLE
media tab users profile

### ISSUE THREAD

**Issue by ilvinc3nt** [TwidereProject/Twidere-Android#220]
Is there any way to add (or setup in settings) media tab in profile? (i mean pics, vids posted by users in each profile)

**Comment by edent** [comment]
It isn't specifically exposed in the API, so might be difficult to recreate.

**Comment by mariotaku** [comment]
Try login with [these keys](https://gist.github.com/mariotaku/5465786), media timeline will be available.

**Comment by LeonTheOriginal** [comment]
Referring to the initial question: There is a Media tab (between Tweets and Likes) on the profile pages, but it shows only one or sometimes a few tweets containing images. Is this issue a bug in Twidere or a restriction of the API?

**Comment by LeonTheOriginal** [comment]
Referring to the initial question: There is a Media tab (between Tweets and Likes) on the profile pages, but it shows only one or sometimes a few tweets containing images. Is this issue a bug in Twidere or a restriction of the API?

**Comment by LeonTheOriginal** [comment]
Referring to the initial question: There is a Media tab (between Tweets and Likes) on the profile pages, but it shows only one or sometimes a few tweets containing images. Is this issue a bug in Twidere or a restriction of the API?

**Comment by mariotaku** [comment]
@LeonTheOriginal Twitter doesn't have media timeline API exposed to third party apps, so Twidere uses search API and filter results, which has some restrictions.

**Comment by bigretromike** [comment]
@mariotaku thanks for info ! This is only one things that started to bother me after switching to Twidere; if so then maybe we could have a switch that would query that one special person to query all (most) tweets and filter out media and ad them in cache. I know about limits etc, but that would be a slow workaround the problem. and after initial `scan` it would be super easy to check for new media

**Comment by orithena** [comment]
@bigretromike Just use the official keys to login to Twitter, then you'll be able to see the whole media timeline: https://gist.github.com/mariotaku/5465786

**Comment by bigretromike** [comment]
I did. BUT how do i logout ? because i switch the switch on accounts. changed keys and switch back.
