### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by JanvierUK** [TwidereProject/Twidere-Android#223]
Twidere is acting oddly. It stops loading tweets and cannot send any either. A message says "Error while sending tweet: network error". I cannot work out what the problem is - my connection is fine, other apps can connect to the internet, Twitter is accessible via twitter.com. Can anyone help?

**Comment by JanvierUK** [comment]
A related feature request would be that when/if the server is down or there's no network connection, tweets are automatically sent once the service resumes.

**Comment by gena01** [comment]
Actually I saw this a few times, sorta got a bit worse with the latest build. One workaround is to go into Android/phone "Settings" -> Apps -> Twidere and then "Force stop" the app and start it up again.
