### ISSUE TITLE
Streaming extension doesn't work anymore

### ISSUE THREAD

**Issue by kathakatze** [TwidereProject/Twidere-Android#228]
After updating to 0.3.0, the streaming extension still does not seem to work as it did before with 0.2.9.
Any new tweets don't show up until manually refreshing in Twidere and logcat shows error messages about missing columns. Manually adding these to the database seemed to work, but there are quite a lot of missing ones. I've seen these before giving up:
- descendent_reply_count in tables statuses and mentions
- mentions_list in table statuses
- media_list in table statuses

Log: http://pastebin.com/EJ51vC7G

Twidere 0.3.0 (dev 2015-10-19)
Twidere Streaming Extension 1.12 (0.3.0-dev)

**Comment by benediktg** [comment]
Is the issue still occuring with the most recent version of Twidere?

**Comment by mariotaku** [comment]
Twidere moved streaming into app but disabled it for now because it's not
yet complete.

Benedikt Geißler <notifications@github.com>于2016年4月3日周日 08:47写道：

**Comment by weaselhawk** [comment]
extensions are completely broken not a single one works and it only see's the is twitlonger and that is broken too

**Comment by mariotaku** [comment]
merging to #81, will add streaming in future releases.
