### ISSUE TITLE
无法移除自定义主机映射

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#230]
系统版本：Android 5.1.1
Twidere版本：0.3.0 (dev 2015-10-24)

现象：无法移除自定义主机映射

复现步骤：
启动Twidere，进入设定->网络->高级->自定义主机映射，然后按住一个条目不松，待出现垃圾桶图标后松开，并点击垃圾桶图标。
结果：待删除的条目并没有被消除。

期望的结果：被删除的条目可以正确的被删除。

logcat：未能捕获到有效信息。

**Comment by teasick** [comment]
貌似自定义hosts功能也没法用了，网络错误
