### ISSUE TITLE
[Feature-request] Hashtags searchs including retweets

### ISSUE THREAD

**Issue by cjchacon** [TwidereProject/Twidere-Android#231]
If you search for a hashtag or click on it, all the retweets of a single tweet are shown, filling the tab with the same tweet. It would be nicer if it only shows
![screenshot_2015-10-29-16-16-33](https://cloud.githubusercontent.com/assets/2378321/10822883/442ecc70-7e59-11e5-85c7-48f72a526053.png)
 the original tweet.

**Comment by mariotaku** [comment]
added in 0669cfe1e5034894bc655f520140e475e0995982.

**Comment by cjchacon** [comment]
Thanks!
