### ISSUE TITLE
New design proposal

### ISSUE THREAD

**Issue by alexsmithfanning** [TwidereProject/Twidere-Android#235]
Would this be something that could be done? The current look is getting outdated and kinda old.

![twidere concept - homepage with tweet](https://cloud.githubusercontent.com/assets/12200557/10886913/f1330c86-8149-11e5-85e1-c4c3d70a6b0b.png)

It redesigns the cards, adds labeled tabs and a dedicated search button.

**Comment by ThePreviousOne** [comment]
So Material UI

**Comment by mariotaku** [comment]
Twidere will keep current design to build minimalistic.
