### ISSUE TITLE
Favourites are now Hearts

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#237]
As per this announcement: https://blog.twitter.com/2015/hearts-on-twitter

The ☆ should be replaced with ♡.

**Comment by blinry** [comment]
And s/favorite/like/g

**Comment by edent** [comment]
https://blog.twitter.com/2015/hearts-for-developers

**Comment by orithena** [comment]
I propose to ignore that change and keep Twideres starry look.

**Comment by Don42** [comment]
I agree with @orithena. Although I would understand that consistency is important.
How much work would a setting be?

**Comment by mariotaku** [comment]
changed in 3417fc68d4da3ed6c1e0dff5798dcaf252f0ba8b.
