### ISSUE TITLE
Add option to disable refresh service

### ISSUE THREAD

**Issue by cygairko** [TwidereProject/Twidere-Android#240]
I did not find an option to completely disable the refresh service running in the background. Is there a reason, why refresh interval cannot the set to "never"?

For me it is enough to update the timeline, when starting the app (it even can be done automatically), but that's just my two cents.

**Comment by mariotaku** [comment]
You can turn all accounts for refreshing off:
![image](https://cloud.githubusercontent.com/assets/830358/12826938/6486f9dc-cbb8-11e5-871d-6994211f0ab0.png)

Then refresh service will be disabled.
