### ISSUE TITLE
Keyboard Autocorrect Disabled on Compose

### ISSUE THREAD

**Issue by morinap** [TwidereProject/Twidere-Android#241]
Since update to 0.3.0 (dev 2015-11-19), opening a compose box brings up the keyboard with autocorrect disabled.

**Twidere Version**: 0.3.0 (dev 2015-11-19)
**OS Version**: 5.1
**Device**: Moto X (2nd Generation)

**Comment by mariotaku** [comment]
Fixed in 75c21cdf51f37270e4a4814b0eec19441eeeda09.
