### ISSUE TITLE
Mentions & hastags not working with version 0.3.0 - (dev 2015-11-20)

### ISSUE THREAD

**Issue by jbfavre** [TwidereProject/Twidere-Android#243]
Since last update, mentions and hashtag completion does not work anymore.

1. __Mentions__: search works but when choosing one, `@` disappear leading to no mentions
2. __Hashtag__: search works, but when choosing one, it displays `null`

__Twidere Version__: 0.3.0 (dev 2015-11-19)
__OS Version__: 6.0 (security fix 2015-11-1)
__Device__: Google Nexus 5

**Comment by mariotaku** [comment]
fixed in 75c21cdf51f37270e4a4814b0eec19441eeeda09
