### ISSUE TITLE
A graphic issue

### ISSUE THREAD

**Issue by bungabunga** [TwidereProject/Twidere-Android#245]
For some last versions of Twidere I sometimes get graphic issues as seen on attached picture when I open a tweet that retweets&comments another tweet. It's not always, only about 10% of times.

Sony Xperia Z3c, Android 5.1

![tmp_3460-screenshot_2015-11-22-15-43-431745022446](https://cloud.githubusercontent.com/assets/2994878/11332513/9112f748-91c6-11e5-85cf-4795c75e1966.png)

**Comment by orithena** [comment]
Can confirm on Nexus 5/Android 5.1.1.

Comes up more often when opening that view for the first time after not using Twidere for some hours.

**Comment by KonomiKitten** [comment]
I've actually seen the official android app do this as well oddly.

**Comment by mariotaku** [comment]
This should get fixed in recent versions.
