### ISSUE TITLE
Error "Perhaps you already saved this search"

### ISSUE THREAD

**Issue by haary** [TwidereProject/Twidere-Android#247]
A few days ago I reported issue #244 . This was closed very quickly, thank you. But I still can't save searches.  Now I get the error message "Perhaps you already saved this search" (of course I didn't).
Using now 0.3.0-dev-135 from F-Droid. I get the error on all my Android devices.

**Comment by mariotaku** [comment]
Could you provide your search query? I'll try to reproduce.

**Comment by haary** [comment]
It happens with any arbitrary search query, like "#esc2016" (without the quotes).

Creating a tab with pre-defined search queries works.

**Comment by mariotaku** [comment]
Hi @haary, you could try https://github.com/TwidereProject/Twidere-Android/releases/tag/0.3.0-dev151214 to see whether it works.

**Comment by haary** [comment]
I tried the f-droid version, uninstalled the last version and installed 0.3.0-dev151214 twidere-fdroid-release.apk.

Same result for saving searches as before:  "Perhaps you already saved this search". But one thing changed: The list with searches I entered and saved about half a year ago re-appeared again, after they were gone/missing in the last versions. But it seems that I still can't save new search terms.

Wild guess: Is the database with saved search terms preserved even after an uninstall? After uninstall and install again I have to enter my settings from the start (Account, Pass, Tabs) but it seems that old searches are still there.  Maybe this database is corrupt and deleting it would help? Where would I find it?

**Comment by mariotaku** [comment]
Is this still happen?

**Comment by haary** [comment]
Latest Version at f-droid is 0.3.0-dev-135 and with this it is still happening, same with 0.3.0-dev151214, see my remarks above. Is there another version I should try?

**Comment by mariotaku** [comment]
there're newer versions like dev160131

**Comment by haary** [comment]
Tried dev160131, same result

![screenshot_2016-02-05-14-49-06](https://cloud.githubusercontent.com/assets/4052999/12848509/b210de7c-cc1a-11e5-989e-b9e590ee7b9d.png)

**Comment by mariotaku** [comment]
I followed your search query and tried to save, it works. Have you set custom API?

**Comment by haary** [comment]
No, I didn't
