### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by whitequark** [TwidereProject/Twidere-Android#248]
The following UI elements don't follow the dark theme when it is selected:
 - [ ] The toast notification brought by the "i" button on "API URL format" in "Default API settings"
 - [ ] The context hint that appears if you long-press an action bar button
 - [x] The name of the tab in the dialog that pops up when you add or edit a tab

Version 0.3.0-dev-130 from F-Droid.

**Comment by mariotaku** [comment]
Hi, could you show a screenshot to those toast? I can't find what went wrong.

**Comment by whitequark** [comment]
Example 1: I long-pressed the @ button
![screenshot_2015-11-25-09-16-32](https://cloud.githubusercontent.com/assets/54771/11385590/606b7b0c-9355-11e5-9f2c-4a14e7c13546.png)

Example 2: I pressed the (i) button
![screenshot_2015-11-25-09-18-05](https://cloud.githubusercontent.com/assets/54771/11385606/7c2fefc6-9355-11e5-8b23-a99261552a52.png)

**Comment by mariotaku** [comment]
I guess it's an issue related to your Xposed module (or somewhat) modding your toasts. Could you give me the address to that module?

**Comment by whitequark** [comment]
I do not have any kind of system-wide theming software installed over CyanogenMod as shipped. It's even set to the default theme.

**Comment by whitequark** [comment]
Note that this is how such a toast looks in an application with a bright color scheme:
![screenshot_2015-11-25-09-24-02](https://cloud.githubusercontent.com/assets/54771/11385702/4b6ef610-9356-11e5-8252-4ddcd3ef05a0.png)

So it looks like the background is inferred correctly, only text color isn't.

**Comment by mariotaku** [comment]
What should it be on a normal dark theme?

**Comment by whitequark** [comment]
Oh, sorry. I should have mentioned that the other toast notifications in Twidere itself look fine and proper, e.g. the favorite notification:
![screenshot_2015-11-25-20-46-23](https://cloud.githubusercontent.com/assets/54771/11397639/e7891616-93b5-11e5-94d1-1bf9f1ba0d80.png)

**Comment by mariotaku** [comment]
Is these problems still exist?

**Comment by whitequark** [comment]
All fixed, thanks!
