### ISSUE TITLE
Wishlist: Please add a Changelog/NEWS file

### ISSUE THREAD

**Issue by aelmahmoudy** [TwidereProject/Twidere-Android#25]
I hope that in that new project you would add a changelog or NEWS file that summarizes the changes between releases. Please note that not all users use Google Play to get Twidere.

Thanks.

**Comment by mariotaku** [comment]
I think commit log is good enough.

**Comment by aelmahmoudy** [comment]
Actually I was thinking of something that summarizes the changes between releases, something like what you put in Google Play's "What's New" section.
