### ISSUE TITLE
Incomplete structure?

### ISSUE THREAD

**Issue by amsomniac** [TwidereProject/Twidere-Android#252]
This is what I see when I log in (I'd paste the text, but it's not selectable)

Am I making a configuration error, or is this a bug?

![screenshot_2015-11-24-17-30-28](https://cloud.githubusercontent.com/assets/6526832/11383191/93229890-92d4-11e5-8a35-d922803e4a5a.png)

**Comment by mariotaku** [comment]
Are you using proxy or custom API server? Seems related to gzip compression.

**Comment by amsomniac** [comment]
Nope, made an API key with apps.twitter.com, no proxies. What's a good way to get more information about what's going on?

**Comment by amsomniac** [comment]
Okay, I switched to wifi and it worked fine. My guess is... something... something... weird APN configurations in mobile data?

Anyway, closing, thanks for a great mobile application!
