### ISSUE TITLE
Feature request: tapping on favorite/retweet activity card

### ISSUE THREAD

**Issue by whitequark** [TwidereProject/Twidere-Android#254]
It would be great if tapping on the card itself would bring up the conversation view for that tweet (so that I can look up context), and tapping on the avatar would bring up the user profile. That functionality is available in the web interface and I find myself using it a lot.

Tapping on the avatar would also be particularly useful for the follow activity card.

**Comment by mariotaku** [comment]
Fixed in recent commits, you will now be able to open who favorited/retweeted your tweet when clicking activity cards.
