### ISSUE TITLE
Replying to yourself should remove @you from the tweet

### ISSUE THREAD

**Issue by whitequark** [TwidereProject/Twidere-Android#257]
To make long conversations thread nicely, you can reply to someone and then keep replying to that tweet. This works well in e.g. the web interface: when you reply to your own reply, you get a text box with "@you <cursor>". However, Twidere makes this hard: it gives you a text box with "@you @otherperson ", where both @-names are highlighted. This makes removing unnecessary "@you" from the tweet quite hard.

I think Twidere's behavior should follow the web interface here.

**Comment by whitequark** [comment]
@mariotaku any chance this can be addressed? It's a simple fix but would vastly improve usability...

**Comment by mariotaku** [comment]
Now twidere will select your own username by default if replying to self.

**Comment by mariotaku** [comment]
![image](https://cloud.githubusercontent.com/assets/830358/14224463/14ebb5b2-f8d0-11e5-9769-ddbbbfb2710a.png)
