### ISSUE TITLE
[Feature Request] - Auto-detect account to tweet from based on active tab

### ISSUE THREAD

**Issue by dougwollison** [TwidereProject/Twidere-Android#258]
When composing a tweet, the account(s) to tweet from are preserved from the last time the window was opened. In the case of tabs that are for specific accounts, I think it would be incredibly convenient option to have where the account set to that of the current tab.

Also, I think it might be worth while to add an option to disable the ability to tweet from multiple accounts at any given time.

**Comment by ThePreviousOne** [comment]
I seem to be Experiencing this in the current Build, is it a bug? As I toggle-able feature It would be great but this 'Permanent' Crap I don't like
