### ISSUE TITLE
Hosts function failure in 0.3.0(dev 2015-11-22)

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#261]
Android系统版本：5.1.1
Twidere版本：0.3.0 (dev 2015-11-22)
现象：Hosts功能失效
复现步骤：
进入设定，网络，高级，自定义主机映射，指定域名映射到IP。然后进入时间线，点击没有头像的推文的头像位置，再点击用户详情页面的头像，显示载入中，然后提示域名和没有被映射的错误解析IP。

截图：
１.已经设定好的Hosts解析：
![screenshot_2015-12-02-10-32-52](https://cloud.githubusercontent.com/assets/515763/11520697/c2fba5cc-98e0-11e5-91ff-de35239e5b74.png)

２.无法获取头像的错误信息：
![screenshot_2015-12-02-10-32-38](https://cloud.githubusercontent.com/assets/515763/11520701/ccd5f160-98e0-11e5-8d78-ae52bc0d46d7.png)

**Comment by chenshaoju** [comment]
在删除所有条目后再重新添加即恢复正常。

此Issue已关闭。

**Comment by chenshaoju** [comment]
该问题仍然不时出现，没有办法摸清楚规律，这是Logcat：

[logcat.txt](https://github.com/TwidereProject/Twidere-Android/files/60942/logcat.txt)

**Comment by mariotaku** [comment]
原因大致是这样：在修改hosts entry之后，已经错误的缓存并没有被清除，所以失败。请尝试今天的snapshot

**Comment by qiyi** [comment]
还是无法工作, 尝试了多次删除条目,关闭程序,启动程序,添加条目,关闭程序,启动程序,设定api地址访问,都访问失败. hosts 没有生效地样子

**Comment by chenshaoju** [comment]
@qiyi 不要设置DNS地址。

**Comment by qiyi** [comment]
没有设置dns，还是不行

**Comment by chenshaoju** [comment]
@qiyi 有尝试重启应用吗？我看了一下我的，已经正常了。
有必要的话，请尝试卸载，然后安装最新版本，或者安装了最新版本以后清空数据重新配置：
https://github.com/TwidereProject/Twidere-Android/releases

**Comment by qiyi** [comment]
@chenshaoju  之前改一个配置都重启了一次应用. 下午也尝试重新安装了(卸载前清理了缓存数据),都没有效果. 版本已经是最新地 20160115 >_<

**Comment by chenshaoju** [comment]
@qiyi 我只能说我没有遇到过这个问题……你能看到我截图中类似的错误提示吗？

**Comment by qiyi** [comment]
@chenshaoju 不能... 只会直接提示网络错误. 另外如果额外设置代理地话,可以从代理上看到,仍然是直接请求原本地host.

不知道如何可以收集日志协助定位...

**Comment by chenshaoju** [comment]
我怀疑有一个地方可能跟你不一样。

我的Hosts用的只是 *.twimg.com 系列的域名，你是不是用的 *.twitter.com 的？

**Comment by qiyi** [comment]
@chenshaoju 我是一个twip api的地址，所以直接填写的域名api.xx.net，然后这个域名实际是没有dns解析的。

**Comment by chenshaoju** [comment]
你用的是Twip的O模式？

你登录的时候需要填写完整地址，并且在PC上可以通过Hosts访问到。如果Apapche或者你的服务器配置不正确，可能会不工作。

另外，建议取消“没有版本后缀，并且在你获得的Twip地址末尾加上 /1.1/ ，比如，你获得的地址是
https://abc.def,gh/twip/o/ijklmn
那么，你需要设置为：
https://abc.def,gh/twip/o/ijklmn/1.1/

**Comment by chenshaoju** [comment]
此问题可能在 0.3.0 (dev 2016-01-24) 中没有得到修复，刚才发现头像无法载入，然后logcat看了一下，仍然在使用一个错误的IP。

Logcat信息： [logcat.txt](https://github.com/TwidereProject/Twidere-Android/files/105254/logcat.txt)

**Comment by qiyi** [comment]
@chenshaoju  是使用地 twip o 模式. 前几天重新刷地 CM13,所以重新配置了一遍 twidere,之前同样地配置是OK 可用地.

**Comment by mariotaku** [comment]
fixed in recent versions.
