### ISSUE TITLE
[Feature request] In-app browser

### ISSUE THREAD

**Issue by thuo** [TwidereProject/Twidere-Android#263]

**Comment by mariotaku** [comment]
I won't integrate in-app browser feature, because in-app browser has different cookie/cache storage, which makes unnecessary network usages.

I would suggest [Link bubble](http://linkbubble.com/) instead, it's the best alternative for in-app browsers.

**Comment by orithena** [comment]
I also want to discourage an in-app browser (at least an obligatory one), because I want to continue reading Twitter while a webpage loads in the background ...

**Comment by thuo** [comment]
The use case I had in mind was to use the in-app browser to preview links and decide if I'll queue them (as a tab in external browser or Pocket) for reading later.

**Comment by maxfragg** [comment]
Though in lowend devices using a real Browser for every link really is not practicable

**Comment by mariotaku** [comment]
I'm closing this issue. If you need in-app browser alternative, just use link bubble, it's way better than any in-app browsers.
