### ISSUE TITLE
Notifications: what is the delay of notifications ?

### ISSUE THREAD

**Issue by warpdesign** [TwidereProject/Twidere-Android#264]
I just installed Twidere for Android and received a mention notification around 15/20min. Is there a way to change the delay of notifications ?

It doesn't look like instant.

**Comment by orithena** [comment]
Twidere does not use a push notification server (it's an open source project, and servers cost moneyz), therefore it has to poll every x minutes, which can be changed in the preferences. But shorter update periods mean more drain on the battery. You might consider using the streaming extension, but that could be an even bigger battery drain.

It's a standing issue to enable users to set up theur own push notification server for Twidere.

**Comment by theracermaster** [comment]
Is there a guide on how to set up a server for push notifications for Twidere?

**Comment by mariotaku** [comment]
Not possible yet. Twidere itself doesn't implement any kind of push notifications.
