### ISSUE TITLE
Confusion 

### ISSUE THREAD

**Issue by ThePreviousOne** [TwidereProject/Twidere-Android#267]
I think I am experiencing a few bugs in the lastest F-droid version of twidere (0.3.0-135) but I would like to confirm fiest, how is twidere supposed to handle multiple accounts

**Comment by ThePreviousOne** [comment]
What I mean is I am seeing some open issues like https://github.com/TwidereProject/Twidere-Android/issues/258 that I am sort-of experiencing already

**Comment by ThePreviousOne** [comment]
And when I pull down to refresh - it doesn't poll Automatically I have to wait untill the next scheduled one. This is likely wrong but that doesn't make it a bug

**Comment by pseudomonas** [comment]
There seems to be a reason (that I don't fully understand) that F-Droid doesn't want to take the most recent updates; I don't know whose end this is best solved by or if it's not in fact a problem. https://gitlab.com/fdroid/fdroiddata/issues/384

**Comment by ThePreviousOne** [comment]
wouldnt the solution to  https://gitlab.com/fdroid/fdroiddata/issues/384 bo bumping the version from .03.0-dev135 to say 0.3.0-dev135a or something

Also I forgot to mention my second post was pertaining to the current "at the time" nightly

**Comment by rugk** [comment]
I think this issue is old and can be closed.

**Comment by ThePreviousOne** [comment]
Actually I'm still wondering about multiple user handling. I stopped using the app as it was a real problem for me but if it has been changed I will start using it again.
