### ISSUE TITLE
Leak in SignInActivity

### ISSUE THREAD

**Issue by ThePreviousOne** [TwidereProject/Twidere-Android#268]
In org.mariotaku.twidere:0.3.0 (dev 2015-12-19 22:33):135.
* org.mariotaku.twidere.activity.support.SignInActivity has leaked:
* GC ROOT org.mariotaku.twidere.app.TwidereApplication.mApplicationModule
* references org.mariotaku.twidere.util.dagger.ApplicationModule.restHttpClient
* references org.mariotaku.restfu.okhttp.OkHttpRestClient.client
* references com.squareup.okhttp.OkHttpClient.networkInterceptors
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references org.mariotaku.twidere.util.OAuthPasswordAuthenticator$1.this$0 (anonymous class implements com.squareup.okhttp.Interceptor)
* references org.mariotaku.twidere.util.OAuthPasswordAuthenticator.loginVerificationCallback
* references org.mariotaku.twidere.activity.support.SignInActivity$SignInTask$InputLoginVerificationCallback.this$0
* references org.mariotaku.twidere.activity.support.SignInActivity$SignInTask.activity
* leaks org.mariotaku.twidere.activity.support.SignInActivity instance

* Reference Key: 93f31e94-7d47-4482-b966-2c89ae8e85a6
* Device: LGE google Nexus 5 hammerhead
* Android Version: 5.1.1 API: 22
* Durations: watch=5023ms, gc=193ms, heap dump=1956ms, analysis=20183ms

**Comment by ThePreviousOne** [comment]
I installed twidere/master from android studio and the debud tool gave me this. Also it crashes after sign in

**Comment by mariotaku** [comment]
Hi, could you provide crash log?

**Comment by ThePreviousOne** [comment]
It must have been that I was trying to use two different OAuth keys because I've taken care of that now and it works (also lost old keys so cant try to reproduce sorry). But I got another leak
SettingsWizardActivity$WizardPageFinishedFragment

**Comment by ThePreviousOne** [comment]
In org.mariotaku.twidere:0.3.0 (dev 2015-12-19 22:33):135.
* org.mariotaku.twidere.activity.support.SignInActivity has leaked:
* GC ROOT org.mariotaku.twidere.app.TwidereApplication.mApplicationModule
* references org.mariotaku.twidere.util.dagger.ApplicationModule.restHttpClient
* references org.mariotaku.restfu.okhttp.OkHttpRestClient.client
* references com.squareup.okhttp.OkHttpClient.networkInterceptors
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references org.mariotaku.twidere.util.OAuthPasswordAuthenticator$1.this$0 (anonymous class implements com.squareup.okhttp.Interceptor)
* references org.mariotaku.twidere.util.OAuthPasswordAuthenticator.loginVerificationCallback
* references org.mariotaku.twidere.activity.support.SignInActivity$SignInTask$InputLoginVerificationCallback.this$0
* references org.mariotaku.twidere.activity.support.SignInActivity$SignInTask.activity
* leaks org.mariotaku.twidere.activity.support.SignInActivity instance

* Reference Key: 93f31e94-7d47-4482-b966-2c89ae8e85a6
* Device: LGE google Nexus 5 hammerhead
* Android Version: 5.1.1 API: 22
* Durations: watch=5023ms, gc=193ms, heap dump=1956ms, analysis=20183ms

**Comment by ThePreviousOne** [comment]
There is no crash no but here is a log of the event (sorry its Verbose)

**Comment by mariotaku** [comment]
Those should be fixed. I'll reopen or create another issue when problem persists.
