### ISSUE TITLE
Feature request: push notifications for starred users' tweets

### ISSUE THREAD

**Issue by emschwartz** [TwidereProject/Twidere-Android#27]
In the official Twitter app there is a way to star users such that you get push notifications every time they post a new tweet. Would it be possible to add this to Twidere?

**Comment by nwtti** [comment]
Sorry for pushing, but I'd like to see that too.

**Comment by mariotaku** [comment]
Push notification requires some servers and a lot more to do, I don't have plan on this. Also buying a server could be very expensive for a free app.

**Comment by nwtti** [comment]
Sorry, i didn't actually mean push notifications, but a replacement for the push notifications function in the official Twitter App.
Couldn't Twidere just check a List of Accounts for new Tweets every x minutes? I could deal with that delay. Accounts on that notification list could get refreshed und checked in the same intervall like auto refresh.

**Comment by FreeK** [comment]
Yeah, I'd like to see this feature too as it helps me to keep up to date (e.g. some accounts keep posting news I'd  like to read) and I don't have to check all accounts manually. It's the only thing I'm missing right now.
