### ISSUE TITLE
Align action icons in a card?

### ISSUE THREAD

**Issue by wynnsyt** [TwidereProject/Twidere-Android#272]
The ideal handling would be to have these icons justified, with ample space in between to show (perhaps) 3 digits. For anything longer than 3 digits it would suffice to show something like "2K+" or "1M+". 

This would serve to reduce UI clutter, and also misclicks due to a variable target size.

![2016-01-01 09 53 21](https://cloud.githubusercontent.com/assets/2130881/12070474/7fbdf146-b0b1-11e5-925a-768610c96a98.png)

**Comment by mariotaku** [comment]
I thinks it's not ideal to align actions icon, but it would be improved a little bit since I use "1 K" or "1 M" for larger numbers.
