### ISSUE TITLE
RTL text in username causes glitches

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#274]
If a user's name contains RTL text (for example Arabic or Hebrew) Twidere displays the name incorrectly in timeline view:

`_example@ مثال` rather than `مثال  @example_`

For example:
![rtl](https://cloud.githubusercontent.com/assets/837136/12078152/4bf84538-b1ff-11e5-90bf-a56b52bf3c9d.png)

Here's how the Tweet is displayed on Twitter's mobile site:
![normal](https://cloud.githubusercontent.com/assets/837136/12078151/4bd70328-b1ff-11e5-933e-d59f1606b6f2.png)

If we take a look at the user's page, you'll see that the user info box at the top is displaying the `@ name` correctly although the Arabic text is hidden behind the "Follow" button.

![view](https://cloud.githubusercontent.com/assets/837136/12078207/3f9f222e-b200-11e5-8cfb-bbc66409d6ed.png)

**Comment by mariotaku** [comment]
@edent I fixed name displaying, can you help me check are there anything displayed incorrectly?

**Comment by edent** [comment]
It's half fixed. The top name (in green) is correct. The bottom name (in red) is wrong.  
Should be `@example_` not `_example@`
![screenshot_20160107-090712](https://cloud.githubusercontent.com/assets/837136/12168000/770b4b6e-b527-11e5-8039-fec258cc24af.png)
