### ISSUE TITLE
change of phone aspect causes position to reset

### ISSUE THREAD

**Issue by andy-twosticks** [TwidereProject/Twidere-Android#277]
Android (CM11). I have Twidere set to refresh from bottom and remember my position. 

If I rotate the phone to landscape and back, it refreshes the feed and I end up at the latest tweet… which kinda breaks POLS/POLA given the above settings.

**Comment by Shulyaka** [comment]
Same here (CM12)

**Comment by benediktg** [comment]
Which Twidere version are you using? With Twidere v3.1.1.6 from F-Droid and CM13 I do not notice this issue.

**Comment by andy-twosticks** [comment]
Now on 3.1.2 and CM11 and … I think it's gone. I turned off Rotation Manager and I've been flipping the phone for two minutes. Nothing. Yay!

**Comment by benediktg** [comment]
@andy-twosticks Nice.

@mariotaku How about closing this issue for the time being?
