### ISSUE TITLE
Deleted tweets aren't removed

### ISSUE THREAD

**Issue by srguglielmo** [TwidereProject/Twidere-Android#278]
I follow my own Tweets using the "User's Tweets" tab. I made a Tweet, then deleted it **using the Twitter website**. When I refresh the tab in Twidere, the deleted tweets do not disappear.

I can select the card and it opens the tweet in Twidere. Selecting "favorite" or "delete" gives the error `Error 144: No status found with that ID.`

I expected that the tweet that I deleted would be removed.

Thanks!

**Comment by ThePreviousOne** [comment]
Twidere doesn't do real-time updates, I don't fully understand how it works but, that's why.

**Comment by srguglielmo** [comment]
Ah, ok @ThePreviousOne. Thanks for the reply. I've since switched to the official Twitter app due to issues with Twidere.
