### ISSUE TITLE
Retweets won't be translated

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#279]

**Comment by ftpur** [comment]
It won't show translation when press language name if that's a retweet (tweet that shows "🔁[Twitter name] retweeted") like this one http://imgur.com/h8Iirep

**Comment by BJSerpas** [comment]
I can confirm this issue. Perhaps the translate option should go back to the three-button menu like it used to be? Even if it doesn't fix this issue, it would make translations MUCH easier to view.
