### ISSUE TITLE
Phantom network error / tweets won't load it send

### ISSUE THREAD

**Issue by kpj104** [TwidereProject/Twidere-Android#280]
Multiple times recently I open twidere and try and lost tweets, it fails silently.   This morning I tried to send one afterwards and it complained about a network error.  Nothing else is having network problems including other twitter app and I'm writing this from same device.  Eventually rate limit is hit and I sang use app for a period of time.

Nexus 5x 6.0.1
Moto X¹ 5.1

**Comment by art1fa** [comment]
I am also experiencing connectivity issues (mostly on Wifi) - Twidere cannot load user profiles / tweets or refresh the home feed. For other apps the internet connection works without problems.

Nexus 5 / OmniROM 5.1.1 / Twidere F-Droid 94ad1a6

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by mariotaku** [comment]
I guess https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.3 will fix this issue. I received many positive feedback of this version. Can you try this version? Remember not to open 'Custom DNS resolver'.

**Comment by bungabunga** [comment]
working great for me! :)

**Comment by mariotaku** [comment]
Fine! I'm closing this.

**Comment by kpj104** [comment]
At this point it won't get any tweets for me.  Just a spinning icon. Have
good signal

[image: Displaying Screenshot_20160210-082248.png][image:
Screenshot_20160210-082248.png]
[image: Displaying Screenshot_20160210-082248.png]

**Comment by mariotaku** [comment]
@kpj104 What version do you have?

**Comment by kpj104** [comment]
It was 3.0.3 .. seems to be fine now, sorry for the false alarm..

**Comment by kpj104** [comment]
Actually on 3.0.4.   And still having issues.  Last night wouldn't
refresh.  Was able to reftesh this am but not "Load More"

**Comment by bungabunga** [comment]
I think this is not the same bug but I can confirm it. Every now and then it's not possible to refresh the timeline anymore. You have to kill the app and start it again to be able to refresh again.

This problem does not occure only on the latest version it was also present on the last dev GPlay version.
