### ISSUE TITLE
F-droid seems to have a version number problem

### ISSUE THREAD

**Issue by pseudomonas** [TwidereProject/Twidere-Android#286]
https://gitlab.com/fdroid/fdroiddata/issues/384 says that the version number on the nightlies is not incrementing, so F-Droid cannot host the newer versions. I'm not sure if this is intentional, given that some of the recent releases are bug-fixes.

**Comment by benediktg** [comment]
I also would like know if this issue could be fixed because somehow Twidere has stopped getting updates in F-Droid since 2 months.

**Comment by pseudomonas** [comment]
Did you find out anything else on this one?

**Comment by mariotaku** [comment]
I'm planning to increment version code in 0.3.0 version.

**Comment by pseudomonas** [comment]
Excellent, thanks! I shall look forward to it.

**Comment by regagain** [comment]
F-Droid is still atuck on the version from November 23rd. Any chance it will be updated soon?

Thank you,

**Comment by pseudomonas** [comment]
Apparently F-droid has some query about signatures. I don't fully understand it, though.

**Comment by pseudomonas** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/396#note_3655430
