### ISSUE TITLE
UI glitches when swiping tabs quickly 

### ISSUE THREAD

**Issue by art1fa** [TwidereProject/Twidere-Android#287]
When quickly swiping through my tabs, the white underline sometimes indicates a wrong current tab. Plus, the content of two tabs overlap or share the screen.

Nexus 5 / OmniROM 5.1.1 / Twidere F-Droid 94ad1a6

**Comment by mariotaku** [comment]
Yes, it's a serious bug across all devices, but I haven't find a way to fix. I'd pay for this bugfix if anyone can.
