### ISSUE TITLE
Socks proxy function NOT working in 0.3.0-dev160124

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#294]
Android版本： 5.1.1
Twidere版本：0.3.0-dev160124
现象：登录时无法使用Socks代理登录
步骤：
　　１.初次登陆时在登录界面点击齿轮按钮，进入网络，高级。
　　２.选中代理服务器，代理类型为SOCKS，代理服务器主机名为 127.0.0.1 ，端口为 1080 （如下图）。
![screenshot_2016-01-24-15-34-46](https://cloud.githubusercontent.com/assets/515763/12535049/9db51966-c2b0-11e5-82d1-2958d75e9600.png)

　　３.返回后并尝试登录，提示失败，网络错误。

分析：通过 logcat 查看日志，代理或者解析功能并未通过SOCKS代理，Twidere通过一个被污染的IP地址进行访问。

附件：
[logcat.txt](https://github.com/TwidereProject/Twidere-Android/files/102214/logcat.txt)

**Comment by mariotaku** [comment]
有个坏消息，DNS客户端不支持代理。先尝试一下TCP查询？

**Comment by chenshaoju** [comment]
@mariotaku 有一个第三方的开源实现，叫DNS2SOCKS，可以给你参考： https://github.com/qiuzi/dns2socks

**Comment by mariotaku** [comment]
疑似okhttp或者Android Framework的bug： https://github.com/square/okhttp/issues/2315

**Comment by chenshaoju** [comment]
Hmmm....

![Suspicious Fry](https://cloud.githubusercontent.com/assets/515763/12836514/aa2902dc-cbf4-11e5-9dd6-d3ed01dbcb87.png)

![Firefox Proxy setting](https://cloud.githubusercontent.com/assets/515763/12836506/8f8d5694-cbf4-11e5-9dd2-599c3f18754a.png)

![Firefox Proxy test running](https://cloud.githubusercontent.com/assets/515763/12836511/937f384e-cbf4-11e5-8947-54a7e271b7c8.png)

**Comment by mariotaku** [comment]
@chenshaoju Firefox的通信方式不一样啦（

**Comment by chenshaoju** [comment]
@mariotaku 刚看了一下，MPL和GPL不兼容，要是直接能复制过来用就好了）

**Comment by mariotaku** [comment]
@chenshaoju 不是这回事……反正这个代码不是那么容易复制的……我看看能不能hack一下okhttp的代码修复这个问题

**Comment by chenshaoju** [comment]
@mariotaku 好人，辛苦了，递卡）

**Comment by fbobraga** [comment]
I'v noted it on early version too (while trying to use a socks proxy [openssh-server with -D...] to use Twidere on my work)

**Comment by fbobraga** [comment]
How can I use Twidere now via a SOCKS proxy server (there's only "HTTP" proxy type here in settings...)? (it's handy on untrusted networks :P)

**Comment by mariotaku** [comment]
`wontfix` until Android fixed this issue.
