### ISSUE TITLE
GNU social support

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#296]
Let's talk about GNU social. Twidere was not designed for GNU social in the beggining, but I think now it's time to do so.

Do you have any suggestions about GNU social support?

**Comment by chenshaoju** [comment]
Too complex,Why not try Creative Commons?

**Comment by mariotaku** [comment]
@chenshaoju Maybe we're not talking about the same thing...

**Comment by chenshaoju** [comment]
Oops,I thought it was an agreement choose 😅

**Comment by annando** [comment]
There are some problems at the moment:

* Picture upload doesn't work with GS since it is now a combination of two different calls that do media upload and posting. GS has a single call for this.
* The GS API doesn't know the API call for fetching conversations (AFAIK GS has its own API call)
* The API path (mostly) contained a "/1.1/" in the path.
* There are some other calls that aren't supported by GS (like /statuses/lookup)

**Comment by mariotaku** [comment]
@annando OK, I'll look into it.

**Comment by iMojito** [comment]
@annando 
MMN already made API changes to be able to post pictures with twidere
Conversations worked on older versions

https://git.gnu.io/gnu/gnu-social/commit/0caf0612d0f3f061f45de2f6a9ede8e738901ef9
https://git.gnu.io/gnu/gnu-social/commit/b570f0d3cbf856843053b4d4d8ab2653476b0845
https://git.gnu.io/gnu/gnu-social/commit/e5019c3858c2be6286fc33d5ee77314bb110bc63

//cc @mariotaku 


>There are some problems at the moment:
>
>Picture upload doesn't work with GS since it is now a combination of two different calls that do media >upload and posting. GS has a single call for this.
>The GS API doesn't know the API call for fetching conversations (AFAIK GS has its own API call)
>The API path (mostly) contained a "/1.1/" in the path.
>There are some other calls that aren't supported by GS (like /statuses/lookup)

**Comment by annando** [comment]
@iMojito Twidere is using the API command "/conversation/show/(number).json" for conversations (if it is enabled in the setup). AFAIK this isn't supported by GS at the moment. On GS the correct call would be "/statusnet/conversation/(number).json".

@mariotaku What I forgot: The API call to "/statusnet/config.json" returns the text limit of the current GNU Social installation. It would be great if the client could fetch that by itself.

**Comment by iMojito** [comment]
@annando *Conversations worked on older Twidere versions (current 0.3.0 on Google Play), I think it issued a search api call (via twitter's compatible api) on those. Still suboptimal

**Comment by hjacobs** [comment]
:+1: for GNU Social support in Twidere!

You mentioned that some things might already work? How can I try it? Which version of Twidere to install or compile?

Thanks :smile:

**Comment by mariotaku** [comment]
@hjacobs You can find directly in Twidere releases, however my builds may have different signature than F-Droid's build, so you may need to uninstall the other one. I'm still discussing how to solve this problem.

**Comment by benediktg** [comment]
It is great to hear that you want to improve the GNU social compatibility – I have reported 2 bugs I have observed: https://github.com/TwidereProject/Twidere-Android/issues/305 and https://github.com/TwidereProject/Twidere-Android/issues/304

**Comment by asterismo** [comment]
Hurry up twitter is dying! lol

**Comment by pizzamaker** [comment]
Relevant: #317

**Comment by benediktg** [comment]
Could it be that groups in GNU social aren't supported by Twidere? Groups are written like "!group" (with a "bangtag" instead of a hashtag) in GS posts.

**Comment by CR0CKER** [comment]
Awesome, would love to see full GNU Social support in Twidere. AndStatus is worlds away in terms of usability and design.

**Comment by resir014** [comment]
I could side with @CR0CKER here. I've had enough of AndStatus because of the same reason and I've managed to give Twidere a go.

I'm currently on https://quitter.is, it works mostly (tweeting and replying to tweet works nicely), the only problems I've encountered so far include not being able to view profiles across nodes, and the inability to upload photos.

From what I've learned, the API shared some similarities to API v1.0 so I could guess that it shouldn't take much work.

Anyways, this app is miles ahead in usability compared to AndStatus and I'd be more than willing to test out GNU Social support on Twidere!

**Comment by Taknamay** [comment]
May I leave any problems related to GNU social support in this thread? Or would you prefer I open a new issue?

Right now the action "open in browser" does not work correctly at all, and just goes to Twitter.

**Comment by benediktg** [comment]
How about opening separate new issues and referencing them here?

**Comment by mariotaku** [comment]
@benediktg Good idea.

**Comment by Taknamay** [comment]
I made #347 for my issue

**Comment by fbobraga** [comment]
How can I add an +1 for this issue? :P

**Comment by dalb8** [comment]
I'm curious why you'd prefer not to make a different app.

**Comment by fbobraga** [comment]
Another app? The problem to be addressed is not the same (or very likely)?
Em 10/02/2016 09:30, "dalb8" <notifications@github.com> escreveu:

**Comment by tchncs** [comment]
:+1: for GNUsocial support in Twidere!

**Comment by Taknamay** [comment]
I made #356 for searching!

**Comment by lebochequirit** [comment]
Could you **setup an f-droid repo to keep track with dev versions**?

A late "I love free software!" for gnusocial support in Twidere. Twidere is a main reason for to stay with twitter.

**Comment by asterismo** [comment]
from a graphic design perspective, Twidere should implement square avatar thumnails instead of circular ones, it breaks so many logos and other avatars, and be able to follow people from it. best regards.

**Comment by benediktg** [comment]
@asterismo When you go to settings → cards → avatar style (in German Einstellungen → Karten → Profilbild-Stil) there is actually a setting to choose between circular (default) and quadratic profile pictures.

**Comment by asterismo** [comment]
thanks benediktg, great! square edges are very sharp, it would be nice to round them just a bit more and set for default. It looks better now! thanks

**Comment by archaeme** [comment]
Is there any plan for supporting larger character limits if the node supports it?

**Comment by archaeme** [comment]
Might just link this issue here: https://github.com/TwidereProject/Twidere-Android/issues/463

**Comment by asterismo** [comment]
i noticed that when trying to read the post from the web URL on the post options, it opens the url with twitter address in the root url, not the actual gnu social pod.

**Comment by asterismo** [comment]
and i noticed some issues trying to upload pictures, after it uploads 100% it fails on networl error, maybe short timeout or something?

**Comment by asterismo** [comment]
it would be nice to havr autocompletion of usernames and group names in gnu social instancrs that allow this freature, cheers

**Comment by asterismo** [comment]
i detected a nasty bug, the number code for changing character limit to 1000 is not working anymore, and anyway mine was set to 1000, when writing a post and rotating screen to horizontal, 1000 changess to 140 and the tweet is not sent. have to copy text, remove draft, and write again. cheers

**Comment by fbobraga** [comment]
@santiago: I've seen something like it with normal Twitter use: the
"characters remaining" counter drops to zero when comparing a tweet, what
makes the send fail...
Em 24 de mar de 2016 12:14 AM, "Santiago Roland" <notifications@github.com>
escreveu:

**Comment by mariotaku** [comment]
Hi everyone, since most features works now, I'll close this issue. Feel free to open separate issue to specific feature requests.

**Comment by asterismo** [comment]
Hi, see a bug. When mentioning some other people using @, it only autocompletes people from the loaded timeline, it wont autocomplete people that hasn't commented anything in the last pull of updates. The same, if you do a search it will only return people that is on the last update of your wall.

**Comment by asterismo** [comment]
It would be nice to make the image preview to match 4:3 or similar aspet ratio, si it could be viewed fine without going to tap on it. moat images satisfy this as u can see in my timeline with 8 out of 10 images or pictures, add an extra height on the preview.

**Comment by benediktg** [comment]
@asterismo When you tap on settings and then "other settings" (down below) → "scrapyard" → "media preview style". There you can choose between scaling or cropping the picture.

**Comment by annando** [comment]
BTW: Since this issue is closed, I would suggest the creation of new issues and not appending new stuff to this one.
