### ISSUE TITLE
In network issue,The refresh will freeze,And timeout function has failed

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#299]
Android版本：5.1.1
Twidere版本：0.3.0 (dev 2016-01-24)
连接方式：Twip
Twip版本：Mar 30, 2015
Twip模式：O模式

现象：
　　当遇到可能的网络问题时（网速太慢或者API无响应），Twidere可能会进入刷新卡死状态，无法再次刷新，也无法停止刷新过程，只能强行结束Twidere后再尝试刷新。即使将超时时间缩短为5秒，一样无法解决该问题。

录像：
　　https://www.youtube.com/watch?v=3Bh06rrh5m4

Logcat：
　　当该问题出现时，logcat里没有有效输出。

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by chenshaoju** [comment]
The test is running.

**Comment by mariotaku** [comment]
I think this is the same bug to #280. To make sure everybody receives update, please subscribe to that issue.
