### ISSUE TITLE
New tweet account selector animation unnecessary

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#300]
This is release 2015-11-22.

I noticed that it tries to move the accounts around when I select and deselect an account in the new tweet account selector.  It's nice, but slightly buggy and superfluous.  Say I have accounts 1 2 3 under each other, I click on 2 to activate it, it will reorder the accounts to show 3 2 1 and then slide 1 and 3 across so they go to the correct position.

**Comment by mariotaku** [comment]
Please check https://github.com/TwidereProject/Twidere-Android/releases/tag/0.3.0-dev160126 , this was fixed in recent versions.
