### ISSUE TITLE
DNS pollution may crash Twidere

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#303]
Android版本：5.1.1
Twidere版本：0.3.0-dev160126
现象：
　　刷新时Twidere偶尔会崩溃，通过logcat分析，怀疑是由于DNS污染导致无法获取图片，返回了空URI后崩溃。具体情况详见Logcat：

Logcat：
[logcat.txt](https://github.com/TwidereProject/Twidere-Android/files/107938/logcat.txt)

**Comment by mariotaku** [comment]
Fixed in 4259be7c23fc5d3ff86f89768b3e9ec341dd9226
