### ISSUE TITLE
Wrong time at GNU social posts

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#305]
I have made the observation that posts from GNU social have the wrong time. It is like the "clock" for GNU social posts gains an hour. As the following screenshot (the blurring is added by me) shows the newest posts have been posted "in 57 minutes" instead of 3 minutes ago. Twidere version is 0.3.0 dev 2016-01-26 and this bug also existed in the current version from F-Droid when I once tried GNU social with it some days ago.

![screenshot_20160128-174948](https://cloud.githubusercontent.com/assets/14795615/12651835/91370bb4-c5e8-11e5-93a3-f75c721c5d30.png)

**Comment by mariotaku** [comment]
Seems it's a bug that Twidere can't handle zone offset properly.

**Comment by benediktg** [comment]
This is indeed solved in the 20160131 release. ;-)
