### ISSUE TITLE
Can't load Activities tab

### ISSUE THREAD

**Issue by art1fa** [TwidereProject/Twidere-Android#319]
On Activities tab, I can't load / refresh any contents, it's just empty. 
By swiping down, I see the spinning circle which disappears a few seconds later, but nothing happened. Logcat doesn't show anything.

Notifications are working great.

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by mariotaku** [comment]
I think this is the same bug to #280. To make sure everybody receives update, please subscribe to that issue.

**Comment by art1fa** [comment]
I don't think this is related to #280. I am still experiencing an empty and not refreshable Activities tab  - although timeline and user profiles are working well.

**Comment by mariotaku** [comment]
@art1fa What kind of instance do you have? Twitter or GNU social?

**Comment by art1fa** [comment]
Twitter. I did not change something in the API except the official keys.

**Comment by mariotaku** [comment]
Twitter shuts down 'activities by friends' API, so this feature won't available.
