### ISSUE TITLE
Threading is broken?

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#32]
Since the update to 0.3.0-dev I've noticed that Twidere no longer shows the "in reply to" threads.

There are several complaints on Google Play about this.

The threaded messages appear to load very briefly but flicker quickly and disappear.  The spinner in the top right freezes when reading a status which is part of a thread.

**Comment by mariotaku** [comment]
https://dl.dropboxusercontent.com/u/2839212/Twidere/twidere-google-debug.apk try this one.
