### ISSUE TITLE
Very slow image loading

### ISSUE THREAD

**Issue by Hodlok** [TwidereProject/Twidere-Android#33]
I see the image previews in the TL, but when I click on them to see full size, it takes very long time loading. Is it normal? Or I have a problem?

**Comment by Sohalt** [comment]
Same issue for me. Clicking on the picture, then the back button, then the picture again usually "fixes" it for me and makes the image load more or less instantly. I'm not 100% sure it's the 2 taps that fixes it, or simply the additional time spent doing those.

**Comment by mariotaku** [comment]
This should be fixed since changed http client implementation, will reopen if issue persists.
