### ISSUE TITLE
Can't refresh activities timeline since the update

### ISSUE THREAD

**Issue by bungabunga** [TwidereProject/Twidere-Android#333]
Since the latest update i can no longer refresh any timline. that used to be a problem with some dev versions in the past, but not with the one i tried just a few days ago.

Sony Xperia Z3c
Lollypop 5.1

**Comment by bungabunga** [comment]
after update to 0.3.1 still can't use Twidere, activities tabs are empty don't refresh.

**Comment by DeadneM** [comment]
Same here but was working before in the 07 January update

**Comment by hahastudio** [comment]
Similar here.
Before Feb 9th update, I can refresh the timeline. But I need to force stop the Twidere once after the Feb 7th update.
Now after Feb 9th update, I can't refresh the timeline in any way.

Nexus 6P, Android 6.0.1

**Comment by daiwenxiamen** [comment]
和诸位问题一致。安装之后界面变成空空的，之前的东西都没了，等待了一段时间之后，它刷新了，可以用之放后台，过段时间去刷，又刷不动。  
Nubia z7 mini Android 6.0.1

**Comment by mariotaku** [comment]
I'll see if 3.0.2 fixes.

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by daiwenxiamen** [comment]
Still the same after updated the version 160209😂😂😂😂.

**Comment by bungabunga** [comment]
@mariotaku just tried it and no, it doesn't solve the problem for me.

**Comment by daiwenxiamen** [comment]
现在可以刷了，我再观察一天再反馈🙋🙋🙋🙋🙋🙋

**Comment by mariotaku** [comment]
Are you using custom API or something?

**Comment by bungabunga** [comment]
the only thing needed for Twidere to work for me at the instalation time was to change the consumer key/secret to official ones as described on Google Play.

**Comment by opticron** [comment]
I had the same problem. I ended up having to clear data for twidere to get it working again.

**Comment by mavit** [comment]
I had this problem after installing the update, but Twidere started working again yesterday afternoon, without me changing anything.

**Comment by Shulyaka** [comment]
Same here. It feels like every network request (not only the timeline) instantly fails, while other apps work nice. Tried to restart the app and reboot the phone with no success. After some time it had been fixed by itself, but then stooped to work again.

**Comment by daiwenxiamen** [comment]
@Shulyaka Exactly the same.

**Comment by mariotaku** [comment]
I think this is the same bug to #280. To make sure everybody receives update, please subscribe to that issue.
