### ISSUE TITLE
Long wait for start

### ISSUE THREAD

**Issue by kamiltalipov** [TwidereProject/Twidere-Android#339]
For 0.3.0 version on my device (nexus 5, Android 6.0.1) first launch (when app isn't in memory) takes much more time than at previous version. I need 2-3 seconds after press the icon to see app instead of nearly instantly launching at previous version.

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by kamiltalipov** [comment]
Unfortunately the problem is still here. I remove my version and install 3.0.2-SNAPSHOT but it didn't help.

**Comment by mariotaku** [comment]
This should work now, it will be available for download after 30 minutes: https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.3-SNAPSHOT-160209

**Comment by mariotaku** [comment]
@kamiltalipov Done. You can try this build.

**Comment by kamiltalipov** [comment]
The responsiveness is better. After press the icon I instantly see that app is loading - gray rectagnle appears on whole screen. After nearly 2 seconds the loading is finish and here becomes the interface. To remember what was I installed some of old build (0.3.0, 2015-12-29). At old version I didn't see gray rectangle - I see just my home screen, but interface appeared faster than at last build.

**Comment by mariotaku** [comment]
Closing this issue now. I'll try improve launch speed in later versions.

**Comment by kamiltalipov** [comment]
Ok. Thank you. Good luck!
