### ISSUE TITLE
Image loading very slow

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#341]
Latest release seems very slow to load images and avatars.  V 0.3.0 (2016-02-07)

I've tried on Wifi and 4G. I've also tried with "Fast image loading" switched on and off.  I've cleared the cache and the databases.  Database size limit is 100MB.

Other apps which connect via the API haven't slowed down.

**Comment by mariotaku** [comment]
Please try this version https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.2-SNAPSHOT-160209

**Comment by edent** [comment]
Avatars nowbload quickly. But if there is media attached to a tweet neither the media nor the avatar loads.

Will see if I can proxy the requests to see what's happening.

**Comment by mariotaku** [comment]
I think this is the same bug to #280. To make sure everybody receives update, please subscribe to that issue.
