### ISSUE TITLE
Images open in Browser

### ISSUE THREAD

**Issue by Harmageddon** [TwidereProject/Twidere-Android#344]
Before v0.3.0, when clicking on an image link inside a tweet (e.g. to pic.twitter.com), the image was opened in Twidere directly. Since v0.3.0 (didn't change with today's 0.3.0.1(?)), a new tab in the default browser opens instead. Is this the desired/expected behaviour or a bug?

Loading an image in the detail view of a single tweet still works.

**Comment by mariotaku** [comment]
Dup to fixed #343, you could try today's snapshots.

**Comment by Harmageddon** [comment]
Ah, sorry! I didn't check the closed issues. Thank you for fixing and for your quick reply!
