### ISSUE TITLE
Indefinitely timeline loading on 0.3.0

### ISSUE THREAD

**Issue by fbobraga** [TwidereProject/Twidere-Android#351]
Frequently it happens:
![screenshot_2016-02-10-07-52-10](https://cloud.githubusercontent.com/assets/3438006/12943872/3f85abb2-cfcb-11e5-899d-aec6d2371bc6.png)
* it is this way for more than 15 minutes, Now

I've also noted other behavior when it's happening: new tweets sent was never sent or putted in to 'drafts'

**Comment by fbobraga** [comment]
I've noted now that I've using "Twitlonger Extension" (Now removed): it may be the cause of this issue

**Comment by mariotaku** [comment]
Dup to #280, I'm moving discussion to that thread.
