### ISSUE TITLE
include tab settings to configuration export

### ISSUE THREAD

**Issue by tbeitter** [TwidereProject/Twidere-Android#353]
The most annoying part of doing a fresh installation is that I have to re-add my accounts and tabs. Could you please add this to the export, too? I think what K9 does with it's export could be a nice thing: Even accounts will be exported but without passwords. So all I have to do with a fresh install is to import my settings and re-enter the password for my accounts.

**Comment by mariotaku** [comment]
Added in 1eada0f0721215d65c653e4c8dee7f8f44269938.
