### ISSUE TITLE
Crash during login to GNU Social instances

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#354]
It doesn't seem to matter where I try to login with the released version (eg. https://api.loadaverage.org/ Basic auth) the screen will go blank and then Twidere will restart.

The bigger problem is that after this it won't be able to refresh the timeline or send new tweets until I destroy the database and kill the running process.  Then it'll work again (no reauthentication needed).

**Comment by ralesk** [comment]
(as in, refreshing existing accounts or post to them, all of which are Twitter accs)

**Comment by mariotaku** [comment]
Can you provide log for crashing?

**Comment by ralesk** [comment]
How do I get the log?

**Comment by mariotaku** [comment]
@ralesk try use Google variation from releases and it will send report automatically.

**Comment by ralesk** [comment]
Turned it on, tried to add my account on loadaverage.org, got the blank screen and then the accounts page.  Hope you received something.
