### ISSUE TITLE
Auto loading feed

### ISSUE THREAD

**Issue by ak04nv** [TwidereProject/Twidere-Android#358]
When I scroll down to the end of the tweets feed, new tweets are auto load only one time. If I scroll down again at the bottom of the feed I see indicator of loading and tweets are not load.
Other feeds (like notifications) are ok.
v. 3.0.4

P.S. Some requests are freeze. Can you add killing feature them by timer?

**Comment by benediktg** [comment]
Should be no problem anymore – at least I can not observe this issue with Twidere v3.1.3 from F-Droid.
