### ISSUE TITLE
Notifications remains on web version after being dismissed in app

### ISSUE THREAD

**Issue by ContactFront** [TwidereProject/Twidere-Android#363]
Not a big issue but this has been in existence for quite some time for me (was present in 0.3.0 dev). Whatever notification I receive on my phone, be it likes, followers, DMs, they will show up again as new notifications on desktop after I've read/dismissed them in app.
I'm using official Twitter key if that matters 

On a side note, DMs deleted in web version remains in app as well.

**Comment by mariotaku** [comment]
If twitter has an API for that, I'll try to implement.

**Comment by art1fa** [comment]
@mariotaku Did you find any hints to mark notifications as read in the API documentation?

**Comment by mariotaku** [comment]
@art1fa No, Twitter doesn't even has such API for official clients. I'm closing this issue.
