### ISSUE TITLE
Add easy login-form for GNUsocial instances 

### ISSUE THREAD

**Issue by raumzeit77** [TwidereProject/Twidere-Android#364]
#296 

As full support for GNUsocial is planned it would be great to have an easy login process. This is the log-in screen from AndStatus with shortcuts to the most popular instances:

https://feez.dubhe.uberspace.de/index.php/s/9Q6ORWBKW9EnxiU

What are your thoughts on this?

**Comment by mariotaku** [comment]
I added some instances: https://github.com/TwidereProject/Twidere-Android/blob/16201b814214f8d0b5def6fff02a43b3ef95a4f6/twidere/src/main/assets/data/default_api_configs.json
If you need more instances, feel free to open an issue, I'll try sign up and obtain a key, or contact site admin.
