### ISSUE TITLE
Have to force stop app to make refreshes work

### ISSUE THREAD

**Issue by dleigh** [TwidereProject/Twidere-Android#366]
About a week or two ago, I began to have a problem with refreshes. I only do manual refreshes via the swipe down. I open twidere after having been away for some hours and when I swipe down the circle spins forever and nothing happens. I have to go to settings > apps and force stop it. Then when I open it all is good again. Any ideas of what this could be? Thanks. Phone: new SONY Xperia Z5 Compact

**Comment by ghc0000** [comment]
I can confirm this, happens exactly as dleigh described. Also, after force stop and restart, the refresh works fine as long as app remains 'active', even in background. Only after some time (indeed some hours) has passed the problem starts. My phone is Nexus 5 and Twidere version 3.0.4. The Builtin DNS resolver option has been turned off.

**Comment by mariotaku** [comment]
Here's a snapshot version. https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.5-SNAPSHOT-160213 Please try this.

**Comment by yamatt** [comment]
I am having similar issues on my Sony Xperia Z3 running the latest version from the Google Play store. I just installed the Google release snapshot and made no difference for me.

I ran the network diagnostics in Twidere and it gets to:

    Testing API functionality
    Testing verify_credentials...

And gets no further.

**Comment by ghc0000** [comment]
Thanks, the snapshot works at least with initial refresh, also refresh after two and ten minutes of inactivity works (but that already worked before). I'll update later today. Should I keep builtin DNS on or off, or does it matter?

**Comment by yamatt** [comment]
Perhaps I have a separate bug?

**Comment by ghc0000** [comment]
After 10 hours refreshing still works. This time, however, I had active network connection before I tried to refresh (I was using my web browser before I tried to refresh timeline in Twidere). I'll try again tomorrow and if the problem is still there I'll get back to this.
@yamatt: Can I ask what network diagnostics tool you used for this? If the problem persists and I get some different information that could help debugging further.

**Comment by yamatt** [comment]
@ghc0000 in Twidere go to Settings > Other Settings > Usage statistics > Network diagnostics

Then press Start and scroll down to the bottom.

**Comment by ghc0000** [comment]
This evening refreshing stopped working. It happened about 5 hours after last working refresh. It happens exactly at the same place as with yamatt, verify_credentials just will never complete, and the 'Send' button never appears. After force stop and restart, diagnostics completes normally (diagnostics continues with get_home_timeline and testing common host names, and then it's done).

@yamatt Thanks for the info, I think I just did not think to look for that option from that place before =)

**Comment by dleigh** [comment]
It's hard to say whether it's been fixed or not for me - not sure whether it should be closed.  Even with the snapshot 3.0.5 I've had to force close now and then to get a refresh to work.  I can confirm that each time I've had to force close it's been hung on "verify_credentials" just like @ghc0000 said.

**Comment by yamatt** [comment]
@dleigh I agree, although the latest release may contain some patches over the snapshot posted previously. I'm currently trying it out.

**Comment by dleigh** [comment]
Ok - thanks.





------ Original Message ------

**Comment by rg3** [comment]
This issue, or a similar one, is stil happening to me on a Nexus 4, Android 5.1.1 with Twidere 3.0.6.1 from the Play Store. It's a show stopper, because I can't use Twidere normally. :-(

In addition, stopping the background service doesn't always help. Network diagnostics show everything OK.

**Comment by dleigh** [comment]
I, on the other hand, seemed to have noticed a resolution to my problem with 3.0.6.1.  I’m pretty sure it’s not hanging anymore – certainly not noticeable like it was for me.

 

 <mailto:david@leighweb.com> DavidEmailSig

**Comment by yamatt** [comment]
I'm finding I'm still having to do this. Significantly less often, maybe once every few days, but it still happens.

**Comment by varod** [comment]
In 3.1.6.2 i'm still having this issue. Time to time I have to kill activity, or switch from wifi to LTE or clear database.
I think so this issue is not closed. How can I help?
Moto G3 CyanogenMod 13 without Gapps.
