### ISSUE TITLE
Notification count on Activities tab for new interaction

### ISSUE THREAD

**Issue by art1fa** [TwidereProject/Twidere-Android#367]
This is a funny, probably easy-to-resolve bug: For new interactions, I get the red notification count on the Activities tab symbol.
Expected behavior: Notification count on the notifications tab symbol.
Found in Twidere 787b78096046d27862f52a4241c14eb282c5894e

**Comment by mariotaku** [comment]
There should be indeed, activities = interactions.

**Comment by art1fa** [comment]
Sorry if I was unclear, I meant the "Activities from friends" tab of course. So, I get a new notifiction count like "User X liked your Tweet" on the "Activities from friends" tab.

The behavior in previous versions - and imho the correct one - was, that the notification count is shown on the Notifications tab. It's also where the actual notification is in.

**Comment by mariotaku** [comment]
Seems activities by friends is not yet implemented. I'll open another issue

**Comment by mariotaku** [comment]
Fixed.
