### ISSUE TITLE
Getting to the end of a list does not load in more tweets

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#369]
I find often that when reading through tweets in any of my lists I reach the 'end' and I have to back out of the list and re-enter it before more are loaded in.

**Comment by yamatt** [comment]
It doesn't happen 100% of the time, in-fact it's improved slightly recently, but still happens. Might depends on the list. Still testing.

**Comment by ak04nv** [comment]
Is it the same #358 ?
I think sometimes request freezes and application has no ways to kill it and resend again.

**Comment by mariotaku** [comment]
Should be fixed in recent versions.
