### ISSUE TITLE
Media preview images and clicking on media preview loads the image twice

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#371]
When you select a Tweet with an image in it so it just displays the card you have the 'Load media' button which when pressed downloads the image and displays a preview. When you press on that image it then loads it up full screen but downloads the image again. Is it possible to use the same cache and half the bandwidth usage?

**Comment by Tedko** [comment]
I will close this issue for now and open a new one later focus on similar bandwidth usage problems. For now we will try to fix all Twitter API related issue 1st.
