### ISSUE TITLE
Notification Sound / Vibration Not Working

### ISSUE THREAD

**Issue by guilhox** [TwidereProject/Twidere-Android#372]
The latest version of Twidere for Android does not show any kind of notification besides the little bell icon on the notifications bar. That's happening for mention notifications on Moto G and LG G2, as far as I've tested.
Before that, there was sound, but it was the default notification sound and LED color as well, despite any custom configuration.

**Comment by chenshaoju** [comment]
I'm upgraded to 3.0.5-SNAPSHOT-160217-2 ,The notification is working,BUT the notification ringtone is system default sound,not my customizationed.
