### ISSUE TITLE
home tl refresh limited come back

### ISSUE THREAD

**Issue by sonicsome2** [TwidereProject/Twidere-Android#373]
twidere 3.0.4&3.0.5
Android MIUI 4.4.4
Twitter for android &Mac key etc.

Tweets will  not be fetched when refreshing home tl  15times +.

**Comment by mariotaku** [comment]
https://dev.twitter.com/rest/public/rate-limits It's rate limit by Twitter, I can't do anything for this.

You can use https://gist.github.com/mariotaku/5465786 for consumer key/secret to bypass rate limits though.
