### ISSUE TITLE
Secret settings: Force private API?

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#375]
When using GNU Social I [read](http://www.haukepauke.de/2014/04/use-friendica-twidere/) it is recommend to select the "Force using private APIs" options in the secret settings.

So my questions are:
1. Is this really necessary for GNU Social? In my case it also worked before doing so, so what are the advantages of enabling this setting?
2. Generally: What does this setting do?

**Comment by mariotaku** [comment]
Not only for GNU social, but also for people using Twitter API proxy like [twip](https://github.com/yegle/twip).

**Comment by annando** [comment]
This setting activates another API call for the thread completion. We are using that in Friendica.

**Comment by mariotaku** [comment]
Closing since better way to use StatusNet specific API was implemented
