### ISSUE TITLE
Make character limit configurable per account

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#376]
Especially for GNU Social it is important to have a configurable character limit. Actually in a secret UI you can [change the character limit](https://github.com/TwidereProject/Twidere-Android/issues/73) ([if it works](https://github.com/TwidereProject/Twidere-Android/issues/374)), but this is unfavourable, because this setting is global.
So if you want to use GNU Social and Twitter at the same time with Twidere, you have to decide on one character limit.

Therefore I suggest to move this option out of the secret settings and into the "account settings", so you can set one limit per account.
When posting to multiple accounts you obviously have to manage the limit somehow too. So you might [split](https://github.com/TwidereProject/Twidere-Android/issues/190) the tweet/queet if it is too long or only allow the smaller character limit.

**Comment by benediktg** [comment]
I also would appreciate it if the setting for the character limit was more prominent. How about setting a default value of 140 chars just as before but letting the user set a higher value for each individual account? I have heard something like that GNU social has an interface for getting the character limit, but decide yourself which is the best way to to this (if you want to implement this feature). ;-)

**Comment by mariotaku** [comment]
I'm planning to add a field to indicate an account's type (twitter, gs, friendica etc), and add separate char limit or something else.

**Comment by rugk** [comment]
:+1: Nice.

**Comment by benediktg** [comment]
great!

**Comment by annando** [comment]
@mariotaku You can fetch the limit by querying the api: /api/statusnet/config.json.

**Comment by mariotaku** [comment]
Done! This will be available in next release.

**Comment by benediktg** [comment]
@mariotaku +1

**Comment by rugk** [comment]
Nice, thanks. 👏
