### ISSUE TITLE
Force close when export settings

### ISSUE THREAD

**Issue by ftpur** [TwidereProject/Twidere-Android#377]
Application crashs when I try to export the settings. Backup file is 0 bytes.
3.0.5-SNAPSHOT-160213-3

**Comment by mariotaku** [comment]
Can you provide further information? Like system version, logcat etc.

**Comment by ftpur** [comment]
Model: SM-N910C
System version: Stock 5.1.1
Logcat: http://pastebin.com/ScGshKkT (I don't know how to logcat. I hope this is logcat 😓)

**Comment by mariotaku** [comment]
@ftpur It helps, can you give me logs containing AndroidRuntime? this will include crash information.

**Comment by ftpur** [comment]
[2016-02-16-14-30-50.txt](https://github.com/TwidereProject/Twidere-Android/files/132030/2016-02-16-14-30-50.txt)

**Comment by mariotaku** [comment]
Found it! this will be fixed in next release.
