### ISSUE TITLE
Tab Icons Missing

### ISSUE THREAD

**Issue by chompteeth** [TwidereProject/Twidere-Android#38]
Hello! I noticed my tab icons are missing completely. I have attached images to illustrate what I mean.

I'm on a note 4 running 4.4.4. I do not believe I had this issue before the latest update.

Thanks!

Screenshots: 
![b3ej0y4caaahp4f](https://cloud.githubusercontent.com/assets/9904229/5155473/02fbadca-7240-11e4-8883-93dedfb5f2cd.png)
![b3ejajzcaaaftmq](https://cloud.githubusercontent.com/assets/9904229/5155474/02fcbad0-7240-11e4-8dcc-c3308bdfb482.png)

**Comment by tobbsn** [comment]
hey, the new fdroid-apk posted in #43 solved it for me, thx!

**Comment by mariotaku** [comment]
fixed in recent version.
