### ISSUE TITLE
Avatars - use square as default

### ISSUE THREAD

**Issue by tbeitter** [TwidereProject/Twidere-Android#382]
Twidere defaults to round avatars, which breaks many of them as every other apps like Tweetdeck and the official page/app work with square ones. That's why all users optimize them to work that way. It would be nice if Twidere could default to the default (:D). Right now I often have to tell friends where they could switch back from the circles.

**Comment by mariotaku** [comment]
I won't change default option since it can be changed. But I'll move this to Settings - Cards.
