### ISSUE TITLE
Twidere crash when click image in mention tab.

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#384]
Android版本：5.1.1
Twidere版本：3.0.4(Google Play,2016-02-10)
现象：
　　在提及（ @ ）页面中，点击任意推友提及中所附带的图片，Twidere将会崩溃。
　　在主页页面中，点击图片，则没有问题。

日志：
　　[logcat_20160218.txt](https://github.com/TwidereProject/Twidere-Android/files/135503/logcat_20160218.txt)

**Comment by mariotaku** [comment]
Fixed in earlier commits.

**Comment by chenshaoju** [comment]
=3= Thank you!
