### ISSUE TITLE
Time line not updating

### ISSUE THREAD

**Issue by travishealey** [TwidereProject/Twidere-Android#386]
Since the last update, the time line will not update with new content. Either the loading indicator spins indefinitely or you can only see the bottom quarter of the circle exposed from under the tabs. 

Using an S6 with 5.1.1 and I have two twitter accounts each with their own home, notification,  and DM tabs (6 total). The time line is set to read from current position after update.

**Comment by mariotaku** [comment]
Are you using 3.0.4 version? This is a known bug and fixed in beta versions. They will be released very soon.

**Comment by benediktg** [comment]
I also recommend trying this build https://github.com/TwidereProject/Twidere-Android/releases/tag/3.0.5-SNAPSHOT-160217-2

**Comment by travishealey** [comment]
@mariotaku Yes, I am running the current version available on the Play Store.
