### ISSUE TITLE
Media attachments and user profiles open in new window

### ISSUE THREAD

**Issue by art1fa** [TwidereProject/Twidere-Android#387]
Since commit 36a052e in your development branch, media attachments and user profiles are opening in a new app window. Besides the long transition animation, they appear also several times in Recent Apps.

Expected behavior: More instant animation (like in previous versions), only one Twidere tab in Recent Apps.

![screenshot](https://cloud.githubusercontent.com/assets/11131859/13199798/568f9194-d82f-11e5-98fc-a242f5ea6bb0.png)

**Comment by mariotaku** [comment]
It's an intended behavior, you can easily navigate through pages, like view another tweet while viewing a user or an image.

I'll add an option for that.

**Comment by art1fa** [comment]
Ok I see. Never experienced this in any App before though. And the animations are kind of annoying, imho they should focus on the requested content - the picture, video etc. Twitter has a nice solution, they zoom in the media and animate the media viewer controls lateron, this feels very instant. You decide ;)

**Comment by art1fa** [comment]
This is not resolved for media attachments, only for user profiles. Is this intended bahavior?
