### ISSUE TITLE
Remove Transition animation on opening user profile Activity with FLAG_ACTIVITY_NEW_DOCUMENT

### ISSUE THREAD

**Issue by LvWind** [TwidereProject/Twidere-Android#390]
The system transition animation here makes it slow(in feeling)

Try add `overridePendingTransition(0,0)` in `onResume()` or get some other cooool stuff here?

**Comment by mariotaku** [comment]
It this solved for you? I provided an option to disable NEW_DOCUMENT flag.

**Comment by LvWind** [comment]
GJ,
Solved my problem, but i think you should move this option to 'Other Settings' from 'Content'. Its nothing about content, right?

**Comment by mariotaku** [comment]
Ummm, `android.content.Intent` (~~fog~~

So I'm closing this issue, if you need further help feel free to reopen or create another issue.
