### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 3.0.4.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [TwidereProject/Twidere-Android#391]

**Comment by locutis-of-borg-1999** [comment]
You could just have them point to: https://github.com/TwidereProject/Twidere-Android/releases  

https://f-droid.org/manual/html_node/Changelog.html#Changelog  

https://f-droid.org/repository/browse/?fdid=org.mariotaku.twidere

**Comment by benediktg** [comment]
Probably this is not the proper place to propose that. The additional links like the source code repository, issue tracker, change log etc. are maintained in the metadata repository located here: https://gitlab.com/fdroid/fdroiddata
