### ISSUE TITLE
Some pictures can't be viewed

### ISSUE THREAD

**Issue by dgeibi** [TwidereProject/Twidere-Android#393]
OS: Android 6.0.1
Version: 3.0.6

some pictures can be previewed like this one

![screenshot_20160222-153521](https://cloud.githubusercontent.com/assets/2224764/13212216/5e211684-d97a-11e5-9e89-590c6f89da58.png)

but can not be viewed the picture after click the preview or the link 

![screenshot_20160222-154059](https://cloud.githubusercontent.com/assets/2224764/13212269/cba5af80-d97a-11e5-99dd-c67412e18d95.png)

reload but

![screenshot_20160222-153547](https://cloud.githubusercontent.com/assets/2224764/13212284/e7de0666-d97a-11e5-83b0-151a72edfb28.png)
 still blank

**Comment by mariotaku** [comment]
Can you provide more problematic tweet links? I'm finding common things between those images.

**Comment by dgeibi** [comment]
https://twitter.com/chengr28/status/702019388661043200

**Comment by dgeibi** [comment]
https://twitter.com/chengr28/status/701660097294913536

**Comment by dgeibi** [comment]
https://twitter.com/0N1NAMAK0/status/701660937200140288

**Comment by dgeibi** [comment]
https://twitter.com/wx0/status/702004776939053056

**Comment by dgeibi** [comment]
Instagram
https://twitter.com/NovaDNG/status/702069632887300096

**Comment by dgeibi** [comment]
https://twitter.com/YigeKing/status/702394324387012608 only the second picture

**Comment by dgeibi** [comment]
Thank you! 😙

**Comment by dgeibi** [comment]
3.0.6.5 https://twitter.com/NovaDNG/status/707800569453346818 picture can't be loaded
