### ISSUE TITLE
Notifications for filtered replies

### ISSUE THREAD

**Issue by vinzv** [TwidereProject/Twidere-Android#394]
I filtered some expressions but nevertheless I get notifications for replies containing them. Can you check/fix that?
(Low prio, I can live with it though)

**Comment by mariotaku** [comment]
What kind filters do you have? Keywords or users?

**Comment by vinzv** [comment]
Keywords like "favorited something by" or "deleted notice".

**Comment by mariotaku** [comment]
I guess you are trying to filter out favorited notifications? It's not yet implemented yet.

**Comment by vinzv** [comment]
Exactly. That's why I opened this issue.

**Comment by mariotaku** [comment]
Fixed in d52983aef442641d19c8a415b2e87750ae6e6f58
