### ISSUE TITLE
Heads-up for possible new Twitter feature: Emoji Favs

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#404]
[Just found out that Twitter is/was experimenting with Emoji Favs](http://www.theverge.com/2015/11/16/9745744/twitter-emoji-reactions) ... thought I'd put it here so it would not come as a surprise when it rolls out.

Simply put: Each fav might get additional metadata in form of selecting an emoji to specify the meaning of a fav.

**Comment by mariotaku** [comment]
Seems this feature is obsolete. Feel free to reopen if Twitter make this someday.
