### ISSUE TITLE
Search history does not fully clear...

### ISSUE THREAD

**Issue by muamma** [TwidereProject/Twidere-Android#408]
Search history does not fully clear, even when I use Settings > Storage > Clear search history.

I've tried re-installing.

Twidere 3.0.6.1

(Great Twitter client, by the way!)

**Comment by mariotaku** [comment]
I can't reproduce that, could you provide a screenshot?

**Comment by muamma** [comment]
Here it is, suitably doctored...

[Twidere.pdf](https://github.com/TwidereProject/Twidere-Android/files/149391/Twidere.pdf)

**Comment by muamma** [comment]
And that screenshot was taken, BTW, immediately after having done a "Clear search history".

**Comment by mariotaku** [comment]
@muamma oh, they're saved searches. You can list/remove them in your profile page

**Comment by muamma** [comment]
Excellent. I see how to do it now. Thanks for the help!

**Comment by herbsmn** [comment]
I deleted some saved searches on my profile page but they aren't going away.
