### ISSUE TITLE
Does not properly proxy through Orbot...

### ISSUE THREAD

**Issue by muamma** [TwidereProject/Twidere-Android#409]
Trying to proxy Twidere thru Orbot, but it does not work.

Settings > Network > Advanced: host set as localhost, port as 8118.

But, when I close Orbot (I checked it is closed!), I can still swipe-update Twidere!

(Android 5.0.2)

**Comment by mariotaku** [comment]
Fixed in 43af801b6cd708148f9d191f33391b1168a730d1. It's actually a intended behavior in okhttp3 which falls back to direct connection when no proxy available.

**Comment by muamma** [comment]
Okay, thanks for the helpful response, and that's good to know. Is there any way of checking, with Orbot on and proxy set, that Twidere is using the Tor proxy?

**Comment by mariotaku** [comment]
New version will be available through releases link.
