### ISSUE TITLE
Tweets are sort neither by time or by ID in timeline

### ISSUE THREAD

**Issue by FromBabylon** [TwidereProject/Twidere-Android#41]
I don't understand why my timeline is messed up : tweets are randomly sort. I have tried to check/unckeck sort by ID in settings but it doesn't change anyhting. 
I would like to have the newest at the top and sort it by time but it doesn't work. (I've seen that you make it possible non long ago but..)

**Comment by mariotaku** [comment]
Is this issue still persists?

**Comment by FromBabylon** [comment]
It seems to be OK now. You can close

**Comment by FromBabylon** [comment]
Well there is still that issue but i think it's on purpose. Indeed, retweets appears in the timeline but I think it's the original tweet date that is displayed.

**Comment by weaselhawk** [comment]
in my home the tweets are in random order
