### ISSUE TITLE
twitlonger by reply to self

### ISSUE THREAD

**Issue by shouya** [TwidereProject/Twidere-Android#412]
When replying to oneself's tweets, a thread will be created even without mentioning his own id. An idea is to use this feature to create long tweets.

logic:

``` ruby
tweets = tweet_text.scan(/.{140}/)
tweet_id = send(tweets[0])

tweets.drop_first.each do |segment|
  tweet_id = send(segment, in_reply_to: tweet_id)
end
```

**Comment by benediktg** [comment]
I think this might be similar to #51.
