### ISSUE TITLE
Delete conversation command doesn't work in Messages tab

### ISSUE THREAD

**Issue by bungabunga** [TwidereProject/Twidere-Android#416]
If i press delete conversation in a conversation in messages tab, it doesen't delete it. Even if i delete it manually on PC it never gets deleted from Twidere. 

This bug is present in Twidere for months but i forgot to report it previously.

Sony Xperia Z3c
Android 5.1.1

**Comment by mariotaku** [comment]
fixed in d9f7ac3a84011cb78e4dae78e9463c1b2c55f56f.
