### ISSUE TITLE
No tab icons view v. 0.3.0

### ISSUE THREAD

**Issue by nemeus** [TwidereProject/Twidere-Android#43]
The top tab icons in the main view are not present, just blank spaces. Thus it is no posible to know what tab you are selecting.

Version 0.3.0 in a Samsung i9505 with stock rom.

Thanks for your amazing work.

**Comment by tobbsn** [comment]
same here. 
version 0.3.0
android 4.4.2
samsung GT-I9515

**Comment by mariotaku** [comment]
@tobbsn @nemeus try this one? https://github.com/TwidereProject/Twidere-Android/releases

**Comment by mariotaku** [comment]
dup to #38
