### ISSUE TITLE
SSL override option missing?

### ISSUE THREAD

**Issue by raidenii** [TwidereProject/Twidere-Android#430]
Hello,

I'm currently using Twidere 3.0.6.1 from Google Play and it seems that the option "Override SSL error" is gone from Network? I have enabled "Force using private APIs" from secret settings, but when I use my twip API to login, logcat says there is a SSL handshake error, so I guess my certificate is probably not trusted in Android.

**Comment by mariotaku** [comment]
Yes, this was removed since it's really not safe by trusting all certificates on all websites. Whitelisted cert management will follow.

**Comment by raidenii** [comment]
Alright. Though interestingly, I have configured nginx to use a certificate chain, thus the certificate should be marked as trusted (and it does work flawlessly in the stock browser), just somehow it doesn't get recognized in Twidere.

**Comment by mariotaku** [comment]
Are you using [Let's Encrypt](https://letsencrypt.org) certificate? Use

````
    ssl_certificate /etc/letsencrypt/live/your.awesome.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/your.awesome.domain/privkey.pem;
````

instead of

````
    ssl_certificate /etc/letsencrypt/live/your.awesome.domain/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/your.awesome.domain/privkey.pem;
````

Will ensure cert working on any application.

Also configuration below is acting like a Twitter API server, without any other requirement.

````
server {
    listen 443 ssl;
    server_name  your.awesome.domain;

    ssl_certificate /etc/letsencrypt/live/your.awesome.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/your.awesome.domain/privkey.pem;

    location ~ ^/domain.([\w\d]+)/(.*) {
        resolver 8.8.8.8;
        proxy_pass  https://$1.twitter.com/$2$is_args$args;
	proxy_cookie_domain twitter.com $server_name;
    }

    location / {
        root /var/www/your.awesome.domain;
    }
}
````

**Comment by raidenii** [comment]
Hmm... I am using LE and the nginx does use "fullchain" certificate (I use acme-tiny to fetch the server certificate and attach the cross-signed X1 cert to the end). Twip works fine if SSL is not a problem.

**Comment by mariotaku** [comment]
@raidenii Could you send me your API address via email? I'll investigate what caused this problem.

**Comment by raidenii** [comment]
@mariotaku Sent. Thanks!

**Comment by mariotaku** [comment]
If problem still exists, try turn http2 on nginx off for this host, I'm not sure if newest nginx works.
