### ISSUE TITLE
"Load More" button doesn't always work

### ISSUE THREAD

**Issue by gena01** [TwidereProject/Twidere-Android#431]
Seems in latest release 3.0.6.4 "load more" animation/activity is missing. Tried hitting it a few times, seems kinda random and everything jumps.

**Comment by benediktg** [comment]
Please try out Twidere v3.1.3 and tell if you still observe this issue.

**Comment by gena01** [comment]
I have it set to load 200 tweets at a time. When I "click" on "load more" there's no visual feedback that it's doing anything for a while. In some cases it's able to load more and i see new tweets show up in others nothing happens.

**Comment by gena01** [comment]
can we have any sort of activity indicator or spinner/animation that shows that Twidere is trying to do something?

**Comment by mariotaku** [comment]
Added an activity indicator to gaps.
