### ISSUE TITLE
No sound when play video second time

### ISSUE THREAD

**Issue by ftpur** [TwidereProject/Twidere-Android#432]
There is no sound when play video again after the first time. The first time is fine.

**Comment by benediktg** [comment]
Could you please provide an example URL?

**Comment by ftpur** [comment]
https://twitter.com/gobou_PTA/status/698374655250288640

(It happen to me every video that hosted on twitter.)

**Comment by benediktg** [comment]
For me it seems to be fine. The first time I watch the video the sound is turned off by default. When I turn it on I can watch the video over and over again without the sound getting turned off.

**Comment by ftpur** [comment]
Whether the sound turned on or not, there is no sound after the first time for me. (The sound icon didn't turn off itself. It stay on.) I use current (beta channel) version from play store.

**Comment by benediktg** [comment]
Maybe there is a regression?

**Comment by mariotaku** [comment]
Closing this issue, if this problem regressed, feel free to reopen or make a new issue.
