### ISSUE TITLE
URL identification issue on 3.0.6.1

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#433]
Twidere版本：3.0.6.1

当中文后连带一个.NET 或域名结尾符时，Twidere将会将其识别为URL：
![screenshot_2016-03-02-15-36-13](https://cloud.githubusercontent.com/assets/515763/13453659/c25694bc-e08c-11e5-8c3d-e40e78e23710.png)

官方Web页面则无此问题：
https://twitter.com/chenshaoju/status/704881596331982850

**Comment by mariotaku** [comment]
Fixed, new tweets after upgrading to this version will work without problem.

**Comment by chenshaoju** [comment]
Thanks! :100:
