### ISSUE TITLE
Card ui bugs

### ISSUE THREAD

**Issue by lixingcong** [TwidereProject/Twidere-Android#438]
1 、使用“纯白背景”作为卡片背景，那个转发按钮和引用按钮也是白色的，与背景一样，看不到。。
2、间歇性的出现收藏（like）按钮按下的现象，表现为收藏按钮亮了，实际上没有收藏过。。

**Comment by mariotaku** [comment]
来个系统版本和截图吧

**Comment by lixingcong** [comment]
Android 4.1.2

下图是白色背景掩盖了按钮。。。
至于那个间歇性的收藏/Like按钮亮了的bug不知道怎么重现。。就是偶尔的会收藏按钮亮起来

![1691224833](https://cloud.githubusercontent.com/assets/7625115/13458178/025a2d7a-e0a7-11e5-9e7e-668d3fb8e0c9.jpg)

**Comment by lixingcong** [comment]
更新后，无法切换到暗色主题。。。
bug又来了？

**Comment by mariotaku** [comment]
@lixingcong 这是其他bug #445
