### ISSUE TITLE
Media viewer hangs

### ISSUE THREAD

**Issue by ivantyr** [TwidereProject/Twidere-Android#441]
![tmp_26221-screenshot_2016-03-02-17-09-491252434505](https://cloud.githubusercontent.com/assets/6587147/13473912/523ab24a-e09a-11e5-8e4d-0d65df4ac12e.png)

Attempting to open an image causes it to load but does not display once load finished, causes the media viewer to instantly hang when loaded
Small image preview works, but loading the large image causes the hang

Running 3.0.6.4 - tried clearing cache but issue keeps happening

**Comment by benediktg** [comment]
Could you please provide an example URL so that other people can try to reproduce the bug?

**Comment by ivantyr** [comment]
I have recorded a video demonstrating it
a.pomf.cat/sebsmm.mp4

The tweets on the video:
https://twitter.com/purocentral/status/705134083551006720
https://twitter.com/Twitch/status/705133869318582272

It also has the same problem on tweets with multiple images:
a.pomf.cat/vwmzmn.mp4

Notice how when swiping to the left to switch to the next image, the top left counter changes, after that the viewer hangs again

https://twitter.com/Yokorick/status/705131975108128768

**Comment by benediktg** [comment]
OK, I assume it could be a regression because I do not have problems when watching these photos and videos.

**Comment by fbobraga** [comment]
Happens here, too

**Comment by fbobraga** [comment]
I don't know if it's related, but since it happens I've received a notification about "99 new mentions" (that don't exists) on a regular basis
