### ISSUE TITLE
feature request: support for groups in GNU social

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#444]
In GNU social there are groups which are written with a bangtag, for example there is a Twidere group which would be written (and displayed) like [!twidere](https://herds.eu/group/twidere). At the moment these bangtags are not highlighted in any way.

Since I think this could be a bit more work it is up to you to decide if you want to implement it. Maybe it is possible to at least detect the groups and figure out their URL to open it in the browser?
#296

**Comment by mariotaku** [comment]
Groups API is too poorly documented, I still need time to figure that out.

**Comment by benediktg** [comment]
OK, I see.

**Comment by mariotaku** [comment]
I implemented group view/timeline feature, managing a group is not implemented yet.

**Comment by mariotaku** [comment]
Most features like timeline/members is working. Feel free to open new issues to this feature.
