### ISSUE TITLE
Dark theme appears as Light theme

### ISSUE THREAD

**Issue by xxkuroikumoxx** [TwidereProject/Twidere-Android#445]
On version 3.0.6.5, Dark theme appears as Light theme. (Android 4.1.2)

**Comment by mariotaku** [comment]
Seems an upstream bug of Android Support Library, will fix when patch come out, please keep this issue open.

**Comment by LvWind** [comment]
Hey juju, I just fixed the same problem here.
The solution of getting everything back to normal with Android Support Library 23.2.0
is just add these in `build.gradle` if you are using gradle1.5
```
android {  
  defaultConfig {  
     generatedDensities = []  
  }   
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
 }  
```

The wrong color of drawable is generated by the gradle plugin.

**Comment by mariotaku** [comment]
should work with new versions
