### ISSUE TITLE
Load More button not showing

### ISSUE THREAD

**Issue by Don42** [TwidereProject/Twidere-Android#446]
When there are more new tweets than the `Load item limit`, there used to be a `Load more` button in the timeline, where there would be missing tweets. That is currently not shown in version 3.0.6.1.
This can be observed on Android 4.3 and 6.0.

This was a very useful feature, because I only irregularly get to check on twitter on my phone.

**Comment by benediktg** [comment]
Do you still observe this issue in Twidere v3.1.3? At least I do not…

**Comment by Don42** [comment]
I'm using the version from the play store. That seems to be v3.1.1.5 and there I can still observe the problem.

**Comment by mariotaku** [comment]
I guess this was fixed in newer version, if you find issue exists, feel free to reopen.
