### ISSUE TITLE
question: make it possible to have "stable" and latest release installed simultaniously

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#447]
Do you think there is a way to make it possible to have the "stable" release from F-Droid and a pre-release from Github installed simultaniously? Unless I'm not mistaken it should work if you additionally publish an APK with a different ID like "org.mariotaku.twidere.beta".

For example Owncloud has done this: there's [com.owncloud.android](https://f-droid.org/repository/browse/?fdid=com.owncloud.android) and [com.owncloud.android.beta](https://f-droid.org/repository/browse/?fdid=com.owncloud.android.beta).

**Comment by mariotaku** [comment]
It's not a good idea I think, installing beta as another application is confusing.

**Comment by benediktg** [comment]
In my opinion it is even more undesirable to have to login again all the time when you switch back and forth between the F-Droid variant and a Github/selfcompiled version. Just providing an additional APK with a different ID would solve this issue because then the different signatures would not compete anymore.

Or could you tell me a simple way to change the ID by myself so that I can install a selfcompiled version without the hassle? ;-) 

PS: I have tried it in Android Studio by refactoring/renaming the package name and the applicationId in the build.gradle but it did not compile then. Or, when I just changed the applicationId and the suffix in the build.gradle it compiled, but the generated APK still had the same ID… :-(

**Comment by mariotaku** [comment]
I have talked with f-droid maintainers for choosing signature, we're planning to use my apk on f-droid in the future, or provide two apks. This would help.

**Comment by benediktg** [comment]
That certainly would be an improvement, but it still does not enable to have two versions installed at the same time. And doing a version downgrade requires you to remove and install and therefore login again. 

btw: Why are the accounts not saved in the exported settings (optionally)? If that was possible it should also be a reasonable compromise.
