### ISSUE TITLE
bug: twidere crashes irrecoverably when scrolling to tweet containing unicode character U+00AD

### ISSUE THREAD

**Issue by 0x1f415** [TwidereProject/Twidere-Android#449]
I follow someone who frequently tweets this character (intentionally).

in Fenix, scrolling to the tweet containing this character will crash the app, but after reopening it it's possible to jump to the top to skip the tweet and use Fenix again. in Twidere, the app crashes and continues crashing immediately after opening. the official Twitter android app does not crash.

[Unicode Character 'SOFT HYPHEN' (U+00AD)](http://www.fileformat.info/info/unicode/char/ad/index.htm)

**Comment by benediktg** [comment]
Could you provide an example URL to a tweet which contains this character so that I can try to reproduce this bug with my version of Twidere?

**Comment by 0x1f415** [comment]
@benediktg [https://twitter.com/0x1f415/status/707051283736190977](https://twitter.com/0x1f415/status/707051283736190977)

**Comment by mariotaku** [comment]
confirmed.

**Comment by benediktg** [comment]
I can confirm it with Twidere version 3.0.6.1 from F-Droid, too.
