### ISSUE TITLE
"un-favoriting" does not work

### ISSUE THREAD

**Issue by braparb** [TwidereProject/Twidere-Android#461]
I am having the constant problem that I cannot un-favorite tweets. I occassionally have to log into twitter on my computer in order to do so. This is highly annoying and I would love to see this fixed. :)

**Comment by benediktg** [comment]
It think that is indeed possible to unfavorite a tweet – you just have to wait a few seconds after you have favorited it. In addition to that I have noticed that sometimes tweets are actually favorited but the star/heart is not coloured.
