### ISSUE TITLE
Adjust character limit for GNU Social nodes that support >140 characters

### ISSUE THREAD

**Issue by archaeme** [TwidereProject/Twidere-Android#463]
Some nodes, such as quitter.no, allow for more than 140 characters per post (quitter.no's limit is 1000 chars), but Twidere has the 140 limit hardcoded. There probably is a way to get the character limit through the API.

**Comment by annando** [comment]
There is a setting in Twidere where you can define a different limit. (It can be reached via the "hidden" menu if @mariotaku hasn't changed that in newer versions). And I guess that this setting will be easier to find in future versions.

**Comment by mariotaku** [comment]
@annando That option was removed because now Twidere will get text limit automatically.

**Comment by archaeme** [comment]
Ok, found that the Google Play version was out of date, so I updated to the latest apk and it works.
