### ISSUE TITLE
Thread completion in GNU Social/Friendica?

### ISSUE THREAD

**Issue by annando** [TwidereProject/Twidere-Android#464]
Older versions used the unofficial Twitter API call to fetch all items of a thread. This setting seems to have vanished now. Has it moved elsewhere or is it replaced by another call? If you use (or want to use) another call, please give me a hint so that I can test Friendica for compatibility.

**Comment by mariotaku** [comment]
Does it have native API for getting thread? I can use that.

**Comment by annando** [comment]
Friendica supports the unofficial Twitter API call "conversation/show". GNU Social has its own call:

````
api/statusnet/conversation/(conversation-id)
````

The conversation id is the id that you get in the message in the field "statusnet_conversation_id". I will add support for the GNU Social command in the upcoming Friendica version.

**Comment by mariotaku** [comment]
I support `/statusnet/conversation/{id}.json`, but it seems returns 404 in quitter.se.

**Comment by annando** [comment]
I just tried. See for example: https://quitter.se/api/statusnet/conversation/4287800.json - that worked for me.

**Comment by mariotaku** [comment]
Seems working fine in 3.1.0+
![image](https://cloud.githubusercontent.com/assets/830358/14012231/6b458548-f1df-11e5-8350-a31a4502ecd1.png)

**Comment by annando** [comment]
I downloaded version 3.1.0.11 and it seems to work very well.

**Comment by annando** [comment]
BTW: I'm closing this issue since it is solved.

**Comment by archaeme** [comment]
It seems to be broken again in 3.1.1.2.
