### ISSUE TITLE
Distribution & Tech Questions

### ISSUE THREAD

**Issue by fredcooke** [TwidereProject/Twidere-Android#47]
Firstly, thank you very much to all contributors, especially the main one(s?) for giving me the opportuity to use twitter. I do not use proprietary software where I can help it, and this is my weapon of choice! :-)

1) Do you work with F-droid to distribute this in a timely and vetted fashion? The latest one had fdroid-dev in the version, so I'm wondering if that's a fork, branch, or what?

2) Should image uploads scale before uploading? I get quite a few failed uploads and the final resolution on twitter is so low that it wouldn't hurt to shrink and reencode within the API bounds, whatever those are.

3) On the previous version occasionally I'd send a tweet with a picture and have it show up without. On upgrade the failed drafts showed negative char chounts, so I suspect something funny went on. Can you help me to understand this with a link to another issue?

Thanks again! :-)

**Comment by benediktg** [comment]
1) F-Droid is now providing pretty recent releases of Twidere.
