### ISSUE TITLE
3.1.0.8.-3.1.1.2 Twidere list timeline always starts at the same position, even after timeline update 

### ISSUE THREAD

**Issue by bungabunga** [TwidereProject/Twidere-Android#472]
I have Twidere list timeline set so that it always open at the position where i left it. But after the latest upgrade it always starts at the same point - at the position just after the upgrade. If i rafresh the timeline and scroll to the top, the next time i open Twidere all of this is forgotten.

After i deleted app cache and restarted Twidere the starting point only moved to that time.

**Comment by bungabunga** [comment]
Sony Xperia Z3c
Android 5.1

**Comment by bungabunga** [comment]
testing 3.1.0.9 to see if it fixes this.

**Comment by bungabunga** [comment]
still present in 3.1.1.2

**Comment by mariotaku** [comment]
Have you tried remove and add tab? I can't reproduce this bug.

**Comment by bungabunga** [comment]
just did what you suggested (also killed app and reset cache) and it solved the problem. thanx!
