### ISSUE TITLE
app name is not translated

### ISSUE THREAD

**Issue by danialbehzadi** [TwidereProject/Twidere-Android#473]
I translated the whole app to Persian and it's available in 3.1.0, but the app name in drawer is still in English. It should be represented in system language like other apps.

**Comment by mariotaku** [comment]
Thanks for your translation, app name 'Twidere' is not translatable.

**Comment by danialbehzadi** [comment]
Of course names are not translatable, but they can be written in different scripts, and since every app name is written in locale destination script (eg. Google), I think Twidere should not be an exception.

**Comment by mariotaku** [comment]
I made app name string translatable now, so closing this issue.
