### ISSUE TITLE
"No account selected" in Home / Activated accounts

### ISSUE THREAD

**Issue by regagain** [TwidereProject/Twidere-Android#475]
Hi!

Anybody else noticed this issue?

My home tab for all activated accounts doesn't display any tweets. Instead I get the following message: "No account selected".

I have a Twitter and a GNU Social account. I also have a home tab for each account, which are working fine.

I am on 3.1.0.8.

**Comment by benediktg** [comment]
I'm using v3.1.0 from F-Droid and did not have this issue. In addition to that I have a combined timeline as well as separate timelines for Twitter and GNU social like you.

**Comment by jagajaga** [comment]
I have the same issue. Version from F-Droid.
