### ISSUE TITLE
Dark theme broken in 0.3.0-dev-fdroid

### ISSUE THREAD

**Issue by schiesbn** [TwidereProject/Twidere-Android#48]
Since I updated to 0.3.0-dev-fdroid the dark theme seems to be broken. If. I want to see my own tweets or any tweets from a specific user the background of the tweets become white while the font color is white too. This makes it impossible to read any tweets.

**Comment by cjeanneret** [comment]
Same problem in here :(. Seems there are some issues propagating "dark theme" across some displays…

**Comment by misterpeguero** [comment]
I can confirm that this is an issue for me, as well! Here are some examples below:

This is what I receive whenever I attempt to view one's timeline by accessing a user's profile and viewing "Tweets":

![timeline](https://cloud.githubusercontent.com/assets/6090866/5986595/7dd5cd2e-a8cc-11e4-911f-80e53eddc14b.png)

And these are my current theme settings:

![settings](https://cloud.githubusercontent.com/assets/6090866/5986597/8fbbfdce-a8cc-11e4-80a2-d101f937b8c8.png)

In this particular case, I am currently running Android v4.4.4. Please do not hesitate to ask for additional information that might be helpful in patching this particular bug!

**Comment by flipsa** [comment]
Same problem here (CM11 / 4.4.2).

**Comment by mariotaku** [comment]
fixed in recent commits.
