### ISSUE TITLE
Links to Tweets not working in GNU Social

### ISSUE THREAD

**Issue by Taknamay** [TwidereProject/Twidere-Android#480]
For GNU social users, I think a link to Twitter should open an external browser. Right now it just results in a 404.

**Comment by mariotaku** [comment]
Which version? Newest version should open correct link.

**Comment by Taknamay** [comment]
3.1.0.9. I'll let you know if it is fixed once F-Droid updates it.

**Comment by mariotaku** [comment]
Oh, I know, open a tweet link inside a status in GS is not working yet, I'll improve twitter link handler in the future.

**Comment by moshpirit** [comment]
I think I know what happens: on GNU social Twidere search the user in the same server that you're using.

If we call the server used by us "A" and the server used by the other user "B" what Twidere is trying to read is "A/username" instead of "B/username".

**Comment by moshpirit** [comment]
Twidere 3.1.1.6 solves what I was saying. @Taknamay, you should probably check it again :)

**Comment by Taknamay** [comment]
Perfect. Works in the latest.

**Comment by regagain** [comment]
It seems this issue is back. I'm using 3.2.5, not sure when it reappeared.
