### ISSUE TITLE
Theme "light" is a little bit dark

### ISSUE THREAD

**Issue by annando** [TwidereProject/Twidere-Android#482]
The 3.0 had white icons in the top bar when you have chosen "orange" as top bar color. This is now changed to black. This is looking a little bit depressing ;-) Could you maybe add a setting if the icons are black or white?

**Comment by BJSerpas** [comment]
I totally agree with this. There really needs to be a way to completely select the color for these icons, just like you can select the primary theme color. Having black icons are seriously annoying, so until this is addressed I'll be using an older version of the app.

**Comment by mariotaku** [comment]
Fixed in eb437d2ba03f959c41517b948eb8025f3a6369f5.
