### ISSUE TITLE
Crash when refreshing GNU Social timeline on 3.1.1

### ISSUE THREAD

**Issue by regagain** [TwidereProject/Twidere-Android#486]
Hi!

Twidere 3.1.1 keeps on crashing when I refresh my GNU Social (quitter.se) timeline.
This doesn't happen with my Twitter account.

It wasn't happening on 3.1.0.10.

Is there any way I can provide logs or anything?

Thanks,

**Comment by mariotaku** [comment]
You can send logcat to twidere.project@gmail.com

**Comment by regagain** [comment]
Done! Thank you :)
