### ISSUE TITLE
Can't select ringtone in 3.1.1.5

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#488]
Twidere Version:3.1.1.5 (Google Play)
Android Version: 5.1.1

现象：在设置->通知->(选择账号)->铃声，里，无法指定铃声，点击铃声后左侧的选择符号并未被选中。

**Comment by mariotaku** [comment]
已确认，下个发布版修复

**Comment by mariotaku** [comment]
Fixed in 1eada0f0721215d65c653e4c8dee7f8f44269938.

**Comment by chenshaoju** [comment]
This issue still NOT fix on 3.1.3.3 (Google Play).

**Comment by chenshaoju** [comment]
This issue still NOT fix on 3.1.4.1 (Google Play).

**Comment by chenshaoju** [comment]
This issue still NOT fix on 3.1.4.2 (Google Play).

**Comment by mariotaku** [comment]
这次真修好了，如果还选不了我直播吃键盘……（如果rom不兼容的不算

**Comment by chenshaoju** [comment]
Google Play尚未更新，travis-ci并不能像appveyor可以提供编译版本下载）

我还是期待一下吃键盘吧）巧克力键盘？ ![doge_org](https://cloud.githubusercontent.com/assets/515763/14286424/8f962686-fb81-11e5-8544-28a99e14870a.gif)

**Comment by RicardoGuzmanVelasco** [comment]
I think the problem is still live. I can only select the default system ringtones. Last version in Play Store.

**Comment by mariotaku** [comment]
@RicardoGuzmanVelasco yup, problem still exists, and it will be fixed in next release.

**Comment by chenshaoju** [comment]
This issue has been fixed on 3.1.5.2,I can confirm.
看起来不用吃键盘了。![doge_org](https://cloud.githubusercontent.com/assets/515763/14662430/b4d8ba54-06e8-11e6-87a4-4cbe307dd214.gif)
