### ISSUE TITLE
404 on GNU social when viewing a profile of another server

### ISSUE THREAD

**Issue by moshpirit** [TwidereProject/Twidere-Android#489]
I think that on GNU social Twidere search the user in the same server that you're using.

If we call the server used by us "A" and the server used by the other user "B" what Twidere is trying to read is "A/username" instead of "B/username".

**Comment by mariotaku** [comment]
Fixed in f8d66448580e341be227575d7bc1a099f93b8bad.

**Comment by moshpirit** [comment]
Thank you!!
