### ISSUE TITLE
Remember position is not working in custom tabs

### ISSUE THREAD

**Issue by LuisGC** [TwidereProject/Twidere-Android#491]
Since the last update, the "remember position" feature is not working. At least in a custom tab I use constantly with one of my twitter lists.

Each time I close the app and open it again, I see the same tweets from (now) 2 days ago. This, combined with the "read from bottom", makes Twidere useless for me. I have to reload the same tweets over and over again...

**Comment by mariotaku** [comment]
Fixed in 9670545236ef72bfdbd923af15f60377b75c85f9.
