### ISSUE TITLE
Data usage

### ISSUE THREAD

**Issue by JanvierUK** [TwidereProject/Twidere-Android#492]
Feature request:

My twidere has been using A LOT of data this month. Can there be a way of setting it to refresh frequently via Wi-Fi but at a lower frequency on mobile data?

**Comment by mariotaku** [comment]
There's an option called Bandwidth saving mode in network preferences, which automatically turns off media preview when you are using metered network (like 3g or mobile hotspot)

**Comment by benediktg** [comment]
I can not complain about Twidere (v3.1.3 from F-Droid) consuming too much data volume…

**Comment by Tedko** [comment]
I guess this wont be a problem with the recent updates.

@JanvierUK @benediktg Just let you know Twidere are back and supported by community. And input and contribution are welcomed. Thx
