### ISSUE TITLE
Tweet count (red badge) not shown in Home tab & not correct tweet count in Android notification panel

### ISSUE THREAD

**Issue by shadow1112** [TwidereProject/Twidere-Android#494]
First issue is resolved for a while by reseting Twidere cache and databases but after a while it is back.
Second issue - every time a notification comes there is a wrong count of tweets indicated.

(Android 5.0, Twidere 3.1.2/3.1.1.x - last versions without this bugs were 3.0.x)

**Comment by shadow1112** [comment]
Still not fixed in last versions... :'(

Where's the problem please?

**Comment by mariotaku** [comment]
I still can't reproduce... not sure why.

**Comment by shadow1112** [comment]
I believe you. But it's very strange as the 3.0.x versions were without this bugs. Really seems that there's a problem in cache/count not resetting - maybe only in Android 5.0?

Please can you make any more investigation to fix it? Notifications are totally unusable for me now and I don't know about new tweets count.

Thanks in advance, Twidere is imho really the best Twitter client. Thanks for your work.
