### ISSUE TITLE
unable to reslove class import fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask

### ISSUE THREAD

**Issue by alhaddadsoft** [TwidereProject/Twidere-Android#495]
when i import twitter( import new module ) to my project i get this error 

Error:(1, 0) Cause: startup failed:
build file 'C:\Users\ammar\Downloads\androidapp\MyApplication3\twidere\build.gradle': 1: unable to resolve class fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask
 @ line 1, column 1.
   import fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask
   ^

1 error

<a href="openFile:C:\Users\ammar\Downloads\androidapp\MyApplication3\twidere\build.gradle">Open File</a>

**Comment by mariotaku** [comment]
What's your JDK version?
