### ISSUE TITLE
Add default API config for public GNU social instances

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#496]
There are many GNU social instances. They are too many that it's hard for me to sign in to every instances and obtain consumer key/secret.

So I need help of admins of those GS instances. I'll add keys provided by you to Twidere and make it possible to log in without too much steps of configuration.

**Comment by annando** [comment]
According to my statistics there are at minimum 190 GNU Social/Statusnet instances. Additionally there are at least 400 Friendica instances out there in the world. Do you want to have keys for all these servers - or only for the public ones? (Open Registration/Invitation)

**Comment by mariotaku** [comment]
@annando For public instances only.

**Comment by MarcusMoeller** [comment]
Which steps are required to help you out?

**Comment by kameleono** [comment]
Manuel, admin of lamatriz.org, my question is the same of @MarcusMoeller which steps are required to help you out?

**Comment by mariotaku** [comment]
@MarcusMoeller @kameleono It's pretty simple, just register an app called Twidere with read-write-directmessage permission (or your desired brand name) and send consumer key/secret to me, I'll do the rest.

Default settings for example:
![image](https://cloud.githubusercontent.com/assets/830358/14226765/5197e834-f91e-11e5-8c9f-03a91a58714c.png)

**Comment by vinzv** [comment]
For anyone searching like me: Registering oauth apps is located under /settings/oauthapps/new.

**Comment by vinilox** [comment]
@mariotaku Hello, I am the admin of https://status.vinilox.eu can you send me (vinilox@vinilox.eu) the consumer key/secret so I can add the app please ?

**Comment by mariotaku** [comment]
@vinilox Hi, could you register with your account? Since you're the admin, the key should work whatever I signed up in your instance or not.

**Comment by vinilox** [comment]
@mariotaku Woops, I didn't knew how all of this worked. I just added the app and sent you an email with everything.
Thanks for your work !
