### ISSUE TITLE
Some crashes since 3.1

### ISSUE THREAD

**Issue by danialbehzadi** [TwidereProject/Twidere-Android#497]
Since Twidere 3.1 there is some crashes which are followed by a force stop:
* While viewing a profile page of an account, on loading pictures (header and big avatar)
* On notification alert about new replies

Tested on Cyanogenmod 11 (based on Android 4.4.4) and Android 5

**Comment by b3180558** [comment]
In direct tab . not exist delete  bottom  for delete pm

**Comment by jpfox** [comment]
Same problem on a phone since 3.1.3 coming from f-droid. reset database (tweet/profile...) does not change anything. Crash directly when pulling to bottom to force update tweets.

On paranoid android 5.1.1 (without gapps)

**Comment by jpfox** [comment]
Export settings / uninstall / reinstall / import settings... seems to correct the problem.

After these operations, I had a "@" tab always empty. I remove it and replace it with "interactions" tab (with a bell logo).

Is this new version manage old "@" tabs ? It could be the reason of crash.

**Comment by danialbehzadi** [comment]
fixed in 3.1.3.2
