### ISSUE TITLE
GNUSocial: Hide favored queets and replies of persons I do not follow

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#498]
Please add an option to hide favorited queets (it is annoying to always see them - they start with "XY favored something by AB" and contain the whole queet which was favored.

Additionally an option to hide the queets, which are directed to other people (`@XY You should do ab.`) would be a nice addition.

Both things are possible in Qvitter (a UI for GNUSocial) and it would be nice to have the same things in Twidere.

**Comment by benediktg** [comment]
Qvitter and the classical view of GNU social just provide an option for only presenting the stream of notices (without conversations), the notices "X favorited something by Y" simply are not displayed at all.

@mariotaku: If you want to do something about this, it might suffice to just filter out messages containing the exact string "favorited something by" (although it is indeed rather a hack).

(referring #296)

**Comment by archaeme** [comment]
"Favorited" notices have a "favorite" activity verb associated with them. This could be useful in filtering them out.

**Comment by benediktg** [comment]
@archaeme Yes, if you put the strings `favorited something by` and `deleted notice {{` into the filters then those notices are not shown.

**Comment by archaeme** [comment]
@benediktg In the ActivityStreams JSON, there's a "verb" key that can have a "favorite" value.

**Comment by rugk** [comment]
Anyway it would be useful if this could be done by tapping a simple checkbox or so. Using filters is really a thing for "advantaged users".

**Comment by allvoxman** [comment]
It'd be great if there was an option to hide favorites ("someone favorited something") & follows ("someone started following someone else") messages from the timeline. I dont' want them there, too much noise. How can this be done?

**Comment by rugk** [comment]
…and retweets. For some reason I see the same queet again and again as an "answer" to the original queet for each user, who retweetet it.

**Comment by mariotaku** [comment]
Though it is not designed to do such thing, #1020 is a solution to this issue. So I'm closing this since it's implemented.
