### ISSUE TITLE
no transparency anymore

### ISSUE THREAD

**Issue by JPRuehmann** [TwidereProject/Twidere-Android#499]
Hello
Transparency is not working anymore, how do I get it back to work?
thanks,
twidere Version: 3.1.1.5
System Version: 5.1.1 / 01.01.2016
Gerät: Huawei Y560-L01

**Comment by mariotaku** [comment]
3.1.3.x should work, I'll publish an update soon.

Jan-Peter Rühmann <notifications@github.com>于2016年4月3日周日 03:32写道：
