### ISSUE TITLE
Twidere for Android 2.3.7

### ISSUE THREAD

**Issue by alexxtasi** [TwidereProject/Twidere-Android#5]
Hi and great work !!
I used Twidere since January (I think) and after re-mod ing my phone I can not install it again. Market says "This app is incompatible with your device". But in your README file it says "Twidere is a powerful twitter client for Android 1.6+" and "There're two versions, one for Android 4.0+, another for Android 1.6 to Android 3.2". How can I install the proper version to my android phone ?

I have Android 2.3.7 (CyanogeMod-7.2.0) and Kernel 2.6.35.7 (as my phone's info says)

regards

**Comment by ilakast** [comment]
Now the legacy apk is on dropbox rather than google drive http://goo.gl/tgLTfJ Again, the link can be found in the profile of the twitter account @TwidereProject
