### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#500]
@mariotaku Could you please check if the latest translations from Crowdin are imported into the repository? I have completed the German translation there some days ago.

**Comment by mariotaku** [comment]
@benediktg Thanks! I'll add it in 3.1.3.1.

**Comment by mariotaku** [comment]
Sorry, I forgot to update translations, it will be available in 3.1.3.2, and will release this week.

**Comment by mariotaku** [comment]
Released, I'm closing this.
