### ISSUE TITLE
craah on new tweet gnu social

### ISSUE THREAD

**Issue by asterismo** [TwidereProject/Twidere-Android#502]
after las 2 updates i'm getting the app to crash every time i hit the new tweet button. First i had the app installed through FDroid but after several updates  of the app to versions 3.1.3 and so on, the app stopped working, so i installed the one from GPlay which was a bit oldr than these. Today GPlay app updated to 3.4 and the same happens. I'm using Cyanogenmod 12 lollipop 5.1 on galaxy s4 mini. After hitting new tweet i get app stopped working, pkease fix this awesome app!!

**Comment by asterismo** [comment]
i can retweet without issues, its only when creating new tweets the crash

**Comment by mariotaku** [comment]
It's a bug in 3.1.4, and has been fixed in 3.1.4.1+, it should be available now.
