### ISSUE TITLE
"tweet too long" on gnusocial server

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [TwidereProject/Twidere-Android#531]
on my server https://gorf.club/ there is no text limit. maybe this is causing the error on twidere? even trying to post a single character results in "tweet too long"

**Comment by orithena** [comment]
This would be a duplicate of #481, marked as fixed 18 days ago. Commit fb9969f looks like it fixes exactly this. Maybe the fix didn't make it into your build yet?

**Comment by berrythesoftwarecodeprogrammar** [comment]
hmm.. im using 3.1.4.2 which seems to be the latest. i got it from fdroid. ill try the github apk

**Comment by berrythesoftwarecodeprogrammar** [comment]
maybe i should also mention im using 'basic' authentication since i still havent been able to get oauth working https://github.com/TwidereProject/Twidere-Android/issues/513
