### ISSUE TITLE
Copy & Paste icon is blending into background when using light theme

### ISSUE THREAD

**Issue by tSU-RooT** [TwidereProject/Twidere-Android#538]
Please see this screen shot;
![copy_paste_blending_into_back](https://cloud.githubusercontent.com/assets/1822861/14789571/22d4b25c-0b48-11e6-8009-0e1702ad298c.png)

Environmet:

```
Nexus 5
Android 5.1.1
Twidere 3.1.5.2 installed from F-Droid
```

**Comment by benediktg** [comment]
v3.1.5.2 is not the most current version, could you please check if this issue also occurs on v3.1.6 which is available at F-Droid? :wink:

**Comment by tSU-RooT** [comment]
It's reproductive on current version(3.1.6)
