### ISSUE TITLE
Feature request: Better multi-account QoL

### ISSUE THREAD

**Issue by lunarxskies** [TwidereProject/Twidere-Android#539]
If you have 2 accounts following the same person, you will see the same tweets multiple times

Liking tweets is always liked by the initial user instead of being able to pick which user likes

Maybe add colour coding to differentiate which tweet is part of which users timeline

**Comment by mariotaku** [comment]
Different account has different color as you set them in Drawer - 'Accounts' - Long click and choose 'Set color', then you'll see its color label on the right side of a tweet.

**Comment by lunarxskies** [comment]
Oh I see that now, is it possible to implement the first 2 requests though?

**Comment by mariotaku** [comment]
1. Different tweet has their different state, like rt/favorite count, so I use multiple tweet by design
2. Liking a tweet will be performed by its corresponding account.

**Comment by trwnh** [comment]
Is it possible to add an account picker for RT/Favorite for accounts you follow from one account but want to RT/fav from another account?

**Comment by DjSlash** [comment]
@trwnh You can open the tweet, then hit the context menu button and select 'open with account'.

@mariotaku Opening accounts, select account and then hit the context menu, there's also an 'set color' option. This setting doesn't reflect anywhere else than in that screen. Is this is a bug (and if so, should I open an different issue)?

**Comment by trwnh** [comment]
@DjSlash
Yes, I know, but this is a very inconvenient workflow. It would be much better to be able to do it from the timeline, e.g. by long pressing the RT icon (as in Flamingo) or using a popup menu (as in Plume).
