### ISSUE TITLE
Bug repport: No notifications for DM

### ISSUE THREAD

**Issue by LTK23** [TwidereProject/Twidere-Android#543]
It's all in the title. Was working a few versions ago on my Galaxy S2 (4.1.2), but the stopped after an update (can't remember which one). Checked the parameters all notifications enabled.

**Comment by LTK23** [comment]
Changed my cell phone, still the same problem on Sony Xperia Z3 compact 5.1.1. Or is it me missing something ? Tried every parameter I could find thought...

**Comment by JanvierUK** [comment]
Samsung S4, Android 5.0.1, same issue.

**Comment by Yowlen** [comment]
Still a problem. LG Leon running Android 5.1.1, as well as Acer B1-730 running 4.4.2.

**Comment by ehashman** [comment]
Same issue on my DTEK60, running BlackBerry Android 6.0.1.

**Comment by Yowlen** [comment]
This seems to have had a regression between versions 3.3.42 & 3.4.2. In 3.3.42, the notification would display when the app was opened by the user or the user manually refreshed the timeline, but in 3.4.2, this no longer occurs. Neither version shows the notification from the background sync, which was the original issue.

**Comment by mariotaku** [comment]
#709 Should fix that, feel free to open new issue if this still exists.
