### ISSUE TITLE
Bug repport: Can't accept or reject a following demand

### ISSUE THREAD

**Issue by LTK23** [TwidereProject/Twidere-Android#544]
On Galaxy S2 (4.1.2), the accept or reject buttons are not there anymore.

**Comment by mariotaku** [comment]
This feature is not available unless you found a consumer key/secret from official client.

**Comment by LTK23** [comment]
Hi, thank you for your answer. The thing is I do have one. It was working a while ago. Then after an update I started to get an error message "this account doesn't exist" when trying to accept or reject, and then after another update the buttons had disappeared. (Sorry, I should have mentioned all that in the first place)

**Comment by mariotaku** [comment]
Ah, my bad, confirmed. Will fix soon.
