### ISSUE TITLE
New Follower notification

### ISSUE THREAD

**Issue by Evild67** [TwidereProject/Twidere-Android#547]
Hi,

There are no notification when we get new follower. Can you add this feature ? :)

**Comment by art1fa** [comment]
Are you using the [offical Twitter-Keys](https://gist.github.com/40298/04ca879b91e1a353711d) in your network settings?

**Comment by Evild67** [comment]
Twitter for Android Keys yes :)

**Comment by mariotaku** [comment]
Do you mean via push notification? Twidere doesn't have push yet.

**Comment by Dostoi** [comment]
Is there a way to have it in the notification tab if you have one ?
