### ISSUE TITLE
Invalid submodule path for DragSortListView

### ISSUE THREAD

**Issue by atavism** [TwidereProject/Twidere-Android#55]
Submodule path 'libraries/SlidingMenu': checked out '1fddbfad5b8cf72073e4bdf95a815b0585078fe1'
Unable to checkout 'cf66bea00da85aa4c65e62b79918e3e6909e9327' in submodule path 'libraries/DragSortListView'

**Comment by mariotaku** [comment]
fixed in recent commits.
