### ISSUE TITLE
No way to create group DMs

### ISSUE THREAD

**Issue by nevillepark** [TwidereProject/Twidere-Android#550]
Twitter now allows direct messages between multiple people, but there doesn't seem to be a way to add more recipients in Twidere. In fact group DMs don't seem to be showing up in my Messages tab at all. 

Using version 3.1.6 on a Moto X Play (XT1563) running CyanogenMod 13 (based on Android 6.0.1).

**Comment by mariotaku** [comment]
Indeed, Twitter doesn't even allows us to access group DMs at all. I'll try some special method though. Please wait for upcoming changes.

**Comment by rodrigoaguilera** [comment]
It is a pity that there is no API support for a feature that is more than a year old.
Maybe posting here can help
https://twittercommunity.com/t/group-dm-support-via-the-apis/31266/15

**Comment by mariotaku** [comment]
See #709, closing this issue for better tracking
