### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by airsynth** [TwidereProject/Twidere-Android#552]
Hi! I love Twidere!

There's a word incorrectly translated to Spanish. It must say "menciones" instead of "mensiones".

I'm sorry if this request does not fit here.

**Comment by mariotaku** [comment]
I'll update. Are you a native Spanish speaker? I can give you higher permission to modify existing translations [here](https://crowdin.com/project/twidere/es-ES)

**Comment by airsynth** [comment]
Yes, I'm a native Spanish speaker. I'll contribute if i can :)
