### ISSUE TITLE
Reversed FAB animation logic

### ISSUE THREAD

**Issue by Low012** [TwidereProject/Twidere-Android#555]
In version 3.1.7 the logic of the animation of the floating action button is reversed in several (all?) lists:

What happens:
- FAB does not disappear when I scroll down in a list.
- FAB disappears when I scroll up in a list.
- FAB reappears when I reach the top of a list.

What I would expect:
- FAB disappears when I scroll down in a list.
- FAB reappears when I scroll up in a list.

**Comment by mariotaku** [comment]
Have you enabled read from bottom? The behavior you've mentioned was made by design if that option enabled.

**Comment by Low012** [comment]
Yes, indeed, I have enabled read from bottom. Now as you mention it, this behaviour makes sense, it just feels a little bit strange _to me_.
