### ISSUE TITLE
Twitter will change the rules regarding character count.

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#556]
Thought this might be interesting to know for @mariotaku: Twitter announced to change the rules on how to count characters in the coming months.

Short version: Up to 50 @-mentions are not counted, Media links at the end of the tweet are not counted.

Long version: [https://dev.twitter.com/overview/api/upcoming-changes-to-tweets](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets)

**Comment by mariotaku** [comment]
Thanks, I've noticed that and will implement ASAP.

**Comment by orithena** [comment]
Seems to work correctly with the new rules now -- closing this (way too late...)
