### ISSUE TITLE
Back button behavior

### ISSUE THREAD

**Issue by ddomgn** [TwidereProject/Twidere-Android#558]
Currently clicking on the back button (arrow) in the top left corner opens the main activity, while pressing the hardware back button opens previous activity. The latter behavior is more intuitive. In my opinion it would be better to make top-left corner button behave the same, i.e. open previous activity. It could also be implemented as an option in app settings.

**Comment by mariotaku** [comment]
That's the 'Navigate Up' action should be, see https://developer.android.com/design/patterns/navigation.html .
