### ISSUE TITLE
Add ability to create, view and respond to polls

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#562]
[This is not supported in the Twitter APIs](https://twittercommunity.com/t/poll-support-for-rest-api/54775/32), but worth tracking it in case others are looking for the same issue.

**Comment by mariotaku** [comment]
[x] View
[x] Respond
[ ] Create
This could be done by [official keys](https://gist.github.com/mariotaku/5465786)

**Comment by rugk** [comment]
Actually I cannot even see polls, so your tick list seems to be incorrect.

**Comment by mariotaku** [comment]
@rugk Have you changed to [official keys](https://gist.github.com/mariotaku/5465786)?

**Comment by rugk** [comment]
Ehh, I would have to logout.
Also the official keys are quite rate-limited, are not they?

**Comment by rugk** [comment]
Ah, no it works.

**Comment by minami-o** [comment]
Hey there,
Trying to get polls to work here (view/respond), but nothing will do, the tweets appear, but not the polls…
Doesn't work from scratch, set up a twitter developer account to repace API keys, also tried with some "official" API keys I found on some git, to no avail!
Also, the link above, supposedly towards official keys, doesn't go anywhere anymore.
So, what am I doing wrong?
Any help appreciated!

**Comment by Tedko** [comment]
> Hey there,
> Trying to get polls to work here (view/respond), but nothing will do, the tweets appear, but not the polls…
> Doesn't work from scratch, set up a twitter developer account to repace API keys, also tried with some "official" API keys I found on some git, to no avail!
> Also, the link above, supposedly towards official keys, doesn't go anywhere anymore.
> So, what am I doing wrong?
> Any help appreciated!

@minami-o  Hi - if you are on 4.1.x+ you will use official API by default.

For now Twitter seems have APIs for poll>? https://developer.twitter.com/en/docs/tweets/enrichments/overview/poll-metadata 

We will work on fix this issue soon.

**Comment by Tedko** [comment]
I will close this issue for now and move discussion to #1276
