### ISSUE TITLE
Clicking on favourites/likes in a card does not bring up list of accounts who favourited/liked

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#563]
1. If you see a tweet, press on it, so that you're in the screen that shows you more detail about that tweet.
2. Press on 'Retweets' and it brings up a list of accounts that have retweeted that tweet.
3. Back out of that and press on 'Favourites'/'Likes' and you **don't** get a list of accounts that have favourited/liked that tweet.

**Comment by mariotaku** [comment]
This is due to Twitter's limitation. It doesn't provide such an API to fetch favorited users to a tweet.

**Comment by mariotaku** [comment]
However this could be done by https://gist.github.com/mariotaku/5465786 .
