### ISSUE TITLE
Changing email address

### ISSUE THREAD

**Issue by aeMKei1** [TwidereProject/Twidere-Android#564]
Hello,
i'm already checking for possible solutions for over an hour but i couldn't find anything. First of all, thank you for a great twitter app. Now i'd like to change my email address in the settings but i can't find it anywhere. Is that even possible with twidere?
Kind regards
- aeMKei1

**Comment by mariotaku** [comment]
No, it's only possible to change email/phone number in official app or website.

**Comment by aeMKei1** [comment]
Thank you for the fast reply.
-aemMKei1
