### ISSUE TITLE
Protect tweets

### ISSUE THREAD

**Issue by aeMKei1** [TwidereProject/Twidere-Android#565]
Hello,
i can't find the option to toggle between protected/unprotected tweets. Is that feature implemented?
Regards
-aeMKei1

**Comment by orithena** [comment]
What exactly do you mean? Assuming you think of protecting/unprotecting your _account_: This feature is not exposed to third-party-clients by the twitter API. "POST account/settings" does not cover it (but you can check the protection status using "GET account/settings") -> see https://dev.twitter.com/rest/reference/post/account/settings and https://dev.twitter.com/rest/reference/get/account/settings
