### ISSUE TITLE
3.1.8 dialog UI regression

### ISSUE THREAD

**Issue by gena01** [TwidereProject/Twidere-Android#573]
With 3.1.8 build that I just installed it seems that there's some weird dialog UI regression. I am using `dark` theme. I noticed in this build that one of the card designs is gone (the one I was using :( ) i started going through the settings screens. For the settings screens that pop a dialog to select an option like: `database limit` or `theme switcher' i get an unreadable dialog. I can see white background and radio and cancel buttons and no readable text.

P.S. Any reason the 'compact card design' option/view is gone in this build?

**Comment by mariotaku** [comment]
Card UI doubles layout code to maintain, so it was removed.

**Comment by gena01** [comment]
content://media/external/file/46121

**Comment by gena01** [comment]
![screenshot_2016-06-27-07-29-54](https://cloud.githubusercontent.com/assets/312125/16379181/fdfef628-3c3d-11e6-8b59-b1770f5b950e.png)

This is what I am seeing. Lg G4 running Android 6.0

**Comment by mariotaku** [comment]
Fixed in dce0739d154206de3655fa1903c1134317bc14d4.
