### ISSUE TITLE
BUG: No notification and no manual refresh possible with DM

### ISSUE THREAD

**Issue by wnabernik** [TwidereProject/Twidere-Android#577]
Similar to #543 there is still the bug that no notifications are shown when a DM is coming in and the auomatic refresh time shows it. It did work before Version 3.1.6.

There is also a 2nd bug: DM will only refresh within the autorefresh time, or (if the setting is set to refresh at start) with a restart of the app. Manual refresh (pulling down) is visually shown, but does nothing.

This happens on different devices (Phone with Android 5.1, Tablet with Android 4.4)

Still happens with Version: 3.1.12

Twitter for Android-API Keys are used.

**Comment by wnabernik** [comment]
Started a older tablet with Twidere 3.1.4.2 and the API Keys of Twitter for Android: here the notify for DM is working!

JFI!

**Comment by mariotaku** [comment]
#709 Should fix this, feel free to open new issue if this still exists.
