### ISSUE TITLE
BUG: Audio notification stops after having 2+ unread notifications 

### ISSUE THREAD

**Issue by wnabernik** [TwidereProject/Twidere-Android#578]
I have the setting that I get audio feedback (special ringtone) when receiving tweets. I discovered the following: No Twidere-Notification area in Android is, Tweet comes in, Notification is shown, and the ringtone is played. If I let the notification now untouched, and a second notification comes in, sometimes the ringtone is played, sometimes not (the notification itself shows correct that there are 2 tweets). But: if you still don't touch the notification, now all audio notifications are gone if tweets come in (the notification itself shows correct that there are more tweets), till you remove the notification - then it starts like written above again.

This happens on different devices (Phone with Android 5.1, Tablet with Android 4.4), with now 3.1.9, but also with the Versions before.

If this is not a bug but a feature, please give us the option to receive audio feedback every time (I don't have always the devices near, and every audio notification reminds to look after - like gmails notify at first mail vs notify always, I prefer always).

Still happens with Version: 3.1.12

Twitter for Android-API Keys are used.

**Comment by mariotaku** [comment]
I guess this is an intended behavior, cause notifications was configured to only alert once.

````java
/**
 * Set this flag if you would only like the sound, vibrate
 * and ticker to be played if the notification is not already showing.
 */
public Builder setOnlyAlertOnce(boolean onlyAlertOnce)
````
