### ISSUE TITLE
[UI] confusing setting window

### ISSUE THREAD

**Issue by kuanyui** [TwidereProject/Twidere-Android#588]
![tmp_12757-screenshot_20160724-222936-812502248](https://cloud.githubusercontent.com/assets/1370070/17084433/119510c4-51f0-11e6-886b-ee7d42514afe.png)
I don't know what to do in this popup window, pressing OK again and again until I finally found this window is scrollable... Possible solutions:
1. Make the window slightly larger.
2. Place the OK button within the bottom of the scroll area.

**Comment by RainbowCrashie** [comment]
I felt the same feeling on adding list timeline tabs. Having to type my own account ID and then waiting to be searched is a little bit dull. I suppose it will be much more easier if my accounts are selectable without searching by default!

**Comment by mariotaku** [comment]
This should be improved now, since OK button is now smaller.
