### ISSUE TITLE
Users favorited this not working

### ISSUE THREAD

**Issue by Riotism** [TwidereProject/Twidere-Android#591]
After pressing on a card for a tweet that has been favorited (or "liked"), there is a counter showing the number of users favorited the tweet. Pressing on the counter does not show which users have favorited the tweet. Pressing on the counter for retweets however does show the users that have retweeted that tweet. Not sure if this relates to #199.

**Comment by Riotism** [comment]
More info: version 3.1.12, from F-droid repo

**Comment by mariotaku** [comment]
It's not possible without official key access, https://gist.github.com/mariotaku/5465786
