### ISSUE TITLE
[Feature Request] Jump to the top

### ISSUE THREAD

**Issue by z751** [TwidereProject/Twidere-Android#593]
A simple jump to the top would be a great feature.

**Comment by orithena** [comment]
Just tap on the active tab header.

Am 4. August 2016 14:35:48 MESZ, schrieb z751 <notifications@github.com>:
>A simple jump to the top would be a great feature.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TwidereProject/Twidere-Android/issues/593

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by z751** [comment]
Thanks.
