### ISSUE TITLE
BUG: Suddenly login and tabs getting lost.

### ISSUE THREAD

**Issue by wnabernik** [TwidereProject/Twidere-Android#594]
I experienced this on my phone (Moto G 1Gen, Android 5.1): suddenly at starting the program (after a couple of weeks normal working) the twitter login infos, and also some settings (most visible: all tabs) getting lost. It happens with Twidere 3.1.12, but happened also in the last 2-3 previous versions - with both login possibilities.

Not all settings are gone: as I use the API-Key of the Twitter-Android client, this key is still there.

Funny fact: the same Twidere version with the same Twitter account works parallel on a Android 4.4.2 tablet, and there this"loss" doesn't happen.

My workaround now is to import all (previous exported) settings, and login into Twitter again every time this happens.

**Comment by TCM1003** [comment]
I have the same bug on my smartphone - moto g1, too. In the last 30 days I got this bug three times. I dont know what to add, cause everything is said by wnabernik.

**Comment by mariotaku** [comment]
I received several reports about moto g database corruption . It seems an OS problem or even hardware problem. I've made accounts stores in system framework, this will prevent Twidere from logged out when bad things on database happened, but tabs and tweets will still be cleared.
