### ISSUE TITLE
No way to check current version

### ISSUE THREAD

**Issue by RenaKunisaki** [TwidereProject/Twidere-Android#595]
I don't see any way to check which version of Twidere I'm currently using from within the app.

(Sorry if this is already reported. Github seems to be missing a search function on mobile...)

**Comment by mariotaku** [comment]
Is version name in 'Settings' - 'About' what you looking for?

**Comment by RenaKunisaki** [comment]
Doh, I didn't realize the menu scrolled. That is what I was looking for, thanks!
