### ISSUE TITLE
Feature Request: select which account retweets

### ISSUE THREAD

**Issue by Rbagman** [TwidereProject/Twidere-Android#597]
This is the option to select which account 'sending' a tweet, but for 'retweeting'.

**Comment by trwnh** [comment]
After using Flamingo for Android I would like to suggest the following:
Upon longpressing RT or favorite or quote, bring up an account selector.

This would properly cap off multiaccount support and make Twidere the best multiaccount app.

**Comment by cyberrubis** [comment]
i second this so hard! 
came for Twidere for your multiaccount merged timeline and stayed for functionality. It could be better in multiaccount area though; this suggestion about RTs, for example. It would be great if we have option to choose the acc we want to RT to, just like in "Write/Compose a tweet" function. Likewise with Follow/unfollow fuction, if we're asked which account (of our accounts) we want to follow/unfollow from.

**Comment by mariotaku** [comment]
Now this could be done by long click on retweet icon.
