### ISSUE TITLE
Not working with API Proxy secured by Let's Encrypt

### ISSUE THREAD

**Issue by lixingcong** [TwidereProject/Twidere-Android#598]
使用Twidere-API-Proxy-Go在自己VPS上面搭建api，nginx反代并加了ssl证书，打开浏览器https网址后也能看见twidere api界面，而手机上不能使用这个api。。

如果改为http就能在手机上使用该api

请问是Twidere for Android不支持let's Encrypt证书吗？

**Comment by mariotaku** [comment]
你Nginx的配置中，ssl_certificate是指向fullchain.pem吗？如果是cert.pem，有可能会出现你所说的问题。
`ssl_certificate /etc/letsencrypt/live/your-domain-name.tld/fullchain.pem;`

**Comment by lixingcong** [comment]
已经把ssl_certificate指向fullchain.pem，手机端添加api还是不行
fullchain.pem的内容是这样获得的。

	wget -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > intermediate.pem
	wget -O - https://letsencrypt.org/certs/isrgrootx1.pem > root.pem
	# 合并
	cat signed.crt intermediate.pem root.pem > full_chained.pem

真是莫明其妙啊~~

**Comment by mariotaku** [comment]
你的设备系统版本是？如果方便可以把域名邮件发给我让我分析证书和错误日志

**Comment by mariotaku** [comment]
另外见这个，你既然用Nginx不妨省略API Proxy直接反向代理： https://github.com/TwidereProject/Twidere-Android/issues/430#issuecomment-191037074

**Comment by lixingcong** [comment]
The API domain was sent to your Gmail. Thanks!

**Comment by lixingcong** [comment]
I turned off HTTP/2 for this virtual server and it works fine.

Thanks!

**Comment by lixingcong** [comment]
<div style="font-family: 'Lucida Grande', 'Segoe UI', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size: 0.9em; overflow-x: hidden; overflow-y: auto; margin: 0px !important; padding: 5px 20px 26px !important; background-color: rgb(255, 255, 255);font-family: 'Hiragino Sans GB', 'Microsoft YaHei', STHeiti, SimSun, 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', 'Segoe UI', AppleSDGothicNeo-Medium, 'Malgun Gothic', Verdana, Tahoma, sans-serif; padding: 20px;padding: 20px; color: rgb(34, 34, 34); font-size: 15px; font-family: 'Roboto Condensed', Tauri, 'Hiragino Sans GB', 'Microsoft YaHei', STHeiti, SimSun, 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', 'Segoe UI', AppleSDGothicNeo-Medium, 'Malgun Gothic', Verdana, Tahoma, sans-serif; line-height: 1.6; -webkit-font-smoothing: antialiased; background: rgb(255, 255, 255);"><p style="margin: 1em 0px; word-wrap: break-word;">另外提一下，宅撩搭建的两种API格式有点不一样</p><table style="padding: 0px; border-collapse: collapse; border-spacing: 0px; margin-bottom: 16px;background-color: rgb(250, 250, 250);">
<thead>
<tr>
<th style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;font-weight: bold;border: 1px solid rgb(230, 230, 230);">版本</th>
<th style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;font-weight: bold;border: 1px solid rgb(230, 230, 230);">API地址格式</th>
</tr>
</thead>
<tbody>
<tr>
<td style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;border: 1px solid rgb(230, 230, 230);"><a href="https://github.com/TwidereProject/Twidere-API-Proxy-Go" style="text-decoration: none; vertical-align: baseline;margin-top: 0px;margin-bottom: 0px;color: rgb(50, 105, 160);">Twidere-API-Proxy-Go</a></td>
<td style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;border: 1px solid rgb(230, 230, 230);"><a href="https://api.xxxxx.rhcloud.com/domain.[DOMAIN]/" style="text-decoration: none; vertical-align: baseline;margin-top: 0px;margin-bottom: 0px;color: rgb(50, 105, 160);">https://api.xxxxx.rhcloud.com/domain.[DOMAIN]/</a></td>
</tr>
<tr style="background-color: rgb(242, 242, 242);">
<td style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;border: 1px solid rgb(230, 230, 230);"><a href="https://github.com/TwidereProject/Twidere-Android/issues/430#issuecomment-191037074" style="text-decoration: none; vertical-align: baseline;margin-top: 0px;margin-bottom: 0px;color: rgb(50, 105, 160);">nginx反代</a></td>
<td style="border: 1px solid rgb(204, 204, 204); margin: 0px; padding: 6px 13px;border: 1px solid rgb(230, 230, 230);"><a href="https://api.awesome.domain.com/domain.[DOMAIN" style="text-decoration: none; vertical-align: baseline;margin-top: 0px;margin-bottom: 0px;color: rgb(50, 105, 160);">https://api.awesome.domain.com/domain.[DOMAIN</a>.]</td>
</tr>
</tbody>
</table><p style="margin: 1em 0px; word-wrap: break-word;">是因为正则表达式不一样吗？</p></div>

**Comment by mariotaku** [comment]
后面那个[DOMAIN.]可能是手滑，总之是不需要点的

Lixingcong <notifications@github.com>于2016年9月14日周三 09:37写道：

**Comment by lixingcong** [comment]
我想使用自签名的证书，可以吗

**Comment by mariotaku** [comment]
@lixingcong 你安装一个CA并用它签发应该就行，HTTPS部分系统说了算

**Comment by lixingcong** [comment]
我按照日志《[chrome58自签证书](https://sqzryang.com/blog/2015/07/09/openssl-since-the-visa-book-with-nginx-bi-directional-SSL-certificate-guarantee/)》签了个证书。

然后我Android 7.1上面安装了CA证书凭据，手机Chrome打开我的API地址是绿锁，可说明系统信任自己CA。可是Twidere还是不信任CA，提示

> java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by lixingcong** [comment]
如果加入一个信任系统中的CA就更好了
