### ISSUE TITLE
App hangs on tweet load

### ISSUE THREAD

**Issue by bennettscience** [TwidereProject/Twidere-Android#599]
Using version 3.1.12 on Google Nexus 5. After long periods of inactivity or on three to four manual refreshes, the app hangs on a manual refresh and needs to be restarted. This happens regardless of how many tweets are requested (tested 10-40 at once) with the refresh.

**Comment by bennettscience** [comment]
Updated to 3.2.3 through the f-droid repository and still seeing the same issue.

**Comment by wnabernik** [comment]
Have the same problem with the update from 3.1.12 to 3.2.4: manual reload via pull down doesn't work - refresh-icon hang in loop, an all refreshes stops till the app gets closed and reopened. Refresh at start work, also the refresh in the choosen interval.

API Key of the official Twitter for Android is in use.
Android Version 5.1

**Comment by ubergeek77** [comment]
I'm glad I'm not the only one. This started happening to me about two weeks ago (August 20th), and it's getting close to a point where Twidere is becoming unusable. I have to constantly close the app and open it. This really doesn't make any sense, since the app is capable of refreshing tweets just fine, even though you have to reopen it first.

I'm using the official Twitter for Android API keys on Android 6.0.

**Comment by bennettscience** [comment]
I've been trying to pay attention to patterns over the last week and I can't find anything discernible. Since updating to 3.2.3 (and currently on 3.2.4, Android 6.0) I only consistently have problems at home on wifi. School wifi seems fine, 4G data seems fine. But at home, the app seems to hang. So, really, I have nothing more than, at times, the app hangs on refresh.

**Comment by Zopieux** [comment]
Can relate too. On cold app boot, tweets load fine whatever the connectivity quality (wifi, LTE or worse). First few manual refreshes work fine. After the app is put in the background and manually refreshed again, the loading animation stays forever – Twidere basically hangs. If yet another refresh motion is attempted while refreshing, the animation does not show up anymore and the app continues to hang.
Only solution is to kill & restart the app.

**Comment by pseudomonas** [comment]
I am still getting this. I can't quite work out what's triggering it. As the others say, killing app and restarting seems to be the only fix. I tried clearing databases while it was in the "stuck" state, but that failed (hung) too - so the problem doesn't seem to be just with fetching data over the network.

**Comment by swilde** [comment]
+1 I have the same problem: twidere is unable to refresh or send tweets until killed and restarted.  This is version 3.7.3 from fdroid.

**Comment by Tedko** [comment]
Will close for now since cant reproduce
