### ISSUE TITLE
Enhancement suggestion: View user's photos.

### ISSUE THREAD

**Issue by madderbomber** [TwidereProject/Twidere-Android#6]
Something the original Twitter app has that I'd love to see in Twidere is the link to view all of a user's photos on their profile page. I'd rather not page through a user's tweets to find the photo posts. That feature would make Twidere perfect for me.

**Comment by mariotaku** [comment]
Available if you use official keys :)
![image](https://cloud.githubusercontent.com/assets/830358/5692179/b5bc8fa4-9925-11e4-9676-e750484dce16.png)
Implemented in previous commits.
