### ISSUE TITLE
[BUG] copy/cut/paste controls broken in retweet window 

### ISSUE THREAD

**Issue by axelsimon** [TwidereProject/Twidere-Android#606]
Hi
As the subject mentions, when entering text in the retweet window/dialog to comment on a tweet being retweeted, one can't copy and paste text entered in the text field because the top bar is blank.

**Comment by axelsimon** [comment]
Can't get a screenshot of it, sorry. Anyway, thanks for looking into it :)

**Comment by mariotaku** [comment]
See #538
