### ISSUE TITLE
New Quoted tweet cuts off characters & inconsistent URL

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#611]
When I view a quoted Tweet in the timeline I can see all 140 characters.

When I click on the Tweet, the last few character are cut off.

If I then click on the Tweet to view it individually, the URL displays as a `t.co` link, not as a `display_url` 

![twidere issue](https://cloud.githubusercontent.com/assets/837136/18542699/0f4521c6-7b24-11e6-96a3-731d0b693aca.png)

Using Tweet ID `776269850188648448`

Latest version from Play Store.

**Comment by mariotaku** [comment]
Does it working now? I tried in latest version and it seems fine.

**Comment by edent** [comment]
The URL display is fixed, but the tweets are still truncated. See https://twitter.com/MarmiteJunction/status/810011941267709952
![tmp_31328-148195964370121576153858](https://cloud.githubusercontent.com/assets/837136/21285211/5bb7ed50-c42a-11e6-9e5f-ad8f92cc2f86.jpg)
![tmp_31328-14819596436830214467388](https://cloud.githubusercontent.com/assets/837136/21285212/5ffa196a-c42a-11e6-8faa-fd6481588a1d.jpg)
![tmp_31328-148195964370011212636356](https://cloud.githubusercontent.com/assets/837136/21285214/638a5446-c42a-11e6-87cf-2c701b9ab0e4.jpg)
