### ISSUE TITLE
Error 150: you cannot send messages to users who are not following you

### ISSUE THREAD

**Issue by axelsimon** [TwidereProject/Twidere-Android#618]
Hi,
I'm worried this has to do with the limits Twitter had decided to artificially impose on third party clients, but I'll report just in case.
After a few tweets in a row (4 to be specific in this case), the next tweet gets refused by Twitter with "Error 150: you cannot send messages to users who are not following you".
To be clear, the message contains no @ mentions.
I'll add a screenshot to s illustrate the issue.

**Comment by axelsimon** [comment]
![tmp_7071-screenshot_2016-09-27-00-26-331027295848](https://cloud.githubusercontent.com/assets/1172256/18854131/96321620-8449-11e6-80b0-def0d033bdf2.png)

**Comment by mariotaku** [comment]
If a tweet starts with D or M, Twitter will interpret them as a direct message.

https://twittercommunity.com/t/cant-tweet-starting-with-certain-letters-words-post-statuses-update-json-interprets-sms-commands/50126/5
