### ISSUE TITLE
Can't open links in email notifications

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#620]
Bear with me, it is probably a Twidere integration issue :)

So when Twitter sends you an email about people favouriting and following or whatever, the email has a link in it.  So I open the Gmail app to read the mail and occasionally want to go to the user profile for example.  Even if I ask my Android 5 to open such a link with Twidere, it will open my default browser (which happens to be Opera), and the URL will change from `https://mobile.twitter.com/…` to something starting with `twitter://` which in turn can, I guess, only be understood by the official Twitter app.

So multiple issues/questions here:
- why doesn't or cannot Twidere get associated with the link in the first place?
- can Twidere learn to hook onto `twitter://` "protocol" and do the right thing?
- (why on Earth is Twitter such an a-hole about third party clients?)

**Comment by mariotaku** [comment]
Most of links can be handled now I believe. If you find some link should be opened in Twidere while it's not, feel free to reopen.
