### ISSUE TITLE
Generic Search tab

### ISSUE THREAD

**Issue by scotty0709** [TwidereProject/Twidere-Android#621]
How do you add a generic search tab? I can't seem to find a way to add a search option which would allow you to click on it, type in what you want to search for i.e. users, hashtags etc and be displayed with a list of results.

To me being able to search Twitter is vital in order to fully utilise it. I would find it strange that something so generic wouldn't be included in this app.

**Comment by orithena** [comment]
Swipe in from the left edge. You'll find the search dialog there.

Am 29. September 2016 23:42:54 MESZ, schrieb scotty0709 <notifications@github.com>:
>How do you add a generic search tab? I can't seem to find a way to add
>a search option which would allow you to click on it, type in what you
>want to search for i.e. users, hashtags etc and be displayed with a
>list of results.
>
>To me being able to search Twitter is vital in order to fully utilise
>it. I would find it strange that something so generic wouldn't be
>included in this app.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TwidereProject/Twidere-Android/issues/621

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jingofett** [comment]
I agree. I don't understand why I can't just add the icon to the top bar to search. Yes I can swipe left to search but I find it's a bit of a hassle after coming from the official Twitter app.

**Comment by mariotaku** [comment]
@jingofett Your request is a bit off-topic, besides, it's not possible to have an action item on a tab bar.

**Comment by jingofett** [comment]
@mariotaku it's the same request as the op...
