### ISSUE TITLE
Unicode smiley user names are shown wrong

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#623]
[This user](https://twitter.com/AaronToponce) is shown like this in Twidere (Android 6.0):
![croppedimage](https://cloud.githubusercontent.com/assets/11966684/19265826/39284e0e-8fa7-11e6-93a5-99f869ac8588.png)

**Comment by orithena** [comment]
Looks correct. Second and fourth letter inverted against current background. Checked with web and official Twitter App with and without Night Mode.

**Comment by rugk** [comment]
Ah, yes the inversions may be the issue. That's why it looks different. So thanks for the hint.
