### ISSUE TITLE
Translation doesn't seem to work

### ISSUE THREAD

**Issue by Torvin** [TwidereProject/Twidere-Android#624]
Hi there! Sorry if it's the wrong place to ask. I've installed Twidere 3.2.7 on CyanogenMod 13 and I cannot see translation for non-English tweets anywhere.  I picked English as the 'Translation Destination' in the settings. Am I missing something?

**Comment by mariotaku** [comment]
Currently translation is only available through official keys.

https://gist.github.com/mariotaku/5465786

**Comment by Torvin** [comment]
Works now, thanks a lot!

**Comment by intrepidOlivia** [comment]
Hey, has this feature been removed? I don't see any translation settings anywhere.

**Comment by imakiro** [comment]
The translation feature seem to be unavailable for the client on F droid, but the google play version doesn't suffer from this. Is there a way to solve this? The key change gist didn't work for me.

**Comment by Torvin** [comment]
@imakiro it stopped working quite [some time ago](https://gist.github.com/mariotaku/5465786#gistcomment-2860255). Some people had success with [xAuth](https://gist.github.com/mariotaku/5465786#gistcomment-2937165), give it a try

**Comment by jvandenbroek** [comment]
I must be really stupid and searched quite a while for it, but I really can't find any option to translate tweets? Other than sharing them with google translate, but that's a bit cumbersome. This has nothing to do with a non working function btw, I just can't find it at all :relaxed:

**Comment by Torvin** [comment]
@jvandenbroek see above. you need to replace your API key with the one from the official app

**Comment by jvandenbroek** [comment]
I did replace it, deleted and readded my account as stated, but this didn't automatically enable the features? Which I didn't expect to happen by just changing the API
.. I suppose when you say it isn't working than changing the API might help, but for me it's just impossible to find this feature in the first place.. 

This client is for me the best already, just missing the translate tweets options others do have.

**Comment by Torvin** [comment]
It should have happen by changing the API key. Try using xAuth option as described in the link above

**Comment by imakiro** [comment]
> 
> 
> It should have happen by changing the API key. Try using xAuth option as described in the link above

After having the issue, even re-logging with xAuth doesn't enable it.
