### ISSUE TITLE
Copy ONLY the Tweet's URL?

### ISSUE THREAD

**Issue by StarMinion** [TwidereProject/Twidere-Android#627]
Twidere seems to allow you to copy the text of a tweet, but not just the URL by itself. If I go to the Share option, it will share the URL but it will copy the text of the tweet along with the URL. I want a way to copy ONLY the URL.  In Twitter's official mobile app you can simply select "Copy link to tweet" and it does that just fine. Is there no way to do that in Twidere, or am I simply overlooking it?

I love Twidere, but this is an option I've really been missing.

**Comment by mariotaku** [comment]
You can select 'Copy Link' in 'Share' menu currently if you are using Marshmallow and above. I'll consider add this to older platforms.
