### ISSUE TITLE
[Feature Request] Configuring to include a prefix/suffix to every tweet

### ISSUE THREAD

**Issue by besim** [TwidereProject/Twidere-Android#631]
I'm using Twidere with a friend which is not really experienced using Twitter. So I'm helping him to organize his Twitter experience with some tweets written by me. But we want to ensure that all tweets are identifiable which are written from him.

So it would be a nice feature to configure Twidere with a function to add a suffix/prefix to every written tweet like "This is a tweet from User XY! /xy" (the suffix is "/xy" here).

**Comment by mariotaku** [comment]
You could use color label feature.

Tap on any user you want, select it's menu and find 'Set color', and you can pick a color for this user. There will be a color strip for their tweet.

**Comment by besim** [comment]
Hi mariotaku,

let me become clearer: I want to add the pre-/suffix to the published tweets automatically to mark up that the posted tweet is from the user directly.

Better example: Use of a company Twitter account: Adding a pre-/suffix automatically gives the opportunity to show up the editor of the correspondent tweet without thinking about marking up every time of tweeting.

**Comment by mariotaku** [comment]
Sorry, I'm closing this issue because its use case is very limited. There're already profile avatar, name, screen name for a tweet, which is enough.
