### ISSUE TITLE
[BUG] Can not tweet a message

### ISSUE THREAD

**Issue by Ariette** [TwidereProject/Twidere-Android#632]
Please excuse my mess English.
I can't tweet a message from several days ago.
When I try to tweet, it shows a blank error message, and saves the message in the draft.

![screenshot_2016-10-28-14-08-57](https://cloud.githubusercontent.com/assets/10518158/19827134/85cce5d0-9dda-11e6-9703-27b2bc041b69.png)
![screenshot_2016-10-28-14-09-04](https://cloud.githubusercontent.com/assets/10518158/19827135/85eee4fa-9dda-11e6-8afa-653e4506953f.png)

At first, I doubted API error because the problem began with the update of Twitter for Android (the official twitter app for android) and I'm using Twidere with custom OAuth (of Twitter for Android).
But still I can do everything (including retweet, favorite, etc.) except tweet, so I thought that may not be a key cause of this problem.

I'm using Android KitKat 4.4.2 (LG Optimus G2)
Thank you.

**Comment by mariotaku** [comment]
Can you tweet other content? You can email me your unsent tweet secretly to help me investigate this issue. mariotaku.lee at gmail.com

**Comment by Ariette** [comment]
At that time, I can not submit any tweets.
Though I tried to solve the problem by re-login my accounts, the problem still occur.

Now I can tweet normally, after I deleted the application completely and reinstalled it.
I think there're something wrong in cached data or like that.
Sorry for bothering you.
