### ISSUE TITLE
[BUG] GNU Social: muting users does not work

### ISSUE THREAD

**Issue by regagain** [TwidereProject/Twidere-Android#633]
Muting users on GNU Social gives a 404 error:

![screenshot_20161028-092756](https://cloud.githubusercontent.com/assets/1060371/19828846/acb5fc9e-9dd1-11e6-9831-c9cfef483228.png)

**Comment by mariotaku** [comment]
Did GS have mute feature? Maybe I should hide this entry for GS services.

**Comment by regagain** [comment]
Ah, actually I don't know, maybe it just doesn't have one! In this case, it would be better to hide this action, as you said.
