### ISSUE TITLE
Use Android's built-in account sync

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#634]
As the title says, I'd like to suggest switching to Android's built-in account sync instead of a constant background process. My device is a low-end phone w/ 1GB RAM, so even a few background tasks tends to make it slow down pretty quickly. AndStatus uses Android's built-in sync, but Twidere has so many more features (plus I like Twidere's UI better).

**Comment by mariotaku** [comment]
I did thought about built-in account manager, but it has a huge drawback - it's name based, which is bad when handling multiple account type, especially same name from different providers.

**Comment by Yowlen** [comment]
I'd think it'd be possible to append the social network onto the name so it doesn't confuse them, wouldn't it? Like "UserName - Twitter" or whatever.

**Comment by mariotaku** [comment]
Hmm, I guess screen_name@provider could do the job. I'll post my thoughts about this feature in this issue and implement in the future maybe.

**Comment by mariotaku** [comment]
For all StatusNet accounts, display screen_name@server.domain.name
For all Twitter accounts, display screen_name@twitter
For all Fanfou accounts, display screen_name@fanfou
