### ISSUE TITLE
[BUG] GNU Social: links provided by the "share" and "open in browser" actions are wrong

### ISSUE THREAD

**Issue by regagain** [TwidereProject/Twidere-Android#635]
They point to Twitter instead of the GNU Social instance.

**Comment by mariotaku** [comment]
Could you provide problematic GS server link? I can't reproduce yet.

**Comment by regagain** [comment]
Hi Mariotaku!

For example, sharing this notice https://loadaverage.org/notice/8927009 gives the following URL:  https://twitter.com/mangeurdenuage/status/8927009
