### ISSUE TITLE
Can't view profile of RT'd user in a "tweets of user" tab

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#637]
I've got a tab showing all tweets of a specific user. Whenever I want to visit the profile of any other user who's been retweeted into this timeline by tapping on that other user's avatar, I get this screen, loading forever:
![tmp_7342-screenshot_2016-11-07-12-26-59 2-1637158479](https://cloud.githubusercontent.com/assets/2767109/20056497/c3d57afa-a4e6-11e6-9942-7bac3623f30d.png)

This problem does persist even when navigating through the thread of the retweeted tweet, tapping tweets and then the avatar... it persists through the whole possible action tree starting at the tab showing the tweets of a specific user (as far as I tested).

Steps to reproduce:
1. Add a tab "tweets of specific user" (e.g. "@kiforbiter", which is a retweet bot)
2. Pick any retweet in that tab and try to visit the retweeted user's profile.

Actual behavior: I see the screen above.
Expected behaviour: I see the retweeted user's profile.

In tabs of a different type, everything's working fine.

Using Twidere 3.2.9 on Nexus 5/Android 5.1.1.

**Comment by mariotaku** [comment]
Seems working in 3.4.22+, feel free to reopen if problem still exists.
