### ISSUE TITLE
Cannot login: Error 404 after completing OAuth

### ISSUE THREAD

**Issue by iomintz** [TwidereProject/Twidere-Android#640]
I'm trying to sign in to Twidere using a custom application with a vanity name, so I have to sign in using OAuth. However, whenever I finish logging in and I click "Authorize App", the browser activity closes after a split second of displaying a 6(?)-digit code of some sort. Then I see the toast: 

"Error while signing in:\
Error 404"

In fact, this happens even when I use the built in API key for Twidere. If it's any help, my account uses SMS 2-factor auth.

**Comment by mariotaku** [comment]
I don't have a valid number for receiving SMS auth code, so I'll put this issue on hold. Please keep this issue open until I fix it or problem disappeared.

**Comment by bmintz** [comment]
It's possible that the bug occurs regardless of account 2FA settings. Not
sure.

**Comment by davux** [comment]
I'm having the same problem, no 2FA involved. My setup:
- Twidere app installed through F-Droid
- Account on loadaverage.org I just created moments ago

**Comment by qirtaiba** [comment]
I also have the same problem with no 2FA on a private GNU Social instance.

**Comment by qirtaiba** [comment]
Checking "No version suffix" in the Edit API dialog seems to fix this problem.

**Comment by bmintz** [comment]
@qirtaiba 
Not for me. I also tried OAuth with and without "use the same URL for OAuth signing" to no avail.

Same for xAuth.

**Comment by Tedko** [comment]
Seems like we dont have this problem now and after we fix the API etc will no longer have this problem.

Also @iomintz @qirtaiba @davux  - Just want to let you know that Twidere will be maintained by community, and supported by [Dimension.im](www.dimension.im) etc. We would like to invite as many community contributor as possible - pls spread the word!
