### ISSUE TITLE
[BUG] Can't edit tab name

### ISSUE THREAD

**Issue by Jiack214** [TwidereProject/Twidere-Android#651]
In the last beta (3.3.15) if I try to change a tab's name and I click on the Save button nothing happen.

**Comment by mariotaku** [comment]
I can't reproduce that, that's your tab type?

**Comment by pcuinty** [comment]
Can confirm this bug for lists. 

Twidere v.3.3.29
Android 4.4.4

**Comment by mariotaku** [comment]
Still can't reproduce. If you have procedure reproducing that, I'll reopen.
