### ISSUE TITLE
App renamed to "mhd fwzy"? 

### ISSUE THREAD

**Issue by edent** [TwidereProject/Twidere-Android#654]
Just installed the latest update via Google Play - 3.3.17.

It has renamed the app "mhd fwzy".

Is this intentional?

![screenshot_20161214-071501](https://cloud.githubusercontent.com/assets/837136/21172999/3c3bf3c2-c1cd-11e6-9af8-07385b4aa8f7.png)
![screenshot_20161214-071107](https://cloud.githubusercontent.com/assets/837136/21173008/470d42ba-c1cd-11e6-892b-2ad7a73e813d.png)

I'm running Android 7.1 via CM14.1 on a Nexus 6.

**Comment by mariotaku** [comment]
So weird and I don't know why. What's your locale?

**Comment by edent** [comment]
EN_GB. 

I've rebooted, but it is still like that. Will try a fresh install.

**Comment by mariotaku** [comment]
@edent It's a incident caused by https://crowdin.com/profile/Vip9300Vip .
This user translated Twidere's app name, I've blocked this user and restored translation. A new update will release soon.

**Comment by edent** [comment]
Latest update fixes everything! 谢谢
