### ISSUE TITLE
List Tabs Losing Recently Loaded Tweets

### ISSUE THREAD

**Issue by morinap** [TwidereProject/Twidere-Android#656]
After an update today to 3.3.23, I'm seeing the following behavior:
* Navigate to a List tab
* Pull down to load recent tweets
* Scroll through tweets to the top
* Leave tab
* Return to tab
* Tab is now at the position it was before I pulled to load recent tweets, and does not have those tweets. Pull to load loads them again (plus any updates since the last time)

Details:
* Device: Google Pixel
* Android Version: 7.1.1
* Twidere Version: 3.3.23

**Comment by mariotaku** [comment]
Fixed in 3.3.24.
