### ISSUE TITLE
Turn OFF auto refresh

### ISSUE THREAD

**Issue by z751** [TwidereProject/Twidere-Android#658]
Recently when I upgraded from version 3.3.16 to 3.3.20 I found that auto refresh mentions and messages HAVE BEEN TURNED ON WITHOUT MY PERMISSION.  

Please disable the automatic enabling of any auto refresh items, as a lot of us do not want our apps connecting to the internet without first attaining a user interaction to initiate it.

THANK YOU!

**Comment by mariotaku** [comment]
I'll add a confirmation for new users in future releases.
