### ISSUE TITLE
Do not open multiple windows

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#662]
When e.g. showing videos or pictures Twidere open a new window. A least this is how it is displayed in the recent apps screen in Android and how it also behaves when e.g. pressing back on such a window when you've previously switched your apps.

These additional screens are heavily annoying as I am constantly irritated by their strange behaviour as I expect one app to have one window and not to open another one for displaying an image.
Thus please concentrate everything in one window if possible.

**Comment by orithena** [comment]
Sorry, I disagree with this proposal. If you're on a slow connection, it's really good that you can wait for the image/video to load in the background while you read on...

**Comment by rugk** [comment]
So that is the sense of it?

If so I have nothing against making it configurable.

**Comment by mariotaku** [comment]
This is configurable, check out Settings - Content - New Document API.

**Comment by orithena** [comment]
Nice, @mariotaku :) ... I forgot that this setting exists.

But may I propose to rename it to "Multitasking"? (Would still be a technical term, but more people would have an idea what it might mean. "New Document API" is only understood by developers...)

**Comment by mariotaku** [comment]
@orithena Great idea! I will use this name from now on.

**Comment by rugk** [comment]
Nice, so I think this issue can be closed.
