### ISSUE TITLE
Tweets not sent

### ISSUE THREAD

**Issue by Ironil** [TwidereProject/Twidere-Android#663]
After upgrading to 3.3.29, I noticed tweets aren't sent at all. A notification toast appears and disappears almost immediately, without any text I would say, and that's all.

Tweets are then stored in drafts, but still can't get sent.

**Comment by mariotaku** [comment]
Is this working on 3.4+ version?

**Comment by Ironil** [comment]
I think the update didn't solve it, but uninstalling the app entirely and reinstalling did. Works fine now, thank you

**Comment by mariotaku** [comment]
OK, if the problem happens on new version, feel free to reopen this issue.
