### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by dominikzogg** [TwidereProject/Twidere-Android#665]
I would love it, if you revert the icon change. I liked the old once, the new once looks very weird on my home screen.

**Comment by mariotaku** [comment]
Twidere needs an icon for both Android and (upcoming iOS) version, also an icon shouldn't be easily changed across major updates. I'll try adjust this icon for a little bit later.

**Comment by dominikzogg** [comment]
@mariotaku i understand, thanks for the fast response and amazing work
