### ISSUE TITLE
ridiculously long delay to play video

### ISSUE THREAD

**Issue by clinty** [TwidereProject/Twidere-Android#666]
When attempting to play [this terrible video](https://twitter.com/iammoshow/status/810882299709550592), Twidere takes ~20 minutes to start playback.

**Comment by orithena** [comment]
Can't reproduce. Took 11 seconds here on WiFi.

Are you sure it isn't your connection? As far as I can see, Twidere waits until the whole video is loaded before starting playback.

**Comment by clinty** [comment]
I was on WiFi without any apparent connection problems.  Android itself was unresponsive for a bit at the beginning.  The progress circle froze for a while in various places throughout the 20 minutes.

**Comment by mariotaku** [comment]
After migrating to ExoPlayer2, this issue should be fixed, also video plays instantly once it begin loading.
