### ISSUE TITLE
Ignores line breaks

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#670]
Here a tweet/qveet from GNUSocial, which is incorrectly displayed in Twidere:

![twiderenolinebreak](https://cloud.githubusercontent.com/assets/11966684/21587672/296b7422-d0df-11e6-9f33-2740098d1d85.png)

original qveet: https://gnusocial.de/notice/8754050
original qveet URL: https://loadaverage.org/notice/9171447

**Comment by mariotaku** [comment]
Confirmed and done! This will be closed automatically when changes pushed to `master` branch.
