### ISSUE TITLE
Missing preview for YouTube links

### ISSUE THREAD

**Issue by wynnsyt** [TwidereProject/Twidere-Android#677]
The tweet itself and profile picture are bugged out as well.

![2017-01-12 05 27 22](https://cloud.githubusercontent.com/assets/2130881/21878142/30782702-d85e-11e6-94cf-bf0197d24131.png)

**Comment by mariotaku** [comment]
Are you using official keys or built in Twidere keys?

**Comment by wynnsyt** [comment]
Twidere keys. If that's causing the glitch how about doing some detection and hiding those tweets if they can't be handle properly?

**Comment by mariotaku** [comment]
@wynnsyt Sure, I filtered those unsupported tweet out in recent commits.
