### ISSUE TITLE
Opening a tweet from Firefox for Android in Twidere results in extra characters

### ISSUE THREAD

**Issue by siccovansas** [TwidereProject/Twidere-Android#678]
When viewing an 'intent' tweet (e.g. like this https://twitter.com/intent/tweet?text=test) in Firefox for Android on your smartphone you can open the tweet in Twidere by click on the Android logo in the address bar:

![screenshot_20170112-152920-2](https://cloud.githubusercontent.com/assets/696839/21893803/f129e5a2-d8dc-11e6-9690-13fd3be2fc08.png)

It will then ask you which app you want to open the URL with (only if you have multiple apps installed which can handle the URL?):

![screenshot_20170112-153721](https://cloud.githubusercontent.com/assets/696839/21894100/4423ac9c-d8de-11e6-972a-a4b8efc85bfe.png)

If you open it with Twidere then ' - ' is added to the tweet. This doesn't happen when I open it using Twitter's own app:

![screenshot_20170112-153738](https://cloud.githubusercontent.com/assets/696839/21894132/5cdbd87c-d8de-11e6-9fb6-5930d4af2510.png)

I think this is due to this line of code: https://github.com/TwidereProject/Twidere-Android/blob/master/twidere.component.common/src/main/java/org/mariotaku/twidere/constant/SharedPreferenceConstants.java#L102

I'm not sure how this should be fixed, but I guess these characters should not appear.

**Comment by siccovansas** [comment]
Thx for the fix! But since the last update the 'Android logo' (as shown in the first image) does not appear anymore for Twidere, so I can't easily open Twitter links in Twidere anymore. I guess this is a bug introduced in this fix?

**Comment by mariotaku** [comment]
I tested with Chrome and it works fine. Maybe Firefox can't handle it correctly?
