### ISSUE TITLE
Searching within a list

### ISSUE THREAD

**Issue by KuroiAghi** [TwidereProject/Twidere-Android#679]
Searching within a list through the query "list:<UserName>/<ListName>" does not work if the list is set as private, even if I'm the owner of the list.
The query does work if the list is set as public.

**Comment by KuroiAghi** [comment]
The query is "list:UserName/ListName".

**Comment by KuroiAghi** [comment]
Searching for tweets from a user with a private account does not work either, even if they allowed me to view tweets.
It seems the search is not done by the connected user's account.

**Comment by mariotaku** [comment]
After some quick test, I found Twitter's "/search/tweets.json" API can't handle protected user properly. That's not Twidere issue. I'll improve that situation for official app keys though.
