### ISSUE TITLE
Tweet Time

### ISSUE THREAD

**Issue by JanvierUK** [TwidereProject/Twidere-Android#680]
Where can you change the settings for displayed tweet time in the home feed, so it is either relative (10 min ago) or absolute (10:30pm)? I'm sure this feature existed in a previous version.

**Comment by orithena** [comment]
In 3.3.29, it's "Additional Settings -> Junkyard -> Show Publish Time" (if I'm translating correctly from german here...)

**Comment by JanvierUK** [comment]
Thank you! No idea why it's in the junkyard, but okay.
