### ISSUE TITLE
Twidere does not honor 10.000 character limit

### ISSUE THREAD

**Issue by asterismo** [TwidereProject/Twidere-Android#681]
Twidere does not honor 10.000 character limit, it shows the stock Twitter 140 limit

**Comment by mariotaku** [comment]
Do you have more information like screenshots?

**Comment by asterismo** [comment]
this is a screenshot, https://jabber.undernet.uy:5281/upload/1f3670c7-9796-497b-ab79-d9a6793baf49/a1fc68cf-548c-4b4f-a192-3f65fcfdf5d3.jpg

**Comment by mariotaku** [comment]
Is 3.3.42 works for you?

**Comment by wynnsyt** [comment]
Both the [FAQ](https://support.twitter.com/articles/13920) and the official web interface still limit the length of a tweet to 140 characters, excluding one @-mentions and one URL. My understanding is that the 10k limit is never implemented.

**Comment by mariotaku** [comment]
@wynnsyt I guess this issue is for GNU social.

**Comment by asterismo** [comment]
BTW, i installed the latest version and selected 'statusnet' type account and now i can send images fine and see the 10k characters limit fine. I'm closing this issue, reopen if you consider otherwise.
