### ISSUE TITLE
[Bug]Interaction won't refresh after changing API Consumer Key

### ISSUE THREAD

**Issue by ryans233** [TwidereProject/Twidere-Android#692]
## Expected behavior
Interaction works as same as usual.

## Actual behavior
Interaction only refresh at first login. After that it never changes when I got a new mention, even I swipe to refresh it manually.

## Steps to reproduce
1. First login with default settings. Everything works fine.
2. Delete current account.
3. Add new account. Change API Consumer Key from default to Twitter for Android on login screen.
4. Save and login. After login success Interaction can be refreshed at first time, but never changes anymore.

## Extra info
I changed API Consumer Key to Twitter for iOS and then click "Clear databases" on Settings - Storage, the problem is gone. Not sure it's a workaround but I'm sure this bug was exist in previous version.

Android version: (version code here)
7.1

Network type:
- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
3.4.2

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:
- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:
- [x] Custom API
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by orithena** [comment]
I remember having that once after upgrading to a new version of Twidere. It went away after I cleared the databases, reinstalled the app and removed thr apps data in Android Settings (or the other way round, can't remember). Could it be some kind of database schema upgrade issue between versions?

**Comment by mariotaku** [comment]
I made some changes for this issue in 3.4.4 version, let's see if it works.

**Comment by ryans233** [comment]
Didn't fix it. But clear databases is a solution.

**Comment by ryans233** [comment]
3.4.9 fixed it. Thx dev.
