### ISSUE TITLE
Can't add to lists - Twitter says it's over limit 

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#694]
## Expected behavior
When I click "Add to lists" on a profile page I expect my lists to open, so I can add the current profile to one or many lists. 

## Actual behavior
Twidere displays a notification that tells me Twitter is over limit when trying to load lists.

## Steps to reproduce
Open profile. Klick on 3 dots. Choose Add to lists.

## Extra info

Android version: 6.0.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.4.2

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
How many lists do you have?

**Comment by diesocke** [comment]
23 own lists plus 5 lists I follow. Is there a limit?

**Comment by mariotaku** [comment]
@diesocke Twitter has their rate limit, usually you can only call 'add user to a list' function 15 times per 15 minutes window, the same to removing a user, so it will easily reach their limit. However you can try this: https://gist.github.com/mariotaku/5465786

**Comment by diesocke** [comment]
I've deleted and unfollowed some lists of lower priority. Now it works again as expected.
