### ISSUE TITLE
Tablet UI - Multiple columns problem

### ISSUE THREAD

**Issue by Jiack214** [TwidereProject/Twidere-Android#695]
(Maybe a duplicate of #682, sorry)
In the latest versions on 10-inch tablet are diplayed more than one column in portrait orientation.
And this make the app unusable. (In my case are displayed 2.1 columns and this make all small and very uncomfortable).
Is it possible to add an option to set the number of columns?

**Comment by mariotaku** [comment]
I'll provide an option later to turn on/off tablet UI, switch between single-column and multi-column, let's track working progress in #682 .
