### ISSUE TITLE
new tweets are positioned top down

### ISSUE THREAD

**Issue by tbeitter** [TwidereProject/Twidere-Android#70]
Until the current build new tweets were positioned above mz current position. With the current build that was changed. After loading a new set of messages I now have to scroll down and  find the last one I read and have then to read upwards. That is weird and time consuming. Please switch back to position new tweets above the current position. Same for new tweets via 'load more'.

Thanks!

**Comment by mariotaku** [comment]
have you try check 'Read from bottom' from content settings?

**Comment by Hodlok** [comment]
I tried to change that setting but it didn't solve the problem for me

**Comment by aelmahmoudy** [comment]
@mariotaku changing that settings does solve the problem when refreshing tweets when the twidere activity is in the foreground.
Yet when tweets are refreshed in the background, then I open Twidere UI, I get positioned in the top !

**Comment by aelmahmoudy** [comment]
Update: just tested with today's commit, and the issue is still the same as my last comment

**Comment by yamatt** [comment]
Ticked it and it seems to have solved the problem when I manually reload although not when my stream is reloaded when I post a new tweet.

Could we also have a better description or title than 'Read from bottom', something like: 'Jump to latest tweet when refreshing.' to make it more obvious what the intention of that option is. I looked for it in the options and skipped straight over it.

**Comment by mariotaku** [comment]
Great Idea, I will use a better description.

**Comment by aelmahmoudy** [comment]
Shouldn't this be closed ?
