### ISSUE TITLE
Back button not working correctly

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#71]
When opening a link from a tweet with an external app, eg Firefox, and then using the back button to get back to Twidere the tweet with the link opens. After using back again one would expect to get to the feed, but Twidere closes(crashes?) and one gets to the least recently used app.

**Comment by mariotaku** [comment]
Twidere will go back to previously used app when pressing 'Back' button, if you need to stay in Twidere, press 'Navigate Up' in toolbar instead.
