### ISSUE TITLE
Login panel is reload after click "Login"

### ISSUE THREAD

**Issue by JakubMajcher** [TwidereProject/Twidere-Android#711]
After one of last update (when logotype was changed, few weeks ago) i was started app and i was logout (before this update i was logon). I was trying to login, but I had a problem with that. I was waiting for new versions, but after that, bug still there is. Reinstall of app doesn't working.

How bug is looking: When I'm starting app I have a login panel and then I'm trying login but I can't. When I'm typing username and password and click on "Login", app is reload and i'm still on login panel. Of course i'm typing correct data. I'm trying with any of connecting setting.

I'm not using 2FA on Twitter.

Android version: 6.0.1 (CM13)

App version: 3.4.28 (and few earlier)

Build variant:

- [X] F-Droid

Micro-blogging service:

- [X] Twitter

**Comment by mariotaku** [comment]
Reload? Do you mean force close?

**Comment by JakubMajcher** [comment]
I mean that the view where is login panel is loaded once again.

**Comment by pseudomonas** [comment]
I have something similar - I'd expect Twidere to spawn a browser window to deal with the oAuth stuff but instead I just get a perpetual "loading" indicator. Is it possible that Twidere is trying to use a proprietary Google control for the browser (which by default CyanogenMod lacks)?

**Comment by JakubMajcher** [comment]
The probled disappered after last update.
