### ISSUE TITLE
Position in timeline lost

### ISSUE THREAD

**Issue by fanf** [TwidereProject/Twidere-Android#714]
I'm on twidere 3.4.22 and since a recent (no more than a couple of months) update, twidere is loosing the position in the timeline. 

That happens when I have a lot of unread tweets, and perhaps reach some resource limit (cache, db?). But when the position his lost, the new false remembered position is rather random. Never 0, nor the number of tweet I get in one call. Sometimes a couple of tens, sometimes several hundred. 

Before, I think that news tweets were no more charged. But for sure, my timeline position was kept even if I was 3 days behind in read tweets. 

## Expected behavior

Expected behavior would be to never ever loose timeline position. 
Perhaps having a configuration option to ask the user if, when the cache is full (if that's the cause), he prefers to stop getting new tweet (keep reminded position) or slide toward newer tweets, new reminded position becoming the last available tweet of the new window. 

## Steps to reproduce

Not sure. Have a several hundreds unread tweets. Close twidere (it happens also at random time, but more systematically if I reopen twidere after some time) 

## Extra info

Android version: (version code here) 
6.0.1

Network type: any (WiFi, 4g,3g)

App version: (version code here)
3.4.22 

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [x] Official twitter keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
I guess this issue is already known. We have snapshot build 3.4.28, could you try this version? You can find apk here in releases section.

**Comment by fanf** [comment]
Thanks, will try, I didn't found a matching bug report before opening this
one, sorry!

**Comment by mariotaku** [comment]
No problem, if you encountered any issues, feel free to leave comment here.

**Comment by fanf** [comment]
So, I installed twidere 2.4.29 from the github release page and still have
the bug.

It seems that it happens when tweets are cleaned up. In place of cleaning
up only tweets orders than the current read position, it seems to clean up
everything and so loose the position in timeline.

It also seems that tweets older than current position are rarely reclaimed.
In fact, it seems (but I'm not sure, I don't have log to analyze) that they
are not deleted at all until everything is cleaned up.

Maybe relevant : I'm on periodic refers (15min), refresh on start and after
sending tweet. Compatibility mode unchecked. Get 100 tweets. Cache 500mo.
Db size 250. Read from bottom. Remember position. Hope it helps.


Le 19 févr. 2017 4:47 PM, "Mariotaku" <notifications@github.com> a écrit :

No problem, if you encountered any issues, feel free to leave comment here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TwidereProject/Twidere-Android/issues/714#issuecomment-280927453>,
or mute the thread

**Comment by fanf** [comment]
Some more information: if after a position lost I scroll back to my old position, the position is not lost again. It let me thing that the problem is not link to the number of tweets between the position and "now", but :
- maybe the number of unread tweets (that number is low after a position is lost)
- the total number of tweets, including old tweets older that current position so maybe cache/etc (that number is lower after position is lost since the tweets between old position and oldest loaded tweet are not loaded again). 

Hope it helps... 
Also, let me know if I can enable some log/debug option to help.

**Comment by andy-twosticks** [comment]
I'm also on 2.4.29. And I'm also getting this behaviour. A lot.

When I appear to see it:

    * when switching between home timeline on my two different accounts. happens every time?
    * when the screen goes off!  I put my phone down for a second? Intermittent.

What I see:

tab icon shows, say, 200 unread tweets. i scroll up. number jumps to say, 6, and it becomes apparent that the timeline was in the wrong position and the number wrong.

Like the OP, I have, of course, got "read from bottom" set.

**Comment by mariotaku** [comment]
I guess this was fixed in recent versions, feel free to reopen if issue persists.

**Comment by BobSoft3000** [comment]
I just subscribed to this issue a few days ago as I was experiencing it too (or maybe its slightly different issue for me?).  I’m on 3.4.48 (twidere-google-release.apk from github); Android 7.1.1 (LineageOS); Galaxy S3 (I9300).

I only have one twitter account but subscribe to (9) private lists in separate tabs.  Whenever I switch to look at one of the list-tabs in recent releases, it always appears blank, automatically refreshes, and shows the most recent tweet instead of last viewed, so I’m always losing track.  With previous versions I was happy to manually refresh each tab, and it would stay in position with newer tweets above (ready to scroll up/look at).

I’ve been through all my settings, and everything looks normal to me (read from bottom; remember position; no auto-refresh; no streaming; no refresh on start; no refresh after tweet sent; db size limit 500).  I don’t look at my timeline often, so it can get very large (many 100s of unread tweets) so I guessed it was due to the tweet database getting too big and auto-deleting entries.  Maybe it’s my own fault for wanting to store >500 tweets over all my tabs?

I’m currently going through the github release pages (fdroid & google versions) trying to find when exactly this started…  Will update when I find anything.  So far, I've tested 3.4.2-fdroid and it looks ok - the list-tabs don't lose their positions or refresh automatically.

Do you need any more info? Is this a different problem to the original one?

Twidere is a really great twitter client.  Thanks very much for making it!

**Comment by fanf** [comment]
I upgraded to twidere 3.5.32, and I'm experiencing an awful regression on
that one after a period of broken-but-bearable (not sure what release it
was, around end of February).

The behavior is now, when I have a long unread history (order: bottom ==
older), after some threshold the oldest entries are lost (and the cursor is
"correctly" at the oldest) . If I download again older entries (and again
and again), then any refresh started by twidere (for ex. by switching to
another app and coming back) loose all newly downloaded entries.

Perhaps it's due to some cache filled up, but in that case, I don't want
new entries until I read older one. I woukd like to have a bar with "cache
full, ô new entries dl until older are read. Remove 500 oldest now?"

This bug is very frustrating for my usage workflow, but in all cases,
thanks for twidere, it's a very solid app.

Le 29 mars 2017 18:56, "BobSoft3000" <notifications@github.com> a écrit :

I just subscribed to this issue a few days ago as I was experiencing it too
(or maybe its slightly different issue for me?). I’m on 3.4.48
(twidere-google-release.apk from github); Android 7.1.1 (LineageOS); Galaxy
S3 (I9300).

I only have one twitter account but subscribe to (9) private lists in
separate tabs. Whenever I switch to look at one of the list-tabs in recent
releases, it always appears blank, automatically refreshes, and shows the
most recent tweet instead of last viewed, so I’m always losing track. With
previous versions I was happy to manually refresh each tab, and it would
stay in position with newer tweets above (ready to scroll up/look at).

I’ve been through all my settings, and everything looks normal to me (read
from bottom; remember position; no auto-refresh; no streaming; no refresh
on start; no refresh after tweet sent; db size limit 500). I don’t look at
my timeline often, so it can get very large (many 100s of unread tweets) so
I guessed it was due to the tweet database getting too big and
auto-deleting entries. Maybe it’s my own fault for wanting to store >500
tweets over all my tabs?

I’m currently going through the github release pages (fdroid & google
versions) trying to find when exactly this started… Will update when I find
anything. So far, I've tested 3.4.2-fdroid and it looks ok - the list-tabs
don't lose their positions or refresh automatically.

Do you need any more info? Is this a different problem to the original one?

Twidere is a really great twitter client. Thanks very much for making it!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TwidereProject/Twidere-Android/issues/714#issuecomment-290153316>,
or mute the thread
