### ISSUE TITLE
Ability to open a tweet in the author feed

### ISSUE THREAD

**Issue by matclab** [TwidereProject/Twidere-Android#715]
Often people retweet another tweet as an invitation to read the whole story written by the original author.
However it seems not possible to open the referenced tweet directly in the author feed (at the location of the tweet).

It would be a very nice feature to have (I hope I didn't miss it).

**Comment by matclab** [comment]
Whow… Yhanks a lot !

**Comment by matclab** [comment]
I tried with twidere 3.6, and did not find how to open the retweeted tweet in the original author feed.

Can you please give me a hint on how to process ?

**Comment by mariotaku** [comment]
By 'retweet', do you mean quote retweet or retweet without any comments?
