### ISSUE TITLE
Support animated GIFs

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#72]
The current image view only shows the first frame for an animated GIF.

**Comment by mariotaku** [comment]
Have you try newest beta builds? https://github.com/TwidereProject/Twidere-Android/releases
This should work.

**Comment by mkody** [comment]
I can confirm it doesn't work. It loads the `tweet_video_thumb` image instead.

**Comment by mariotaku** [comment]
@mkody https://gist.github.com/mariotaku/5465786 you may need to use official key. vine support is available only for official clients

**Comment by mkody** [comment]
@mariotaku Hmm... You should still be able to get the "GIFs" (I hate their idea to convert this to mp4) from any apps: 
https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070

**Comment by mariotaku** [comment]
@mkody sweet! I'll implement soon.

**Comment by mariotaku** [comment]
implemented.
