### ISSUE TITLE
[Bug/Regression] Notifications No Longer Work

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#722]
The notifications revamp has essentially made it so that none of the notifications are working now. Whether the app is in the foreground and I trigger a manual sync or it's just doing a background sync, no notifications for any of the 3 categories appear whatsoever.

## Extra info

Android version: 5.1.1
App version: 3.4.31
Build variant: Google
Micro-blogging service: Twitter
App settings:
- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor]
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
Is this version work for you? https://github.com/TwidereProject/Twidere-Android/releases/tag/3.4.32

Haven't uploaded yet since it has some compatibility issues with pre-lollipop devices.

**Comment by Yowlen** [comment]
Well, after immediately opening it, I see the Home tab's notification works. So, yeah, seems this bug has already been addressed. 😆

I'll keep an eye out for the other two just to be sure and will create a new issue report if they're still missing. Thanks for the prompt reply and keep up the good work. I hope those 4.x issues get worked out soon. My Kit Kat tablet needs this update, too, if you catch my drift. 😉 In fact, if you need the help, I'd be happy to play around with it to try to narrow down the cause.
