### ISSUE TITLE
Mentions Order Gets Messed Up When Replying To Self

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#723]
## Expected behavior
The original order gets kept.

## Actual behavior
The first & second handles get switched.

## Steps to reproduce
Example: I reply to @.SomeUser1, who mentions @.SomeUser2 and @.SomeUser3 in their tweet. This part works like it's supposed to, and it's laid out in the compose window as "@.SomeUser1 @.SomeUser2 @.SomeUser3 ". After sending the tweet, I reply to the tweet I just sent to add onto it. This is where things go wrong. The compose window flips @.SomeUser1 & @.SomeUser2 when adding my user handle to the list. It becomes "@.Me @.SomeUser2 @.SomeUser1 @.SomeUser3 " instead of keeping the previous structure and adding my handle to the end.

In fact, I'd like to suggest Twitter-like behavior also gets added for this situation. Twitter only adds my handle when there's no other handles present.

## Extra info

Android version: Tested on both 4.4.2 & 5.1.1 

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: All known versions I've used since I started using Twidere almost a year ago.

Build variant: Both, as I've switched between Google & F-Droid on occasion.

- [X] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [X] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys (with and without)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

And my apologies for not reporting sooner. Whenever I remember this bug, I either don't have the time to report it, or I get sidetracked with the tweet thread. XD

**Comment by Yowlen** [comment]
I'm not sure why this was marked as "fixed" & closed. It's not fixed, though the order was changed. Now, using my initial example as a reference, @.SomeUser1 gets pushed to the very end just before my handle, giving a list like "@.SomeUser2 @.SomeUser3 @.SomeUser1 @.Me".

**Comment by mariotaku** [comment]
Seems mentions were sorted alphabetically by mistake, I'll investigate.

**Comment by mariotaku** [comment]
Now mentions are not sorted alphabetically anymore, they sorted by order they appeared in a tweet instead.

**Comment by Yowlen** [comment]
So, I assume this was in the 3.4.48 update that was released the same day? If so, it's not fixed because as of that version, it's still mixing up the order.

**Comment by mariotaku** [comment]
@Yowlen This fix was pushed **after** 3.4.48, and will be available in next release.
