### ISSUE TITLE
Could I proxy video?

### ISSUE THREAD

**Issue by lixingcong** [TwidereProject/Twidere-Android#725]
Thumbor is useful to proxy pictures. And what about videos?

How could I proxy video as simple as using thumbor? I don't want to turn my shadowsocks on again.

Thanks.

**Comment by mariotaku** [comment]
There's no server implementation found for video proxying. I'd be glad to add support if there's one.

**Comment by lixingcong** [comment]
With the help of nginx, I want to proxy video as easily as proxy Twidere API.

The link of twitter videos look like this:

	https://video.twimg.com/ext_tw_video/812376079151276032/pu/vid/24000/27000/640x360/gmg-pVBmMJ2Kq9H9.ts


I want to set-up a virtual server to proxy video.

	server {
		server_name proxy.yyy.com;
		
		listen 443 ssl;
		ssl_certificate /tmp/fullchain.pem;
		ssl_certificate_key /tmp/domain.key;
		
		resolver 8.8.8.8;
		
		location ~ ^/ext_tw_video/(.*) {
			proxy_pass  https://video.twimg.com/$1$is_args$args;
			proxy_cookie_domain twitter.com $server_name;
		}
	}

Could I add this video proxy like Twidere API proxy?

**Comment by mariotaku** [comment]
I got a better idea, that is to make reverse proxy work for all network requests. I'll implement in future versions.

**Comment by mariotaku** [comment]
Config example

````
    location ~ ^/(http|https)/([^/]+)/(.*) {
        resolver 8.8.8.8;
        proxy_pass $1://$2/$3$is_args$args;
        proxy_cookie_domain ~.* $server_name;
        proxy_cookie_path $uri /$2/uri;
        proxy_buffering off; # Turn off buffer in order to get stream as-is
        proxy_set_header Host $2;
        proxy_http_version 1.1; # This was necessary!!!
    }
````

**Comment by lixingcong** [comment]
Thanks very much.

One more question: How to set up on client side?

- Proxy type: reverse proxy
- Proxy host: 443
- Proxy username: use nginx http-simple-auth usrname
- Proxy passwd: use nginx http-simple-auth pwd

Am I right?

**Comment by mariotaku** [comment]
No, please refer to documentation below:

# Supported patterns

* `[SCHEME]`: E.g. `http` or `https`
* `[HOST]`: Host address
* `[PORT]`: Port number
* `[AUTHORITY]`: `[HOST]`:`[PORT]` or `[HOST]` if port is default. Colon **will be** URL encoded
* `[PATH]`: Raw path part, **without leading slash**
* `[/PATH]`: Raw path part, **with leading slash**
* `[PATH_ENCODED]`: Path, **will be** URL encoded again
* `[QUERY]`: Raw query part
* `[?QUERY]`: Raw query part, with `?` prefix
* `[QUERY_ENCODED]`: Raw query part, **will be** URL encoded again
* `[FRAGMENT]`: Raw fragment part
* `[#FRAGMENT]`: Raw fragment part, with `#` prefix
* `[FRAGMENT_ENCODED]`: Raw fragment part, **will be** URL encoded again
* `[URL_ENCODED]`: URL Encoded `url` itself
* `[URL_BASE64]`: Base64 Encoded `url` itself

# Null values
`[PATH]`, `[/PATH]`, `[QUERY]`, `[?QUERY]`, `[FRAGMENT]`, `[#FRAGMENT]` will be empty when
it's null, values and base64-encoded will be string `"null"`.

A valid format might looks like

`https://proxy.com/[SCHEME]/[AUTHORITY]/[PATH][?QUERY][#FRAGMENT]`,

A request

`https://example.com:8080/path?query=value#fragment`

Will be transformed to

`https://proxy.com/https/example.com%3A8080/path?query=value#fragment`

**Comment by mariotaku** [comment]
@lixingcong https://github.com/mariotaku/twidere/wiki/Reverse-Proxy permalink of this document will be located here.

P.S. Twidere will send basic `Proxy-Authorization` header to your proxy server, you can handle on your server side.

**Comment by lixingcong** [comment]
Thank you I successfully proxy all network reqeusts.

But all medias in Twidere tmeline cannot be previewed. I have to click on the image or video to show or play.

这是一个timeline媒体可以预览正常的配置，没有配置Proxy Auth
```
server {
	server_name proxy.yyy.com;
	
	listen 443 http2 ssl;
	ssl_certificate /tmp/fullchain.pem;
	ssl_certificate_key /tmp/domain.key;
	
	location ~ ^/(http|https)/([^/]+)/(.*) {
          resolver 8.8.8.8;
          proxy_pass $1://$2/$3$is_args$args;
          proxy_cookie_domain ~.* $server_name;
          proxy_cookie_path $uri /$2/uri;
          proxy_buffering off; # Turn off buffer in order to get stream as-is
          proxy_set_header Host $2;
          proxy_http_version 1.1; # This was necessary!!!
          proxy_ssl_server_name on; # It may solve HTTP ERROR 502
      }
}
```

但是把```listen 443 http2 ssl```改为```listen 443 ssl```就没法在timeline预览了，手动点击媒体就能打开图片或者视频。

[UPDATE: 2017-4-12]
经查，确认是Thumbor的问题。Thumbor的URL字符串是已经转义的，与reversed proxy for Twidere的构造字符串冲突。

**Comment by mariotaku** [comment]
@lixingcong I forgot to mention, seems it can't cooperate well with Thumbor.

**Comment by lixingcong** [comment]
How to make Proxy Authorization?

Should I install squid? Is that something looks like the graph below?

```
Twidere ---> Internet(GFW) ---> squid ---> nginx(if auth ok)
```

**Comment by mariotaku** [comment]
@lixingcong No, `Proxy-Authorization` isn't a standard for reverse proxies, maybe you'll need to configure nginx to consume this header, or use some classic way like add a random path like proxy.com/R4ND0M/[SCHEME]/...
