### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by zenimchan** [TwidereProject/Twidere-Android#727]
刚更新的beta版本闪退用不了，机型，黑莓Priv

Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
This was fixed in 3.4.39.
