### ISSUE TITLE
Add support to open a list timeline directly

### ISSUE THREAD

**Issue by franciscojunior** [TwidereProject/Twidere-Android#728]
Hello! I just started to use you app and I'm enjoying it very much.

I use lists a lot and one feature I would like to see is the ability to open an specific list timeline directly.

It would be awesome if I could create shortcuts in my homescreen for specific lists. My own, subscribed, or even from other users.

I think this is a very nice feature and would make Twidere the best twitter client.

As a reference, the only other twitter client which does exactly that is Twicca. 

Thanks in advance!

**Comment by franciscojunior** [comment]
After playing more with the app, I notice that I can add a list of my own, or of others in the Tabs -> List Timeline configuration option. This alleviates a lot the issue I'm requesting. Even so, I think the ability to create a shortcut to open a list directly would be very welcome!

**Comment by mariotaku** [comment]
Yep, this will be added in the future.

**Comment by franciscojunior** [comment]
Awesome!! I'm looking forward to try it! Thanks in advance for considering
it.


Em 16 de mar de 2017 1:31 AM, "Mariotaku" <notifications@github.com>
escreveu:

**Comment by franciscojunior** [comment]
Hello, guys! Thank you for implementing this functionality so fast! I joined the beta program as you suggested in a tweet reply and could create a link to a list directly. 

I tried and I liked it very much! 

I noticed that when you try to add a list, after you select an account, you have to choose a user. Would it be possible to show the account's list below the search for the user? This way I could add a link to my own lists directly instead of having to search for my own user to get them.

If you want, I can open a new issue about that.

Again, thank you very much for such fast response to implement this feature and keep up the good work! 

You rock!

**Comment by mariotaku** [comment]
@franciscojunior Feel free to create a new issue about this, it's a good idea.

**Comment by franciscojunior** [comment]
> @franciscojunior Feel free to create a new issue about this, it's a good idea.

Done
