### ISSUE TITLE
We can't create new posts on GNU social

### ISSUE THREAD

**Issue by moshpirit** [TwidereProject/Twidere-Android#73]
I've just seen you moved the GH project to here. That's a feature the GS users asked you a few months ago, with the last version we can't add our accounts and it's sort of annoying to stay always with an old version.

#### Update:
**Loging in:**

- https://server.domain/api
- Basic
- "No suffix" enabled

**Deleting the limit characters**:
Press \*#\*#8943373#\*#*

**The problem**:
Now we're logged in but we can't post new messages, just replies.

**Comment by moshpirit** [comment]
@mariotaku I am so sorry for insist here but if I could help in any way... (I'm not a developer, but maybe I could find someone who could help you or something)

**Comment by mariotaku** [comment]
@moshpirit Well, I'd like to implement that but I don't even know which GNU social instance is most popular and suitable for my development, and no api documentation given.

**Comment by moshpirit** [comment]
The most important instances are in gnu.io/social and I'll ask for the API :-) thanks for the answer and your support!

**Comment by moshpirit** [comment]
API: http://skilledtests.com/wiki/Twitter-compatible_API

**Comment by moshpirit** [comment]
Please, if you need any other thing, let me know! I'd really like to have my GNU social account on Twidere!

**Comment by Turbito** [comment]
I would appreciate the integration of gnu social with twidere :)

**Comment by LumenTeun** [comment]
GNU Social actually sort of works, kind of, a little bit, almost. After trying for about an hour I managed to add my account by changing the API to [that of my GNU Social instance](http://social.munsking.com/api/) and the authentication method to basic, as per [the instructions on F-Droid](https://f-droid.org/repository/browse/?fdfilter=twidere&fdid=org.mariotaku.twidere).

For some reason, the app crashes every time I refresh it, I'll try to dig into my logcat and find out what's wrong. Upon restarting it, the new statuses are available though, so it's not a huge problem. Posting stuff works as well, but the 140 character limit of Twitter is still there.

**Comment by moshpirit** [comment]
Looks like only some instances allow that option, I've been trying it with quitter.es/status.vinilox.eu/quitter.se and I always get a connection error.

**Comment by postblue** [comment]
I'm having the same issue and don't understand how it could be possible for @LumenTeun to make it work;

1. Removed the old version installed.
2. Install the latest available on the Play Store (0.3.0 dev 2015-05-01).
3. Launch the application.
4. Configure later.
5. Tap on "Accounts".
6. Click on the cross in top right.
7. Click on the router icon in top right.
8. Change authentication method to Basic.
9. Change API to https://herds.eu/api
10. Select "no suffix" and validate.
![screenshot_2015-05-21-14-38-15](https://cloud.githubusercontent.com/assets/696539/7748862/c8b3404e-ffc8-11e4-98b2-e619c18f9b75.png)

11. Insert login credentials.
12. Connect.
13. Network / connection error.
![screenshot_2015-05-21-14-49-09](https://cloud.githubusercontent.com/assets/696539/7748870/d232cafe-ffc8-11e4-95ec-0f9583e24a4b.png)

**Comment by LumenTeun** [comment]
@postblue Yeah, I don't know why it suddenly decided to work for me; I'd encountered the same error as you for about an hour before it did. Hopefully someone decides to take a proper look at this.

**Comment by zackp30** [comment]
Any news on this?

**Comment by moshpirit** [comment]
No, I think there's no news about this issue.

**Comment by zackp30** [comment]
:(

**Comment by rogerbraun** [comment]
Just as an added piece of information, I was successful in adding my gnu social account on my own server to Twidere by the method mentioned above. Nothing would show up, though, until I uninstalled and reinstalled Twidere.

**Comment by moshpirit** [comment]
So, now you can't access to your GS account, right?

**Comment by rogerbraun** [comment]
No, everything works now.

**Comment by zackp30** [comment]
@rogerbraun did you have to change any GNU Social settings? I get a 401 even with the correct username/password.

**Comment by rogerbraun** [comment]
@zackp30 No, I changed nothing. This is a GNU Social instance set up from yesterdays master.zip with the Twitter bridge activated, otherwise nothing special.

**Comment by zackp30** [comment]
I see, thanks!

**Comment by sinozzuke** [comment]
I can use Twidere only  responsing a previous mention, but can't write a new mens. Is there any fix for that?

**Comment by Bretos** [comment]
I can confirm what @sinozzuke is saying, same here! Is there any chance of fixing that?

**Comment by moshpirit** [comment]
OK, I finally could log in by selecting:

- https://server.domain/api
- Basic
- "No suffix" enabled

Please, confirm that you guys can also do it in order to close the issue and create some tutorial on my blog.

**Comment by Bretos** [comment]
Logging in was never the problem. After adding an account can you post a
new tweet, that is not a reply to a different one?
7 lis 2015 16:16 "moshpirit" <notifications@github.com> napisał(a):

**Comment by moshpirit** [comment]
Hmm you're right!

**Comment by ahstro** [comment]
@Bretos Logging in was the problem for a little bit. But yeah, posting is a problem as well.

**Comment by Taknamay** [comment]
I also had trouble logging in with Twidere until now. I can reply to posts, even my own posts, but cannot create new ones.

I don't know much about GNU Social's API, but this sounds really weird :S

**Comment by smalltock** [comment]
Same here

**Comment by mariotaku** [comment]
Hi everyone, I found the reason to this issue, will fix in next commit.

**Comment by moshpirit** [comment]
\o/ weeeeee thank you so much!!! I'll try to donate you some money! :)

**Comment by postblue** [comment]
THANK YOU @mariotaku !

**Comment by realramnit** [comment]
so AWESOME!!! @mariotaku when will we see the new version on PlayStore/F-Droid?

**Comment by lupa18** [comment]
+1

**Comment by asterismo** [comment]
I'm having the same issue, it would be awesome to be able to post on GNU-Social from Twidere client, can't wait, cheers!

**Comment by moshpirit** [comment]
What version are you using? On F-droid the last version (0.3.0-dev-135) was released in November.

**Comment by asterismo** [comment]
Yes i'm using that version, and i have this issue. I can configure the GS account, fetch statuses and reshare them but not posting new ones.

**Comment by moshpirit** [comment]
Then you should wait to the next version (the one that fixes it) gets released there. If it's already released on Google Play,maybe it's an error from F-droid to be reported

**Comment by postblue** [comment]
@moshpirit @asterismo You can find compiled APK's [here](https://github.com/TwidereProject/Twidere-Android/releases).

**Comment by moshpirit** [comment]
Thanks! downloaded! :)

**Comment by asterismo** [comment]
Its working now! Let me know when available on fdroid

**Comment by asterismo** [comment]
Well, i cannot attach images on pots. :(

**Comment by lupa18** [comment]
Hello, here I'm with 0.3.0-dev-135 and having the same problem, when trying to post, got an error 404

**Comment by postblue** [comment]
@asterismo It depends on the version of GNU social you're running. @mmn did some changes yesterday about it.

**Comment by asterismo** [comment]
i'm running GNU Social 1.2.0-beta3. Here is a screenshot of another bug, which is that i cannot mark posts as favorite (red heart), it marks but tells about error 500.
![screenshot_2016-01-16-19-35-31](https://cloud.githubusercontent.com/assets/5679035/12376055/b16d0d2a-bcbf-11e5-833a-4f027763ad35.png)

**Comment by mariotaku** [comment]
@asterismo It works fine on quitter.se. Let's move this issue to another issue #290.

**Comment by lupa18** [comment]
Ok, but what versions of GS works with? Because I sill having this problem as I wrote before.

**Comment by pizzamaker** [comment]
I'm still having this issue for my quitter.se account, using the latest version from F-Droid: Version 0.3.0-dev-135

**Comment by postblue** [comment]
@pizzamaker Use one here, FDroid versions are not yet up-to-date. https://github.com/TwidereProject/Twidere-Android/releases
