### ISSUE TITLE
Unread group messages are in notifications, DMs empty and can't be refreshed

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#730]
## Expected behavior
Display DMs, especially group messages. Display DMs after refresh, when empty
## Actual behavior
Notifications for unread group messages are displayed. On click Twidere doesn't open. When manually navigating to Messages the tab is empty. After refresh messages are still empty. Neither personal DMs nor group messages are displayed.

## Steps to reproduce
As given above 

## Extra info

Android version: (version code here) 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here) 3.4.39

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Is the account that has notifications enabled in 'Accounts' list?

**Comment by diesocke** [comment]
All accounts are activated in the Accounts tab. I hadn't noticed that there now is an extra tab for streaming under preferences. This hadn't been activated for the relevant accounts before. Now that it is, it doesn't change the described behaviour, however.

**Comment by mariotaku** [comment]
Notification is now yet clickable indeed, and will be fixed soon.

**Comment by diesocke** [comment]
Thanks. How come the Messages tab is empty? Before group messages were supported I could see the messages. Still I recently had opened another issue about missing notifications for DMs. As those are now implemented this seems a step in the wanted direction. Seeing nothing there however is suboptimal. :-)

**Comment by mariotaku** [comment]
Can you check your DM tab configuration? Settings - Tabs, it should be 'Activated accounts'

**Comment by diesocke** [comment]
The chosen account there is the one that is supposed to get DMs I want to read.

**Comment by diesocke** [comment]
Strange: I've added a Messages tab for another account. This works, even group messages for this account work as expected. So I deleted the messages tab for my main account, restarted and readded the tab. It is no longer empty, but the only displayed content is an empty chat called Messages. On reception this one produced a notification with the comment "null (0)" IIRC.

**Comment by mariotaku** [comment]
This is really strange. Maybe we need to dig further. Let's communicate by
email. I'll send you a debug build so you can provide more information. My
email is twidere.project@gmail.com

**Comment by diesocke** [comment]
E-mail is sent. Funny detail: My second account was recently added to the same group DM list. Now every time I get a message there Twidere shows a second notification with "null". Thus, Twidere keeps receiving DMs for my main account, but doesn't display them.

**Comment by diesocke** [comment]
Deleting my main account and re-adding it after restart did the job. Now all DMs are displayed properly. Thanks.
