### ISSUE TITLE
[Feature request] Show account when retweeting/quoting/faving,  change account in same tab

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#734]
When I open a tweet to retweethe,  quote or fav it,  I have to make sure with which account I'm doing this. This depends on the tab I'm in, what I forget sometimes.  This results in RTs by the wrong account.

I've seen a twitter client that does shows a solution: Falcon Pro not only display the account used when opening a tweet. It also allows to change the account to use for RTs/Quotes/Favs in the same tab. I'd like to see this in Twidere as well.

**Comment by mariotaku** [comment]
Have you noticed the color strip on the right of a tweet/dialog? It indicates which account you're currently using. Also by long-clicking on retweet/fav button you'll be able to select account.

**Comment by diesocke** [comment]
Hadn't noticed this before. However, Twidere crashes when selecting an account this way reproducably. Also this selection is not available when opening the tweet. There I have to choose "open with account" to change accounts.

**Comment by diesocke** [comment]
When #738 is fixed, I'm fine.
