### ISSUE TITLE
Cannot open Twidere on DM notification

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#735]
## Expected behavior

A tap on the notification of a DM should open Twidere and show the DM.

## Actual behavior

Tapping on the notification does not work/does not do anything. I can only swipe it away.

## Steps to reproduce

1. Let someone sent you a DM.
2. Try to tap on the notification shown by Twidere.

## Extra info

Android version: 6.0

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.4.39

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
This was known in #730 and fixed in f3ebbc3.
