### ISSUE TITLE
Inconsistent order of menu items

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#736]
In tweet view, the dot-dot-dot menu ends with:
Open in browser
Copy link
Open with account

When looking at a profile, the end of the menu is:
Open with account
Open in browser

I regularly click the wrong one because of the inconsistency.  I'm not sure which one would be better, but it would be nice if all the menus with those two open functions would display in the same order.

**Comment by mariotaku** [comment]
Done!
