### ISSUE TITLE
Show account's lists below user search when adding Quick Action shortcut

### ISSUE THREAD

**Issue by franciscojunior** [TwidereProject/Twidere-Android#737]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

After selecting an account, its lists should be shown below the search field. This way, you don't need to look for the account's user to get her lists.  See https://github.com/TwidereProject/Twidere-Android/issues/728#issuecomment-289836659 

## Actual behavior

After selecting an account, only a search field is shown to look for a user which lists should be shown.

## Steps to reproduce

1. Select to add a quick action shortcut
2. Select an account

## Extra info

Android version: (version code here)

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: (version code here)
3.4.48

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Done! Now when adding a list timeline, it will show your lists first.
