### ISSUE TITLE
Crash when selecting different account to open tweet

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#738]
## Expected behavior
Tweet opens with selected account

## Actual behavior
Twidere crashes

## Steps to reproduce
Longpress retweet icon underneath tweet, select account

## Extra info

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.4.44

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Could you provide logcat? `adb logcat -a AndroidRuntime` Will print out all information needed.
