### ISSUE TITLE
Lists are being reloaded when starting or resuming the application

### ISSUE THREAD

**Issue by franciscojunior** [TwidereProject/Twidere-Android#739]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

As I have remember last position on, the list should be at the same position since the last time I opened the list tab before leaving the application. Also, as I have automatic update off, it shouldn't be refreshed.

## Actual behavior

Some times, it works as expected, but most of the time, when I open the list tab, it is refreshed and my position is lost, going to the most recent tweet. 

## Steps to reproduce

1. Add a list tab.
2. Close the application or go to other applications which use memory enough to cause the system to remove the activity from memory (which means, destroy the activity)
3. Return to the application and select the tab with the list

## Extra info

I started to notice that with latest beta version 3.4.48. The previous stable version worked ok and I never noticed this odd behavior.

Android version: (version code here)

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Confirmed. It's a bug in data caching.
