### ISSUE TITLE
Instant (Accelerated) Back to Top

### ISSUE THREAD

**Issue by wynnsyt** [TwidereProject/Twidere-Android#74]
If you go far enough down a list, it takes several seconds to slowly scroll back to the latest tweet after pressing the tab icon. Don't see why this is not instantaneous.
Animation is fun to have but this feels unnecessary.

**Comment by Sohalt** [comment]
+1
The animation is really annoying and wasn't there in previous versions of Twidere.
If the animation should be kept for whatever reasons, I would suggest that double tapping the tab icon moves to the top instantaneously.

**Comment by mariotaku** [comment]
fixed in cf03196923d5d67b0fc3f6219b816e4d579b1d43, now timeline scrolls to top instantly.
