### ISSUE TITLE
[Bug] Replying to self quotes tweet

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#742]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Replying to self should just add the reply.

## Actual behavior
Instead, it adds a link to the tweet it's replying to, essentially quoting it without notifying the user it's doing so until after it gets sent.

## Steps to reproduce
Make a tweet. Reply to the tweet.
Note that this doesn't occur in replies to others, only to replies to self.

## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.4.49

Build variant:

- [X] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
Have you removed your own @ username? It's a behavior change cause by Twitter's new 140 characters reply.

**Comment by Yowlen** [comment]
Yes, I've tried with & without usernames in the reply. Same result. And it's probably worth noting that Twitter's mobile site, as well as Twidere 3.4.48 doesn't do this.

**Comment by mariotaku** [comment]
I've tried replying to self without removing @ username, it sent as a reply without problem, in addition, my own @ username was not appearing in that reply.

**Comment by Yowlen** [comment]
![screenshot_2017-04-03-11-10-36](https://cloud.githubusercontent.com/assets/17078692/24616211/73c0bcdc-185e-11e7-8177-392373aacf3a.png)
![screenshot_2017-04-03-11-11-01](https://cloud.githubusercontent.com/assets/17078692/24616222/7a837c62-185e-11e7-84d5-4f61003f071d.png)
![screenshot_2017-04-03-11-11-14](https://cloud.githubusercontent.com/assets/17078692/24616227/7e7d70de-185e-11e7-929e-748b3260ee96.png)

**Comment by mariotaku** [comment]
@Yowlen Yeah I know, it's an intended behavior. I'll add an explanation under composing text for that case.

**Comment by Yowlen** [comment]
But why is it intended? It completely ruins my threading, and doesn't happen on the mobile site. Is Twitter really getting this shitty that they're screwing with their users like this?

**Comment by mariotaku** [comment]
@Yowlen Yes it is. Technically speaking new form of reply doesn't contains any @ mentions, all users mentioned before will be mentioned in this reply by default.

The worst thing is, you can't remove original tweet user's mention without losing `in_reply_to` data anymore, so the only way removing tweet user's @ username without losing context is to use quote tweet.

However, as you can see, existing mentions in a reply doesn't count in 140 characters. Also when you mentioning your self, seems Twitter will automatically remove @ username for you.

**Comment by mariotaku** [comment]
@Yowlen So, my suggestion is, when replying to your own tweet, there's no need to remove @ mention anymore, since it doesn't count in 140 characters, and doesn't show @ username at the beginning of the tweet actually.

**Comment by kathakatze** [comment]
I totally agree, quoting the tweet instead of simply replying is unexpected and nearly always undesired. This breaks the usual self-reply threading and makes it even more confusing than twitter's new reply style. In most cases I've seen nobody else is involved, so the problem doesn't exist for these tweet/reply chains.

I noticed this earlier when I wanted to add another tweet to the one I had just posted and got exactly what I wanted (a reply to the first tweet, without any mentions), plus an undesired quote.

**Comment by mariotaku** [comment]
@Yowlen Yep - this affects all replies, Twidere actually uses some magic text parsing method to mimic old style mentions, though Twitter's new reply doesn't use @ mentions at all.

**Comment by mariotaku** [comment]
@kathakatze When tweet user removed, you'll be able to see a label indicating this reply will be sent as a quote in next version.

**Comment by Yowlen** [comment]
@mariotaku Thanks again. I suppose this is yet more proof Twitter has no idea what they're doing when it comes to coding. lol

**Comment by mariotaku** [comment]
@Yowlen I don't know what they are think about, all I can do is trying hard to bring good old Twitter experience back.

**Comment by Yowlen** [comment]
Haha. Fair enough. Keep up the good work. This app is a godsend - especially for cheap devices like mine. 1GB of RAM means Twitter's official app would eat up way too many resources given its bloat, and the mobile site is clunky and slow, at best - even on lightweight browsers like Lightning.

**Comment by kathakatze** [comment]
@mariotaku I see. Just tested again with the current beta, I'll have to keep "@​user" and it works as I originally intended. I didn't know you put in that magic, just did the same as always and got confused.

I've been thinking about how to make it a bit more obvious what gets sent and what is just "virtual" text, but didn't come up with an idea.

**Comment by Yowlen** [comment]
@kathakatze Maybe a little background shading for the affected text? A sort of "highlight" effect using a different shade of grey than the window itself?

**Comment by mariotaku** [comment]
@Yowlen @kathakatze Made @ mentions a little bit grey. I guess this will help people distinguish.
![image](https://cloud.githubusercontent.com/assets/830358/24643475/d0809414-1940-11e7-9dd2-9b7c8c999acc.png)
