### ISSUE TITLE
[Feature Request] Option for a dropdown menu in place of the scrolling top bar

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#743]
Title pretty much says it. When there's a lot of custom tabs for lists & stuff, the top bar can get pretty cluttered. A dropdown menu would help keep it clean.

**Comment by mariotaku** [comment]
Most pages can be accessed via side menu, if you really have that much page, performance may be impacted a lot. I'll keep current tab design untouched.
