### ISSUE TITLE
Notification shown multiple times

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#749]
## Expected behavior

Show notification once.

## Actual behavior

The notification ("1 new interaction…") is shown and when I hide it (e.g. when I swipe it away or open Twidere to view the notification) it is shown again after some time.

## Steps to reproduce

1. Get many notification.
2. Last notification should be a reply from a user to your account.
3. Open notifications/view them. All of them are hidden, but the last notification is shown again (see above).

## Extra info

Android version: 6 (CM 13)

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.4.48

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
You expect notifications not showing twice after cleared right? I made some change, which may help

**Comment by rugk** [comment]
Yes.

**Comment by mariotaku** [comment]
@rugk new version's coming out, is this version solved your problem?
