### ISSUE TITLE
Streaming: poll tweets are broken

### ISSUE THREAD

**Issue by kathakatze** [TwidereProject/Twidere-Android#751]
## Expected behavior
Tweets with polls have their little poll symbol in the timeline, tapping them shows the actual poll.
## Actual behavior
Everything works as expected with manual refreshs or when loading tweets by any other means like via a user's profile or by opening a reply, but not in the timeline while streaming. Retweeted tweets with polls don't show the poll when being opened (if they were received by streaming).
## Steps to reproduce
- enable streaming
- receive a tweet with a poll
- receive a retweeted poll tweet
## Extra info
Probably closely related to #746.

App version: 3.4.54

**Comment by mariotaku** [comment]
This is not possible because Twitter UserStream doesn't provide poll data, even with official keys.

**Comment by kathakatze** [comment]
So it's either streaming or usable poll tweets? Not even an indication that a tweet has an attached poll? Oh silly twitter, more or less enforcing streaming while breaking it *facepalm*. I shouldn't be surprised, but I still am every time stuff like this shows up.

Is there a way to manually reload a tweet to get the poll without having to search it in the user's tweets on their profile or opening a reply and then the original tweet? That's especially annoying for retweeted poll tweets, because the retweet doesn't ever have the poll (let me guess: that's another twitter API weirdness).
