### ISSUE TITLE
GPLv3 violation of your work

### ISSUE THREAD

**Issue by grawlinson** [TwidereProject/Twidere-Android#752]
@FlorentAnders has cloned your work, and is profiting from IAP/advertisements. There is no GPLv3 source made available, which is a violation of that license.

https://github.com/FlorentAnders/Spreadsheet
https://play.google.com/store/apps/details?id=com.fa.spreadsheet

EDIT: He has also cloned other applications as shown [here](https://github.com/tootsuite/mastodon/issues/1105)

**Comment by mariotaku** [comment]
@grawlinson Thanks, I'll report violation immediately.

**Comment by orithena** [comment]
I just opened the Spreadsheet 1.1.3 APK file and ran dex2jar on the .dex files ... he didn't even bother to refactor your class names. Also, I found classes by @vanita5 (Twittnuker fork) in there.

**Comment by mariotaku** [comment]
@orithena Hope a DMCA takedown I just sent would help.

**Comment by vanita5** [comment]
@orithena Thanks for the notice. I will also fill out a DMCA request. Hope this helps.

**Comment by FlorentAnders** [comment]
I just removed the app from the Play Store. Please excuse what I did, I was not aware of the fact that I needed to publish the source code.

**Comment by FlorentAnders** [comment]
As I already said in other posts, I have fully removed any access to the app by publishing an update that breaks the app, removed every part of the Play Store entry, unpublished the app as a whole and disabled ad serving to it. Please excuse what I did, as I said, I was not aware.

**Comment by mariotaku** [comment]
@FlorentAnders I'll close this issue as it should be solved. Remember, do the right thing.

**Comment by FlorentAnders** [comment]
Do you think that my account is going to get locked? Greetings.

**Comment by mariotaku** [comment]
@FlorentAnders I'm not sure what account you're referring to, since you've removed violations, other apps developer by you should be fine.

**Comment by FlorentAnders** [comment]
@mariotaku Yes, I meant my Google Play account. Okay then.
