### ISSUE TITLE
No automatic update since mid-late March

### ISSUE THREAD

**Issue by LukasThyWalls** [TwidereProject/Twidere-Android#753]
## Expected behavior
I have configured Twidere to automatic update every 15 minutes, Home, Interactions and DMs. Until ~version 3.4.41 or 3.4.44~ (See https://github.com/TwidereProject/Twidere-Android/issues/753#issuecomment-294294133) mid-late March it was doing that without problems.

## Actual behavior
Since ~version 3.4.41 or 3.4.44~ mid-late March (i can't remember exactly day) the automatic update in Home, Interactions and DMs doesn't happens. I can update manually without problems and use Twitter as normal.

## Steps to reproduce
I clean the data, uninstall, an install the last version available in f-droid (3.4.48).
I logged in and, instead using stored Twidere Settings, i only change from default settings to update every 15 minutes the tabs Home, Interactions and DMs.
For testing purposes, i use too "Keep Screen On" App to keep the screen on and look if Twidere updates at any moment.
More than 45 minutes before, there is no updates. I manually update Twidere and shows me tweets from 41 minutes ago and less, and a DM test from 22 minutes ago.

## Extra info
My phone has options for keep every app alive or not when the screen is off. Since i use Twidere in this phone, the app is always configured there to keep alive and autostart app. I think this doesn't matter because i tested Twidere with the screen always on and i have the problem too.
I tested some configurations: Battery safe mode on/off, compatibility mode for Android 5.0+ on/off, using custom twitter API Keys, without any change of behaviour.

Android version: Android 6.0 in Huawei P8 Lite with EMUI 4.0. 

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.4.48. The problem exists since ~3.4.41-3.4.44~ (See https://github.com/TwidereProject/Twidere-Android/issues/753#issuecomment-294294133) mid-late March.

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
I just published 3.5.0, let's see if this helps.
It changed the way it receives network change events.

**Comment by LukasThyWalls** [comment]
Tested 3.5.0 without any luck.

I'm going to downgrade to identify exactly the last working build, and the first non-working.

Tell me about to share other useful information. Thanks in advance.

**Comment by regagain** [comment]
I have the same issue. I am also using imported settings. Can we please reopen this issue?

**Comment by mariotaku** [comment]
Still not able to reproduce at all, is it because I use a Nexus device without any root or modifications?

**Comment by mariotaku** [comment]
@regagain I'll reopen this as you wish, if I can reproduce, I'll try investigate and fix ASAP.

**Comment by LukasThyWalls** [comment]
I tried to see if with an old imported settings file (from March 24) something happens, but now it works too with that old settings too. The imported settings doesn't matter for me.

Twidere has been going update without problem since yesterday, except 40 minutes this afternoon, i don't know why, but now is doing it again. Maybe for using other apps and touching other things, i suppose, but i will be stay tuned.

The only trick i can say it has do anything is cleaning the Twidere app data. Quick steps i do yesterday:
1) Uninstall all Twidere versions. 
2) Install 3.5.0 or lastest (the one i installed yesterday was 3.5.0, i see now there is 3.5.1). 
3) Configure for your account and update tabs to see your timelines. 
4) Clean Twidere app data.
5) Enter Twidere, the account is still there but any other thing is in default configuration. Configured Twidere like you want, and see if it autoupdates (for me, it did).
I don't know if this make sense or not... i didn't do anything else different in the others tests.

**Comment by regagain** [comment]
What to you mean by `Clean Twidere app data.`?

**Comment by mariotaku** [comment]
I guess it's more like Twidere being killed for some reason, then it cannot
refresh messages. Have you tried to remove Twidere from recents and see
what happens?

regagain <notifications@github.com>于2017年4月9日周日 02:41写道：

**Comment by regagain** [comment]
Hi Mariotaku,

First, thank you for getting back to me so quickly.

The instructions provided by @LukasThyWalls do not fix it for me, even with a fresh installation I get this issue, so you might be right.
I don't know how to remove Twidere from recents, can you explain? :$

I'm using a Nexus 6P / Nougat 7.1.2 / Copperhead.

**Comment by mariotaku** [comment]
@regagain Remove from recents means open your device's "Overview" screen and swipe to remove it from recents.

**Comment by regagain** [comment]
Ok! Still getting the same issue when removing the app from recents.

**Comment by LukasThyWalls** [comment]
> What to you mean by Clean Twidere app data.?

Settings -> Applications -> Twidere -> Clean Data
(Some modified UIs have other additional steps, but more or less should be the same)

Only for pointing out, i always clear all the apps from recent almost every time, and Twidere is still working. I think the no-autoupdate gap from yesterday was the low battery feature, so no problem at the moment.

**Comment by regagain** [comment]
Thanks. I'm still getting the same issue after this.

**Comment by LukasThyWalls** [comment]
Since yesterday, Twidere is not autoupdate itself again. I don't change anything from it, only yesterday i change 3.5.0 with 3.5.11 without any results today.

I manually update all the tweets today at 12:00am without problems, and since that, i didn't do anything. There isn't any updates since then.

I have the phone connected to computer via ADB and i can put logcat since 18:23, when i opened Twidere and at 18:24 i put _Keep Screen On App_ to keep the screen on. I haven't touched anything since then:

```
1|shell@hwALE-H:/ $ ps | grep mariotaku
u0_a335   12790 2505  1641676 71020 SyS_epoll_ 0000000000 S org.mariotaku.twidere
shell@hwALE-H:/ $ logcat | grep 12790
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
04-12 18:23:23.719 12790 12790 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorD
rawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would hav
e incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-12 18:23:23.735 12790 12790 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
04-12 18:23:23.804 12790 12790 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
04-12 18:23:24.272 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:23:24.284 12790 12790 E HAL     : load: id=gralloc != hmi->id=gralloc
04-12 18:23:24.524 12790 23146 I OpenGLRenderer: Initialized EGL, version 1.4
04-12 18:23:24.529 12790 23146 W OpenGLRenderer: load: so=/system/lib64/libhwuibp.so
04-12 18:23:24.529 12790 23146 W OpenGLRenderer: dlopen failed: library "/system/lib64/libhwuibp.so" not found
04-12 18:23:24.529 12790 23146 W OpenGLRenderer: Initialize Binary Program Cache: Load Failed
04-12 18:23:24.529 12790 23146 E HAL     : load: id=gralloc != hmi->id=gralloc
04-12 18:23:24.701 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:23:24.702 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:23:26.490 12790 12790 I Choreographer: Skipped 106 frames!  The application may be doing too much work on its main thread.
04-12 18:23:27.041 12790 12790 I Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
04-12 18:23:34.284 12790 23145 I FA      : Tag Manager is not found and thus will not be used
04-12 18:24:10.248 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:24:10.249 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:30:58.350 12790 15775 I System  : core_booster, getBoosterConfig = false
04-12 18:30:58.409 12790 15775 I System  : core_booster, getBoosterConfig = false
04-12 18:41:09.582 12790 12816 I System  : core_booster, getBoosterConfig = false
04-12 18:41:09.637 12790 12816 I System  : core_booster, getBoosterConfig = false
04-12 18:51:30.812 12790 15752 I System  : core_booster, getBoosterConfig = false
04-12 18:51:30.882 12790 15752 I System  : core_booster, getBoosterConfig = false
04-12 18:57:59.273 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 18:57:59.274 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 19:01:51.965 12790 15785 I System  : core_booster, getBoosterConfig = false
04-12 19:01:52.026 12790 15785 I System  : core_booster, getBoosterConfig = false
04-12 19:07:33.547 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 19:07:33.548 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
```

I do a manual update

```
04-12 19:09:27.012 12790 12790 I HwSecImmHelper: mSecurityInputMethodService is null
04-12 19:09:27.447 12790 15766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:27.517 12790 15766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.417 12790 32766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.426 12790   301 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.440 12790 32766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.448 12790   300 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.453 12790   301 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.470 12790   302 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.475 12790   300 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.478 12790   303 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.479 12790   305 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.483 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.485 12790   306 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.497 12790   302 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.503 12790   305 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.505 12790   303 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.510 12790   306 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.511 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:28.577 12790 12799 I art     : Background sticky concurrent mark sweep GC freed 71154(3MB) AllocSpace objects, 5(272KB) LOS objects, 5% fr
ee, 23MB/24MB, paused 6.483ms total 85.880ms
04-12 19:09:28.700 12790 12799 I art     : Background sticky concurrent mark sweep GC freed 44589(2MB) AllocSpace objects, 1(68KB) LOS objects, 0% fre
e, 24MB/24MB, paused 9.926ms total 75.598ms
04-12 19:09:29.237 12790 15766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:29.401 12790 15766 I System  : core_booster, getBoosterConfig = false
04-12 19:09:29.404 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:29.488 12790 12799 I art     : Background sticky concurrent mark sweep GC freed 40868(6MB) AllocSpace objects, 9(372KB) LOS objects, 11% f
ree, 36MB/41MB, paused 6.405ms total 49.788ms
04-12 19:09:29.523 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:29.722 12790 12799 I art     : Background partial concurrent mark sweep GC freed 18410(1868KB) AllocSpace objects, 31(14MB) LOS objects, 3
7% free, 26MB/42MB, paused 5.842ms total 76.817ms
04-12 19:09:30.593 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:30.620 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:30.710 12790   300 I System  : core_booster, getBoosterConfig = false
04-12 19:09:30.758 12790   300 I System  : core_booster, getBoosterConfig = false
04-12 19:09:31.190 12790   303 I System  : core_booster, getBoosterConfig = false
04-12 19:09:31.274 12790   303 I System  : core_booster, getBoosterConfig = false
04-12 19:09:31.577 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:31.635 12790   304 I System  : core_booster, getBoosterConfig = false
04-12 19:09:31.999 12790   305 W Bitmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
04-12 19:09:32.003 12790   305 W Bitmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
```

Now i will disconect the phone, clean data and use again my stored settings to set up Twidere again and see if something changes.

I hope this helps.

**Comment by LukasThyWalls** [comment]
I will update the subject by all the test i do in the last days, because i can't say the problem is there "since a concrete version" because i tested some older versions (Mostly 3.3.35 and 3.4.29) and with them i don't have automatic updates, but i have manual updates. When these versions are the newest i'm sure Twidere was working with autoupdates in my phone, so, there is something else related with Twitter, Options or the phone itself doing Twidere no autoupdate well since mid-late March.

**Comment by LukasThyWalls** [comment]
Yesterday i think i got the trick.

I was testing every option in Twidere, if anyone do something different, and now i have autoupdates, and yesterday i made Twidere to go to don't have autoupdates to have autoupdates, twice.

This is how i reproduce the problem:
- I made a clear install of Twidere (or Clean app data of actual installation)
- I configured it, but i haven't autoupdates (like always, i have manual updates without problem)
- In configuration -> Automatic Updates, switch off and switch on autoupdates for your account. (I normally tap in my account and use the main switch above all the others)
- Now, i have autoupdates in Twidere.

I can do a logcat (like the one above https://github.com/TwidereProject/Twidere-Android/issues/753#issuecomment-293646040) if it's needed.

PD.: I do this with Twidere 3.5.18
PD. 2: When this is done, maybe we can talk about how erratic is Twidere with a 5 minutes autoupdate option. Maybe have some relation with the problem, or the limitations with the API, but sometimes updates every 5 minutes, or 7, or 10, or 12, o what it wants. I'm seeing the tweets in official twitter app at the same time to test it and i see this behaviour. Anyway, i never use 5 minutes, i always use 15 minutes, and then seems ok.

**Comment by mariotaku** [comment]
@LukasThyWalls YOU ARE AWESOME! I found the root cause of this bug. Will fix soon!

**Comment by LukasThyWalls** [comment]
I do another test with 3.5.29: exporting settings, cleaning the app data and importing the settings again. It seems to be working now, i don't need to switch off/on the main autoupdates button (only need to switch on the Home tab updates like said in this issue https://github.com/TwidereProject/Twidere-Android/issues/788) but the interactions was updating alone without doing anything and when i switched on the home updates it updated alone without any manual interaction, and are still doing it.

**Comment by LukasThyWalls** [comment]
I know this is closed, but until i check a little bit more and create a new one, you should check if could be a similar or related problem to this when it comes from save mode (the Twidere option, it seems the mobile doesn't have anything build-in, but who knows) or when the mobile comes from a period without internet connection (and maybe forgetting to switch off wifi connection in that period without any wifi around, i don't know if that matters). I'm not really sure, but in the last two weeks i have two similar issues to this bug, and maybe are related to that, but i'm not sure and those seems difficult to test.
