### ISSUE TITLE
GNU social: Add support for public and network timeline

### ISSUE THREAD

**Issue by uvok** [TwidereProject/Twidere-Android#758]
I would like to add a tab with the public timeline of a GNU social instance (/main/public) and maybe even the network one (/main/all). This doesn't seem to be possible with the current version.

**Comment by jasonmacduffie** [comment]
Did you support public (/main/public) and network (/main/all), or only public? Right now I only see the public timeline.

**Comment by mariotaku** [comment]
@jasonmacduffie Does they have such API for network timeline?

**Comment by jasonmacduffie** [comment]
I believe the location is

statuses/networkpublic_timeline

For example I see it here:

https://quitter.is/api/statuses/networkpublic_timeline.json
