### ISSUE TITLE
Actionbar Color in Select Mode

### ISSUE THREAD

**Issue by wynnsyt** [TwidereProject/Twidere-Android#76]
It sucks to be stuck in KitKat but look at this..

![2015-03-18 09 50 35](https://cloud.githubusercontent.com/assets/2130881/6710053/ff635008-cdb8-11e4-9dd8-e4970db57a1b.png)

**Comment by mariotaku** [comment]
confirmed, really annoying

**Comment by mariotaku** [comment]
does it work?

**Comment by wynnsyt** [comment]
Confirmed as fixed. Thanks.
