### ISSUE TITLE
[Bug] Replying to self receives different treatment with mentions

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#761]
First off, a rather meta complaint: Why is reply-to-self handled with a completely different subroutine than other replys in Twidere? I can tell there's separate rules for reply-to-self due to how many issues I have had in the past few months just in that area that didn't affect other replies. There's no reason to treat them differently on the composition end afaik unless Twitter's own API has different areas to send the requests to. The receiving end is different, obviously, since the notifications timeline needs to filter them out. If the composition does indeed require a complete set of separate rules for replying to self, I would enjoy an explanation as to why since it currently makes no sense to me.

But anyway, the issue I'm having this time is that I noticed you fixed the removal of users from the list by just removing the @ name in the compose box. However, as of 3.5.16, it doesn't apply this to reply-to-self compositions. In fact, it does the opposite. It actually replies with all users mentioned getting ADDED IN ADDITION TO the list of participants, which means it counts it towards the tweet character limit and will end up duplicating the participants list in Twidere and show the handles within the tweet itself on the official channels.

Edited to shorten the rant on the meta issue for the past few bug reports I've filed. I repeat myself a lot, unfortunately, kinda like the meta issue itself. Sorry. 😅

**Comment by mariotaku** [comment]
This is confirmed as a bug. I'll take a look to it.

**Comment by mariotaku** [comment]
Done! This was released in beta channel, hope it works without problem.
