### ISSUE TITLE
[Bug] Profile Banner Not Scaled Properly

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#762]
Just noticed this, so I'm not sure how long it's been bugged, nor whether it's ever worked properly.
The profile pic is zoomed in by about 2x. Tested on both portrait & landscape w/ the same result.
Screenshots for comparison:
![Mobile site](https://cloud.githubusercontent.com/assets/17078692/25071208/345c5a30-227f-11e7-9048-165a9feee396.png)
![Twidere](https://cloud.githubusercontent.com/assets/17078692/25071215/4ec87caa-227f-11e7-99c8-05f505dc3e8a.png)

**Comment by mariotaku** [comment]
Old way always load 2:1 banner, causes banner to be cropped twice when aspect ratio is larger than 2:1. I improved this in ea924cb. When you're in landscape mode, the profile banner will load that one with 3:1 aspect ratio.
