### ISSUE TITLE
FileNotFoundException when sending images

### ISSUE THREAD

**Issue by Nervengift** [TwidereProject/Twidere-Android#763]
Since updating every time I try to send a tweet with pictures attached, I get a toast saying `java.io.FileNotFoundException: No such file or directory`

## Expected behavior
I can send a tweet with image(s) attached

## Actual behavior
sending fails

## Steps to reproduce
* write new tweet
* attach an image
* press the send button

## Extra info

Android version: 7.0

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.5.16

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [X] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
Done! New version will be available in beta channel very soon.

**Comment by Nervengift** [comment]
Problem still exists in 3.5.17…

**Comment by Nervengift** [comment]
can confirm: seems to work under 3.5.18
