### ISSUE TITLE
[Urgent] [Bug] Java IO Exception When Trying to Send a Picture

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#764]
Selecting pictures works fine, and the small preview, too. It's when I go to actually post the tweet that I get this toast error.
![screenshot_2017-04-16-15-38-14](https://cloud.githubusercontent.com/assets/17078692/25073752/11c44924-22bb-11e7-9fd8-6016dba1ea4a.png)

I meant to post this issue last night along w/ the reply-to-self one, but I forgot. (Thanks for the quick fix on that, btw.)

**Comment by mariotaku** [comment]
This was a duplicate to #763. You'll see the fix in 3.5.18.
