### ISSUE TITLE
"friendica_owner" is not the same like "user"

### ISSUE THREAD

**Issue by annando** [TwidereProject/Twidere-Android#765]
Since some time I noticed that the author of a post was often displayed wrong when working with Friendica. I think the cause is this code:
https://github.com/TwidereProject/Twidere-Android/blob/0a3a5b10ad2afd9a58e46592816970ccc13788f0/twidere.component.common/src/main/java/org/mariotaku/microblog/library/twitter/model/Status.java#L99

The field "friendica_owner" is not the same as the "user" field. The "user" is always the author that should be displayed, while the "friendica_owner" is only of some interest with forum posts. Then it would make sense to show both "user" and "friendica_owner" at the same time.

The easiest solution is to not display the "friendica_owner" at all.

**Comment by mariotaku** [comment]
Thanks! I've removed this field and it will be available in next version.
