### ISSUE TITLE
Tap on links do nothing (with Chrome tab option enabled)

### ISSUE THREAD

**Issue by LukasThyWalls** [TwidereProject/Twidere-Android#766]
EDIT: This happens with Chrome tab option enabled, when it's disabled Twidere works normal.

## Expected behavior
In a tweet with a link, if i tap on the link it should appear the options to open the link or open the link directly if i have it configured.

## Actual behavior
When i tap the link, it do nothing. (When i tap on more times, normally tries to select the text, like should do with normal text)

## Steps to reproduce
It happens always in a tweet. Tap on a tweet in a list, or in an opened tweet.

## Extra info

Android version: Android 6.0 with EMUI 4.0

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: ~3.5.18~ 3.5.19

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
@LukasThyWalls What browser do you have?

**Comment by LukasThyWalls** [comment]
Holy s**t... when i read that question i realized what is the problem...

Yes, I have Firefox, Chrome, Chromium (With this https://f-droid.org/repository/browse/?fdfilter=Chromium&fdid=com.dosse.chromiumautoupdater) and Privacy Browser (https://f-droid.org/repository/browse/?fdfilter=Privacy+Browser&fdid=com.stoutner.privacybrowser.standard).

But when i switch off the "Chrome Integrated Tab" option it works again. Anyway, it should open with Chrome (or Chromium? Maybe this is the problem?).

**Comment by mariotaku** [comment]
@LukasThyWalls Is 3.5.27 fixed this issue?

**Comment by LukasThyWalls** [comment]
Now with the option enabled or disabled, the open dialog always appears.

With the option enabled, if i open the link with Chrome or Chromium, they open only one tab for the content like should be.

With the option disabled, If i open the link with Chrome it opens the link like the normal chrome browser with the ability to create new tabs, etc. like should be. Chromium stills uses the one tab configuration.

**Comment by mariotaku** [comment]
@LukasThyWalls What's your expected behavior? I can't fully understand your description.

**Comment by LukasThyWalls** [comment]
Ok, sorry.

I only pointed out that if i pick to use Chromium, it uses the "integrated tab", whatever the option is On or Off. It works like should be with Chrome.

And like i have 4 options to open links, it shows me always an open dialog to choose browser, at the beginning i thought this option should open directly the page in chrome, without any dialog.

**Comment by mariotaku** [comment]
@LukasThyWalls "Chrome custom tabs" still respects system browser settings because some browsers like Opera also have this feature. Do you think this issue is resolved?

**Comment by LukasThyWalls** [comment]
If "Chrome custom tabs" should work with other browsers with this feature and not only Chrome, in that case, Chromium should be respecting the configuration, and now it's opening a "custom tab" always, whatever is the configuration in Twidere.

Anyway, it can be a problem of the build of Chromium (create with this https://f-droid.org/repository/browse/?fdfilter=Chromium&fdid=com.dosse.chromiumautoupdater) and not directly Twidere.

**Comment by Tedko** [comment]
Seems like fixed already

**Comment by Tedko** [comment]
@LukasThyWalls Let me know if you still have any question.

Just let you know now twidere is maintained by community and supported by www.dimension.im / maskbook.com - we would love to have more community support and feedbacks. pls spread the words.
