### ISSUE TITLE
Mastodon replies don't include full addresses

### ISSUE THREAD

**Issue by jbbdude** [TwidereProject/Twidere-Android#776]
When replying to a user on a federated instance on Mastodon, the user's full address is not auto-populated into the reply field. This thus fails to actually tag the user in the reply correctly.

## Expected behavior
Hit "reply" to a Mastodon toot, toot is auto-populated with the user's full address (@username@instance.tld)
## Actual behavior
Hit "reply" to a Mastodon toot, toot is autopopulated with just the user's username (@username)
## Steps to reproduce
View timeline. Hit reply on a toot from a user on a different instance.
## Extra info

Android version: 6.0

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.5.25

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by yiskah** [comment]
Can confirm that this happens for me too. Same app version. I'm on Android 7.1.1

**Comment by yiskah** [comment]
You're the best mariotaku ♥️♥️♥️♥️♥️

**Comment by jbbdude** [comment]
Can verify this is resolved in app ver 3.5.27.

**Comment by smalltock** [comment]
I'm using app version 3.6.21 and this isn't working.

I am logged into a Pleroma instance, using the GNU Social API.  I know Pleroma isn't GNU Social, but the api still works and I can log into the account and post things in Twidere.  It's worth noting, I guess.

I respond to mastodon users, but only their username is populated in the reply, not their server address.

Granted, on an actual GNU Social instance, using the GNU Social API, this does work properly.

Maybe in the settings, there can be a toggle option to always populate the full user@address.  I think that would be good.
