### ISSUE TITLE
"Public Timeline" & "Network public timeline" appear to be the same for Mastodon accounts

### ISSUE THREAD

**Issue by yiskah** [TwidereProject/Twidere-Android#777]
Mastodon has two public timelines. "Local" which shows all public posts from just the local instances; and "Federated" which corresponds to The Whole Known Network on GNU Social, showing public posts from all connected instances local or remote. On Twidere, both "Public" and "Network" public seem to display the Local timeline.

## Expected behavior
One timeline should show all public posts from local instance, and another should show public posts from all connected domains, local or remote. These should be easily differentiated, (perhaps if you are logged in from Mastodon, it shows their names as Local and Federated?). 
## Actual behavior

Both appear to display the Local timeline.

## Steps to reproduce

Log into Twidere from a Mastodon account. Tap "public timeline" and look at the posts. Tap "network public timeline" and look at the posts. It's pretty much the same. Tap on users and you'll see that everyone you see is on the same domain as you.

## Extra info

Android version: 7.1.1

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.5.25

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by jbbdude** [comment]
Can confirm this behavior on Android 6.0.

Also, yeah, for parallelism with default Mastodon lingo, they should be "local timeline" and "federated timeline" rather than "public timeline" and "network public timeline".

**Comment by jbbdude** [comment]
This issue persists in app ver 3.5.27. Now, the "public timeline" (should be "local timeline") and "federated timeline" both show the local timeline. Both options are prone to failing to load with an undefined "Network error" though.

**Comment by yiskah** [comment]
In 3.5.27 there appears to now only be a public timeline, which points to Local. No way to view Federated timeline. So not a total fix but it's progress!

**Comment by gled-rs** [comment]
Can confirm the behaviour of 3.5.27

**Comment by mariotaku** [comment]
I figured out what happened. Mastodon does not accept `true` or `false` for `local` parameter, it checks existence of `local` parameter to decide whether show federated timeline or not.

**Comment by amphineko** [comment]
Confirmed 3.5.27 on Android 7.0, mastodon v1.2.2

**Comment by jbbdude** [comment]
Can confirm this seems to be working correctly on 3.5.30

Still, "Public Timeline" should be called "Local Timeline" to match Mastodon terminology.

**Comment by mariotaku** [comment]
@jbbdude Twidere also work on other platforms, to prevent ambiguity with "Local (geo-wise) timeline", this will not change.
