### ISSUE TITLE
Mastodon Notifications: last notification reappear as new at each refresh

### ISSUE THREAD

**Issue by gled-rs** [TwidereProject/Twidere-Android#785]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

Twidere does not notify of a new interaction if we already saw the last 'new interaction' upon refresh

## Actual behavior

Twidere show a notification for the last 'interaction' each time there's a refresh, background or manual, even if it was already seen.

## Steps to reproduce

Have someone follow you, send you a mention. Refresh the timeline, you have the notification.

## Extra info

Android version: 7.1.2

Network type:

- [X ] Cellular
- [X] Wi-Fi

App version: 3.5.27

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by karlyeurl** [comment]
I experienced that behavior too. For now, I have disabled notifications from the Mastodon account altogether.

**Comment by xsteadfastx** [comment]
I can reproduce this too.

**Comment by mariotaku** [comment]
This is a duplicate to #770 .
P.S. Good news! Fixed in 92ab85adf949a1c554825622ef1f077ee3df47a2.

**Comment by daks** [comment]
nice, waiting for f-droid new upload :)
