### ISSUE TITLE
Split tweets when longer than 140 xters

### ISSUE THREAD

**Issue by thegrandvezir** [TwidereProject/Twidere-Android#790]
Hi 
Thank you for all your work. This is a great app
I would like to request an option to split a tweet longer than 140 xters into several tweets that are then tweeted in a thread.
Entries in the thread are then designated with a (1/n) suffix, where n is the final number of entries in the thread
Thank you again.

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by orithena** [comment]
This is a duplicate of issue #190, which already contains a lot of thoughts around the idea. Please close this one.

**Comment by thegrandvezir** [comment]
Thanks for your response.

My bad. I didn't read that far back.

I will close it.
