### ISSUE TITLE
'My account' app icon shortcut on 7.1.1

### ISSUE THREAD

**Issue by thegrandvezir** [TwidereProject/Twidere-Android#791]
Hi, thank you again for your work.

If it's not too much to ask, I would like to request the addition of a 'my account' app icon shortcut to the existing ones ( compose tweet, and take a picture) that immediately takes one to one's profile page.

Thank you again.

**Comment by mariotaku** [comment]
@thegrandvezir I guess "Quick Action" is what you want, simply add a "Quick Action" and pick user, then you'll be able to add user profile to home screen.

**Comment by thegrandvezir** [comment]
Thank you for your response.
Where do I find this 'quick action's
Pressing and holding the twidere app icon only shows me 'compose tweet' and 'take a picture' on my device.
I'm on android 7.1.1 running version 3.5.30 of the app

**Comment by thegrandvezir** [comment]
Forgot to also mention that I use Nova launcher. 
If that is important.

**Comment by thegrandvezir** [comment]
Hi again.
I've found it.
A widget.

Thank you for your help.

**Comment by thegrandvezir** [comment]
I'll close the issue now.
