### ISSUE TITLE
[Feature Request] Display photos from Facebook

### ISSUE THREAD

**Issue by soaringowl2145** [TwidereProject/Twidere-Android#794]
Is it possible to make photos from Facebook display in the media preview like Instagram does?

Thanks.

**Comment by mariotaku** [comment]
@soaringowl2145 Can you share me some example tweets to that?

**Comment by soaringowl2145** [comment]
Like this?

https://twitter.com/DaniDivineModel/status/857268002269650946

**Comment by mariotaku** [comment]
I guess this is not possible yet because Twitter and Facebook *intentionally* blocking each other's access to link details.
