### ISSUE TITLE
Custom Servers for GNU Social/StatusNet?

### ISSUE THREAD

**Issue by roytam1** [TwidereProject/Twidere-Android#795]
There is only a limited choices in StatusNet section when adding account. I hope a server field for people adding custom GNU Social/StatusNet servers just like adding Mastodon account.

Android version: 5.0.2

Network type:

- [x] Cellular
- [ ] Wi-Fi

App version: 3.5.25

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
You can edit OAuth and server address in sign-in screen. Just click that server button on top right of the screen.

**Comment by keverets** [comment]
The custom server addresses are a bit too advanced for the average user. They may know they use "quitter.is" but not what the settings need to be.

The Mastodon version of this is much easier, and having an "Other..." option for GNU Social that matched the type-in for Mastodon may be beneficial.

**Comment by mariotaku** [comment]
@keverets It's not possible. An OAuth key is needed to be obtained on instance in order to sign in, which is impractical on GNU social because Mastodon gave user an API to fetch such key on client side while GNU social requires me to register an account on every instances, fetch the key, or contact their site owner to obtain one.

**Comment by roytam1** [comment]
> t's not possible. An OAuth key is needed to be obtained on instance in order to sign in

I heard that GNU social can just use "Basic" auth.

**Comment by mariotaku** [comment]
@roytam1 Yes it does. However Basic auth is a really bad practice. Though Twidere haven't remove Basic auth yet for some legacy reason, it's still strongly discouraged and will never be default.
