### ISSUE TITLE
HTML entities not decoded in some toots

### ISSUE THREAD

**Issue by fpom** [TwidereProject/Twidere-Android#799]
On Mastodon, some toots are displayed with the HTML entities not decoded. Others are OK. See screenshot:

![screenshot_2017-04-26-08-58-56](https://cloud.githubusercontent.com/assets/4525552/25422211/6cd4116c-2a60-11e7-8bb5-e044cbe000cb.png)

Here are the links of the two toots I've underlined:

- https://mamot.fr/@ThierryJoffredo/790952
- https://social.tchncs.de/users/NinahMarie/updates/64650

Note that this is not related to language. I've seen toots correctly displayed and others not both in French and English.

Android version: 5.1.1
Network type: any
App version: 3.5.25
Build variant: F-Droid
Micro-blogging service: Mastodon
App settings:
    [X] Official keys
    [X] Media preview enabled

**Comment by mariotaku** [comment]
@fpom Please update to latest version and try, "&apos;" encoding should working since 3.5.27.

**Comment by fpom** [comment]
OK, I'll wait it appears on F-Droid. Thanks!  :)
