### ISSUE TITLE
[Feature request] Favourited/retweeted notifications

### ISSUE THREAD

**Issue by hsanjuan** [TwidereProject/Twidere-Android#8]
Hello,

twitter official client replaced the mentions tab with a notifications tab which also lets the user know if one of their tweets have been favourited, or someone has retweeted a tweet in which they are mentioned etc... is it possible to bring this functionality to twidere?

**Comment by HikageKyun** [comment]
I'd like to Neco this request, as I would really like to switch over to the Twidere client from moving between Talon and the Official app. 
However, myself and peers who are all looking for a new client rely on a "Like/ReTweet" notification with how we use twitter.
You've mentioned that you're not sure if it can be implemented, however from my experiences, Twidere seems to be the only 3rd party client that doesn't offer notifications for "Likes" and ReTweets.
I've been searching for a little and this is the only result I could find that remotely addresses this. I'm unsure if this is a commonly sought after feature, but I do know that many would appreciate having the option to have it included.

**Comment by mariotaku** [comment]
A good news for you: I'm now starting make activities tab default for official keys, this will be implemented in near future.

**Comment by mariotaku** [comment]
It'd be possible if you are using [official keys](https://gist.github.com/mariotaku/5465786) since [0.3.0-dev151214](https://github.com/TwidereProject/Twidere-Android/releases/tag/0.3.0-dev151214). System-wide notifications will follow.

**Comment by mariotaku** [comment]
I'm closing this.

**Comment by jluttine** [comment]
I'm using official keys and version 3.2.7 but I can't find a tab which shows notifications for likes and retweets.

**Comment by orithena** [comment]
Strange. Works here on the interactions tab. (3.2.7, official keys). Did you enter the keys before entering your account data for the first time? If not, your account is still running on the standard keys -- i.e. delete data and cache and try again with entering the keys first.

**Comment by jluttine** [comment]
Ah, ok, I had just deleted the account and re-created it. I now wiped the app cache before entering the keys and creating my account - and it works, thanks!
