### ISSUE TITLE
Off-by-one notification error

### ISSUE THREAD

**Issue by fpom** [TwidereProject/Twidere-Android#800]
After a refresh, Twidere shows again and again a notification for the same tweets/toots it has already notified before. On this screenshot, the Android notification is about a mention I've received already, the counter on the icon in Twidere bar is correct (I have no new event indeed, but a notification is displayed anyway).

![screenshot_2017-04-26-09-44-08](https://cloud.githubusercontent.com/assets/4525552/25423786/31848b18-2a66-11e7-9d78-4838853e2e53.png)

If there are new events, the counter in Twidere bar will be correct (say, 5) but the Android notification will show one more event (6 in this case).

The wrongly counted event may be from any account, and sometimes one notification from each account is wrongly counted. So it is an off-by-one error for each account, which may result in several Android notifications wrongly displayed.

Android version: 5.1.1
Network type: any
App version: 3.5.25
Build variant: F-Droid
Micro-blogging service: Twitter, Mastodon
App settings:

    [X] Official keys
    [X] Media preview enabled

**Comment by mariotaku** [comment]
This is also a dup to #770 and seems to be fixed. You can try newest builds here: https://github.com/TwidereProject/Twidere-Android/releases/

**Comment by fpom** [comment]
I've installed 3.5.35 and it still occurs, even more often. But only for Mastodon notifications so far.
