### ISSUE TITLE
Confused with API keys

### ISSUE THREAD

**Issue by fpom** [TwidereProject/Twidere-Android#802]
I used to use Android version from F-Droid. In order to have several bugs fixed, I've installed fdroid-release from GitHub (3.5.31). Unfortunately, it did not upgrade, so I had to uninstall the previous version, reinstall and reconfigure.

Then, I wanted to setup the official API keys, I've taken "Twitter Android" keys from https://gist.github.com/mariotaku/5465786 But it looks like they are not recognised has the official keys.

Consequently, I cannot receive notifications for favs and RT, but only mentions. The option to change this remains disabled. I've removed and reinstalled all my accounts but it remains the same. I also have a warning when looking at a tweet's answers telling me that not every answer can be downloaded, which presumably is also a consequence of wrong API keys.

Here are two screenshots, one to show how the option is disabled, the other to show the API keys I've entered.

![screenshot_2017-04-27-07-32-40](https://cloud.githubusercontent.com/assets/4525552/25470548/fbee5656-2b22-11e7-81dd-af468f59cc77.png)
![screenshot_2017-04-27-08-08-34](https://cloud.githubusercontent.com/assets/4525552/25470547/fbed6886-2b22-11e7-8f4e-1650cbc0a354.png)

I've also noticed that even if I uninstall completely, it complains at the first startup that account data is corrupted. Maybe I should remove some information somewhere to really clear accounts informations, but I don't know where.

Thanks for your help!

## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.5.25

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by Yowlen** [comment]
Umm, I've found that I've had the same issue with the Twitter for Android keys listed there. I think there might be a typo in there somewhere or maybe they're old keys that are for versions with more limited functionality than newer versions. I did some searching, though, & found the Twitter for Android keys in this pastebin work just fine: https://pastebin.com/Fgqed59f

**Comment by fpom** [comment]
Thanks for you help. Yes, it looks like to keys on your pages are exactly the same. I've noticed also for the spaces, and I do not have them. I've deleted all my account, entered the new keys (even if they are the same), and recreated all the accounts. Nothing changed...  :'(

**Comment by mariotaku** [comment]
@fpom Have you selected "Twitter" in the dialog popped up in login screen?

**Comment by fpom** [comment]
Yes, sure!

**Comment by mariotaku** [comment]
@fpom Well this leads to some confuse indeed. You should click "Default" to use your settings, I've improved this by adding "Default" to its account type to distinguish with built-in one.

**Comment by mariotaku** [comment]
I believe #818 is related.

**Comment by fpom** [comment]
It works! \o/
Thank you so much. :) 

Indeed default/twitter is confusing... ;) 

Cheers, 
Franck
