### ISSUE TITLE
No Mastodon's toots in home

### ISSUE THREAD

**Issue by KillianKemps** [TwidereProject/Twidere-Android#808]
Hello,

I'm using Twidere for my Twitter account and my Mastodon account, but I can't see the toots in the Home view.

## Expected behavior
When adding my Mastodon account I was expecting one of those behaviours:
- Have the tweets and the toots mixed together in the home column
- Have a home view for tweets when my Twitter account is selected on the left, and have a home view for toots when my Mastodon account is selected on the left.

## Actual behavior
I only see tweets in the Home view. Even when I switch accounts in the sidebar, it has no effect on the column view. I can't see toots of the Home column.

## Steps to reproduce
Start Twidere with the Twitter account already opened (after the first start of the phone) to only be able to see tweets in the home column.
Start Twidere with the Mastodon account already opened (after the first start of the phone) to only be able to see toots in the home column.

## Extra info
I know the Mastodon account works because I can see the local toots in the Public Timeline and the Network Timeline.

Okay, I just tried again and it seems I can see toots in the Home view when I open Twidere with the Mastodon account already selected (at the phone's first start). In this case it's this time the tweets which don't display in the Home view.

My Twitter and Mastodon accounts are exactly the same name (@KillianKemps), maybe is it there a conflict.

Android version: 5.1

Network type:

- [x] Cellular
- [ ] Wi-Fi

App version: 3.5.25

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [x] Mastodon

**Comment by mariotaku** [comment]
@KillianKemps Have you checked in "Accounts" in your sidebar? Account will show in timeline when it gets checked, and tab has "Activated account" option.

**Comment by KillianKemps** [comment]
Oh thanks it seems that resolved my problem! I had to go to Settings > Tabs > Home and then choose "Activated accounts" instead of one of my account name.

Maybe it would be nice to do some design  work in order to make it clearer. :)
