### ISSUE TITLE
Availability of conversation thread under a given reply.

### ISSUE THREAD

**Issue by muamma** [TwidereProject/Twidere-Android#809]
I've been running Twidere against Talon to see how they compare.

Talon is much slower. But it does have the (only!) advantage that conversation threads are almost always available under a reply. Whereas, with Twidere, they are often not (the "limitation of 3rd party apps" thing).

i wondered why Talon does this more successfully, and whether Twidere could improve this element of its provision?

App version: 3.5.31

Build variant:
- [x ] F-Droid

Micro-blogging service:
- [x ] Twitter

**Comment by mariotaku** [comment]
@muamma After looked into their implementation, I found talon tries to find more tweets at once so I also adjusted Twidere to higher value, which may help. However, honestly speaking it's still incomplete. You may want use this workaround: https://gist.github.com/mariotaku/5465786

**Comment by muamma** [comment]
Thanks. I'll try that out.
