### ISSUE TITLE
Can't add more account on Android 4.0.3

### ISSUE THREAD

**Issue by jdfq** [TwidereProject/Twidere-Android#810]
原来已经有一个推特账户，再点击添加新账户时，直接跳出设置界面，回到主界面。也就是说，不能添加。

**Comment by mariotaku** [comment]
@jdfq 请提供更详细的信息，

* App版本是？
* 要添加的账号是什么，饭否、Twitter、Mastodon？
* 是否出现崩溃的提示？
* 从哪里安装的？

**Comment by jdfq** [comment]
就这里下载的最新版，又试了3.5.36，一样。选择账户界面点击“+”，然后就关闭了设置界面，回到了主界面。都没有弹出选择账户种类的界面。

**Comment by mariotaku** [comment]
找到原因了，下一个版本中会修复，多谢报告！
