### ISSUE TITLE
[Bug] Retweet Button Going Haywire When Scrolling

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#813]
The retweet button is retweeting other tweets instead of the one it's attached to visually. It seems to be the detection system that isn't lining up with the visual result when scrolling. Likes work fine. I'm pretty sure this only popped up within the last 3 or 4 updates from the Play Store betas. I can't narrow it down more, unfortunately. Too many happened & I wasn't paying much attention.

**Comment by mariotaku** [comment]
@Yowlen do you mean after clicking "Retweet" button, tweet it displayed in retweet dialog isn't what you expected?

**Comment by Yowlen** [comment]
Correct.

**Comment by Yowlen** [comment]
Umm, I stand corrected. It actually shows the correct tweet in the dialog, but applies it to the one above or below, depending on the direction the user last scrolled.

**Comment by mariotaku** [comment]
@Yowlen I've received some same reports about this. Let's sssume we have two tweets A and B. A is what you want to retweet while B is another one.

1. When you tapped RT button in tweet A, does it 
1) Open retweet dialog showing A
2) Open retweet dialog showing B

2. When you performed retweet action in that dialog, does it
1) Retweeted A actually
2) Retweeted B actually

3. Also does this problem happens in
1) Home timeline
2) Interactions (mentions) timeline
3) Other users timeline
4) Favorites timeline

4. Last question: What did you do before tapping retweet button?

Since other reports haven't let me to reproduce this problem so far, could you provide more detailed information as I mentioned above? Thanks!

**Comment by 0x1f415** [comment]
I'm getting this bug too. when I try to retweet something the dialog shows the correct tweet, but ends up retweeting the tweet below it.

I use streaming, so maybe - I'm just guessing here - a new tweet appeared in the timeline in the process of retweeting and some index got offset?

**Comment by Yowlen** [comment]
First off, to address @0x1f415, it's not streaming, though it may be refresh-related. I don't use streaming & I get all potential outcomes, which I'll try to walk through here. I can't guarantee this will work 100% of the time, but it should be relatively accurate.

First off, I can verify this happens for all main tabs. Lists or user timelines within other areas may or may not be affected as I haven't tested them yet. I also can't state for sure if it occurs within the conversation popup view, but more on that later.

As I stated, I believe the issue occurs when I scroll through my main timeline and/or the timeline gets refreshed and tweets get added to it. More specifically, scrolling really fast seems to offset it more than a more casual scroll, or maybe it's just sheer numbers where it builds up based on how many you scroll past. I sometimes end up retweeting a tweet 2-3 tweets away in the timeline.

It also might be directional-based, as I stated in my initial report, but I'm not 100% sure as I mainly tested a single direction (upward). For example, if I scroll towards the top to view newer tweets, the retweet happens further up. The opposite (scrolling down to view older tweets) hasn't been tested by me, but I bring it up as a possibility to test if someone has time.

I believe the retweet dialog has better compensation for this than the actual retweet function itself, which allows it to show the proper tweet while still retweeting an improper one if the scrolling isn't too rapid or whatever.

Regarding the conversation popup, it's worth noting that opening a tweet or switching tabs seems to reset this issue, as does interacting with the retweet button. Once I retweet something, it starts functioning normally until I scroll more. I can scroll a little bit without it messing up, which lets me cancel the incorrect retweets if they're too far up to see, but going a dozen or two tweets through the list is all but guaranteed to trigger it again. On the other hand, liking a tweet seems to have no bearing on this issue. Only ones that switch focus to another area.

**Comment by mariotaku** [comment]
I found a possible bug to this problem, this patch in included in 3.5.37. Please try and see if it still happens.

**Comment by Yowlen** [comment]
Admittedly very little testing so far, but first impression is that it's fixed. At the very least, the bug you found definitely contributed. I'll continue testing throughout the day to be sure & get back to you.

**Comment by mariotaku** [comment]
I think this issue has been completely fixed. Feel free to reopen if you have this kind of issue again.
