### ISSUE TITLE
Conservation of Content Warning when replying to Mastodon post

### ISSUE THREAD

**Issue by Vrashnak** [TwidereProject/Twidere-Android#815]
## Expected behavior
When replying to a Toot with a content warning in Mastodon interface, Content Warning is conserved and propagated
## Actual behavior
In Twidere last beta, Content Warning is not conserved and has to be re-entered everytime.
## Steps to reproduce
Answer to a post with Content Warning
## Extra info

Android version: (version code here)
6.0
Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
3.5.36
Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:
Mastodon
- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
So, do you mean when replying to a sensitive toot, this should be also sensitive?

**Comment by Vrashnak** [comment]
Yes, unless we disable the Content Warning. This is the behaviour when replying in the original interface.

**Comment by novadeviator** [comment]
This does not work on Twidere 3.6.21

i've sent a toot to myself (from different account) with a Content Warning ('sensitive' is not the same as content warning. it is for images - ex-NSFW) and replied with twidere, but the Content Warning was not preserved.

see: https://creativity.cafe/@novadeviator/349365

**Comment by mariotaku** [comment]
@novadeviator Well I misunderstood this issue.
