### ISSUE TITLE
The new Beta version (3.5.37) can not use API consumer Key

### ISSUE THREAD

**Issue by eatradish** [TwidereProject/Twidere-Android#818]
## 问题
Twidere 在 Google Play Beta 测试组推送的新版 (3.5.37) 在 OAuth 模式下不能使用官推的 consumer key，但 xAuth 下在应用内登录后 (不经过浏览器授权) 可以使用官推 API

## 操作步骤

在应用内先设置好自己的 API consumer key 和 secret 删除账号再登录 (选择 Twitter) 在点选应用的 Login 的按钮后打开的浏览器授权页面还是显示授权的是 Twidere for Twitter #5 而不是 Twitter for Android，登录后也是使用的 Twidere 的 API。

当我选择 xAuth 的模式后，删除账号重新登录 (弹出账号选择，不选择任何东西) 然后直接在应用内登录则使用的是 Twitter for Android 的 API

## 相关信息
系统: Android 5.0.2 (Sony sol26 ROM)
Twidere 版本: 3.5.37 (Google Play Beta Version)

**Comment by mariotaku** [comment]
@eatradish 点击的是Twitter还是Default？

**Comment by eatradish** [comment]
@marootaku 是 Twitter，突然意识到可能是这个原因.....

**Comment by mariotaku** [comment]
@eatradish OK, 那么这和802是同样的问题，我改进了一下，希望下一个版本可以避免疑惑

**Comment by mariotaku** [comment]
Dup to #802
