### ISSUE TITLE
Messages in DMs displayed twice

### ISSUE THREAD

**Issue by mkody** [TwidereProject/Twidere-Android#83]
Using latest commit 72aaf3a8878a97b405485b4a4d7d9d67c9fcd785 - Nexus 5 android 5.1
When I'm opening a conversation, I see my messages twice, like this: 
![screenshot_2015-03-21-14-52-46](https://cloud.githubusercontent.com/assets/843787/6765304/45cebc9e-cfda-11e4-86ac-a4813f55ac67.png)

**Comment by mkody** [comment]
Looks fixed, using 4f34fb4780c8af511a9e5e6ca3e4d98d3d9dedcc

**Comment by hebu** [comment]
I can still see double message, when scrolling up a chat's history.

Twidere 0.3.0 dev 2015-03-29 / Android 4.3

**Comment by mariotaku** [comment]
does new version fixed this? (for new messages)

**Comment by hebu** [comment]
Seems so. I haven't experienced it recently. Thanks for fixing! :)

**Comment by mariotaku** [comment]
OK, I'll close it. if you encounter any problems I'll repoen this.
