### ISSUE TITLE
[Advice] is there a way to switch off auto rotate?

### ISSUE THREAD

**Issue by suddenrabbit** [TwidereProject/Twidere-Android#832]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Extra info

Android version: (version code here)

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
No. Twidere respects system settings, and adapts to different orientations automatically.
