### ISSUE TITLE
Bundle Twemoji

### ISSUE THREAD

**Issue by KAMiKAZOW** [TwidereProject/Twidere-Android#833]
Twitter develops their own set of Creative Commons-licensed emoji graphics: https://github.com/twitter/twemoji

Unlike Android, where users are dependent on OEMs to ship updates for new Unicode versions, Twemoji is constantly being updated. They are also used by Twitter for their hashflags feature. For details see http://emojipedia.org/twitter/

Bundling Twemoji would give users a consistent Twitter experience across formfactors. It would also ensure that users don't get to see a placeholder, just because their phone is one year old.

**Comment by mariotaku** [comment]
Twidere has external emoji pack support. See https://github.com/TwidereProject/Twidere-Android-Emoji-Noto and https://github.com/TwidereProject/Twidere-Android-Emoji-Apple .

**Comment by KAMiKAZOW** [comment]
I know but neither is Twemoji and neither is available from the Play Store. Also I think that Twemoji being Twitter's first party emoji pack, should be bundled by Twidere itself.

**Comment by mariotaku** [comment]
@KAMiKAZOW I'll make an extension available on Google Play, rather than bundle into Twidere. Those emoji adds up to several hundreds of megabytes to packages size, which is unacceptable.

**Comment by KAMiKAZOW** [comment]
Not sure where you got you totally inaccurate info about Twemoji's size from. Maybe you judged them by the size of the Adobe Illustrator files. The 72x72 PNGs in "twemoji/2/72x72" are just 2MB.

**Comment by mariotaku** [comment]
@KAMiKAZOW Sorry, not 100+MB. But 29MB is also too large for just a emoji pack.
![image](https://cloud.githubusercontent.com/assets/830358/26026859/4770d944-3836-11e7-9f72-2f149b919880.png)

To reduce memory usage, we need to scale each vector image into bitmaps for different densities, so it's way larger than single sized bitmaps.

**Comment by mariotaku** [comment]
The repo is created https://github.com/TwidereProject/Twidere-Android-Emoji-Twemoji and releases will be available soon.

**Comment by KAMiKAZOW** [comment]
Whether bundled or a separate emoji pack: Maybe have a look what Telegram, WhatsApp, etc are doing because they bundle emoji sets and they are vastly smaller. Maybe via WebP compression?

**Comment by mariotaku** [comment]
They have several ways for doing that, like download when needed, or just use a low-res emoji set for all resolutions. But no, I won't doing that since

1. Downloading emojis requires a server, and F-Droid variant users doesn't like outgoing connection to servers other than Twitter's.
2. Transparent WebP isn't available on all supported system versions
3. Low-res emojis looks terrible on newer phones.

**Comment by KAMiKAZOW** [comment]
> I'll make an extension available on Google Play

No release, yet: https://play.google.com/store/apps/dev?id=6556784347186425317
