### ISSUE TITLE
Number of new tweets

### ISSUE THREAD

**Issue by MrReSc** [TwidereProject/Twidere-Android#836]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Showing the correct number of new tweets.
## Actual behavior
Showing always maximum 20.
## Steps to reproduce
-Wait a couple hours
-Load all tweets
-Press "Load More"
-Max. 20 is showing in the red dot
## Extra info
![screenshot_20170515-153634](https://cloud.githubusercontent.com/assets/24952268/26071875/ec7d6b86-39a9-11e7-98f1-cb167679ddd8.png)

Android version: (7.1.2)

Network type:

- [ x ] Cellular
- [ x ] Wi-Fi

App version: (3.5.40)

Build variant:

- [ ] Google
- [ x ] F-Droid

Micro-blogging service:

- [ x ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
1. Returning exactly 20 tweets is not guaranteed
2. The last "Load more" gap is also a tweet.
3. Twitter may not be able to return older tweets after several hours.

**Comment by MrReSc** [comment]
Thanks for your answer.
When I remember right, showing more then 20 tweets was working on previous versions.

**Comment by mariotaku** [comment]
@MrReSc I tried and it's still working, you can set this to a higher value in Settings - Contents - Load item limits.

**Comment by MrReSc** [comment]
@mariotaku Thanks, It works.
