### ISSUE TITLE
Doesn't load text of toot after image on Mastadon

### ISSUE THREAD

**Issue by Canageek** [TwidereProject/Twidere-Android#839]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Should load the full toot, including text and links that come after an image. 
Example toot as it was sent and appears via web interface: 
![997b43cca6a96f1d](https://cloud.githubusercontent.com/assets/1037179/26126717/94ef93de-3a3b-11e7-84c6-866bb6298af5.png)

## Actual behavior
Appears to stop loading the message at the first set of images. 
Example as it showed up on my phone: 
![cb99cf7db8a1e639](https://cloud.githubusercontent.com/assets/1037179/26126728/9ce91fba-3a3b-11e7-8b66-6d1764fdf373.png)

## Steps to reproduce
View this toot in Twidere vs Mastadon: https://cybre.space/@kit/1038107

## Extra info

Android version: 7.1.2

Network type:

- [X] Cellular
- [X] Wi-Fi

App version:3.6.11

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
@Canageek Your guess is right, Twidere treats last media link as the end but haven't checked if there're more text. I'll fix this in next commit.
