### ISSUE TITLE
Selecting a trend location: tapping the bullet doesn't work

### ISSUE THREAD

**Issue by mkody** [TwidereProject/Twidere-Android#84]
Using commit 72aaf3a8878a97b405485b4a4d7d9d67c9fcd785 - Nexus 5 android 5.1

If I tap the bullet on the list, it doesn't work, I need to tap the text or on the blank space. [Here's a little screencast to demonstrate](http://s.kdy.ch/device-2015-03-21-154617.mp4).

**Comment by hebu** [comment]
In my version, the bullets are overlapped by the scrollbar. I think, that's why they can't be tapped. Instead, the list's scrolling position is changed.

Twidere: 0.3.0 dev 2015-03-29 / Android 4.3

**Comment by soerenk** [comment]
I use Version 0.3.0-dev-135 (F-Droid) on CM 12.1 / Android 5.1.1 and have the same issue. Short click on the text works and immediately closes the dialog, so you don't know for sure that it worked.

**Comment by mariotaku** [comment]
Closing since trends location picker redesigned.
