### ISSUE TITLE
Conversation page scrolling loading issue

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#845]
I believe the cause is similar to #820. The result is definitely the same & I think the two may have popped up around the same time (I just didn't pay attention at first 😅). The main difference I can see is that conversation view doesn't allow refreshing without exiting the window like the profile view does, so I can't ever get it to load the next tweets.

To reproduce, bring up a tweet with more than 20-30 replies, scroll to the bottom. Twidere looks like it's starting to load more (it gives the little refresh circle icon), but it fails.

**Comment by mariotaku** [comment]
Have you change your consumer key/secret?

**Comment by Yowlen** [comment]
I'm still using the official keys like I mentioned in #820.

**Comment by mariotaku** [comment]
Thanks, this has been confirmed as a bug.
