### ISSUE TITLE
Detect the allowed file size for attachments in GNU social

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#848]
In the API for the settings of the node (located at `/api/statusnet/config.xml` on every GNU social or Statusnet instance) there is an entry called `file_quota`. You can find it in the XML tree under 
```
config > attachments > file_quota
```
and it shows the allowed file size in Bytes.

I think it'd be nice if Twidere could read this value and warn the user if he is about to send a bigger attachment as allowed. The current behavior is that the post is submitted as normal, but the attachment is missing and the user notices this only afterwards.

And I sometimes wondered why the image is missing although I intended to (and did) add one… 😉

*Edit:* Of course there is also JSON, e.g.:
```sh
curl https://gnusocial.de/api/statusnet/config.json | jq .attachments.file_quota
```

**Comment by mariotaku** [comment]
This would be great!
