### ISSUE TITLE
Image/Video Full Screen Top Bar

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#849]
## Expected behavior
When the user opens an image or a video, Twidere hides the system's status & navigation bars
## Actual behavior
The status & navigation bars get hidden, but an empty, transparent bar gets left in the status bar's place.
## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.15, but it's been present for a few versions.

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by Yowlen** [comment]
Has this not been released? Or is it still bugged? I'm using the latest beta version (3.6.29) & the transparent bar is still visible when viewing media.

**Comment by mariotaku** [comment]
@Yowlen It's not released yet. I've got some build problem so release APK cannot produced yet.

**Comment by Yowlen** [comment]
Ah, ok. Thank you for the answer.
