### ISSUE TITLE
Feature request: Home column per account

### ISSUE THREAD

**Issue by Geobert** [TwidereProject/Twidere-Android#851]
Hi there, 

At the moment we have the Home column that merge all the message from different accounts. 

It would be cool if we can define multiple « Home » and say which account(s) we want inside each.

So we can have a Home for twitter, a Home for mastodon for instance

**Comment by mariotaku** [comment]
You can add tab for separate account in Settings - Tabs.

**Comment by Geobert** [comment]
oh, just find how indeed, thank you!
