### ISSUE TITLE
Notifications do not refresh properly (Twitter/Mastodon)

### ISSUE THREAD

**Issue by alugarius** [TwidereProject/Twidere-Android#855]
## Expected behavior
1. I swipe down in the notification tab to reload
2. It shows my test-message ive send myself also the test follower

## Actual behavior
1. I swipe down in the notification tab to reload
2. It acts like there is nothing new..

Android version: 4.3

Network type:

- [x] Cellular
- [ ] Wi-Fi

App version: 3.6.15

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

---
It loads the notifications after I delete the database, but after that I have to delete the db again.
So its not incapable of loading notifications, its just not in the freaking mood to do what I want.

I am angry as hell because this is basic functionality that I need.

**Comment by mariotaku** [comment]
@alugarius Calm down. I tried to mention and reply to self several ways, and no notifications indeed -- even official web interface doesn't have that. I'd say it's a bug (or feature?) of Mastodon it self. And I received notifications from others normally.

**Comment by alugarius** [comment]
I do not.
I dont get notifications at all.

Of course I use a different account to test the function

**Comment by mariotaku** [comment]
@alugarius Could you try include your test account's id into your reply and test?

**Comment by alugarius** [comment]
I hardly think this is changing something but if you want I do so...

**Comment by alugarius** [comment]
@mariotaku
nope, including the own id doesn't change anything. 
Also even IF that would work, everyone has to mention themselves to message me? What the heck?

**Comment by alugarius** [comment]
An as said, Twidere is not incapable of loading Notifications. 
I can forceload them while deleting the database all the time. Then its loading them without problems. 

So to make that clear @mariotaku it IS a bad bug in your awesome app. Nobody else's fault.

**Comment by mariotaku** [comment]
Fixed.

**Comment by alugarius** [comment]
Cool, how to test (update apk)

**Comment by mariotaku** [comment]
@alugarius I'll push a new version to play store along with other minor fixes.
