### ISSUE TITLE
Feature request: Federated and Twitter timelines in the same tab (sorted)

### ISSUE THREAD

**Issue by stormwatch** [TwidereProject/Twidere-Android#856]

**Comment by alugarius** [comment]
What?

**Comment by stormwatch** [comment]
I'd like to clarify but I don't know how.

**Comment by mariotaku** [comment]
Federated timeline can't be combined with home timeline. They aren't the same type. If you want to see more toots in your Mastodon timeline, try follow more interested users.

**Comment by stormwatch** [comment]
I don't want to see more toots in my Mastodon timeline.

I cannot imagine what prevents from combining timelines (not just Home). How are they not of the same type? Every tweet/toot/o Status is just text and I believe they have an associated timestamp (?)

**Comment by mariotaku** [comment]
@stormwatch One simple reason, it adds too much complexity to user settings. Though it's easy to implement.
