### ISSUE TITLE
Mastodon: no notification for direct messages

### ISSUE THREAD

**Issue by NekoiNemo** [TwidereProject/Twidere-Android#857]
## Expected behavior
Messages with visibility "direct" should appear in the direct messages tab (with Mastodon account enabled) and show notifications

## Actual behavior
Direct messages only show up in home timeline for Mastodon and seem to be completely ignored when it comes to notifications

## Extra info

App version: 3.6.15

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Direct reply is not direct message. Please keep in mind that it's not private at all acrossing instances. I'll add DM for Mastodon once it have real DM feature.

**Comment by alugarius** [comment]
It has DM
It just working different

**Comment by alugarius** [comment]
They have DMs
They are the direct reply (so that noone else sees)
They dont seem to add "real DM" because that what mastodon has already replaces the need of it

**Comment by NekoiNemo** [comment]
Then, if they aren't real DMs, the issue is that they are not shown in the interactions tab and also do not get notifications.
Basically my issue is that i have to manually open the home timeline and visually scan for the envelope icon to know if i got the direct message.

**Comment by mariotaku** [comment]
@NekoiNemo Sometimes notifications can't be retrieved (see #855), this was fixed and will be available soon. 
@alugarius Mastodon's direct reply is **not** DM, if you send this to other GS servers, you'll see it's just normal mentions. I won't give user false sense of privacy to this feature, it's not private **at all**.

**Comment by NekoiNemo** [comment]
@mariotaku Are you sure it's that same issue? Afaik this (not showing up in interactions) only affects specifically Mastodon direct messages

**Comment by alugarius** [comment]
@mariotaku 
the DMs in mastodon are only readable by the people who are mentioned. It is very private. 
Ive tested it! 
Its working.
its possible to use it as full replacement of "real DMs"

I can just send one to prove it to you.

@NekoiNemo yes its the same issue and it got fixed

**Comment by alugarius** [comment]
@mariotaku 
also you dont have to implement them
you already did. Its fine

@NekoiNemo 
also please close this issue because its a duplicate of mine.

**Comment by mariotaku** [comment]
@NekoiNemo 

![image](https://cloud.githubusercontent.com/assets/830358/26674413/fd1cfd20-46f2-11e7-8932-3ac8d4d3081c.png)

https://quitter.se/notice/12648861

As you can see, this direct reply got retweeted on quitter, so I believe this should never be moved to real DM tab.

**Comment by alugarius** [comment]
Its not a dm you've send dude

**Comment by alugarius** [comment]
@mariotaku I cant reproduce that

**Comment by mariotaku** [comment]
@alugarius This is a status sent with 'direct' visibility to user @mariotaku@quitter.se . 

To reproduce you'll only need to

1. Mention a user in non-Mastodon instance with 'direct' visibility
2. Check your notifications in that instance
3. Do anything you want with this status.

If I move direct reply to DM tab, users will believe this is the 'real' DM. If someone send some private information to non-Mastodon instances, and get retweeted, who's responsible for this?

**Comment by alugarius** [comment]
Of course I see the message if I mention it. That's how it works

**Comment by alugarius** [comment]
If you dont mention any account,  only you can see it, if you mention an account it has access to it
![screenshot_2017-06-01-12-05-25](https://cloud.githubusercontent.com/assets/16763352/26675311/bf232ad2-46c3-11e7-82d6-1e8d983f7484.png)
![screenshot_2017-06-01-12-04-30](https://cloud.githubusercontent.com/assets/16763352/26675327/cadd32be-46c3-11e7-8f47-126c600daffa.png)

**Comment by NekoiNemo** [comment]
@alugarius Well, if it is indeed a duplicate...

**Comment by alugarius** [comment]
To sum that up,
If you send an dm to someone, this person has access to it.
that also counts to ANY network
I could also share any message I got from anyone because I am the receiver. Twitter, SMS etc
if I am not the reciver of a message, I can't see it unless a reciver shares it.
if @mariotaku sends a DM to @NekoiNemo via Mastodon I cant see it.

if @NekoiNemo shares it public via retweet or copy and paste ot a screenshot. Eveyone will see.

for example here is a message someone send me on twitter.
I haven't played with it yet, but it seems like it has potential

**Comment by alugarius** [comment]
@mariotaku so if you send someone a DM over mastodon or twitter , and this someone leaks/share the message to someone else/public
its your/someone's fault.  
This has nothing to do with a network providing the DMs.
ok?

**Comment by mariotaku** [comment]
@alugarius Sharing your DMs to public is different with lacks of privacy protection across instances. Sharing your DMs without permission means you don't have respect to who you're messaging. I'm blocking you from further comments. Goodbye.
