### ISSUE TITLE
Notifications get grouped with the service tweet streaming notification

### ISSUE THREAD

**Issue by NekoiNemo** [TwidereProject/Twidere-Android#858]
## Expected behavior
Notifications should be grouped by account and be separate from the service notification

## Actual behavior
In some cases groups of notifications get grouped themselves into the "Twidere" group, along with the service one. While grouping of notifications is a mere inconvenience, grouping together with the service one make normal notifications undismissable.

## Steps to reproduce
Uncertain. Having 3-4+ *groups* of notifications along with the timeline streaming being turned on?

## Extra info

Android version: 7.1.2

App version: 3.6.15

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

![screenshot_20170601-213348-01](https://cloud.githubusercontent.com/assets/3595771/26695731/9336d418-4714-11e7-90b8-34ad75d254b8.jpeg)

**Comment by mariotaku** [comment]
Looks like you're on Android Nougat. This is system bahavior. Android groups notifications automatically when an app has more than 4 notifications on the screen. You can dismiss individually by swiping down on this grouped notification and make them expand (or click that arrow to do so)

**Comment by NekoiNemo** [comment]
I know, but is there no way to make a service notification separate? Or does android groups them based on the app id automatically?

**Comment by mariotaku** [comment]
@NekoiNemo Seems they can be separated by type. I'll try this out.

**Comment by NekoiNemo** [comment]
Thank you~
