### ISSUE TITLE
Option to move scrollbar to the left or disable it

### ISSUE THREAD

**Issue by Sohalt** [TwidereProject/Twidere-Android#86]
When I scroll through my feed with my thumb holding my phone in the right hand I often accidentally touch the scrollbar therefore jumping to another location in my feed. This also sometimes happens when I want to touch the context menu on a card (top right corner of the card). My proposed solution would be an option to disable the interactive scrollbar or move the scrollbar to the left side (preferred option).

**Comment by mkody** [comment]
You can disable the "interactive scrollbar" by going to the preferences, _Interface_  and uncheck "Fast scroll thumb".

But I like the idea to have the choice to move it to the left, especially for left-handed people.

**Comment by Sohalt** [comment]
Oh. Thanks. Didn't find the option because the German translation is completely wrong. Gonna fix that if I remember tomorrow.

**Comment by mariotaku** [comment]
great idea, I'll try implement that.

**Comment by mariotaku** [comment]
This issue seems obsolete, if you encountered any other problems, fell free to reopen or create new issue.
