### ISSUE TITLE
Allow retweets from Mastodon to Twitter and vice versa

### ISSUE THREAD

**Issue by icheyne** [TwidereProject/Twidere-Android#862]
I would like to be able to retweet from Twitter to both Twitter and Mastodon and from Mastodon to both Twitter and Mastodon.

- Twitter --> Twitter
- Twitter --> Mastodon
- Twitter--> Mastodon + Twitter
- Mastodon --> Mastodon
- Mastodon --> Twitter + Mastodon
- Mastodon --> Twitter

Thanks for the great work. :-)

**Comment by mariotaku** [comment]
You can now retweet to other instances/accounts by long-tapping on retweet icon. Retweeting to multiple accounts simultaneously is not supported.

**Comment by regagain** [comment]
This is really cool and a much-appreciated improvement!
Can we please make this use the quote format defined in the settings?

**Comment by smalltock** [comment]
@mariotaku This doesn't always work.  For smaller cards, you can long-press the RT button to have it RT to another account/platform.  But for larger cards, like if you enter a thread and want to RT the tweet you're focused on, the long-press doesn't work.  You have to find a way to view that tweet in a smaller card, probably by selecting a different tweet in the thread, but that's not always an option.

Here's a video to demonstrate what I mean.
http://roaming-initiative.com/mediagoblin/u/anastasius/m/minor-twidere-bug/

**Comment by mariotaku** [comment]
@smalltock Got it, this still not supported in details page right? I will try find a way to implement this.

**Comment by mariotaku** [comment]
Oh, forgot to mention that this feature is available in details page too.
