### ISSUE TITLE
Tweet text is no longer selectable on single tweet activity

### ISSUE THREAD

**Issue by wzyboy** [TwidereProject/Twidere-Android#864]
## Expected behavior
Tweet text is selectable on single tweet activity.

## Actual behavior
Tweet text is not selectable on single tweet activity.

## Steps to reproduce
- Open a tweet;
- Long-press on tweet text;
- Squint.

## Extra info

Android version: 7.1.2

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.6.18

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
Migrate to #842
