### ISSUE TITLE
Shortened links aren't parsed for media preview

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#866]
Shortened links like `youtu.be` or `bit.ly` aren't showing previews within the tweet.

**Comment by mariotaku** [comment]
Yes that's normal. Short links can't be expanded without request to shortener service, and don't give metadata for Twitter for showing preview.

**Comment by Yowlen** [comment]
Would it be possible to implement the request ability to get the final URL and then use that to fetch the media preview?

**Comment by mariotaku** [comment]
It's practically impossible. A single refresh action would make several link expansion requests, this will be a huge impact on refreshing speed. On 4G network, a request takes 100ms at least, if there are 15 links in total, it would take 1.5s while refreshing itself only takes ~300ms.

**Comment by Yowlen** [comment]
I see. I was afraid of that. Oh, well. It was worth the try. Thanks for the reply. Maybe if ISPs ever start allowing more than 1/5th of the 4G spec's top speeds, the issue can be revisited.
