### ISSUE TITLE
[crash] click on a tweet frm JK Rolling

### ISSUE THREAD

**Issue by dhardy92** [TwidereProject/Twidere-Android#869]
## Expected behavior
Display tweet threads

## Actual behavior
Crash

## Steps to reproduce
Click on https://twitter.com/jk_rowling/status/873207949564497920

## Extra info

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.19

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [x] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
dup to #867
