### ISSUE TITLE
Image upload with alternative Consumer Key results in 404.

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#87]
Working: After deleting the complete app data and app cache and logging in, image upload via Twitter Image Service (default service) works.

Not working: After deleting the complete app data and app cache again, then changing the Consumer Key and Consumer Secret, and logging in, image upload via Twitter Image Service (default service) results in an Error 404 and saving the tweet to draft.

Using Twidere 0.3.0-dev150322 fdroid-release.

**Comment by HamiTsuka** [comment]
Same problem over here.

**Comment by orithena** [comment]
@HamiTsuka: I just saw your issue #85 (why did I overlook that before?) ... Are you having the exact same problem or can't you post any pictures at all, even without changing the default keys? (Because if it's the exact same behaviour, one of the issues #85 or #87 should be closed as duplicate.)

**Comment by HamiTsuka** [comment]
I have the same problem. Everything is doing fine with the default keys.

**Comment by mariotaku** [comment]
this should work in newest version. have you tried? @HamiTsuka @orithena

**Comment by orithena** [comment]
@mariotaku Sorry, overlooked your answer up until now. 

Using "0.3.0 (dev 2015-04-09)" (according to About Screen), it works! \o/ (not sure whether this update came via fdroid or google play)

I'm closing the issue, then. Thanks! I can finally go back to use Twidere as my primary client! Whohoo!
