### ISSUE TITLE
[Mastodon] Login fails with "Network error"

### ISSUE THREAD

**Issue by Risen-phoenix** [TwidereProject/Twidere-Android#870]
## Expected behavior
Login prompt for Mastodon displayed
## Actual behavior
"Network error" shown despite internet connection.
## Steps to reproduce
Attempt to login to Mastodon via the app for the first time.

Android version: 6.0

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.6.16

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Please update to newer 3.6.21 version.

**Comment by Risen-phoenix** [comment]
This version is not available via F-Droid.

**Comment by duvjones** [comment]
I have been getting the same error with 3.6.21, I have been trying to sign on to niu.moe

**Comment by mariotaku** [comment]
Migrated to #885.
