### ISSUE TITLE
Cannot boost (retweet) public posts from locked Mastodon accounts

### ISSUE THREAD

**Issue by yiskah** [TwidereProject/Twidere-Android#871]
## Expected behavior

A public post should be boostable regardless of whether the account is locked. A private (followers-only) post should not be bootable regardless of whether the account is locked. (Account locking on Mastodon just means you have to approve new followers it does not affect post privacy)

## Actual behavior

Public posts from locked Mastodon accounts are treated the same as locked Twitter accounts. A retweet dialog opens and the "retweet" button is grayed out even though the post would be bootable from the web interface.

## Steps to reproduce

Follow a locked Mastodon account, be approved, have that user make a public post, attempt to boost it from twidere.

## Extra info

Android version: 7.1. 

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: 3.6.21

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
So the only thing affects on boosts is visibility flag of a status, despite user's lock settings right?

**Comment by yiskah** [comment]
Correct. On Mastodon "locking" is simply making it so you have to approve new followers, but post scope/visibility/privacy is still exclusively on a per-post basis (one of the main selling points of Mastodon). Users who lock their accounts usually also change their default scope to "followers-only" but they can still, for a specific post, set that one to public in which case that post should be boostable.

**Comment by yiskah** [comment]
Its marked done? Which release is the fix coming out in? I still have this bug
