### ISSUE TITLE
Twidere crashes when a retweet is tapped

### ISSUE THREAD

**Issue by bennettscience** [TwidereProject/Twidere-Android#875]
## Expected behavior
A user I follow has retweeted something from someone whom I do not follow. I tap on the timeline item to see the tweet and the tweet should open showing replies, etc.

## Actual behavior
The app crashes.

## Steps to reproduce
Load your timeline. Find a **retweet** (quoted tweets work as expected) by someone you follow **of someone you do not follow**. Tap the tweet and the app should crash.

## Extra info
This is the only discernable pattern I can find. It's been happening since the update to 3.6.19.

Android version: (version code here)
6.0.1 

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here)
3.6.19

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by orithena** [comment]
In contrast: Can't reproduce this on Twidere 3.6.21-google/Android 6.0.1. Also, this crash behaviour never happened to me.

Am 18. Juni 2017 03:35:41 MESZ schrieb Brian <notifications@github.com>:
>## Expected behavior
>A user I follow has retweeted something from someone whom I do not
>follow. I tap on the timeline item to see the tweet and the tweet
>should open showing replies, etc.
>
>## Actual behavior
>The app crashes.
>
>## Steps to reproduce
>Load your timeline. Find a **retweet** (quoted tweets work as expected)
>by someone you follow **of someone you do not follow**. Tap the tweet
>and the app should crash.
>
>## Extra info
>This is the only discernable pattern I can find. It's been happening
>since the update to 3.6.19.
>
>Android version: (version code here)
>6.0.1 
>
>Network type:
>
>- [x] Cellular
>- [x] Wi-Fi
>
>App version: (version code here)
>3.6.19
>
>Build variant:
>
>- [ ] Google
>- [x] F-Droid
>
>Micro-blogging service:
>
>- [x] Twitter
>- [ ] Fanfou
>- [ ] GNU Social / StatusNet
>- [ ] Mastodon
>
>App settings:
>
>- [ ] Custom API
>- [ ] Custom consumer key/secrets
>- [ ] Official keys
>- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
>- [ ] Connected through proxy
>- [x] Media preview enabled
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TwidereProject/Twidere-Android/issues/875

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mariotaku** [comment]
dup to #867
