### ISSUE TITLE
Video fails to unpause after screen off

### ISSUE THREAD

**Issue by axelsimon** [TwidereProject/Twidere-Android#877]
Hi,
I just discovered this: was watching a Twitter video, I paused it as someone talked to me, pause was long enough for my screen to turn off (I have a short timeout) and after unlocking the screen, the video was black and I couldn't play it.

I couldn't unpause it, nor reload it, neither by tapping the reload button or by going back to the tweet and then tapping to play the video again.

Essentially, in this case, screen off during a video killed the video.

Hope you can reproduce :)

Thanks for making twidere!

**Comment by mariotaku** [comment]
What's your system version? This can't be reproduced on Twidere 3.6.21, Android 8.0.
