### ISSUE TITLE
Mastodon - Answer to a boosted toot not appearing on this toot web page

### ISSUE THREAD

**Issue by Lertsenem** [TwidereProject/Twidere-Android#878]
Hi! Thanks for your awesome work on supporting Mastodon!

This is a bug I reported on the Mastodon side, but it seems it's actually linked to Twidere behaviour : https://github.com/tootsuite/mastodon/issues/3845

## Expected behavior

An answer to a boosted (retweeted) toot should be addressed to the original toot, and thus appear on the original toot webpage.

## Actual behavior

When answering a boosted toot, the answer does not appear on the original toot webpage, but instead appears on the boosted toot webpage.

## Steps to reproduce

Answer to a boosted toot, and then select "Open in browser" for this boosted toot.
Your answer is there, but this is the booster webpage (check the url)
Click on the boosted toot date to access the original toot webpage
Your answer is not there.

## Extra info

An example of this behaviour:

Here I answered @Ymelia_@witches.town boost of @Hylde_@imaginair.es and my toot appears on her page: https://witches.town/users/Ymelia_/updates/349643
Here is @Hylde_@imaginair.es original toot webpage, where my answer does not appear: https://imaginair.es/users/Hylde_/updates/2245

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.21

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
I'll make this special case for Mastodon. I think this should be also supported on server side.

**Comment by Lertsenem** [comment]
I agree.
Thanks for making a special case anyway. :]
