### ISSUE TITLE
Mastodon - Bug when clicking on a non-followed user's toot

### ISSUE THREAD

**Issue by DansLeRuSH** [TwidereProject/Twidere-Android#881]
Hi and thank you for your hard work on integrating MASTODON.

Here a small behaviour that we are several users to experience when we try to "click" on a toot from a user we don't follow ...

## Expected behavior

Opening the toot to have more details

## Actual behavior

CRASH of Twidere

## Steps to reproduce

At this time, by clicking on any message from a user you don't follow

## Extra info

Android version: 7.1.2

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.19

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
This is a duplicate to #867.
