### ISSUE TITLE
Feature request: Split long Tweet in "n" parts

### ISSUE THREAD

**Issue by Zagur** [TwidereProject/Twidere-Android#882]
It would be interesting to write a long Tweet and Twidere automatically made a split.

For example, if I type a Tweet of 200 characters, two Tweets will be automatically sent; One of 137 characters and another 63.

As you can see in this screenshot:

[https://anonimag.es/image/JT9sVbF](url)

## **Useful cases:**

**You have set up a Twitter account**: The case I explained above, you write a long Tweet and send two separately.

**You have a Twitter account and a GNU Social account**: Some GNU Social nodes allow you to send more than 140 characters. When you send a Tweet selecting two accounts (Twitter and GNU Social) what happens is that GNU Social is sent correctly and on Twitter gives error.

I hope I explained well, my English is not very good 🌵

**Comment by Evpok** [comment]
Covered by #190
