### ISSUE TITLE
Twidere's interface is terribly slow since last updates

### ISSUE THREAD

**Issue by vovokrall** [TwidereProject/Twidere-Android#883]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Actual behavior
Everytime I refresh a timeline, click or like a twitt, Twidere freezes for a second. Sometimes it freezes for 2 or more seconds. This begun in last updates - most probably since the Mastodon update. 

My phone is an old Moto G XT1033, but since this behavior started not long ago and apps like Instagram  or Relay are still working fine, the problem seems to be in Twidere. Even if I clean the cache, the issue persists. 

## Extra info

Android version: 7.1.2 (RR 5.8.3) / In CM13.1 I had the same issue.

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.21

Build variant:

- [ ] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by Yowlen** [comment]
I've noticed this, too. I've cleared the databases in the settings & it seems to speed back up for a while, so I can only assume it has to do with excess database usage.

**Comment by vovokrall** [comment]
It gets a little faster when I clean the cache, but it doesn't persist for long. 
It's using now 5.88MB of cache (in a total of 46MB) and it's slow. 

I installed Flamingo and it seems pretty good, fast, pretty and full of gestures, but I'm already missing the simplicity of Twidere.

**Comment by edent** [comment]
Agreed. I'm on the Nexus 6 running Lineage 7.1.

Actions like adding a favourite can sometimes take several seconds to complete - freezing the app. Happens on wifi or cellular. 

Clearing the cache seems to work for a short while.

**Comment by nikclayton** [comment]
I see the same thing on a Nexus 5x running Android 7.1.2. Multi second pauses, especially when returning to the app.

**Comment by paulfariello** [comment]
Same thing on Nexus 5X running Android 7.1.2 and twidere 3.6.21.

**Comment by ctweney** [comment]
Same thing with a Samsung Galaxy S5, Android 6.0.1, twidere 3.6.21. 

Clearing cache helped me for a few minutes, but after that it seemed even worse than before.

**Comment by mariotaku** [comment]
Seems this problem was caused by a silly bug by me, hopefully previous commit can fix this problem!

**Comment by nbara** [comment]
@mariotaku is 4812e1b already included in the latest play store version ? 

Because I'm still experiencing those bad slowdowns. It gets a bit better right after the upgrade, but starts slowing down soon after...

**Comment by Yowlen** [comment]
I've been watching anxiously for an update, too, and there hasn't been an update posted on the Play Store since this commit was made. So no, @nbara, the latest version still has this bug.

**Comment by mariotaku** [comment]
@Yowlen @nbara https://github.com/TwidereProject/Twidere-Android/releases/tag/3.6.22 I've made a release including fix to this issue, please check out.

**Comment by schaal** [comment]
Running version 3.6.29 from F-droid I still experience slowdowns after some time, clearing the database helps for a while, but then it starts to slow down again

**Comment by regagain** [comment]
Still seeing this issue on 3.7.3 from F-Droid.

**Comment by nbara** [comment]
Me too. Actually this issue has never been solved for me. I'm still experiencing heavy slowdowns every time I activate the app, for about ~15s and then it gets better.

Running Android 6.0.1.

**Comment by reinob** [comment]
#metoo, with version 3.7.3 from F-Droid FWIW..

Every couple of days I have to use the "clear databases" option ("clear cache" does not provide a significant improvement -- if at all).

Then it works smoothly again.. until it starts getting slow again. I even went back to the official app again for some time, but the experience was so bad that I continue using Twidere, despite this extremely annonying behavior.

Please fix it! :)

**Comment by gimbar** [comment]
As of today (version 3.7.3 from f-droid) the slow down is not tolerable any more. I won't use Twidere anymore.

**Comment by mariotaku** [comment]
@gimbar I feel sorry for your experience. Twidere is working on a full rewrite, as far as I can tell, scrolling performance has improved to a whole new level.

**Comment by gimbar** [comment]
@mariotaku Thanks for your reply!
But more importantly: I'm sorry I left out my frustration on you.
You are doing great work and I'm appreciating your very professional reply to my snarky comments.

PS: I'm totally fine if this comment gets deleted. I understand it's offtopic but I think I'm in need of apologising.
