### ISSUE TITLE
Running "Clear databases" doesn't clear "list timeline" tabs

### ISSUE THREAD

**Issue by sycoso** [TwidereProject/Twidere-Android#886]
## Expected behavior
Running "Clear databases" removes all tweets, including those in the "list timeline" tabs

## Actual behavior
Running "Clear databases" removes all tweets in all tabs except for the "list timeline" tab where all the tweets are still present

Android version: 6.0.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.21

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [x] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Fixed along with #835 .
