### ISSUE TITLE
Generated QR is barely detectable

### ISSUE THREAD

**Issue by Ai-rin** [TwidereProject/Twidere-Android#890]
Only one of my friends was able to decode my profile QR. Web decoders I've tried couldn't detect it either. I'll attach it here.
I am on latest twidere-android from google play.

![file1499091740883](https://user-images.githubusercontent.com/29887769/27825392-0a5468e6-60b8-11e7-80bc-8283cd268cb9.png)

**Comment by mariotaku** [comment]
Can you give me your Twitter id? I'll adjust QR code style and make sure your QR code can be scanned correctly.

**Comment by Ai-rin** [comment]
It's on mastodon, and the profile is @airin@niu.moe

**Comment by Ai-rin** [comment]
Can I get develop build to test it?

**Comment by mariotaku** [comment]
You can either compile manually or wait for a new release on beta channel soon.

**Comment by orithena** [comment]
Just found this: There's a new paper to generate Halftone QR Codes:
http://vecg.cs.ucl.ac.uk/Projects/SmartGeometry/halftone_QR/halftoneQR_sigga13.html

Possibly interesting to use as alternate Fancy QR Code generator? :D
