### ISSUE TITLE
Feature request - show number of unread notifications on icon

### ISSUE THREAD

**Issue by thatguyhex** [TwidereProject/Twidere-Android#895]
It would be great if the number of unread notifications was shown in a "bubble" on the app icon.

**Comment by mariotaku** [comment]
Do you mean [Notification Badges](https://developer.android.com/preview/features/notification-badges.html)?

**Comment by thatguyhex** [comment]
Yes, that's exactly it.

**Comment by mariotaku** [comment]
@thatguyhex This will be supported soon, since Twidere is working on integrating brand-new notification channels.
