### ISSUE TITLE
Missing and/or misnamed Twitter lists

### ISSUE THREAD

**Issue by thatguyhex** [TwidereProject/Twidere-Android#897]
For some reason one of my Twitter lists is not visible when opening the view from the left panel - it would usually appear at the end. Also, some are also appearing with "s" added to the end of their name. However, the list is visible from the "Add to list" dialog - where it appears with the extra "s" and in lowercase. The list is https://twitter.com/hex/lists/tech if that's of any use. 

App version: 3.6.21

**Comment by mariotaku** [comment]
Have you tried swipe up? I saw your "Tech" list after swiping up to load more.

**Comment by thatguyhex** [comment]
Hi Mariotaku,

This report can be closed. The misnamed lists appeared to be the
side-effect of something else and I can't reproduce the "missing" list.
Thank you.
