### ISSUE TITLE
Retweet/Like account selection doesn't work on single tweet view

### ISSUE THREAD

**Issue by NekoiNemo** [TwidereProject/Twidere-Android#902]
## Expected behavior
When viewing a single tweet long press on retweet/like button should display an account selection to do action from, like in the timeline

## Actual behavior
Long press causes a "Retweet"/"Like" toast to pop right below button and nothing else happens

## Steps to reproduce
1) Press tweet in timeline to view only it
2) Long press the retweet or like button

## Extra info

Android version: 7.1.2

Network type:

- [ ] Cellular
- [ ] Wi-Fi

App version: 3.6.21

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
This has implemented in recent releases.
