### ISSUE TITLE
Trouble Customizing Column

### ISSUE THREAD

**Issue by StarMinion** [TwidereProject/Twidere-Android#904]
I had to reinstall Twidere recently on my Android phone. I know I had an activity column that just showed likes and retweets and not mentions but I can't for the life of me remember how I got it set up that way orginally. If anyone would be kind enough to assist me, I'd greatly appreciate it!

**Comment by mariotaku** [comment]
@StarMinion You'll need this for initial setup: https://gist.github.com/mariotaku/5465786
