### ISSUE TITLE
Favoriting a Notice Favorites the Wrong Notice

### ISSUE THREAD

**Issue by smalltock** [TwidereProject/Twidere-Android#905]
This weird phenomenon only occurs, to my knowledge, with one user in particular.  I went through the profile of @donniethedumbass@quitter.im and favorited a few notices of his.  Then I look at my own profile @gooz@shitposter.club to see that I've favorited notices I've never even seen before, some of which were in German or other languages I don't speak.  But looking at my profile, there was no trace of the notes that I ACTUALLY favorited.  I tried favoriting the same notes in AndStatus and through the web interface, both of which did the correct thing—favorited the right notices instead of these seemingly random ones.  I don't know where to begin troubleshooting this.  If there's any info you need me to gather, just ask.

## Expected behavior
Favorite the note when I press the favorite button.

## Actual behavior
In most cases, it behaves as expected, but for notes posted by @donniethedumbass@quitter.im and perhaps some others, rather than favoriting THAT note, a seemingly random otder note gets favorited.

## Steps to reproduce
1) Be a GNUu Social user on shitposter.club (maybe not necessary)
2) Find @donniethedumbass@shitposter.club
3) Favorite one of his notes.

## Extra info

Android version: (version code here) 7.1.2 NZH54B

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: (version code here) 3.6.21

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [x] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Should be the same issue as #813 , and fixed in later releases.
