### ISSUE TITLE
Duplicate self tweet show up in timeline when send tweet from twidere

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#907]
My English is poor,This issue write in Chinese:

Twidere 2.6.21
Android 7.1.2
LineageOS 14.1

我注意到会出现发出去的推文显示两个的现象，实际上只发出去一条，通过推文菜单，复制链接的话，两条推文的链接都是一样的。

基于Shadowsocks的连接，Twidere 默认 API ( #5 ) 。

Screenshot:

![screenshot_20170728-153249](https://user-images.githubusercontent.com/515763/28710923-64ef05f0-73b8-11e7-83f6-0c632c10faa7.png)

**Comment by mariotaku** [comment]
看右边的账号条，你是不是登录了两个账号，并且都关注了（或者是） @chenshaoju 本人？目前设计如此。

**Comment by chenshaoju** [comment]
@mariotaku 原来如此，是的，感谢。
