### ISSUE TITLE
Group DM's not showing

### ISSUE THREAD

**Issue by Shadowigor** [TwidereProject/Twidere-Android#908]
## Expected behavior
Group DM's are shown in the 'Messages' tab.

## Actual behavior
Only DM conversations between two users are displayed, not the ones between multiple users.

## Steps to reproduce
Nothing special, tried reinstalling and refreshing, did not help.

## Extra info
Might be related to #730? No notifications for group messages are shown.

Android version: 6.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.21

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by orithena** [comment]
Related to #872 ? (Although, ok, you tried reinstalling... did you delete app data, too?)

**Comment by Shadowigor** [comment]
Yes, just tried deleting the app data and also reinstalling again. Didn't work. Neither did deleting and re-adding the 'Messages' tab.

**Comment by orithena** [comment]
Hm. It works here, using Twitter with Twidere 3.6.21-google with the official keys from https://gist.github.com/mariotaku/5465786 ... did you enter one of these after reinstalling, but before logging in?

**Comment by Shadowigor** [comment]
Hm. With this key it does indeed work, thank you. It's just a bit strange that it doesn't work with the default key.

**Comment by orithena** [comment]
You'd have to thank Twitter for that. Third-party apps (more exactly: their keys) do not get access to some features. This includes group DMs and some notifications (you might have noticed that your notifications are now complete in Twidere, too).

**Comment by Shadowigor** [comment]
Ok, I see, thanks for clarifying!
