### ISSUE TITLE
identi.ca signin not working

### ISSUE THREAD

**Issue by mbanck** [TwidereProject/Twidere-Android#909]
## Expected behavior

It is possible to create an account for identi.ca, at least from posts on the web.

I used the following settings:

Accounts -> click "Add Account" icon -> click outside the "Twitter/Fanfou/Mastodon/StatusNet" pop-up -> click the server icon in the top right

API URL Format: https://identi.ca/api
Account type: [tried Twitter and StatusNet, does it matter what you select here?]
Auth Type: Basic
no version suffix: [tried both]

I then entered my identi.ca username and password (the latter multiple times, including changing it on identi.ca, to be sure), and got an error: "Incorrect API settings" if I did not select "No version suffix" and "Wrong username/password" if I selected "No version suffix" (if I mistype the API URL format in thsi case, I also get "Incorrect API settings").

## Actual behavior

Login to identi.ca succeeds and I see my identi.ca timeline as I do see Twitter and Mastodon

## Extra info

Android version: 7.1.2

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.6.21

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by annando** [comment]
Identi.ca is using pump.io as micro blogging service.

**Comment by mbanck** [comment]
So what you are saying is that the information on the web is outdated, and identi.ca/pump.io won't work with Twidere? Too bad, ok.

**Comment by annando** [comment]
Twidere can do:

- Twitter
- Fanfou
- Mastodon
- StatusNet (GNU Social)

Pump.io is not on that list. You could use AndStatus for pump.io.

BTW: Concerning "the information on the web is outdated": Yes, many information is outdated there ;-) To which page are you referring?

**Comment by mbanck** [comment]
I found a few, but this one claims to be from late last year, which is why thought I'd try: https://it-stuff.info/twidere-open-source-client-for-twitter-and-identi-ca-android/ - I now guess it's just a rip-off or repost from a much earlier site, as identi.ca switched to pump.io in late 2013.

Too bad, pump.io support is not being worked on I guess?

**Comment by annando** [comment]
The pump.io network is nearly dead. See here for a status of the known servers:
https://sjoberg.fi/pumpcheck.txt

```
Sun Apr  9 21:30:01 CEST 2017
********** Checking Pump.io servers...

Public servers (have, or had, open registration):
=============================================================================

identi.ca: Server: pump.io/3.0.1 express/3.21.2 node.js/v4.2.6
microca.st: -- FAILED --  (SSL issues)
mipump.es: Server: pump.io/3.0.2 express/3.21.2 node.js/v4.2.6
fmrl.me: -- FAILED --  (SSL issues)
pumpity.net: -- FAILED --
pumpdog.me: -- FAILED --  (SSL issues)
1realtime.net: -- FAILED --  (SSL issues)
pumpit.info: -- FAILED --
pumpbuddy.us: -- FAILED --
pumprock.net: -- FAILED --  (SSL issues)
hotpump.net: -- FAILED --  (SSL issues)
pumpyourself.com: -- FAILED --  (SSL issues)
urmf.net: -- FAILED --
i.rationa.li: Server: pump.io/3.1.0-alpha.0 express/3.21.2 node.js/v6.9.5
datamost.com: Server: pump.io/3.0.1 express/3.21.2 node.js/v6.10.0


Private servers (some might allow registration upon request):
=============================================================================

e14n.com: -- FAILED --
zombienet.org: Server: pump.io/3.0.1 express/3.21.2 node.js/v4.7.2
pump.saz.im: Server: pump.io/3.0.1 express/3.21.2 node.js/v6.10.2


*** Check complete! ****** 12 failed! (6 were OK)
```

**Comment by Tedko** [comment]
as @annando mentioned Pump.io is almost dead, and its maintainer's website is also down -

https://github.com/pump-io/pump.io/commit/88a003e2c2c2bd17fa46b8cada5c412ac43187bf

Also the url @annando referring is down, and the author is moving away from pomp.io to Mastodon 
 -- https://sjoberg.fi/blog/pump-shutdown.html

I will close this issue now. Since we start to maintain development of Twidere I'm also thinking about the future of fedeverse and open web, 2020 might be better compare to 2017 with many interesting technology on p2p network, blockchain etc. 

@mbanck Thank you for your feedback. Pls spread the word that twidere is back and we definitely would like to have more feedback and support from community.

**Comment by mbanck** [comment]
Cool, I didn't realize twidere was back, glad to hear that and I've reinstalled it on my mobile.

The only thing I'm missing is the link preview images you get from the official client...

**Comment by Tedko** [comment]
> Cool, I didn't realize twidere was back, glad to hear that and I've reinstalled it on my mobile.
> 
> The only thing I'm missing is the link preview images you get from the official client...

Gotcha. Gonna add this functionality soon as well!!

**Comment by mbanck** [comment]
That's #1004 as I found out - I've added a comment to it.
