### ISSUE TITLE
[Feature Request] Show avatar of retweeter

### ISSUE THREAD

**Issue by Shadowigor** [TwidereProject/Twidere-Android#911]
Inspired by [TweetCaster](https://play.google.com/store/apps/details?id=com.handmark.tweetcaster), it would be cool to have a similar feature where the profile picture of the person retweeting something would also be shown in addition to the tweet author. In my opinion this greatly helps identifying retweets and their origin.

**Comment by mariotaku** [comment]
Actually this was added for a little while and got removed shortly. The reason I decide not to add retweeter icon is it may distract when reading through timeline, and also has performance impact on some devices.

**Comment by Shadowigor** [comment]
Ok, thanks for the clarification.
