### ISSUE TITLE
Scanners fail to read generated QR

### ISSUE THREAD

**Issue by Rorudo** [TwidereProject/Twidere-Android#914]
QR was generated for twitter account by latest (3.6.21) Twidere from Google Play.
I've attached the screenshot.
My profile image: https://pbs.twimg.com/profile_images/477895826476240897/lygx3xR9_400x400.jpeg

![qr](https://user-images.githubusercontent.com/5068621/28995514-b48ead9a-79f3-11e7-8363-2160fe0f0c6d.png)

**Comment by mariotaku** [comment]
This is a duplicate to #890 and fixed in 3.6.23.
