### ISSUE TITLE
Video controls blocked off by Android navigation buttons

### ISSUE THREAD

**Issue by defaultxr** [TwidereProject/Twidere-Android#919]
In the latest version of Twidere from Google Play, the video controls are blocked off by Android's navigation bar (back/home/apps). When I tap the screen to hide the Android navigation bar, it also hides the video controls. This makes it impossible to unmute videos, seek to a specific time, restart playback, etc.

![screenshot_2017-08-06-12-45-04](https://user-images.githubusercontent.com/601567/29005692-6c1572d4-7aa6-11e7-8a19-3eb778b7cb69.png)

## Expected behavior
I expect the video controls to appear above the Android buttons, or to appear when the Android bar is hidden.

## Actual behavior
The Android navigation bar blocks the video controls, preventing them from being used.

## Steps to reproduce
Open a video in Twidere by pressing the play icon that appears over the thumbnail.

## Extra info

Android version: 5.1.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.23

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [x] Fanfou
- [x] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

Thank you for making Twidere! It's the best twitter app by far. I've donated for it and I always recommend it to my friends.

**Comment by thegreatprophetzarquon** [comment]
Same here on Nougat 7.0 with a Moto Z Play.
