### ISSUE TITLE
[Feature Request] RTs from one platform to another (Attachments)

### ISSUE THREAD

**Issue by smalltock** [TwidereProject/Twidere-Android#921]
When RTing from one platform to another (eg. from Twitter to GNU Social), Twidere will grab a link to the attachment where it is on the original platform.

At least for some kinds of attachments, like images most importantly, I think it would be a good idea for Twidere to download the image(s) and upload them as attachments when tweeting to the destination platform, rather than just linking to the first one.

Off the top of my head, this gives us two benefits.
1. If the original tweet gets deleted or censored, the RT on GNU Social will still be intact.
2. Users on GNU Social can view the attachments without sending traffic back to Twitter and perhaps being tracked when they don't want to be.

**Comment by mariotaku** [comment]
Copying tweet and its media involves two problems:

1. Some users don't want their content to be reposted without consent, especially photography/artworks.
2. If user deletes a tweet, then in most cases the user really wants to delete it. Making that tweet out of control is disrespect to its owner.

IMO Twidere shouldn't make those operations too easy, so this issue will be closed.

**Comment by orithena** [comment]
For what it's worth: I approve of that reason.

Furthermore, there's a legal reason not to do that: Twitters API usage rules explicitely state that if you're embedding a tweet elsewhere you must check back regularly whether that tweet has been deleted. Copying a tweet blatantly ignores that rule, while linking adheres to that (the check is performed inherently on accessing the link).
