### ISSUE TITLE
Reply to quote tweet w/ handles has mixed-up user handles order

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#925]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Actual behavior
Say @.User1 quotes a tweet by @.User2 and mentions @.User3 in their tweet. The result would look like this:

@.User1's tweet
Blah, blah, @.User3
| @.User2's tweet

Replying to @.User1's tweet results in the following order in the compose window: @.User1 @.User2 @.User3

## Expected behavior
The problem with this is that the quoted tweet's handle isn't exempted from the character limit, so @.User3 becomes excluded, as well. @.User2 should be moved to the end of the list so that @.User3 properly gets shown as exempt.

Either that, or add support for tagging users so that extra user handles can be added to a tweet without affecting the limit.

## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.24

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by mariotaku** [comment]
Tried and I don't find any problem about mention text counting and ordering.
Please keep in mind that:

* Mentions' order are undefined (Twidere use hacks to keep reply style classic, but Twitter treats mentions as a set rather than an ordered list)
* Quoted tweets' mentions counts in tweet text, because quoted tweets are a link embedded in a tweet actually.

**Comment by Yowlen** [comment]
Sorry. I kept forgetting to make a note of this issue whenever it comes up in my timeline. I'll be using this tweet as an example: https://twitter.com/People4Bernie/status/928294692969574400
When I hit the reply button, I get this:
![screenshot_2017-11-08-14-49-08](https://user-images.githubusercontent.com/17078692/32571047-23f53d12-c494-11e7-96b4-5597c24c906a.png)
The handle from the quoted tweet gets put in between the main tweet & the handle(s) mentioned in the main tweet & causes the ones after it to turn white & count towards the character limit as a result. The middle handle should instead be put on the end like this:
![screenshot_2017-11-08-14-52-59](https://user-images.githubusercontent.com/17078692/32571219-a81766d8-c494-11e7-8e4d-2d9fd6a7f2ad.png)
