### ISSUE TITLE
[Feature Request] Enable streaming for DM only while in a DM

### ISSUE THREAD

**Issue by ghost** [TwidereProject/Twidere-Android#927]
I don't want streaming on generally, but I want to be able to enter a DM groupchat and see new messages without backing out, refreshing, and coming back in.

Please either enable streaming only while looking at a DM (screen on) OR place a refresh button inside the DM interface.  Either way would do the job for me.

**Comment by Tedko** [comment]
streaming API is dead. will close this issue for now.
