### ISSUE TITLE
only very specific webpages are supported to use via ostatus

### ISSUE THREAD

**Issue by PaulFree14** [TwidereProject/Twidere-Android#928]
I want to use twidere to login to my ostatus accounts. 
The problem only very specific webpages are supported. 
Why is that? 

I can login via gnusocial.de but can't via plateia.org 

Is there any technical reason for having it just available for some pages?

**Comment by orithena** [comment]
If I see that correctly, your question is answered in #795. So, the answer is: Twidere would need an app key for each and every gnusocial instance. Keeping track of all instances popping up is almost impossible. Use basic auth (or somehow get a key for Twidere to include).
