### ISSUE TITLE
Notifications new tweets by users ("mobile notifications")

### ISSUE THREAD

**Issue by rugk** [TwidereProject/Twidere-Android#931]
In the official Android Twitter app and in the web interface I can activate "mobile notifications" for any Twitter account, so I get a notification if there is a new tweet by that user.

It would be nice if that is also possible with Twidere.
When I try to activate it in the web interface Twitter wants a phone number from me.

**Comment by Yowlen** [comment]
This has been implemented in Twidere. It requires Media Streaming to be enabled & running to work properly. Look for this option in the 3-dot dropdown menu within the user profile page:
![screenshot_2017-09-14-11-29-57 01](https://user-images.githubusercontent.com/17078692/30438817-2e3a8482-9940-11e7-8c99-e9e19a563876.png)
.

**Comment by rugk** [comment]
Great, but is media streaming required for it? Can't we have nice things without that…

**Comment by Yowlen** [comment]
I don't know, tbh. I never tested it. But I don't see why it shouldn't work w/ the normal sync.

**Comment by mariotaku** [comment]
Mobile notifications are limited to official apps and SMS only, and streaming is only workaround to this.
