### ISSUE TITLE
Mute postings from followed accounts when they mentions anyone

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#932]
I would like Twidere that does not only mute postings from followed accounts when they retweet someone, but also when they mentions anyone. Some accounts I follow regularly post the same message to umpteen users. This floods my timeline temporarily. Still I'd like to follow them for relevant posts.

**Comment by mariotaku** [comment]
There's an option of your home timeline to show tweets only, filter out all mentions and replies. You can find it in each home timeline tab in Settings - Tabs.
