### ISSUE TITLE
Sign to Mastodon.social with ssl error

### ISSUE THREAD

**Issue by Tback1** [TwidereProject/Twidere-Android#936]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
it shows login i type in mastodon.social
## Actual behavior
![maston](https://user-images.githubusercontent.com/8872546/29576208-9b19f10e-8799-11e7-886c-045fccc1b0ef.jpg)

## Steps to reproduce
input Mastodon.social,than "登录"
## Extra info
no proxy，Under the same network，WEB and iOS cilents(Pawoo, amaroq.) works well ，no 2steps.
Android version: (version code here)
4.4.4
Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Is Tusky working on your phone?

**Comment by mariotaku** [comment]
Merged to #885 .

**Comment by Tback1** [comment]
@mariotaku The Tusky also fail to authenticating with thar instance

是因为安全认证方式不对么？Mastodon.social现在是1.6.0rc2的版本，是更换了认证的加密方式导致客户端无法识别？

**Comment by Tback1** [comment]
@mariotaku Trsky and Twidere-Android both work well onthe instance https://cn.tootist.net/about

**Comment by mariotaku** [comment]
@Tback1 Android 4.4的TLS加密存在一些问题，不能开启TLS 1.2（虽然理论上支持），而很多Mastodon实例只支持TLS 1.2。

**Comment by Tback1** [comment]
@mariotaku Thanks ,明白了，我去看看有没有在底层上打补丁的办法。受教了～建议在4.4的机器上弹出的错误时加上这个解释，能减少issus提问
