### ISSUE TITLE
Tabs not showing their names (3.6.24)

### ISSUE THREAD

**Issue by regalz** [TwidereProject/Twidere-Android#937]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior

Show tabs with names

## Actual behavior

Only showing icons

## Steps to reproduce

Just creater a new tab for your list timeline and name it

## Extra info

Android version: 7.12

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.24

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings: (dont know what to check here)

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

Well, the issue is simple. When im creating tabs for my lists timeline, it doesnt show the name anymore, just the icon. Im naming it the tab like "Sports" but it only shows the icon. I may be missing something on the settings but i just cant seem to find it anything regardind this. Thanks and great app

**Comment by mariotaku** [comment]
This is available in Settings - Others - Scrapyard (sorry for making this preference too deep!)
