### ISSUE TITLE
Android menu button doesn't open Twidere menu any more

### ISSUE THREAD

**Issue by ilf** [TwidereProject/Twidere-Android#939]
## Expected behavior

Press [Android overview button](https://support.google.com/nexus/answer/6073614) -> open Twidere menu.

This used to work a few versions back.

## Actual behavior

Press [Android overview button](https://support.google.com/nexus/answer/6073614) -> nothing happens.

## Steps to reproduce

1. Open Twidere.
2. Press [Android overview button](https://support.google.com/nexus/answer/6073614).

## Extra info

Android version: 7.1.2

App version: 3.6.24

Build variant:

- [ ] Google
- [x] F-Droid

**Comment by mariotaku** [comment]
Pressing 'overview' button should open recent tasks screen. Have you upgraded your system?

**Comment by ilf** [comment]
Yes, I upgraded from Android 5.1 to 7.1.2. The overview button does nothing now.

**Comment by mariotaku** [comment]
@ilf Do you mind give me some details about your device model, and some screenshot about your launcher and Twidere on your phone?

**Comment by ilf** [comment]
@mariotaku Mailed you.

**Comment by mariotaku** [comment]
@ilf I saw a message with nearly empty attachment. Could you check and send me again?

**Comment by mariotaku** [comment]
@ilf I saw your message. "Overview" button should always open recent tasks screen, not device menu. Maybe your device firmware update changed keymap from "Menu" key to "Overview" button, so it changes Twidere's behavior. I believe this is related to firmware configuration not Twidere it self.

**Comment by ilf** [comment]
My device is a Samsung Galaxy S4. By "overview button", I mean the left lit button on the device: https://i.stack.imgur.com/6R5GF.jpg

The buttons behaviour is still identical in all other apps, just not in Twidere.

By "Twidere menu" I mean the sliding menu from the left, with my account(s) and "search, likes, lists, accounts, drafts, fiters, settings".

**Comment by mariotaku** [comment]
@ilf I get you. This is called 'Menu' button, and will be fixed soon.
