### ISSUE TITLE
minimalistic ui

### ISSUE THREAD

**Issue by oprudkyi** [TwidereProject/Twidere-Android#94]
Hi , 
Thank you for new version. Looks cool. 
But on small screens it has lost main feature - ability to disable user avatars (logos) and use all width for text. 
also would be great to have ability to hide tweet specific buttons (reply, retweet etc) to save space

**Comment by oprudkyi** [comment]
seems avatars has been gone. thank you

**Comment by mariotaku** [comment]
implemented in newest versions.

**Comment by oprudkyi** [comment]
Hi Mariotaku, 

I've just found the setting to disable 'tweet buttons' . twidere looks great now, the most 'compact' twitter client ever :) Thank you
