### ISSUE TITLE
Twitter DM's with multiple participants are not shown in Twidere

### ISSUE THREAD

**Issue by fschaap** [TwidereProject/Twidere-Android#940]
## Expected behavior
DM chats with multiple participants are shown in the Messages tab and exchanging DMs with multiple participants in the chat works as it does in the web client.

## Actual behavior
DM chats with multiple participants are not shown in the Messages tab and you can't start a DM chat with multiple participants: this generates the error 'Too many participants'

## Steps to reproduce
* Start DM chat with multiple participants in the web client and refresh the Messages tab with Twidere.
* Try to start a DM chat with multiple participants in Twidere

## Extra info

Android version: 7.1.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.24

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [x] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Only [official keys](https://gist.github.com/mariotaku/5465786) can access group DMs. Please make sure you re-login after keys changed.
