### ISSUE TITLE
Sharing picture from gallery uploaded as .bin file in Pleroma

### ISSUE THREAD

**Issue by imolein** [TwidereProject/Twidere-Android#942]
## Expected behavior

Mediafile is uploaded with the correct file type to Pleroma instance.

## Actual behavior

The mediafile is uploaded as `application/octet-stream` and stored as .bin file, when shared from another app:
![bildschirmfoto_2017-08-29_11-16-05](https://user-images.githubusercontent.com/14206433/29813801-7f883902-8cab-11e7-9755-7bd5771f2a3b.png)

It was working before the last update.

## Steps to reproduce

* Go into your gallery/file explorer app
* Select a picture
* Press the share symbole and select Twidere
* Send it
* Post appears with a attached .bin file, instead a picture

## Extra info

If a mediafile is selected within Twidere App, it is uploaded correctly. It appears only when sharing from another app.

Can be tested at https://pleroma.soykaf.com (Pleroma developers test instance) or https://edolas.world (my instance). Account can be added to Twidere with GNUsocial settings and Basic auth.

Android version: 7.1.1, 6.0.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.24

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon
- [X] Pleroma (GNU Social API)

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
What gallery app you're using? I tried with Google Photos but it works.

**Comment by imolein** [comment]
I don't use this one, but you're right, with Google Photos it's working. I checked it now with the following apps:
* Simple-Gallery - Not working
* Simple-File-Manager - Not working
* ES File Explorer - Working
* Google Photo - Working
* Gallery from SB Studio - Not working
* Asus File Manager - Not working
