### ISSUE TITLE
Android Oreo icon specs have changed causing icon to be mangled

### ISSUE THREAD

**Issue by JonathanWolfe** [TwidereProject/Twidere-Android#943]
In the newest Android update it changed how icons are supposed to be sized and such which means that the twidere icon has become scrunched into a circle. 

![screenshot_20170830-130033](https://user-images.githubusercontent.com/1449779/29885149-bade9d88-8d83-11e7-99f0-a70e898231d0.png)

Only thing that should need to be done is read the new icon guidelines and add a new icon to the manifest for Oreo.

**Comment by mariotaku** [comment]
Adaptive icon is ready in beta channel, you'll soon be able to get an update once it's ready.
