### ISSUE TITLE
Commenting already retweeted Tweet deletes RT, comment vanishes

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#944]
## Expected behavior
When commenting a tweet that I have already retweeted, I expect the RT to persist and the commenting tweet posted

## Actual behavior
After I send the comment I cannot find the commenting tweet and my retweet of the original tweet is deleted.

## Steps to reproduce
Retweet a tweet. Comment retweeted tweet with same account.

## Extra info

Android version: 7.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.24

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Dup to #912.
