### ISSUE TITLE
Retweeting Broke

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#945]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Tapping the retweet button opens the window to retweet

## Actual behavior
Twidere crashes when tapping that button. It happens on the main list, as well as when they're opened. I sent a crash report including system logs titled something like "Retweets broken with this update."

## Steps to reproduce
Tap the retweet button in the latest version (3.6.26, just released today on the Play Store)

## Extra info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.26

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [X] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by twig** [comment]
confirming I'm also experiencing this on latest update with Android marshmallow

**Comment by tcitworld** [comment]
Can confirm it too.
