### ISSUE TITLE
open user profiles from links like twitter.com/username

### ISSUE THREAD

**Issue by oprudkyi** [TwidereProject/Twidere-Android#95]
if user is referred via link like twitter.com/username (used to avoid notifications instead of @username) twidere at first suggests to open it in external browser (and twidere by self) but if selected again suggests to open in browser.

**Comment by mariotaku** [comment]
could you provide the twitter link or screenshot? seems https://twitter.com/#!/mariotaku not work but https://twitter.com/mariotaku is supported.

**Comment by oprudkyi** [comment]
- I reset default apps (chrome) via 'default app reset' app (just to be sure)
- I've created tweet (at web site) "test https://twitter.com/mariotaku"
- refreshed twidere, get ''test twitter.com/mariotaku"
- clicked highlighted link 
- got application selection window, with chrome and twidere
- selected twidere - chrome started automatically and page was opened in it

**Comment by mariotaku** [comment]
tried, seems fixed.

**Comment by oprudkyi** [comment]
Hi, 

for me it didn't work anyway. 
Android 4.2.2 if this might help

**Comment by mariotaku** [comment]
@oprudkyi could you provide links not work?

**Comment by oprudkyi** [comment]
by example https://twitter.com/mariotaku

**Comment by benediktg** [comment]
@oprudkyi I click on that link and choose to open it with Twirde → works.

I have Cyanogenmod 13 and the most recent Twidere from F-Droid.
