### ISSUE TITLE
Reply on main screen ignores already-tagged handles for Twitter's character limit changes

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#950]
Edited to reflect actual behavior. I was mistaken on some things.
## Expected vs. Actual behavior
When replying on the main screen's timelines, any users not shown - such as ones mentioned inside the tweet or re - aren't grayed out anymore & Twidere counts them towards Twitter's 140-character limit. In conversation view, reply recipients are fine as long as it loads their replies, but any handles added by the tweet being replied to are affected. I understand the motive behind the replying-to-a-reply thing, since protected/blocked/muted users aren't likely to be interested, but it can cause problems on shoddy networks or rate limits, and causes problems on the main screen regardless.

Example:
@.User1 replies to @.User2
Tweet mentions @.User3
I reply to @.User1's tweet.
In main window, it shows @.User1 as greyed & therefore exempt from the character limit, but 2 & 3 are white & count towards the limit.
In conversation view, assuming @.User2's tweet loads, only @.User3 isn't greyed out.

In my opinion, this should be refined so that everyone mentioned is greyed out, but the ones that don't load are moved to the end of the list for easy removal.

## Extra info

Android version: 4.4.2 & 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: Worked fine in 3.6.26, bugged in 3.6.28, indicating a regression in functionality

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Note: This is caused by same reason in #956.
