### ISSUE TITLE
Should content warning hide media?

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#952]
https://twitter.com/stlman/status/906595784245874688

**Comment by andy-twosticks** [comment]
I think most users when posting content behind a CW expect it to.  IIRC the Mastodon web interface does this?

**Comment by mariotaku** [comment]
@andy-twosticks Web interface only hides texts. Seems Twidere is handling sensitive flag well.

**Comment by andy-twosticks** [comment]
I don't know what version of Mastodon you tested this against, but that's a [bug](https://github.com/tootsuite/mastodon/issues/1371) that was apparently fixed in April? 

The canonical behavior is to hide the media. Which, if you think about it, makes sense.

**Comment by mariotaku** [comment]
@andy-twosticks It's not a link, it's an image attached. Seems mastodon.social doing this by forcing Sensitive on while CW enabled, but not on pawoo.net . IMHO CW and Sensitive flag should be treated different. Twidere hides media when Sensitive on, and hides detailed text when CW on.

**Comment by andy-twosticks** [comment]
Does mastodon _have_ a sensitive flag?  I'm not aware of one, other than the CW thing.
