### ISSUE TITLE
UI bug in Likes section when you swipe down to refresh

### ISSUE THREAD

**Issue by rancidfrog** [TwidereProject/Twidere-Android#954]
When swiping down to refresh Likes section, the refresh graphic is hidden behind Action bar:
While swiping:

![](https://i.imgur.com/7LLIo3G.png)
Refresh icon hidden, you can just see the edge:

![](https://i.imgur.com/DTlAv2s.png)

Small UI annoyance, that is all.

**Comment by mariotaku** [comment]
What's this version?

**Comment by rancidfrog** [comment]
3.6.29
