### ISSUE TITLE
Feature Request: Retweet expansion 

### ISSUE THREAD

**Issue by Sixfootsquirrel** [TwidereProject/Twidere-Android#955]
Just recently discovered Twidere, enjoying it so far and looking forward to seeing where the project goes.

I use my twitter client with 2 accounts and one main feed. When Retweeting an item in the main feed it would be useful if I could choose which account to Retweet the tweet from. I've seen this in other twitter clients and it would be useful

**Comment by diesocke** [comment]
+1

**Comment by mariotaku** [comment]
Well this feature is kinda undocumented. I'll think how to give users a notice about this.

You can choose who to RT/fav by long-tapping on RT/fav icon.

**Comment by diesocke** [comment]
Only from the Timeline, Not from the Retweet Window. Therme the longtap result in a Retweet tooltip.

**Comment by Sixfootsquirrel** [comment]
Many thanks everyone, I have now found this feature. It was quite well hidden

It would be good if the same options appears if you held down the Retweet option when you open a tweet
