### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by n8noon** [TwidereProject/Twidere-Android#957]
Hi
i filter spam tweets by its source but i still see that source tweets in every hashtag or search

can u add "multiple selection option" for many tweets so i can retweet it by one click or follow their users , spam them .....

**Comment by mariotaku** [comment]
@n8noon Could you provide more information? 
For example, is tweets sent by 'web' still exists in search results, even you added 'web' to Filters - Sources list?

Multiple selection is worth considering, although retweeting/following too often in a short period of time may have some problems on Twitter side...
