### ISSUE TITLE
Promotions Won't Mute

### ISSUE THREAD

**Issue by Foggalong** [TwidereProject/Twidere-Android#958]
## Expected behavior
"Please enable promotions" notification shows up once, and then gives the option to dismiss or enable.

## Actual behavior
The notification instead has been showing up every single day and doesn't seem to have the option dismiss it.

## Steps to reproduce

Android version: 7.1.2
Network type: Cellular & Wi-Fi
App version: 3.6.29
Build variant: Google
Micro-blogging service: Twitter
App settings: Media preview enabled

**Comment by mariotaku** [comment]
Currently you can open this notification, and quit that settings page. It won't show twice.

**Comment by Foggalong** [comment]
Cool, I'll try that and see if it works. I can't help but think some explicit options would be better from a UX perspective mind

**Comment by mariotaku** [comment]
@Foggalong Totally agree. I'll add actions to turn it on/off directly inside notification.
