### ISSUE TITLE
Some settings don't work anymore

### ISSUE THREAD

**Issue by lescheff** [TwidereProject/Twidere-Android#96]
Since 0.3.0-dev 2015-03-29 the following settings don't work:

- highlighted links are not highlighted but just plain text
- the unread counter isn't displayed at all
- remember position in timeline

**Comment by lescheff** [comment]
Correction:
Links are highlighted in the detailed tweet view but not in the timeline where they aren't even clickable

**Comment by mmogithub** [comment]
I can confirm this in Android 5.0 (CM12 on a Hammerhead)
Regards

**Comment by MttCastelli** [comment]
I can confirm too, both in android lollipop 5.0.2 and cyanogen 12 latest nightlie (Moto G).

**Comment by mariotaku** [comment]
is third issue fixed?

**Comment by mmo-ghub** [comment]
No, I'm sorry. 
With 0.3. 0 when you update it jumps to first Tweet (just know) forgetting when it was in timeline.

**Comment by lescheff** [comment]
@mariotaku sorry for the confusion; twidere remembers the position in the timeline if closed and started again but between refreshes of the timeline it always jumps to the newest tweet.

**Comment by mmo-ghub** [comment]
Ok. I understand behaivor, but I think in older version that WAS the use case. It refreshes but stay it latest read tweet sowing unread counter. As you keep going up it decreases unread count. 
TTherefore, I would like this would be the actual behaivor. In this way it is easier to read timeline 
Regards

**Comment by mariotaku** [comment]
link highlighting fixed in 490b1d3aef17e8c850fbef2b5baede0ea6d1a42a

**Comment by mariotaku** [comment]
unread count implemented in 6d76e18d8a39e7d159a5b6c4563537c14e2f1c27.

**Comment by mariotaku** [comment]
does remember position work?

**Comment by lescheff** [comment]
@mariotaku kind of. Between restarts of the app the position is remembered. But between two refreshes of the timeline it is not.
In the latter case, twidere jumps  to the top but the expected behaviour would be twidere staying on the last read tweet.

**Comment by mariotaku** [comment]
@lescheff how about enable 'read from bottom' option?

**Comment by mmo-ghub** [comment]
Read from bottom IS WORKING fine. It is an awesome feature. 
WWith this enabled is as keeping read position always. 
Thanks

**Comment by mariotaku** [comment]
ok, I'll close this issue.

**Comment by lescheff** [comment]
Ah, sorry, I missed that option. Thanks for pointing that out! :)

**Comment by danbruegge** [comment]
* the unread counter isn't displayed at all

For me this is still an issue. :(
