### ISSUE TITLE
Possible option to load all messages instead of 20 at a time

### ISSUE THREAD

**Issue by moritzheiber** [TwidereProject/Twidere-Android#962]
_Note: I'm using the Mastodon feature of Twidere, this might be different for Twitter. I also apologize if this had been reported before (wasn't able to find anything resembling what I was looking for) or if I wasn't able to read the options correctly (yet)._

Whenever I read my Mastodon toots using Twidere it only loads the 20 most recent toots, leaving a gap between where I left off and where my current timeline is. As somebody who's only checking their social media roughly once or twice a day that's really irritating, and I would love for Twidere to have an option which allows me to adjust that behavior.

Is that possible? Is this a Mastodon API limitation?

**Comment by mariotaku** [comment]
@moritzheiber You can load up to 200 messages at a time by change "Load item limit" in Settings - Contents.

**Comment by moritzheiber** [comment]
@mariotaku Ah, that's great, I knew I just hadn't found the right option. While 200 isn't necessarily "everything" it's enough for my purposes. Closing.
