### ISSUE TITLE
toots behind content warning (CW) also display a "sensitive content" label

### ISSUE THREAD

**Issue by novadeviator** [TwidereProject/Twidere-Android#964]
## Expected behavior
When seeing a toot (post on mastodon) with a content warning, there should be a warning (written by author) and "Show more" and nothing more.

## Actual behavior
Below content warning and "show more" there's always also "Sensitive content"

## Steps to reproduce
Post a toot with content warning only.

## Extra info
It just seems that everything that is hidden behind the content warning now also has a label "Sensitive content". Toots that have an image with "Sensitive content" flag on don't necessarily have a 'show more' link (content warning). So probably when sensitive content flag is on it is being displayed correctly in twidere, but not the CW-flaged toots which are always shown with "Sensitive content" label below the "show more".

Android version: 7.0

Network type:
- [ ] Cellular
- [ ] Wi-Fi

App version: 3.6.29

Build variant:
- [x] Google
- [ ] F-Droid

Micro-blogging service:
- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:
- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
Fixed in bcc1d2f140e594dfd5d001d5463a4bfa9f8fe0f1.
