### ISSUE TITLE
[Mastodon] Character Limit Issue

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [TwidereProject/Twidere-Android#966]
Some Mastodon instances have 1024 character limit but Twidere only allows users to publish 500-characters toots. The GNUsocial instance, Load Average, has no limit and Twidere respects that. Please make Twidere do the same for Mastodon instances.

Android 5.1. Twidere version 3.6.29 (F-Droid).

Thanks.

**Comment by mariotaku** [comment]
Mastodon didn't provide character limit info in their API - And any changes to character limit is undocumented. Twidere can't aware of that kind of changes unless they support this feature officially. Feel free to reopen this or create a new issue if Mastodon add this feature officially.
