### ISSUE TITLE
Suspicion of copyright violation

### ISSUE THREAD

**Issue by Poussinou** [TwidereProject/Twidere-Android#973]
Hi @TwidereProject

[This app](https://play.google.com/store/apps/details?id=org.lazyfew.yapping_free) and [this one](https://play.google.com/store/apps/details?id=org.lazyfew.yapping_pro) have Settings and a part of the UI which are very similar to those of Twidere.

I cannot install this apps alongside Twidere, too. It looks suspicious.

Are this applications approved by your team?

**Comment by orithena** [comment]
(I'm not on the Twidere team.) Really does look like a rip-off of a two-year old version of Twidere. Reported it.

**Comment by mariotaku** [comment]
Thanks for report. I'll take action soon.

**Comment by Poussinou** [comment]
#752

**Comment by mariotaku** [comment]
Since they're playing dead after I tried to reach them out, I sent DMCA takedown request. Hope this will work!

**Comment by Poussinou** [comment]
@mariotaku Any news from Google regarding the DMCA takedown requests?

**Comment by mariotaku** [comment]
@Poussinou Ah, Google Play replied me to ask for more information, but I ignored that message. Now I sent them more information and hope they can take action.

**Comment by Poussinou** [comment]
Good :)

**Comment by mariotaku** [comment]
Done :)
Those apps are taken down from Google Play. Thanks to everyone for your information!
