### ISSUE TITLE
Heads-up: Twitter might increase character limit!

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#975]
https://twitter.com/Twitter/status/912783930431905797 says:
"We’re trying something new with a small group, and increasing the character limit to 280!"
https://blog.twitter.com/official/en_us/topics/product/2017/Giving-you-more-characters-to-express-yourself.html

TL;DR: Twitter might at some point in the future increase the character limit to 280 (except for Japanese, Chinese, and Korean script, where one character conveys double the information on average).

**Comment by orithena** [comment]
Looks like it's already possible just by setting the parameter "weighted_character_count" to true:
"Click 'Tweet' in the web ui
F12 Remove 'disable' on the tweet button
Click it, and go to 'network', right click on the request and copy as cURL
Then, add &weighted_character_count=true as a param to the end of the url
Then, resubmit the tweet with curl."
https://twitter.com/ErrataRob/status/912904724063641602

**Comment by orithena** [comment]
Also, just to confirm: Reading Tweets with 280 characters already works perfectly.

**Comment by xkfngs** [comment]
I was just coming in here to remark on the "weighted_character_count" parameter. I do hope this is an easy addition. I'll take a look and see if I can even make the necessary change later today if it has not been commented on.

**Comment by keithzg** [comment]
Twitter appears to have "fixed" the web hack.

**Comment by bmx22c** [comment]
The 280 characters hack is still possible via the Tweetdeck endpoint. You can read more here: https://github.com/quinncomendant/280Characters/issues/2

**Comment by voidzero** [comment]
280 enabled globally now... But it looks like it doesn't work for me in Twidere, nor on mobile.twitter.com...

**Comment by orithena** [comment]
280 characters are now enabled according to https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html

Also, I can confirm this by checking the official Twitter App.

**Comment by mariotaku** [comment]
@orithena Yes, this feature is available to all users. I'll start to change text counting algorithm.

**Comment by mariotaku** [comment]
Hi there, this feature may not be available soon since Twidere is working on a major refactoring, and my job draws me more attention this time. I'll make it ASAP but don't expect a new update too soon.
