### ISSUE TITLE
Twidere cannot show pinned tweets

### ISSUE THREAD

**Issue by CKrome** [TwidereProject/Twidere-Android#976]
## Expected behavior
Twidere show pinned tweets.
## Actual behavior
It won't show.
## Steps to reproduce
Tap any user's profile which has a pinned tweet.
## Extra info
Android version: Android 7.1.2 API 25
Network type:

- [x] Cellular
- [x] Wi-Fi

tatlo version: (version code here)

Build variant:

- [x] Google

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Any actions related pinned tweets are restricted to official apps only. Please try [Custom API keys](https://gist.github.com/mariotaku/5465786)
