### ISSUE TITLE
Ads when pausing videos on Twitter

### ISSUE THREAD

**Issue by nakal** [TwidereProject/Twidere-Android#978]
I am not sure if this can be suppressed, but I'm seeing ads by Google when playing videos on Twitter and press on the pause button.

[Here](https://twitter.com/holyknee/status/913835471720951808) an example.

## Screenshot

![screenshot_20170930-124407](https://user-images.githubusercontent.com/7075413/31045217-ebb0512c-a5de-11e7-9a96-ceda3c744796.png)

## Steps to reproduce

* click on link above
* press pause button (bottom left)

## Extra info

Android version: Paranoid Android 7.3.0 (Android 7.1.2)

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: (version code here)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

**Comment by mariotaku** [comment]
Yes, this is opted-in ad in Twidere. You'll see some ads after 'Promotion rewards' option enabled. If you don't want to see ads, you can disable this option or purchase enhanced features.

**Comment by nakal** [comment]
Oh yes. I wondered what it is and enabled it a while ago. I haven't understood what this does and did not disable it, because I did not find the settings entry for this. I just found it hidden in a three-dot menu in parts of settings that do not even mention "promotions".

It would be if you translate the menus/settings and describe more clearly what you get and that you see ads in some places within the app.

I have nothing against ads if I get features, by the way. I just don't see what features I got. And I need to be able to associate the features with the ads somehow.

So far, it's solved for me. Thank you.

**Comment by mariotaku** [comment]
@nakal I'll add more info of this option (e.g. adding examples) in future releases to help people understand this feature, thanks for your report!

**Comment by nakal** [comment]
One more thing. I haven't seen any hint how to "purchase enhanced features" that you just mentioned as an alternative to ads. I remember that it is possible back when I enabled promotions, but I cannot find it anywhere in the app.

**Comment by mariotaku** [comment]
@nakal Oh, promotions should be disabled first. Then you'll be able to see purchase option.

**Comment by X52p** [comment]
Hi, I can't find the option to disable the ads. Were is it located?
