### ISSUE TITLE
Notifications without sound, light or vibration

### ISSUE THREAD

**Issue by hebu** [TwidereProject/Twidere-Android#98]
In the notification settings, I have enabled notifications for mentions and incoming messages. I turned on vibration, sound and LED light. When a mention or message comes in, it will be notified on the status bar, but there is not light, sound or vibration. So I will never get notified when the screen is off.

Twidere 0.3.0 dev 2015-03-29 / Android 4.3

**Comment by mmogithub** [comment]
I can confirm this in Android 5.0 (CM12 on a Hammerhead)
Also in 0.2.9.12 on the same phone.
Regards

**Comment by hebu** [comment]
As for me, I did not have the issue with version 0.2.9.12. I am using a Samsung Galaxy SIII LET (i9305).

**Comment by mariotaku** [comment]
I'll fix this soon.

**Comment by hebu** [comment]
This is working rudimentary now in 0.3.0 dev 2015-04-04.

I have the feeling, that with phone volume up, I'll get sound + vibration, while with phone in vibration mode, I'll get LED light only. I'd expect to have LED+vib+sound with volume up, LED+vib in vibration mode and LED only in silent mode.

Also, the default notification sound was played, not the one configured.

But this is already far better than no alarm at all! Thanks!

**Comment by hebu** [comment]
Just found out: LED+vib in the phone's vibration mode is working :)

**Comment by mariotaku** [comment]
does new version fixed this?

**Comment by hebu** [comment]
I think so – except that the default notification sound is played, instead of the one configured.

**Comment by mmogithub** [comment]
On latest play store version is not working. No sound (custom ringtone) no vibration and no led color...
I only have lock screen notification and/or status bar notification...
Regards

**Comment by mariotaku** [comment]
fixed in 01cfec55ddef18f6779a5d7fb8ff62ee38adaf42
