### ISSUE TITLE
Android Twitter Filters no longer being applied to `List timeline' and `User's tweets' views

### ISSUE THREAD

**Issue by jcs100** [TwidereProject/Twidere-Android#980]
## Expected behavior

`Users`, `Keywords`, `Sources` and `Links` filters should be applied to tweets contained within the `List timeline` and `User's Tweets` views.

## Actual behavior

Since Android version `3.6.33`, Twitter `List timeline` and `User's Tweets` are unfiltered.

## Steps to reproduce

Open the app, and add any Twitter filter that should exclude a tweet under either a `List timeline` or `User's Tweets` view. The tweet will remain.

## Extra info

Android version: 7.0 (Samsung S7 Build NRD90M.G935FXXS1DQHF)

Network type:

- [ x ] Cellular
- [ x ] Wi-Fi

App version: 3.6.33

Build variant:

- [ x ] Google
- [ ] F-Droid

Micro-blogging service:

- [ x ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Are you testing with your own tweets? Currently Twidere won't filter tweets in your own timeline. For list timeline I'll try reproduce.

**Comment by jcs100** [comment]
A `User's Tweets` tab can be added with `Settings->Tabs->+`, and can be set to show any Twitter user's timeline.

In versions of Twidere before `3.6.33`, filters were applied to these tabs.

Having control over whether filters are applied or not to `User's Tweets` tabs seems reasonable. It is not clear whether filter setting `Add rule->Advanced->Apply To...->Other` targets this type of tab.

**Comment by mariotaku** [comment]
@jcs100 Ah I see. Are rules applied to newly refreshed tweets? Since only home/interactions has real-time filter applying for now.

**Comment by jcs100** [comment]
@mariotaku filter rules are not being applied to any tweets in the `List timeline` and `User's Tweets` views, including newly refreshed tweets.

**Comment by jcs100** [comment]
Filters being applied in Twidere version 3.7.1 to both views.
