### ISSUE TITLE
Filter retweets by specific user

### ISSUE THREAD

**Issue by georgedorn** [TwidereProject/Twidere-Android#988]
A feature request - I'd like to be able to mute / filter tweets that are retweeted by specific users.  That is, I want to see their normal tweets, but not see their retweets (regardless of the source of the retweet).

**Comment by mariotaku** [comment]
Here's a more universal solution: Turn off "Enable retweets" in user's profile (located in menu). This feature is also available in official clients and webpages.

If you want to exclude retweets in a user's timeline, you can easily tap filter icon on top of the timeline and uncheck "Retweets"

**Comment by georgedorn** [comment]
Ah, it wasn't clear that that was what that checkbox was for.  It doesn't apply to already-loaded tweets, so I assumed it referred to notifications about that user retweeting me.

**Comment by mariotaku** [comment]
@georgedorn Does this feature matches your need?

**Comment by georgedorn** [comment]
Yeah, more testing shows it does do what I want.  It just wasn't obvious.

**Comment by Webreaper** [comment]
Just found this issue while looking for the same feature. Might make it more intuitive if the checkbox states were reversed, and the caption was "Mute Retweets" (defaulting to unchecked).
