### ISSUE TITLE
Heads Up: Breaking change coming to Mastodon API

### ISSUE THREAD

**Issue by yiskah** [TwidereProject/Twidere-Android#989]
# **An API-Breaking change is coming to the next Mastodon update**

https://github.com/tootsuite/mastodon/releases/tag/v2.0.0rc1

If Twidere isn't updated to reflect the API change then once everyone upgrades to 2.0 Twidere will stop working with Mastodon

**Comment by mariotaku** [comment]
Phew. All `id` attributes in Twidere are strings already. Twidere users don't have to worry about API changes.

**Comment by mariotaku** [comment]
If any problem occurs after server side update, please reopen this.

**Comment by yiskah** [comment]
Fantastic. No problems are occurring. Thank you!!
