### ISSUE TITLE
[Feature Request] Make display name of post configurable

### ISSUE THREAD

**Issue by Technowix** [TwidereProject/Twidere-Android#991]
Right now, everything is a "Tweet", but in Mastodon, thoses are "Toots", or some call them "Posts", and anywhere on the Fediverse there is lot of names for thoses.
So, it would be cool to be able to personalize the name of thoses "posts" by whatever we want :3 !

Thanky ~ ❤️

**Comment by mariotaku** [comment]
This is the same issue as #854
