### ISSUE TITLE
Unable send direct message by use twip

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#993]
Sorry for my English.

设备：Google Nexus 5X
Android系统： LineageOS 14.1
Android版本： 7.1.2
Twidere版本： 3.7.1
Twip版本：248 (commits)

现象：
当场尝试使用经由Twip O模式的API代理的情况下给任何人发送私信均无法发送，提示 Empty data 。

Twip日志：
已通过邮件发送。

Logcat：
没有有效信息。

Apache日志：
```
<IP ADDRESS> - - [14/Oct/2017:04:04:37 +0000] "POST /t/o/<TWIP CODE>/1.1/direct_messages/events/new.json HTTP/1.1" 415 1764 "-" "Twidere/3.7.1 okhttp/3.8.1 Android/7.1.2"
```

备注：
查了一下，这个415是不支持的媒体请求类型，stackoverflow有一个回复，但是我不确认是客户端（Twidere）的问题还是服务器Twip的问题（或是Apache的设置问题等）：
https://stackoverflow.com/questions/22566433/http-415-unsupported-media-type-error-with-json

**Comment by chenshaoju** [comment]
我尝试在客户端用curl访问API地址发送私信给自己，是可以正常发送的：
```
D:\Software\curl>curl -vv --insecure -H "Content-Type: application/json" -X POST "https://<WEB SITE ADDRESS>/t/o/<TWIP CODE>/1.1/direct_messages/new.json?text=TestFromCurl&user_id=17482838
```

**Comment by mariotaku** [comment]
@chenshaoju 请注意 '/direct_messages/event/new.json' 是Twitter的新版私信接口，会不会是这个问题？

**Comment by chenshaoju** [comment]
不知道。。。。😑
我只能说按照api文档的地址发私信是可以发出来的。。。
如果请求地址没问题的话，是不是参数有问题什么的。。。

**Comment by mariotaku** [comment]
@chenshaoju 这应该是twip的bug。新的私信通过 `/direct_messages/event/new.json` 发送，这个接口是使用JSON传递数据的。
![image](https://user-images.githubusercontent.com/830358/34042442-b2cceb9c-e1d7-11e7-96e2-2976e6abd5e0.png)

**Comment by chenshaoju** [comment]
比较奇怪的是，为什么curl可以发……

@yegle @jimmyxu 可能得麻烦腐狸酱和吉米桑看看了……

**Comment by AstroProfundis** [comment]
似乎是因为 twip 向 twitter 发请求的时侯 content-type 不是 json

`    [connection] => TwitterOAuth Object
        (
            [http_code] => 415
            [url] => https://api.twitter.com/1.1/direct_messages/events/new.json
            [host] => https://api.twitter.com/1.1/
            [timeout] => 30
            [connecttimeout] => 30
            [ssl_verifypeer] => 
            [format] => json
            [decode_json] => 
            [http_info] => Array
                (
                    [url] => https://api.twitter.com/1.1/direct_messages/events/new.json
                    [content_type] => text/html;charset=utf-8
                    [http_code] => 415
                    [header_size] => 1711
                    [request_size] => 473
                    [filetime] => -1
                    [ssl_verify_result] => 0
                    [redirect_count] => 0
                    [total_time] => 0.130382
                    [namelookup_time] => 0.008464
                    [connect_time] => 0.010492
                    [pretransfer_time] => 0.017474
                    [size_upload] => 274
                    [size_download] => 0
                    [speed_download] => 0
                    [speed_upload] => 2101
                    [download_content_length] => 0
                    [upload_content_length] => 274
                    [starttransfer_time] => 0.130116
                    [redirect_time] => 0
                    [certinfo] => Array
                        (
                        )

                    [redirect_url] => 
                )
`

**Comment by Tedko** [comment]
twip 应该已经修好了。
