### ISSUE TITLE
Cannot post to Mastodon

### ISSUE THREAD

**Issue by kuba-orlik** [TwidereProject/Twidere-Android#997]
## Expected behavior

Posting to Mastodon sends the post to Mastodon

## Actual behavior

A "Network error: timeout" toast appears and the post is not sent

## Steps to reproduce

1. Setup a mastodon.host account in Twidere
2. Open the "Compose" dialog, and enter some text
3. Click "send"
4. Notice the error message

## Extra info

Android version: 7.1.2

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: 3.7.1

Build variant: 

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by kuba-orlik** [comment]
It eventually worked, but is very sketchy. It's a shame, I saw Twidere as a way to easilly cross-post

**Comment by mariotaku** [comment]
"Connection timeout" error is network related. Either your network was slow or mastodon instance failed to respond.

**Comment by trwnh** [comment]
Mastodon posting works fine for me on mastodon.social and anticapitalist.party, so I don't think this is a bug in Twidere. Also, mastodon.host failed to load in a web browser while typing this comment, so it's definitely problems with their host. Trying again succeeded, but it took some time.

**Comment by jdfq** [comment]
我也不能发布。刷新信息正常，所以觉得可能是APP的问题

**Comment by jdfq** [comment]
好像发布成功了。国内网络本来就不好。

**Comment by HugoPoi** [comment]
I encounter this issue a lot, on my own mastodon server, and only with Twidere client. And I can reproduce especially when I have big media attached, the media upload goes well, then the posting take multiple seconds and failed with just "timeout" toast.

**Comment by HugoPoi** [comment]
After digging a little I think my mastodon instance is somehow slow to respond on the post API call, so the http socket stay empty too long (processing stuff on the server side) and the java network stack close the connection too early and don't wait enough ?

Maybe we can add a java.net.SocketTimeout settings
